# `get_synonyms()` for All APIs

Run from the **project root** so that `scripts/` is on the Python path.

This notebook demonstrates the `get_synonyms()` pipeline for every API client in `scripts/apis_pipe/`. For each API, you will see:
- The raw data returned at each fetch step (printed by the API itself)
- The final compiled synonym DataFrame

**APIs covered:**
- Standard base-class pipeline: COL, GBIF, Index Fungorum, MushroomObserver, GenBank, FishBase
- Custom `get_synonyms()` orchestration: ITIS, Tropicos, Symbiota portals

Each section queries three cases: an **accepted name**, a **known synonym**, and **"Not species"** (a control that should return an empty result).


Notice: If you see an error that says "notebook controller is DISPOSED." when using run all, you can still run the notebook by clicking each run button one at a time. 

Notice: If any changes are made to the codebase, restart the notebook to run with the most up-to-date changes.

In [1]:
import sys, os

# Ensure the project root is on sys.path when running from notebooks/apis_pipe/
project_root = os.path.abspath(os.path.join(os.getcwd(), "../.."))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from IPython.display import display

In [2]:
import time
import pandas as pd

pd.set_option("display.max_colwidth", None)

from scripts.config import (
    COL_PORTAL,
    GBIF_PORTAL,
    GENBANK_PORTAL,
    INDEX_FUNGORUM_PORTAL,
    ITIS_PORTAL,
    MUSHROOM_OBSERVER_PORTAL,
    TROPICOS_PORTAL,
    FISHBASE_PORTAL,
    SYMBIOTA_PORTAL_BY_NAME,
)


def show(df):
    """Display a synonym DataFrame with api_link rendered as a clickable anchor."""
    if df.empty:
        display(df)
        return
    display(
        df.style.format(
            {
                "api_link": lambda url: (
                    f'<a href="{url}" target="_blank">{url}</a>'
                    if url and url not in ("U", "")
                    else url
                )
            }
        )
    )


def run_queries(queries, sleep_between_species=0.0):
    """
    Run get_synonyms() for each (portal, client, accepted_name, synonym_name) tuple.

    For each entry, queries three cases in order:
      1. The accepted name
      2. A known synonym of the accepted name
      3. "Not species" — a control that should return an empty result

    Parameters
    ----------
    queries : list of (portal, client, accepted_name, synonym_name)
    sleep_between_species : float
        Seconds to sleep between each species query. Used for rate-limited APIs.
    """
    for portal, client, accepted, synonym in queries:
        for species, name_type in [
            (accepted, "accepted"),
            (synonym, "synonym"),
            ("Not species", "not species"),
        ]:
            print(f"\n{'='*60}")
            print(f"  {portal.display_name}  ({client.__class__.__name__})")
            print(f"  Species:   {species}")
            if name_type == "synonym":
                print(f"  Name type: {name_type}  (synonym of: {accepted})")
            else:
                print(f"  Name type: {name_type}")
            print(f"{'='*60}")
            try:
                result = client.get_synonyms(species)
                print(f"Synonyms returned: {len(result)}")
                show(result)
            except Exception as e:
                print(f"ERROR: {e}")
            if sleep_between_species:
                time.sleep(sleep_between_species)

---
## How the Standard `get_synonyms()` Pipeline Works

Most API clients in this project inherit `get_synonyms()` directly from the base class (`SpeciesAPI`) without overriding it. The method orchestrates a fixed four-step pipeline:

```python
def get_synonyms(self, name: str) -> pd.DataFrame:
    name = normalize_query_string(name)

    raw_data = self._fetch_query_data(name)
    if self._is_empty(raw_data):
        return empty_synonym_table()

    synonym_data = self._fetch_synonym_data(raw_data)
    accepted_data = self._fetch_accepted_data(raw_data, synonym_data)

    synonyms = self._compile_synonyms(synonym_data) if not self._is_empty(synonym_data) else []
    accepted = self._compile_accepted(accepted_data)  if not self._is_empty(accepted_data) else []

    rows = accepted + synonyms
    return pd.DataFrame(rows) if rows else empty_synonym_table()
```

**Step 1 — `_fetch_query_data(name)`**
Makes the initial API request for the search term. Returns the raw response in the API's native format (JSON dict, list, or XML element). If nothing is found, the pipeline short-circuits and returns an empty DataFrame immediately.

**Step 2 — `_fetch_synonym_data(raw_data)`**
Uses the raw query result to fetch the list of synonyms. For most APIs this means extracting an internal ID from `raw_data` and making a second request to the synonyms endpoint.

**Step 3 — `_fetch_accepted_data(raw_data, synonym_data)`**
Fetches the full record for the accepted name — taxonomy, authorship, publication metadata, etc. Some APIs return the accepted name inline with query results (`raw_data` is reused); others require a separate request.

**Step 4 — `_compile_accepted` and `_compile_synonyms`**
Convert the raw API responses into pipeline-standard row dicts. `_compile_accepted` produces one row for the accepted name (with full taxonomy). `_compile_synonyms` produces one row per synonym. Both call `_format_row` internally to enforce the output schema. The rows are concatenated into the final DataFrame.

**What you'll see printed**
Each `get_synonyms()` call prints the raw API response after each fetch step, labelled `_fetch_query_data`, `_fetch_synonym_data`, and `_fetch_accepted_data`. This is intentional — it lets you inspect exactly what each API returns before any compilation happens.

---
## COL (Catalogue of Life)

COL is a global taxonomic checklist aggregating accepted names and synonymies across all kingdoms, maintained by a consortium of taxonomists. This client queries the ChecklistBank REST API, pinned to the COL26.5 dataset.

Uses the **standard base-class** `get_synonyms()` pipeline.

In [3]:
from scripts.apis_pipe.col import COLAPI

run_queries([(COL_PORTAL, COLAPI(), "Quercus robur", "Quercus atrosanguinea")])

============================================================
  COL  (COLAPI)
  Species:   Quercus robur
  Name type: accepted
============================================================
_fetch_query_data
{'offset': 0, 'limit': 10, 'total': 2, 'result': [{'id': '4R5YN', 'classification': [{'id': 'CS5HF', 'name': 'Eukaryota', 'authorship': '(Chatton, 1925) Whittaker & Margulis, 1978', 'rank': 'domain', 'status': 'accepted', 'labelHtml': 'Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978'}, {'id': 'P', 'name': 'Plantae', 'rank': 'kingdom', 'status': 'accepted', 'labelHtml': 'Plantae'}, {'id': 'CMQ8S', 'name': 'Pteridobiotina', 'authorship': 'Britton & Brown', 'rank': 'subkingdom', 'status': 'accepted', 'labelHtml': 'Pteridobiotina Britton & Brown'}, {'id': 'TP', 'name': 'Tracheophyta', 'rank': 'phylum', 'status': 'accepted', 'labelHtml': 'Tracheophyta'}, {'id': 'MG', 'name': 'Magnoliopsida', 'rank': 'class', 'status': 'accepted', 'labelHtml': 'Magnoliopsida'}, {'id': '384', 'name': 'Fagales', 'authorship': 'Engl.', 'rank': 'order', 'code': 'botanical', 'status': 'accepted', 'labelHtml': 'Fagales Engl.'}, {'id': 'NPBN9', 'name': 'Fagaceae', 'authorship': 'Dumort.', 'rank': 'family', 'code': 'botanical', 'status': 'accepted', 'labelHtml': 'Fagaceae Dumort.'}, {'id': 'V58RW', 'name': 'Quercoideae', 'authorship': 'Irvine', 'rank': 'subfamily', 'code': 'botanical', 'status': 'accepted', 'labelHtml': 'Quercoideae Irvine'}, {'id': '8W2YL', 'name': 'Quercus', 'authorship': 'L.', 'rank': 'genus', 'code': 'botanical', 'status': 'accepted', 'labelHtml': '<i>Quercus</i> L.'}, {'id': '4R5YN', 'name': 'Quercus robur', 'authorship': 'L.', 'rank': 'species', 'code': 'botanical', 'status': 'accepted', 'labelHtml': '<i>Quercus robur</i> L.'}], 'usage': {'created': '2026-04-14T22:05:53.134642', 'createdBy': 102, 'modified': '2026-04-14T22:05:53.134642', 'modifiedBy': 102, 'datasetKey': 315192, 'id': '4R5YN', 'sectorKey': 66228, 'verbatimSourceKey': 320776883, 'name': {'created': '2026-04-14T22:05:53.134642', 'createdBy': 102, 'modified': '2026-04-14T22:05:53.134642', 'modifiedBy': 102, 'datasetKey': 315192, 'id': 'O3PF8o6GnVvM2OAvyXqEP1', 'sectorKey': 66228, 'verbatimSourceKey': 320776883, 'namesIndexId': 18938128, 'namesIndexType': 'exact', 'scientificName': 'Quercus robur', 'authorship': 'L.', 'rank': 'species', 'genus': 'Quercus', 'specificEpithet': 'robur', 'combinationAuthorship': {'authors': ['L.']}, 'code': 'botanical', 'publishedInId': '58d80489-b216-4ebf-b05a-22945345c325', 'origin': 'source', 'type': 'scientific', 'link': 'http://www.worldplants.de/?deeplink=Quercus-robur', 'parsed': True}, 'status': 'accepted', 'origin': 'source', 'parentId': '8W2YL', 'identifier': ['wfo:wfo-0000292858-2025-12', 'grin:sp:30739'], 'link': 'http://www.worldplants.de/?deeplink=Quercus-robur', 'referenceIds': ['58d80489-b216-4ebf-b05a-22945345c325'], 'label': 'Quercus robur L.', 'labelHtml': '<i>Quercus robur</i> L.', 'merged': False}, 'sectorDatasetKey': 1141, 'group': 'angiosperms', 'vernacularNames': [{'name': 'Chene pedoncule', 'language': 'fra'}, {'name': 'Dub Cereščatyj', 'language': 'rus'}, {'name': 'Pelarek', 'language': 'swe'}, {'name': 'dub čereščatyj', 'language': 'rus'}, {'name': 'xia li', 'language': 'zho'}, {'name': 'carvalho', 'language': 'por'}, {'name': 'carvalho-alemão', 'language': 'por'}, {'name': 'carvalho-comum', 'language': 'por'}, {'name': 'carvalho-da-europa', 'language': 'por'}, {'name': 'carvalho-europeu', 'language': 'por'}, {'name': 'carvalho-inglês', 'language': 'por'}, {'name': 'English oak', 'language': 'eng'}, {'name': 'European oak', 'language': 'eng'}, {'name': 'chêne pédonculé', 'language': 'fra'}, {'name': 'pedunculate oak', 'language': 'eng'}, {'name': 'Almindelig eg', 'language': 'dan'}, {'name': 'Stilk-eg/almindelig eg', 'language': 'dan'}, {'name': 'ek', 'language': 'swe'}, {'name': 'skogsek', 'language': 'swe'}, {'name': 'sommarek', 'language': 'swe'}, {'name': 'stjälkek', 'language': 'swe'}, {'name': 'Zomereik', 'language': 'nld'}, {'name': 'metsätammi', 'language': 'fin'}, {'name': 'sommareik', 'language': 'nno'}, {'name': 'sommereik', 'language': 'nob'}, {'name': 'Common Oak', 'language': 'eng'}, {'name': 'Derwen Goesog', 'language': 'cym'}, {'name': 'Derwen Gyffredin', 'language': 'cym'}, {'name': 'Derwen Mes Coesynnog', 'language': 'cym'}, {'name': 'Dâr', 'language': 'cym'}, {'name': 'Stiel-Eiche', 'language': 'deu'}, {'name': 'Farnia', 'language': 'ita'}, {'name': 'Quercia comune', 'language': 'ita'}]}, {'id': 'SFTX6', 'classification': [{'id': 'CS5HF', 'name': 'Eukaryota', 'authorship': '(Chatton, 1925) Whittaker & Margulis, 1978', 'rank': 'domain', 'status': 'accepted', 'labelHtml': 'Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978'}, {'id': 'P', 'name': 'Plantae', 'rank': 'kingdom', 'status': 'accepted', 'labelHtml': 'Plantae'}, {'id': 'CMQ8S', 'name': 'Pteridobiotina', 'authorship': 'Britton & Brown', 'rank': 'subkingdom', 'status': 'accepted', 'labelHtml': 'Pteridobiotina Britton & Brown'}, {'id': 'TP', 'name': 'Tracheophyta', 'rank': 'phylum', 'status': 'accepted', 'labelHtml': 'Tracheophyta'}, {'id': 'MG', 'name': 'Magnoliopsida', 'rank': 'class', 'status': 'accepted', 'labelHtml': 'Magnoliopsida'}, {'id': '384', 'name': 'Fagales', 'authorship': 'Engl.', 'rank': 'order', 'code': 'botanical', 'status': 'accepted', 'labelHtml': 'Fagales Engl.'}, {'id': 'NPBN9', 'name': 'Fagaceae', 'authorship': 'Dumort.', 'rank': 'family', 'code': 'botanical', 'status': 'accepted', 'labelHtml': 'Fagaceae Dumort.'}, {'id': 'V58RW', 'name': 'Quercoideae', 'authorship': 'Irvine', 'rank': 'subfamily', 'code': 'botanical', 'status': 'accepted', 'labelHtml': 'Quercoideae Irvine'}, {'id': '8W2YL', 'name': 'Quercus', 'authorship': 'L.', 'rank': 'genus', 'code': 'botanical', 'status': 'accepted', 'labelHtml': '<i>Quercus</i> L.'}, {'id': '4R5YN', 'name': 'Quercus robur', 'authorship': 'L.', 'rank': 'species', 'code': 'botanical', 'status': 'accepted', 'labelHtml': '<i>Quercus robur</i> L.'}, {'id': '7KPMG', 'name': 'Quercus robur subsp. brutia', 'authorship': '(Ten.) O.Schwarz', 'rank': 'subspecies', 'code': 'botanical', 'status': 'accepted', 'labelHtml': '<i>Quercus robur</i> subsp. <i>brutia</i> (Ten.) O.Schwarz'}, {'id': 'SFTX6', 'name': 'Quercus robur', 'authorship': 'Asso', 'rank': 'species', 'code': 'botanical', 'status': 'synonym', 'labelHtml': '<i>Quercus robur</i> Asso'}], 'usage': {'created': '2026-05-15T21:24:32.030241', 'createdBy': 466, 'modified': '2026-05-15T21:24:32.030241', 'modifiedBy': 466, 'datasetKey': 315192, 'id': 'SFTX6', 'sectorKey': 49811, 'verbatimSourceKey': 324439383, 'name': {'created': '2026-05-15T21:24:32.030241', 'createdBy': 466, 'modified': '2026-05-15T21:24:32.030241', 'modifiedBy': 466, 'datasetKey': 315192, 'id': '~CY0', 'sectorKey': 49811, 'verbatimSourceKey': 324439383, 'namesIndexId': 18938118, 'namesIndexType': 'exact', 'identifier': ['tpl:tro-50280607', 'lsid:urn:lsid:ipni.org:names:296691-1'], 'scientificName': 'Quercus robur', 'authorship': 'Asso', 'rank': 'species', 'genus': 'Quercus', 'specificEpithet': 'robur', 'combinationAuthorship': {'authors': ['Asso']}, 'code': 'botanical', 'publishedInId': 'a86c1dff-508a-4d0b-a81f-36dd8f925bbf', 'origin': 'source', 'type': 'scientific', 'link': 'https://list.worldfloraonline.org/wfo-0001275587', 'parsed': True}, 'status': 'synonym', 'origin': 'source', 'parentId': '7KPMG', 'identifier': ['wfo:wfo-0001275587-2025-12'], 'accepted': {'id': '7KPMG', 'name': {'scientificName': 'Quercus robur subsp. brutia', 'authorship': '(Ten.) O.Schwarz', 'rank': 'subspecies', 'code': 'botanical', 'type': 'scientific', 'parsed': False}, 'status': 'accepted', 'label': 'Quercus robur subsp. brutia (Ten.) O.Schwarz', 'labelHtml': '<i>Quercus robur</i> subsp. <i>brutia</i> (Ten.) O.Schwarz'}, 'label': 'Quercus robur Asso', 'labelHtml': '<i>Quercus robur</i> Asso', 'merged': True}, 'sectorDatasetKey': 2004, 'group': 'angiosperms'}], 'empty': False, 'last': True}
_fetch_synonym_data

============================================================
  COL  (COLAPI)
  Species:   Quercus atrosanguinea
  Name type: synonym  (synonym of: Quercus robur)
============================================================
_fetch_query_data
{'offset': 0, 'limit': 10, 'total': 2, 'result': [{'id': '4R4BH', 'classification': [{'id': 'CS5HF', 'name': 'Eukaryota', 'authorship': '(Chatton, 1925) Whittaker & Margulis, 1978', 'rank': 'domain', 'status': 'accepted', 'labelHtml': 'Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978'}, {'id': 'P', 'name': 'Plantae', 'rank': 'kingdom', 'status': 'accepted', 'labelHtml': 'Plantae'}, {'id': 'CMQ8S', 'name': 'Pteridobiotina', 'authorship': 'Britton & Brown', 'rank': 'subkingdom', 'status': 'accepted', 'labelHtml': 'Pteridobiotina Britton & Brown'}, {'id': 'TP', 'name': 'Tracheophyta', 'rank': 'phylum', 'status': 'accepted', 'labelHtml': 'Tracheophyta'}, {'id': 'MG', 'name': 'Magnoliopsida', 'rank': 'class', 'status': 'accepted', 'labelHtml': 'Magnoliopsida'}, {'id': '384', 'name': 'Fagales', 'authorship': 'Engl.', 'rank': 'order', 'code': 'botanical', 'status': 'accepted', 'labelHtml': 'Fagales Engl.'}, {'id': 'NPBN9', 'name': 'Fagaceae', 'authorship': 'Dumort.', 'rank': 'family', 'code': 'botanical', 'status': 'accepted', 'labelHtml': 'Fagaceae Dumort.'}, {'id': 'V58RW', 'name': 'Quercoideae', 'authorship': 'Irvine', 'rank': 'subfamily', 'code': 'botanical', 'status': 'accepted', 'labelHtml': 'Quercoideae Irvine'}, {'id': '8W2YL', 'name': 'Quercus', 'authorship': 'L.', 'rank': 'genus', 'code': 'botanical', 'status': 'accepted', 'labelHtml': '<i>Quercus</i> L.'}, {'id': '4R5YN', 'name': 'Quercus robur', 'authorship': 'L.', 'rank': 'species', 'code': 'botanical', 'status': 'accepted', 'labelHtml': '<i>Quercus robur</i> L.'}, {'id': '5KTTT', 'name': 'Quercus robur subsp. robur', 'rank': 'subspecies', 'code': 'botanical', 'status': 'accepted', 'labelHtml': '<i>Quercus robur</i> subsp. <i>robur</i>'}, {'id': '4R4BH', 'name': 'Quercus atrosanguinea', 'authorship': 'K.Koch', 'rank': 'species', 'code': 'botanical', 'status': 'synonym', 'labelHtml': '<i>Quercus atrosanguinea</i> K.Koch'}], 'usage': {'created': '2026-04-14T22:06:29.941626', 'createdBy': 102, 'modified': '2026-04-14T22:06:29.941626', 'modifiedBy': 102, 'datasetKey': 315192, 'id': '4R4BH', 'sectorKey': 66228, 'verbatimSourceKey': 320790243, 'name': {'created': '2026-04-14T22:06:29.941626', 'createdBy': 102, 'modified': '2026-04-14T22:06:29.941626', 'modifiedBy': 102, 'datasetKey': 315192, 'id': 'DFu0vX-3GOeW8x4AOFlik', 'sectorKey': 66228, 'verbatimSourceKey': 320790243, 'namesIndexId': 18842798, 'namesIndexType': 'exact', 'scientificName': 'Quercus atrosanguinea', 'authorship': 'K.Koch', 'rank': 'species', 'genus': 'Quercus', 'specificEpithet': 'atrosanguinea', 'combinationAuthorship': {'authors': ['K.Koch']}, 'code': 'botanical', 'publishedInId': 'e1d1e709-4a75-4671-a010-0bf42206da10', 'publishedInPage': '28', 'origin': 'source', 'type': 'scientific', 'parsed': True}, 'status': 'synonym', 'origin': 'source', 'parentId': '5KTTT', 'identifier': ['wikidata:Q111328401'], 'referenceIds': ['e1d1e709-4a75-4671-a010-0bf42206da10'], 'accepted': {'id': '5KTTT', 'name': {'scientificName': 'Quercus robur subsp. robur', 'rank': 'subspecies', 'code': 'botanical', 'type': 'scientific', 'parsed': False}, 'status': 'accepted', 'label': 'Quercus robur subsp. robur', 'labelHtml': '<i>Quercus robur</i> subsp. <i>robur</i>'}, 'label': 'Quercus atrosanguinea K.Koch', 'labelHtml': '<i>Quercus atrosanguinea</i> K.Koch', 'merged': False}, 'sectorDatasetKey': 1141, 'group': 'angiosperms'}, {'id': 'SF5RP', 'classification': [{'id': 'CS5HF', 'name': 'Eukaryota', 'authorship': '(Chatton, 1925) Whittaker & Margulis, 1978', 'rank': 'domain', 'status': 'accepted', 'labelHtml': 'Eukaryota (Chatton, 1925) Whittaker & Margulis, 1978'}, {'id': 'P', 'name': 'Plantae', 'rank': 'kingdom', 'status': 'accepted', 'labelHtml': 'Plantae'}, {'id': 'CMQ8S', 'name': 'Pteridobiotina', 'authorship': 'Britton & Brown', 'rank': 'subkingdom', 'status': 'accepted', 'labelHtml': 'Pteridobiotina Britton & Brown'}, {'id': 'TP', 'name': 'Tracheophyta', 'rank': 'phylum', 'status': 'accepted', 'labelHtml': 'Tracheophyta'}, {'id': 'MG', 'name': 'Magnoliopsida', 'rank': 'class', 'status': 'accepted', 'labelHtml': 'Magnoliopsida'}, {'id': '384', 'name': 'Fagales', 'authorship': 'Engl.', 'rank': 'order', 'code': 'botanical', 'status': 'accepted', 'labelHtml': 'Fagales Engl.'}, {'id': 'NPBN9', 'name': 'Fagaceae', 'authorship': 'Dumort.', 'rank': 'family', 'code': 'botanical', 'status': 'accepted', 'labelHtml': 'Fagaceae Dumort.'}, {'id': 'V58RW', 'name': 'Quercoideae', 'authorship': 'Irvine', 'rank': 'subfamily', 'code': 'botanical', 'status': 'accepted', 'labelHtml': 'Quercoideae Irvine'}, {'id': '8W2YL', 'name': 'Quercus', 'authorship': 'L.', 'rank': 'genus', 'code': 'botanical', 'status': 'accepted', 'labelHtml': '<i>Quercus</i> L.'}, {'id': '4R5YN', 'name': 'Quercus robur', 'authorship': 'L.', 'rank': 'species', 'code': 'botanical', 'status': 'accepted', 'labelHtml': '<i>Quercus robur</i> L.'}, {'id': 'SF5RP', 'name': 'Quercus atrosanguinea', 'authorship': 'hort.', 'rank': 'species', 'code': 'botanical', 'status': 'synonym', 'labelHtml': '<i>Quercus atrosanguinea</i> hort.'}], 'usage': {'created': '2026-05-15T21:24:31.550271', 'createdBy': 466, 'modified': '2026-05-15T21:24:31.550271', 'modifiedBy': 466, 'datasetKey': 315192, 'id': 'SF5RP', 'sectorKey': 49811, 'verbatimSourceKey': 324439365, 'name': {'created': '2026-05-15T21:24:31.550271', 'createdBy': 466, 'modified': '2026-05-15T21:24:31.550271', 'modifiedBy': 466, 'datasetKey': 315192, 'id': '~CXs', 'sectorKey': 49811, 'verbatimSourceKey': 324439365, 'namesIndexId': 18842816, 'namesIndexType': 'exact', 'identifier': ['tpl:kew-171681', 'lsid:urn:lsid:ipni.org:names:295814-1'], 'scientificName': 'Quercus atrosanguinea', 'authorship': 'hort.', 'rank': 'species', 'genus': 'Quercus', 'specificEpithet': 'atrosanguinea', 'combinationAuthorship': {'authors': ['hort.']}, 'code': 'botanical', 'publishedInId': '9bef744c-9ed4-45f4-831e-a74ec8703189', 'origin': 'source', 'type': 'scientific', 'link': 'https://list.worldfloraonline.org/wfo-0000289653', 'parsed': True}, 'status': 'synonym', 'origin': 'source', 'parentId': '4R5YN', 'identifier': ['wfo:wfo-0000289653-2025-12'], 'accepted': {'id': '4R5YN', 'name': {'scientificName': 'Quercus robur', 'authorship': 'L.', 'rank': 'species', 'code': 'botanical', 'type': 'scientific', 'parsed': False}, 'status': 'accepted', 'label': 'Quercus robur L.', 'labelHtml': '<i>Quercus robur</i> L.'}, 'label': 'Quercus atrosanguinea hort.', 'labelHtml': '<i>Quercus atrosanguinea</i> hort.', 'merged': True}, 'sectorDatasetKey': 2004, 'group': 'angiosperms'}], 'empty': False, 'last': True}
_fetch_synonym_data

============================================================
  COL  (COLAPI)
  Species:   Not species
  Name type: not species
============================================================
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

---
## GBIF (Global Biodiversity Information Facility)

GBIF aggregates occurrence records and taxonomic data contributed by institutions worldwide. This client uses the GBIF backbone taxonomy via `/species/match` to resolve a name to a usage key, then retrieves its synonym list from `/species/{id}/synonyms`.

Uses the **standard base-class** `get_synonyms()` pipeline.

In [4]:
from scripts.apis_pipe.gbif import GBIFAPI

run_queries([(GBIF_PORTAL, GBIFAPI(), "Amanita muscaria", "Agaricus muscarius")])

============================================================
  GBIF  (GBIFAPI)
  Species:   Amanita muscaria
  Name type: accepted
============================================================
_fetch_query_data
{'usageKey': 8168319, 'scientificName': 'Amanita muscaria (L.) Lam.', 'canonicalName': 'Amanita muscaria', 'rank': 'SPECIES', 'status': 'ACCEPTED', 'confidence': 98, 'matchType': 'EXACT', 'kingdom': 'Fungi', 'phylum': 'Basidiomycota', 'order': 'Agaricales', 'family': 'Amanitaceae', 'genus': 'Amanita', 'species': 'Amanita muscaria', 'kingdomKey': 5, 'phylumKey': 34, 'classKey': 186, 'orderKey': 1499, 'familyKey': 4171, 'genusKey': 6005964, 'speciesKey': 8168319, 'class': 'Agaricomycetes'}
_fetch_synonym_data

============================================================
  GBIF  (GBIFAPI)
  Species:   Agaricus muscarius
  Name type: synonym  (synonym of: Amanita muscaria)
============================================================
_fetch_query_data
{'usageKey': 5451774, 'acceptedUsageKey': 8168319, 'scientificName': 'Agaricus muscarius L.', 'canonicalName': 'Agaricus muscarius', 'rank': 'SPECIES', 'status': 'SYNONYM', 'confidence': 99, 'matchType': 'EXACT', 'kingdom': 'Fungi', 'phylum': 'Basidiomycota', 'order': 'Agaricales', 'family': 'Amanitaceae', 'genus': 'Amanita', 'species': 'Amanita muscaria', 'kingdomKey': 5, 'phylumKey': 34, 'classKey': 186, 'orderKey': 1499, 'familyKey': 4171, 'genusKey': 6005964, 'speciesKey': 8168319, 'class': 'Agaricomycetes'}
_fetch_synonym_data

============================================================
  GBIF  (GBIFAPI)
  Species:   Not species
  Name type: not species
============================================================
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

---
## Index Fungorum

Index Fungorum is the global nomenclatural database for fungi, maintained by the Royal Botanic Gardens Kew, CAB International, and Landcare Research. It exposes a legacy ASMX web service (XML over HTTP) rather than a REST/JSON API; all responses are parsed as XML. The service can be slow and may time out; requests use a 60-second timeout.

Uses the **standard base-class** `get_synonyms()` pipeline.

In [5]:
from scripts.apis_pipe.index_fungorum import IndexFungorumAPI

run_queries([(INDEX_FUNGORUM_PORTAL, IndexFungorumAPI(), "Amanita muscaria", "Agaricus muscarius")])

============================================================
  Index Fungorum  (IndexFungorumAPI)
  Species:   Amanita muscaria
  Name type: accepted
============================================================
_fetch_query_data
<Element 'IndexFungorum' at 0x1749dc9f0>
_fetch_synonym_data
<NewDataSet>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus aureolus</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>Kalchbr.</AUTHORS>
    <SPECIFIC_x0020_EPITHET>aureolus</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>sp.</INFRASPECIFIC_x0020_RANK>
    <VOLUME>1</VOLUME>
    <PAGE>9</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1873</YEAR_x0020_OF_x0020_PUBLICATION>
    <LITERATURE_x0020_LINK>3210</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>298478</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>298478</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>298478</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <UpdatedBy>AD\mba13kg</UpdatedBy>
    <AddedBy>EGHAM_SQL\kirk</AddedBy>
    <UpdatedDate>2026-06-07T13:01:58.26+01:00</UpdatedDate>
    <AddedDate>2005-06-27T08:25:00+01:00</AddedDate>
    <UUID>326d045b-f935-40cb-aeec-460a95abc693</UUID>
    <NAME_x0020_STATUS>Legitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus imperialis</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>Batsch</AUTHORS>
    <SPECIFIC_x0020_EPITHET>imperialis</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>sp.</INFRASPECIFIC_x0020_RANK>
    <TYPIFICATION_x0020_DETAILS>Typification: Tab. XXVII (Sch.); Tab. LXXVII, fig. 2 (Micheli)</TYPIFICATION_x0020_DETAILS>
    <PAGE>59</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1783</YEAR_x0020_OF_x0020_PUBLICATION>
    <EDITORIAL_x0020_COMMENT>Circumscription includes the type of a name (&lt;i&gt;Agaricus muscarius&lt;/i&gt; L. 1753), the epithet of which ought to have been adopted</EDITORIAL_x0020_COMMENT>
    <NOMENCLATURAL_x0020_COMMENT>Nom. illegit., Art. 52.1</NOMENCLATURAL_x0020_COMMENT>
    <CORRECTION>https://books.google.co.uk/books?id=2LXcjmuJa1wC&amp;pg=PA59</CORRECTION>
    <SANCTIONING_x0020_AUTHOR>Fr.</SANCTIONING_x0020_AUTHOR>
    <LITERATURE_x0020_LINK>811</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>495382</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>495382</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>375287</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <UpdatedBy>AD\mba13kg</UpdatedBy>
    <AddedBy>CABI_UK\KIRK</AddedBy>
    <UpdatedDate>2025-08-27T09:22:53.993+01:00</UpdatedDate>
    <AddedDate>2007-03-26T12:35:00+01:00</AddedDate>
    <UUID>314f38f1-370a-4d77-90ad-dae09902e21c</UUID>
    <NAME_x0020_STATUS>Illegitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus muscarius</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>L.</AUTHORS>
    <SPECIFIC_x0020_EPITHET>muscarius</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>sp.</INFRASPECIFIC_x0020_RANK>
    <TYPIFICATION_x0020_DETAILS>Typification: Tab. s.n. (Clusius, 1601)</TYPIFICATION_x0020_DETAILS>
    <VOLUME>2</VOLUME>
    <PAGE>1172</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1753</YEAR_x0020_OF_x0020_PUBLICATION>
    <HOST>in meadows</HOST>
    <LOCATION>Europe</LOCATION>
    <CORRECTION>https://www.biodiversitylibrary.org/page/359193</CORRECTION>
    <SANCTIONING_x0020_AUTHOR>Fr.$https://www.biodiversitylibrary.org/page/4338017</SANCTIONING_x0020_AUTHOR>
    <SANCTIONING_x0020_REFERENCE_x0020_VOLUME>1</SANCTIONING_x0020_REFERENCE_x0020_VOLUME>
    <SANCTIONING_x0020_REFERENCE_x0020_PAGE>16</SANCTIONING_x0020_REFERENCE_x0020_PAGE>
    <SANCTIONING_x0020_REFERENCE_x0020_YEAR>1821</SANCTIONING_x0020_REFERENCE_x0020_YEAR>
    <SANCTIONING_x0020_REFERENCE_x0020_LITERATURE_x0020_LINK>889</SANCTIONING_x0020_REFERENCE_x0020_LITERATURE_x0020_LINK>
    <LITERATURE_x0020_LINK>1606</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>375287</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>375287</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>375287</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <SQLTimeStamp>AAAAAAhchlo=</SQLTimeStamp>
    <UpdatedBy>AD\mba13kg</UpdatedBy>
    <AddedBy>EGHAM_SQL\kirk</AddedBy>
    <UpdatedDate>2025-08-27T09:54:59.637+01:00</UpdatedDate>
    <AddedDate>2004-08-09T11:44:00+01:00</AddedDate>
    <UUID>8d452a04-f09a-433a-b530-ca2af289cff2</UUID>
    <NAME_x0020_STATUS>Legitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus muscarius var. albus</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>Peck</AUTHORS>
    <SPECIFIC_x0020_EPITHET>muscarius</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>var.</INFRASPECIFIC_x0020_RANK>
    <INFRASPECIFIC_x0020_EPITHET>albus</INFRASPECIFIC_x0020_EPITHET>
    <TYPIFICATION_x0020_DETAILS>Typification: not indicated</TYPIFICATION_x0020_DETAILS>
    <VOLUME>33</VOLUME>
    <PAGE>44</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1883</YEAR_x0020_OF_x0020_PUBLICATION>
    <YEAR_x0020_ON_x0020_PUBLICATION>1880</YEAR_x0020_ON_x0020_PUBLICATION>
    <CORRECTION>https://www.biodiversitylibrary.org/page/35614352</CORRECTION>
    <LITERATURE_x0020_LINK>7700</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>665959</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>665959</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>665959</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <UpdatedBy>AD\pk23kg</UpdatedBy>
    <UpdatedDate>2026-05-25T21:28:40.227+01:00</UpdatedDate>
    <AddedDate>2026-05-25T21:24:42.063+01:00</AddedDate>
    <UUID>5796a030-d773-4222-96c5-61f792ef09c1</UUID>
    <NAME_x0020_STATUS>Legitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus muscarius var. formosus</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>(Pers.) J. Kickx f.</AUTHORS>
    <SPECIFIC_x0020_EPITHET>muscarius</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>var.</INFRASPECIFIC_x0020_RANK>
    <INFRASPECIFIC_x0020_EPITHET>formosus</INFRASPECIFIC_x0020_EPITHET>
    <PAGE>185</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1835</YEAR_x0020_OF_x0020_PUBLICATION>
    <CORRECTION>https://www.biodiversitylibrary.org/page/62999572</CORRECTION>
    <LITERATURE_x0020_LINK>1894</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>537188</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>160520</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>160520</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <UpdatedBy>AD\mba13kg</UpdatedBy>
    <AddedBy>CABI_UK\KIRK</AddedBy>
    <UpdatedDate>2025-08-27T10:01:09.95+01:00</UpdatedDate>
    <AddedDate>2009-10-06T08:59:00+01:00</AddedDate>
    <UUID>5a29c83d-3132-4c48-9293-92f85faf850d</UUID>
    <NAME_x0020_STATUS>Legitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus muscarius var. formosus</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>(Gonn. &amp; Rabenh.) Peck</AUTHORS>
    <SPECIFIC_x0020_EPITHET>muscarius</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>var.</INFRASPECIFIC_x0020_RANK>
    <INFRASPECIFIC_x0020_EPITHET>formosus</INFRASPECIFIC_x0020_EPITHET>
    <VOLUME>33</VOLUME>
    <PAGE>44</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1883</YEAR_x0020_OF_x0020_PUBLICATION>
    <YEAR_x0020_ON_x0020_PUBLICATION>1880</YEAR_x0020_ON_x0020_PUBLICATION>
    <EDITORIAL_x0020_COMMENT>537188$Agaricus muscarius var. formosus J. Kickx f. 1835</EDITORIAL_x0020_COMMENT>
    <NOMENCLATURAL_x0020_COMMENT>Nom. illegit., Art. 53.1</NOMENCLATURAL_x0020_COMMENT>
    <CORRECTION>https://www.biodiversitylibrary.org/page/35614352</CORRECTION>
    <LITERATURE_x0020_LINK>7700</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>505642</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>212977</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>212977</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <UpdatedBy>AD\mba13kg</UpdatedBy>
    <AddedBy>EDMUNDMASON\kirk</AddedBy>
    <UpdatedDate>2025-08-27T09:22:55.04+01:00</UpdatedDate>
    <AddedDate>2008-04-07T08:28:00+01:00</AddedDate>
    <UUID>5d1495f1-bd10-4912-9e54-3b46b5623996</UUID>
    <NAME_x0020_STATUS>Illegitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus muscarius var. puella</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>(Batsch) Sw.</AUTHORS>
    <SPECIFIC_x0020_EPITHET>muscarius</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>var.</INFRASPECIFIC_x0020_RANK>
    <INFRASPECIFIC_x0020_EPITHET>puella</INFRASPECIFIC_x0020_EPITHET>
    <VOLUME>30</VOLUME>
    <PART>2</PART>
    <PAGE>81</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1809</YEAR_x0020_OF_x0020_PUBLICATION>
    <CORRECTION>https://www.biodiversitylibrary.org/page/46996760</CORRECTION>
    <LITERATURE_x0020_LINK>9892</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>496820</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>372222</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>372222</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <UpdatedBy>AD\mba13kg</UpdatedBy>
    <AddedBy>CABI_UK\KIRK</AddedBy>
    <UpdatedDate>2025-08-27T09:59:23.023+01:00</UpdatedDate>
    <AddedDate>2007-03-26T12:36:00+01:00</AddedDate>
    <UUID>5895d9ed-479f-47e0-97e6-0d57c1b1c104</UUID>
    <NAME_x0020_STATUS>Legitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus muscarius var. puella</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>J. Kickx f.</AUTHORS>
    <SPECIFIC_x0020_EPITHET>muscarius</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>var.</INFRASPECIFIC_x0020_RANK>
    <INFRASPECIFIC_x0020_EPITHET>puella</INFRASPECIFIC_x0020_EPITHET>
    <PAGE>185</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1835</YEAR_x0020_OF_x0020_PUBLICATION>
    <EDITORIAL_x0020_COMMENT>496820$Agaricus muscarius var. puella (Batsch) Sw. 1809</EDITORIAL_x0020_COMMENT>
    <NOMENCLATURAL_x0020_COMMENT>Nom. illegit., Art. 53.1</NOMENCLATURAL_x0020_COMMENT>
    <CORRECTION>https://www.biodiversitylibrary.org/page/62999572</CORRECTION>
    <LITERATURE_x0020_LINK>1894</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>507090</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>507090</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>507090</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <UpdatedBy>AD\mba13kg</UpdatedBy>
    <AddedBy>CABI_UK\KIRK</AddedBy>
    <UpdatedDate>2025-08-27T09:22:55.293+01:00</UpdatedDate>
    <AddedDate>2008-10-30T14:30:00+00:00</AddedDate>
    <UUID>5d81ed25-94bb-4735-9ba8-647e8a0a7bed</UUID>
    <NAME_x0020_STATUS>Illegitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus muscarius var. regalis</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>Peck</AUTHORS>
    <SPECIFIC_x0020_EPITHET>muscarius</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>var.</INFRASPECIFIC_x0020_RANK>
    <INFRASPECIFIC_x0020_EPITHET>regalis</INFRASPECIFIC_x0020_EPITHET>
    <TYPIFICATION_x0020_DETAILS>Typification: not indicated</TYPIFICATION_x0020_DETAILS>
    <VOLUME>33</VOLUME>
    <PAGE>44</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1883</YEAR_x0020_OF_x0020_PUBLICATION>
    <YEAR_x0020_ON_x0020_PUBLICATION>1880</YEAR_x0020_ON_x0020_PUBLICATION>
    <CORRECTION>https://www.biodiversitylibrary.org/page/35614352</CORRECTION>
    <LITERATURE_x0020_LINK>7700</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>665960</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>665960</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>665960</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <UpdatedBy>AD\pk23kg</UpdatedBy>
    <UpdatedDate>2026-06-02T12:44:05.993+01:00</UpdatedDate>
    <AddedDate>2026-05-25T21:28:38.553+01:00</AddedDate>
    <UUID>36c993ee-ca75-458b-b17f-da218e94c0a1</UUID>
    <NAME_x0020_STATUS>Legitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus muscarius var. sanguineus</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>J. Kickx f.</AUTHORS>
    <SPECIFIC_x0020_EPITHET>muscarius</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>var.</INFRASPECIFIC_x0020_RANK>
    <INFRASPECIFIC_x0020_EPITHET>sanguineus</INFRASPECIFIC_x0020_EPITHET>
    <VOLUME>2</VOLUME>
    <PAGE>128</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1867</YEAR_x0020_OF_x0020_PUBLICATION>
    <CORRECTION>https://hdl.handle.net/2027/wu.89036490332?urlappend=%3Bseq=140</CORRECTION>
    <LITERATURE_x0020_LINK>1017</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>507350</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>507350</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>507350</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <UpdatedBy>AD\mba13kg</UpdatedBy>
    <AddedBy>CABI_UK\KIRK</AddedBy>
    <UpdatedDate>2025-08-27T09:59:40.577+01:00</UpdatedDate>
    <AddedDate>2008-10-30T14:30:00+00:00</AddedDate>
    <UUID>6c522a1f-090e-4c64-a939-6411a8f2d274</UUID>
    <NAME_x0020_STATUS>Legitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus muscarius var. umbrinus</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>Peck</AUTHORS>
    <SPECIFIC_x0020_EPITHET>muscarius</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>var.</INFRASPECIFIC_x0020_RANK>
    <INFRASPECIFIC_x0020_EPITHET>umbrinus</INFRASPECIFIC_x0020_EPITHET>
    <TYPIFICATION_x0020_DETAILS>Typification: not indicated</TYPIFICATION_x0020_DETAILS>
    <VOLUME>33</VOLUME>
    <PAGE>44</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1883</YEAR_x0020_OF_x0020_PUBLICATION>
    <YEAR_x0020_ON_x0020_PUBLICATION>1880</YEAR_x0020_ON_x0020_PUBLICATION>
    <CORRECTION>https://www.biodiversitylibrary.org/page/35614352</CORRECTION>
    <LITERATURE_x0020_LINK>7700</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>665961</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>665961</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>665961</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>

============================================================
  Index Fungorum  (IndexFungorumAPI)
  Species:   Agaricus muscarius
  Name type: synonym  (synonym of: Amanita muscaria)
============================================================
_fetch_query_data
<Element 'IndexFungorum' at 0x1749ebf60>
_fetch_synonym_data
<NewDataSet>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus aureolus</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>Kalchbr.</AUTHORS>
    <SPECIFIC_x0020_EPITHET>aureolus</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>sp.</INFRASPECIFIC_x0020_RANK>
    <VOLUME>1</VOLUME>
    <PAGE>9</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1873</YEAR_x0020_OF_x0020_PUBLICATION>
    <LITERATURE_x0020_LINK>3210</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>298478</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>298478</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>298478</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <UpdatedBy>AD\mba13kg</UpdatedBy>
    <AddedBy>EGHAM_SQL\kirk</AddedBy>
    <UpdatedDate>2026-06-07T13:01:58.26+01:00</UpdatedDate>
    <AddedDate>2005-06-27T08:25:00+01:00</AddedDate>
    <UUID>326d045b-f935-40cb-aeec-460a95abc693</UUID>
    <NAME_x0020_STATUS>Legitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus imperialis</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>Batsch</AUTHORS>
    <SPECIFIC_x0020_EPITHET>imperialis</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>sp.</INFRASPECIFIC_x0020_RANK>
    <TYPIFICATION_x0020_DETAILS>Typification: Tab. XXVII (Sch.); Tab. LXXVII, fig. 2 (Micheli)</TYPIFICATION_x0020_DETAILS>
    <PAGE>59</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1783</YEAR_x0020_OF_x0020_PUBLICATION>
    <EDITORIAL_x0020_COMMENT>Circumscription includes the type of a name (&lt;i&gt;Agaricus muscarius&lt;/i&gt; L. 1753), the epithet of which ought to have been adopted</EDITORIAL_x0020_COMMENT>
    <NOMENCLATURAL_x0020_COMMENT>Nom. illegit., Art. 52.1</NOMENCLATURAL_x0020_COMMENT>
    <CORRECTION>https://books.google.co.uk/books?id=2LXcjmuJa1wC&amp;pg=PA59</CORRECTION>
    <SANCTIONING_x0020_AUTHOR>Fr.</SANCTIONING_x0020_AUTHOR>
    <LITERATURE_x0020_LINK>811</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>495382</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>495382</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>375287</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <UpdatedBy>AD\mba13kg</UpdatedBy>
    <AddedBy>CABI_UK\KIRK</AddedBy>
    <UpdatedDate>2025-08-27T09:22:53.993+01:00</UpdatedDate>
    <AddedDate>2007-03-26T12:35:00+01:00</AddedDate>
    <UUID>314f38f1-370a-4d77-90ad-dae09902e21c</UUID>
    <NAME_x0020_STATUS>Illegitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus muscarius</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>L.</AUTHORS>
    <SPECIFIC_x0020_EPITHET>muscarius</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>sp.</INFRASPECIFIC_x0020_RANK>
    <TYPIFICATION_x0020_DETAILS>Typification: Tab. s.n. (Clusius, 1601)</TYPIFICATION_x0020_DETAILS>
    <VOLUME>2</VOLUME>
    <PAGE>1172</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1753</YEAR_x0020_OF_x0020_PUBLICATION>
    <HOST>in meadows</HOST>
    <LOCATION>Europe</LOCATION>
    <CORRECTION>https://www.biodiversitylibrary.org/page/359193</CORRECTION>
    <SANCTIONING_x0020_AUTHOR>Fr.$https://www.biodiversitylibrary.org/page/4338017</SANCTIONING_x0020_AUTHOR>
    <SANCTIONING_x0020_REFERENCE_x0020_VOLUME>1</SANCTIONING_x0020_REFERENCE_x0020_VOLUME>
    <SANCTIONING_x0020_REFERENCE_x0020_PAGE>16</SANCTIONING_x0020_REFERENCE_x0020_PAGE>
    <SANCTIONING_x0020_REFERENCE_x0020_YEAR>1821</SANCTIONING_x0020_REFERENCE_x0020_YEAR>
    <SANCTIONING_x0020_REFERENCE_x0020_LITERATURE_x0020_LINK>889</SANCTIONING_x0020_REFERENCE_x0020_LITERATURE_x0020_LINK>
    <LITERATURE_x0020_LINK>1606</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>375287</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>375287</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>375287</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <SQLTimeStamp>AAAAAAhchlo=</SQLTimeStamp>
    <UpdatedBy>AD\mba13kg</UpdatedBy>
    <AddedBy>EGHAM_SQL\kirk</AddedBy>
    <UpdatedDate>2025-08-27T09:54:59.637+01:00</UpdatedDate>
    <AddedDate>2004-08-09T11:44:00+01:00</AddedDate>
    <UUID>8d452a04-f09a-433a-b530-ca2af289cff2</UUID>
    <NAME_x0020_STATUS>Legitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus muscarius var. albus</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>Peck</AUTHORS>
    <SPECIFIC_x0020_EPITHET>muscarius</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>var.</INFRASPECIFIC_x0020_RANK>
    <INFRASPECIFIC_x0020_EPITHET>albus</INFRASPECIFIC_x0020_EPITHET>
    <TYPIFICATION_x0020_DETAILS>Typification: not indicated</TYPIFICATION_x0020_DETAILS>
    <VOLUME>33</VOLUME>
    <PAGE>44</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1883</YEAR_x0020_OF_x0020_PUBLICATION>
    <YEAR_x0020_ON_x0020_PUBLICATION>1880</YEAR_x0020_ON_x0020_PUBLICATION>
    <CORRECTION>https://www.biodiversitylibrary.org/page/35614352</CORRECTION>
    <LITERATURE_x0020_LINK>7700</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>665959</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>665959</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>665959</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <UpdatedBy>AD\pk23kg</UpdatedBy>
    <UpdatedDate>2026-05-25T21:28:40.227+01:00</UpdatedDate>
    <AddedDate>2026-05-25T21:24:42.063+01:00</AddedDate>
    <UUID>5796a030-d773-4222-96c5-61f792ef09c1</UUID>
    <NAME_x0020_STATUS>Legitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus muscarius var. formosus</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>(Pers.) J. Kickx f.</AUTHORS>
    <SPECIFIC_x0020_EPITHET>muscarius</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>var.</INFRASPECIFIC_x0020_RANK>
    <INFRASPECIFIC_x0020_EPITHET>formosus</INFRASPECIFIC_x0020_EPITHET>
    <PAGE>185</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1835</YEAR_x0020_OF_x0020_PUBLICATION>
    <CORRECTION>https://www.biodiversitylibrary.org/page/62999572</CORRECTION>
    <LITERATURE_x0020_LINK>1894</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>537188</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>160520</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>160520</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <UpdatedBy>AD\mba13kg</UpdatedBy>
    <AddedBy>CABI_UK\KIRK</AddedBy>
    <UpdatedDate>2025-08-27T10:01:09.95+01:00</UpdatedDate>
    <AddedDate>2009-10-06T08:59:00+01:00</AddedDate>
    <UUID>5a29c83d-3132-4c48-9293-92f85faf850d</UUID>
    <NAME_x0020_STATUS>Legitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus muscarius var. formosus</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>(Gonn. &amp; Rabenh.) Peck</AUTHORS>
    <SPECIFIC_x0020_EPITHET>muscarius</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>var.</INFRASPECIFIC_x0020_RANK>
    <INFRASPECIFIC_x0020_EPITHET>formosus</INFRASPECIFIC_x0020_EPITHET>
    <VOLUME>33</VOLUME>
    <PAGE>44</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1883</YEAR_x0020_OF_x0020_PUBLICATION>
    <YEAR_x0020_ON_x0020_PUBLICATION>1880</YEAR_x0020_ON_x0020_PUBLICATION>
    <EDITORIAL_x0020_COMMENT>537188$Agaricus muscarius var. formosus J. Kickx f. 1835</EDITORIAL_x0020_COMMENT>
    <NOMENCLATURAL_x0020_COMMENT>Nom. illegit., Art. 53.1</NOMENCLATURAL_x0020_COMMENT>
    <CORRECTION>https://www.biodiversitylibrary.org/page/35614352</CORRECTION>
    <LITERATURE_x0020_LINK>7700</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>505642</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>212977</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>212977</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <UpdatedBy>AD\mba13kg</UpdatedBy>
    <AddedBy>EDMUNDMASON\kirk</AddedBy>
    <UpdatedDate>2025-08-27T09:22:55.04+01:00</UpdatedDate>
    <AddedDate>2008-04-07T08:28:00+01:00</AddedDate>
    <UUID>5d1495f1-bd10-4912-9e54-3b46b5623996</UUID>
    <NAME_x0020_STATUS>Illegitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus muscarius var. puella</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>(Batsch) Sw.</AUTHORS>
    <SPECIFIC_x0020_EPITHET>muscarius</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>var.</INFRASPECIFIC_x0020_RANK>
    <INFRASPECIFIC_x0020_EPITHET>puella</INFRASPECIFIC_x0020_EPITHET>
    <VOLUME>30</VOLUME>
    <PART>2</PART>
    <PAGE>81</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1809</YEAR_x0020_OF_x0020_PUBLICATION>
    <CORRECTION>https://www.biodiversitylibrary.org/page/46996760</CORRECTION>
    <LITERATURE_x0020_LINK>9892</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>496820</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>372222</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>372222</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <UpdatedBy>AD\mba13kg</UpdatedBy>
    <AddedBy>CABI_UK\KIRK</AddedBy>
    <UpdatedDate>2025-08-27T09:59:23.023+01:00</UpdatedDate>
    <AddedDate>2007-03-26T12:36:00+01:00</AddedDate>
    <UUID>5895d9ed-479f-47e0-97e6-0d57c1b1c104</UUID>
    <NAME_x0020_STATUS>Legitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus muscarius var. puella</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>J. Kickx f.</AUTHORS>
    <SPECIFIC_x0020_EPITHET>muscarius</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>var.</INFRASPECIFIC_x0020_RANK>
    <INFRASPECIFIC_x0020_EPITHET>puella</INFRASPECIFIC_x0020_EPITHET>
    <PAGE>185</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1835</YEAR_x0020_OF_x0020_PUBLICATION>
    <EDITORIAL_x0020_COMMENT>496820$Agaricus muscarius var. puella (Batsch) Sw. 1809</EDITORIAL_x0020_COMMENT>
    <NOMENCLATURAL_x0020_COMMENT>Nom. illegit., Art. 53.1</NOMENCLATURAL_x0020_COMMENT>
    <CORRECTION>https://www.biodiversitylibrary.org/page/62999572</CORRECTION>
    <LITERATURE_x0020_LINK>1894</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>507090</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>507090</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>507090</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <UpdatedBy>AD\mba13kg</UpdatedBy>
    <AddedBy>CABI_UK\KIRK</AddedBy>
    <UpdatedDate>2025-08-27T09:22:55.293+01:00</UpdatedDate>
    <AddedDate>2008-10-30T14:30:00+00:00</AddedDate>
    <UUID>5d81ed25-94bb-4735-9ba8-647e8a0a7bed</UUID>
    <NAME_x0020_STATUS>Illegitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus muscarius var. regalis</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>Peck</AUTHORS>
    <SPECIFIC_x0020_EPITHET>muscarius</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>var.</INFRASPECIFIC_x0020_RANK>
    <INFRASPECIFIC_x0020_EPITHET>regalis</INFRASPECIFIC_x0020_EPITHET>
    <TYPIFICATION_x0020_DETAILS>Typification: not indicated</TYPIFICATION_x0020_DETAILS>
    <VOLUME>33</VOLUME>
    <PAGE>44</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1883</YEAR_x0020_OF_x0020_PUBLICATION>
    <YEAR_x0020_ON_x0020_PUBLICATION>1880</YEAR_x0020_ON_x0020_PUBLICATION>
    <CORRECTION>https://www.biodiversitylibrary.org/page/35614352</CORRECTION>
    <LITERATURE_x0020_LINK>7700</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>665960</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>665960</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>665960</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <UpdatedBy>AD\pk23kg</UpdatedBy>
    <UpdatedDate>2026-06-02T12:44:05.993+01:00</UpdatedDate>
    <AddedDate>2026-05-25T21:28:38.553+01:00</AddedDate>
    <UUID>36c993ee-ca75-458b-b17f-da218e94c0a1</UUID>
    <NAME_x0020_STATUS>Legitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus muscarius var. sanguineus</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>J. Kickx f.</AUTHORS>
    <SPECIFIC_x0020_EPITHET>muscarius</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>var.</INFRASPECIFIC_x0020_RANK>
    <INFRASPECIFIC_x0020_EPITHET>sanguineus</INFRASPECIFIC_x0020_EPITHET>
    <VOLUME>2</VOLUME>
    <PAGE>128</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1867</YEAR_x0020_OF_x0020_PUBLICATION>
    <CORRECTION>https://hdl.handle.net/2027/wu.89036490332?urlappend=%3Bseq=140</CORRECTION>
    <LITERATURE_x0020_LINK>1017</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>507350</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>507350</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>507350</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <GSD_x0020_FLAG>GSD25</GSD_x0020_FLAG>
    <UpdatedBy>AD\mba13kg</UpdatedBy>
    <AddedBy>CABI_UK\KIRK</AddedBy>
    <UpdatedDate>2025-08-27T09:59:40.577+01:00</UpdatedDate>
    <AddedDate>2008-10-30T14:30:00+00:00</AddedDate>
    <UUID>6c522a1f-090e-4c64-a939-6411a8f2d274</UUID>
    <NAME_x0020_STATUS>Legitimate</NAME_x0020_STATUS>
    <NameReleaseStatusID>3</NameReleaseStatusID>
  </IndexFungorum>
  <IndexFungorum>
    <NAME_x0020_OF_x0020_FUNGUS>Agaricus muscarius var. umbrinus</NAME_x0020_OF_x0020_FUNGUS>
    <AUTHORS>Peck</AUTHORS>
    <SPECIFIC_x0020_EPITHET>muscarius</SPECIFIC_x0020_EPITHET>
    <INFRASPECIFIC_x0020_RANK>var.</INFRASPECIFIC_x0020_RANK>
    <INFRASPECIFIC_x0020_EPITHET>umbrinus</INFRASPECIFIC_x0020_EPITHET>
    <TYPIFICATION_x0020_DETAILS>Typification: not indicated</TYPIFICATION_x0020_DETAILS>
    <VOLUME>33</VOLUME>
    <PAGE>44</PAGE>
    <YEAR_x0020_OF_x0020_PUBLICATION>1883</YEAR_x0020_OF_x0020_PUBLICATION>
    <YEAR_x0020_ON_x0020_PUBLICATION>1880</YEAR_x0020_ON_x0020_PUBLICATION>
    <CORRECTION>https://www.biodiversitylibrary.org/page/35614352</CORRECTION>
    <LITERATURE_x0020_LINK>7700</LITERATURE_x0020_LINK>
    <RECORD_x0020_NUMBER>665961</RECORD_x0020_NUMBER>
    <BASIONYM_x0020_RECORD_x0020_NUMBER>665961</BASIONYM_x0020_RECORD_x0020_NUMBER>
    <PROTONYM_x0020_RECORD_x0020_NUMBER>665961</PROTONYM_x0020_RECORD_x0020_NUMBER>
    <NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17030</NAME_x0020_OF_x0020_FUNGUS_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME>Amanita muscaria</CURRENT_x0020_NAME>
    <CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>161267</CURRENT_x0020_NAME_x0020_RECORD_x0020_NUMBER>
    <CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>17045</CURRENT_x0020_NAME_x0020_FUNDIC_x0020_RECORD_x0020_NUMBER>

============================================================
  Index Fungorum  (IndexFungorumAPI)
  Species:   Not species
  Name type: not species
============================================================
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

---
## Mushroom Observer

Mushroom Observer is a community-driven database of fungal observations. The JSON API embeds synonym lists directly in each name record, so synonyms require no second network request. Rather than "accepted"/"synonym" labels, Mushroom Observer uses a `deprecated` boolean flag; status is inferred from that field.

Uses the **standard base-class** `get_synonyms()` pipeline.

In [6]:
from scripts.apis_pipe.mushroomobs import MushroomObserverAPI

run_queries([(MUSHROOM_OBSERVER_PORTAL, MushroomObserverAPI(), "Amanita muscaria", "Amanita amerimuscaria")])

============================================================
  Mushroom Observer  (MushroomObserverAPI)
  Species:   Amanita muscaria
  Name type: accepted
============================================================
_fetch_query_data
{'version': 2.0, 'run_date': '2026-06-23T06:27:06.830Z', 'query': 'SELECT DISTINCT `names`.* FROM `names` WHERE (`names`.`id` IN (374, 5066, 16015, 28495, 41324, 59384, 373, 31199, 59289, 109028, 110413, 111780)) AND (`names`.`correct_spelling_id` IS NULL) AND (`names`.`correct_spelling_id` IS NULL) ORDER BY `names`.`id` ASC', 'number_of_records': 7, 'number_of_pages': 1, 'page_number': 1, 'results': [{'id': 373, 'type': 'name', 'name': 'Amanita muscaria', 'author': '(L.) Lam.', 'rank': 'species', 'deprecated': False, 'misspelled': False, 'citation': '<a href="https://biodiversitylibrary.org/page/716703"><cite>Encycl. Méth. Bot.</cite> (Paris) 1: 111</a> (1783)', 'created_at': '2007-01-10T05:03:59.000Z', 'updated_at': '2025-04-02T17:58:46.000Z', 'number_of_views': 7427, 'last_viewed': '2026-06-22T19:14:25.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 31199, 'name': 'Amanita muscarea', 'rank': 'species', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}, {'id': 59289, 'name': 'Amanita mascaria', 'rank': 'species', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}, {'id': 109028, 'name': 'Aminata mascura', 'rank': 'species', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}, {'id': 110413, 'name': 'Aminita muscaria', 'rank': 'species', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}, {'id': 111780, 'name': 'Amanita', 'author': 'Musccaria', 'rank': 'genus', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}], 'comments': [{'id': 43620, 'summary': 'Approved', 'content': 'I understand that the botanical code says that you should use the infra-species autonym, but there is still value in have a page the species as a whole. Consequently, I am approving this name.', 'created_at': '2011-11-02T21:02:01.000Z', 'updated_at': '2011-11-02T21:02:01.000Z', 'owner': {'id': 1, 'login_name': 'nathan', 'legal_name': 'Nathan Wilson'}}]}, {'id': 374, 'type': 'name', 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'misspelled': False, 'citation': 'Bibliotheca Mycologica 57: 56 (1977) [MB#487346]', 'created_at': '2007-01-10T05:03:59.000Z', 'updated_at': '2025-05-23T22:24:35.000Z', 'number_of_views': 1024, 'last_viewed': '2025-12-17T19:19:52.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}], 'comments': [{'id': 45557, 'summary': 'Deprecated', 'content': 'Technically both <a href="https://mushroomobserver.org/lookups/lookup_name/Amanita+muscaria+var.+flavivolvata"><i>Amanita muscaria var. flavivolvata</i></a> and <a href="https://mushroomobserver.org/lookups/lookup_name/Amanita+muscaria+subsp.+flavivolvata"><i>Amanita muscaria subsp. flavivolvata</i></a> are valid. However, to ensure that we aren&#8217;t exporting both to third parties like EOL, I&#8217;m suggesting that we prefer the subspecies. This follows what Rod is currently doing on Amanitaceae.org and I believe there is good evidence that this is a distinct species that will eventually be published as <a href="https://mushroomobserver.org/lookups/lookup_name/Amanita+amerimuscaria"><i>Amanita amerimuscaria</i></a>. Given this subspecies status seems more appropriate than a variety.', 'created_at': '2011-12-13T14:57:29.000Z', 'updated_at': '2011-12-13T14:57:29.000Z', 'owner': {'id': 1, 'login_name': 'nathan', 'legal_name': 'Nathan Wilson'}}]}, {'id': 5066, 'type': 'name', 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'deprecated': False, 'misspelled': False, 'citation': '<a href="https://www.zobodat.at/pdf/Sydowia_11_0354-0374.pdf#page=21"><cite>Sydowia</cite> 11(1-6): 374</a> (1958) [1957]', 'created_at': '2007-09-23T01:34:49.000Z', 'updated_at': '2025-04-02T18:28:07.000Z', 'number_of_views': 3112, 'last_viewed': '2026-05-27T17:26:30.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}]}, {'id': 16015, 'type': 'name', 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'misspelled': False, 'created_at': '2009-02-13T03:42:08.000Z', 'updated_at': '2025-05-23T22:24:33.000Z', 'number_of_views': 3182, 'last_viewed': '2026-06-22T19:14:41.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}], 'comments': [{'id': 167081, 'summary': 'What ever happened to this name?', 'content': '<p>What ever happened to this name?   Was it decided that it didn&#8217;t need to be published because Amanita muscaria subsp. flavivolvata is a good name for this taxon?</p>', 'created_at': '2019-02-20T17:59:29.000Z', 'updated_at': '2019-02-20T17:59:29.000Z', 'owner': {'id': 123, 'login_name': 'Alan Rockefeller', 'legal_name': 'Alan Rockefeller'}}]}, {'id': 28495, 'type': 'name', 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'misspelled': False, 'created_at': '2011-08-10T22:18:52.000Z', 'updated_at': '2025-05-24T22:12:18.000Z', 'number_of_views': 614, 'last_viewed': '2026-06-11T06:55:46.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}]}, {'id': 41324, 'type': 'name', 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'misspelled': False, 'created_at': '2013-11-13T09:11:24.000Z', 'updated_at': '2025-04-02T22:12:09.000Z', 'number_of_views': 84, 'last_viewed': '2024-10-31T03:37:51.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}]}, {'id': 59384, 'type': 'name', 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'misspelled': False, 'notes': '<p>Geographic origin: Santa Cruz Island, California, USA</p>\n<p>Geml, J., Tulloss, R.E., Laursen, G.A., Sazanova, N.A. and Taylor, D.L., 2010. Phylogeographic analyses of a boreal-temperate ectomycorrhizal basidiomycete, Amanita muscaria, suggest forest refugia in Alaska during the last glacial maximum. In Relict Species (pp. 173-186). Springer Berlin Heidelberg.</p>\n<p><a href="http://taylorlabunm.weebly.com/uploads/2/5/0/2/25029144/geml_relict-species-phylogeography-and-conservation-biology_2010.pdf">http://taylorlabunm.weebly.com/...</a></p>', 'created_at': '2016-10-17T14:30:57.000Z', 'updated_at': '2026-04-28T18:32:58.000Z', 'number_of_views': 72, 'last_viewed': '2022-08-31T14:51:37.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}]}], 'run_time': 0.264959015}
_fetch_synonym_data
[{'id': 31199, 'name': 'Amanita muscarea', 'rank': 'species', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}, {'id': 59289, 'name': 'Amanita mascaria', 'rank': 'species', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}, {'id': 109028, 'name': 'Aminata mascura', 'rank': 'species', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}, {'id': 110413, 'name': 'Aminita muscaria', 'rank': 'species', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}, {'id': 111780, 'name': 'Amanita', 'author': 'Musccaria', 'rank': 'genus', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}]
_fetch_accepted_data

============================================================
  Mushroom Observer  (MushroomObserverAPI)
  Species:   Amanita amerimuscaria
  Name type: synonym  (synonym of: Amanita muscaria)
============================================================
_fetch_query_data
{'version': 2.0, 'run_date': '2026-06-23T06:27:07.832Z', 'query': 'SELECT DISTINCT `names`.* FROM `names` WHERE (`names`.`id` IN (374, 5066, 16015, 28495, 41324, 59384)) AND (`names`.`correct_spelling_id` IS NULL) AND (`names`.`correct_spelling_id` IS NULL) ORDER BY `names`.`id` ASC', 'number_of_records': 6, 'number_of_pages': 1, 'page_number': 1, 'results': [{'id': 374, 'type': 'name', 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'misspelled': False, 'citation': 'Bibliotheca Mycologica 57: 56 (1977) [MB#487346]', 'created_at': '2007-01-10T05:03:59.000Z', 'updated_at': '2025-05-23T22:24:35.000Z', 'number_of_views': 1024, 'last_viewed': '2025-12-17T19:19:52.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}], 'comments': [{'id': 45557, 'summary': 'Deprecated', 'content': 'Technically both <a href="https://mushroomobserver.org/lookups/lookup_name/Amanita+muscaria+var.+flavivolvata"><i>Amanita muscaria var. flavivolvata</i></a> and <a href="https://mushroomobserver.org/lookups/lookup_name/Amanita+muscaria+subsp.+flavivolvata"><i>Amanita muscaria subsp. flavivolvata</i></a> are valid. However, to ensure that we aren&#8217;t exporting both to third parties like EOL, I&#8217;m suggesting that we prefer the subspecies. This follows what Rod is currently doing on Amanitaceae.org and I believe there is good evidence that this is a distinct species that will eventually be published as <a href="https://mushroomobserver.org/lookups/lookup_name/Amanita+amerimuscaria"><i>Amanita amerimuscaria</i></a>. Given this subspecies status seems more appropriate than a variety.', 'created_at': '2011-12-13T14:57:29.000Z', 'updated_at': '2011-12-13T14:57:29.000Z', 'owner': {'id': 1, 'login_name': 'nathan', 'legal_name': 'Nathan Wilson'}}]}, {'id': 5066, 'type': 'name', 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'deprecated': False, 'misspelled': False, 'citation': '<a href="https://www.zobodat.at/pdf/Sydowia_11_0354-0374.pdf#page=21"><cite>Sydowia</cite> 11(1-6): 374</a> (1958) [1957]', 'created_at': '2007-09-23T01:34:49.000Z', 'updated_at': '2025-04-02T18:28:07.000Z', 'number_of_views': 3112, 'last_viewed': '2026-05-27T17:26:30.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}]}, {'id': 16015, 'type': 'name', 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'misspelled': False, 'created_at': '2009-02-13T03:42:08.000Z', 'updated_at': '2025-05-23T22:24:33.000Z', 'number_of_views': 3182, 'last_viewed': '2026-06-22T19:14:41.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}], 'comments': [{'id': 167081, 'summary': 'What ever happened to this name?', 'content': '<p>What ever happened to this name?   Was it decided that it didn&#8217;t need to be published because Amanita muscaria subsp. flavivolvata is a good name for this taxon?</p>', 'created_at': '2019-02-20T17:59:29.000Z', 'updated_at': '2019-02-20T17:59:29.000Z', 'owner': {'id': 123, 'login_name': 'Alan Rockefeller', 'legal_name': 'Alan Rockefeller'}}]}, {'id': 28495, 'type': 'name', 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'misspelled': False, 'created_at': '2011-08-10T22:18:52.000Z', 'updated_at': '2025-05-24T22:12:18.000Z', 'number_of_views': 614, 'last_viewed': '2026-06-11T06:55:46.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}]}, {'id': 41324, 'type': 'name', 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'misspelled': False, 'created_at': '2013-11-13T09:11:24.000Z', 'updated_at': '2025-04-02T22:12:09.000Z', 'number_of_views': 84, 'last_viewed': '2024-10-31T03:37:51.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}]}, {'id': 59384, 'type': 'name', 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'misspelled': False, 'notes': '<p>Geographic origin: Santa Cruz Island, California, USA</p>\n<p>Geml, J., Tulloss, R.E., Laursen, G.A., Sazanova, N.A. and Taylor, D.L., 2010. Phylogeographic analyses of a boreal-temperate ectomycorrhizal basidiomycete, Amanita muscaria, suggest forest refugia in Alaska during the last glacial maximum. In Relict Species (pp. 173-186). Springer Berlin Heidelberg.</p>\n<p><a href="http://taylorlabunm.weebly.com/uploads/2/5/0/2/25029144/geml_relict-species-phylogeography-and-conservation-biology_2010.pdf">http://taylorlabunm.weebly.com/...</a></p>', 'created_at': '2016-10-17T14:30:57.000Z', 'updated_at': '2026-04-28T18:32:58.000Z', 'number_of_views': 72, 'last_viewed': '2022-08-31T14:51:37.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}]}], 'run_time': 0.291066592}
_fetch_synonym_data
[{'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}]
_fetch_accepted_data

============================================================
  Mushroom Observer  (MushroomObserverAPI)
  Species:   Not species
  Name type: not species
============================================================
_fetch_query_data
{'version': 2.0, 'run_date': '2026-06-23T06:27:08.834Z', 'errors': [{'code': 'API2::ObjectNotFoundByString', 'details': 'Name "Not species" does not exist, or someone has deleted it.', 'fatal': 'true', 'trace': "/var/web/mo/app/classes/api2/parsers/name_parser.rb:23:in 'API2::Parsers::NameParser#try_finding_by_string'\n/var/web/mo/app/classes/api2/parsers/name_parser.rb:13:in 'API2::Parsers::NameParser#find_object'\n/var/web/mo/app/classes/api2/parsers/object_base.rb:10:in 'API2::Parsers::ObjectBase#parse'\n/var/web/mo/app/classes/api2/parsers/base.rb:25:in 'API2::Parsers::Base#parse_scalar'\n/var/web/mo/app/classes/api2/parsers/base.rb:45:in 'API2::Parsers::Base#parse_array'\n/var/web/mo/app/classes/api2/core/parameters.rb:94:in 'API2::Parameters#parse_array'\n/var/web/mo/app/classes/api2/name_api.rb:23:in 'API2::NameAPI#query_params'\n/var/web/mo/app/classes/api2/model_api.rb:39:in 'API2::ModelAPI#build_query'\n/var/web/mo/app/classes/api2/model_api.rb:11:in 'API2::ModelAPI#get'\n/var/web/mo/app/classes/api2/core/base.rb:295:in 'API2::Base#process_request'\n/var/web/mo/app/classes/api2/core/base.rb:226:in 'API2::Base::ClassMethods#execute'\n/var/web/mo/app/controllers/api2_controller.rb:155:in 'API2Controller#render_api_results'\n/var/web/mo/app/controllers/api2_controller.rb:120:in 'API2Controller#rest_query'\n/var/web/mo/app/controllers/api2_controller.rb:69:in 'API2Controller#names'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_controller/metal/basic_implicit_render.rb:8:in 'ActionController::BasicImplicitRender#send_action'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/abstract_controller/base.rb:215:in 'AbstractController::Base#process_action'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_controller/metal/rendering.rb:193:in 'ActionController::Rendering#process_action'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/abstract_controller/callbacks.rb:261:in 'block in AbstractController::Callbacks#process_action'\n/home/mo/.gem/ruby/3.4.9/gems/activesupport-7.2.3.1/lib/active_support/callbacks.rb:121:in 'block in ActiveSupport::Callbacks#run_callbacks'\n/var/web/mo/app/controllers/application_controller.rb:148:in 'ApplicationController#catch_errors_and_log_request_stats'\n/home/mo/.gem/ruby/3.4.9/gems/activesupport-7.2.3.1/lib/active_support/callbacks.rb:130:in 'block in ActiveSupport::Callbacks#run_callbacks'\n/home/mo/.gem/ruby/3.4.9/gems/turbo-rails-2.0.23/lib/turbo-rails.rb:24:in 'Turbo.with_request_id'\n/home/mo/.gem/ruby/3.4.9/gems/turbo-rails-2.0.23/app/controllers/concerns/turbo/request_id_tracking.rb:10:in 'Turbo::RequestIdTracking#turbo_tracking_request_id'\n/home/mo/.gem/ruby/3.4.9/gems/activesupport-7.2.3.1/lib/active_support/callbacks.rb:130:in 'block in ActiveSupport::Callbacks#run_callbacks'\n/home/mo/.gem/ruby/3.4.9/gems/activesupport-7.2.3.1/lib/active_support/callbacks.rb:141:in 'ActiveSupport::Callbacks#run_callbacks'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/abstract_controller/callbacks.rb:260:in 'AbstractController::Callbacks#process_action'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_controller/metal/rescue.rb:27:in 'ActionController::Rescue#process_action'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_controller/metal/instrumentation.rb:77:in 'block in ActionController::Instrumentation#process_action'\n/home/mo/.gem/ruby/3.4.9/gems/activesupport-7.2.3.1/lib/active_support/notifications.rb:210:in 'block in ActiveSupport::Notifications.instrument'\n/home/mo/.gem/ruby/3.4.9/gems/activesupport-7.2.3.1/lib/active_support/notifications/instrumenter.rb:58:in 'ActiveSupport::Notifications::Instrumenter#instrument'\n/home/mo/.gem/ruby/3.4.9/gems/activesupport-7.2.3.1/lib/active_support/notifications.rb:210:in 'ActiveSupport::Notifications.instrument'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_controller/metal/instrumentation.rb:76:in 'ActionController::Instrumentation#process_action'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_controller/metal/params_wrapper.rb:259:in 'ActionController::ParamsWrapper#process_action'\n/home/mo/.gem/ruby/3.4.9/gems/activerecord-7.2.3.1/lib/active_record/railties/controller_runtime.rb:39:in 'ActiveRecord::Railties::ControllerRuntime#process_action'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/abstract_controller/base.rb:152:in 'AbstractController::Base#process'\n/home/mo/.gem/ruby/3.4.9/gems/actionview-7.2.3.1/lib/action_view/rendering.rb:40:in 'ActionView::Rendering#process'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_controller/metal.rb:252:in 'ActionController::Metal#dispatch'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_controller/metal.rb:335:in 'ActionController::Metal.dispatch'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/routing/route_set.rb:67:in 'ActionDispatch::Routing::RouteSet::Dispatcher#dispatch'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/routing/route_set.rb:50:in 'ActionDispatch::Routing::RouteSet::Dispatcher#serve'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/journey/router.rb:53:in 'block in ActionDispatch::Journey::Router#serve'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/journey/router.rb:133:in 'block in ActionDispatch::Journey::Router#find_routes'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/journey/router.rb:126:in 'Array#each'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/journey/router.rb:126:in 'ActionDispatch::Journey::Router#find_routes'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/journey/router.rb:34:in 'ActionDispatch::Journey::Router#serve'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/routing/route_set.rb:896:in 'ActionDispatch::Routing::RouteSet#call'\n/home/mo/.gem/ruby/3.4.9/gems/rack-3.2.6/lib/rack/tempfile_reaper.rb:20:in 'Rack::TempfileReaper#call'\n/home/mo/.gem/ruby/3.4.9/gems/rack-3.2.6/lib/rack/etag.rb:29:in 'Rack::ETag#call'\n/home/mo/.gem/ruby/3.4.9/gems/rack-3.2.6/lib/rack/conditional_get.rb:31:in 'Rack::ConditionalGet#call'\n/home/mo/.gem/ruby/3.4.9/gems/rack-3.2.6/lib/rack/head.rb:15:in 'Rack::Head#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/http/permissions_policy.rb:38:in 'ActionDispatch::PermissionsPolicy::Middleware#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/http/content_security_policy.rb:38:in 'ActionDispatch::ContentSecurityPolicy::Middleware#call'\n/home/mo/.gem/ruby/3.4.9/gems/rack-session-2.1.2/lib/rack/session/abstract/id.rb:274:in 'Rack::Session::Abstract::Persisted#context'\n/home/mo/.gem/ruby/3.4.9/gems/rack-session-2.1.2/lib/rack/session/abstract/id.rb:268:in 'Rack::Session::Abstract::Persisted#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/middleware/cookies.rb:704:in 'ActionDispatch::Cookies#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/middleware/callbacks.rb:31:in 'block in ActionDispatch::Callbacks#call'\n/home/mo/.gem/ruby/3.4.9/gems/activesupport-7.2.3.1/lib/active_support/callbacks.rb:101:in 'ActiveSupport::Callbacks#run_callbacks'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/middleware/callbacks.rb:30:in 'ActionDispatch::Callbacks#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/middleware/debug_exceptions.rb:31:in 'ActionDispatch::DebugExceptions#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/middleware/show_exceptions.rb:32:in 'ActionDispatch::ShowExceptions#call'\n/home/mo/.gem/ruby/3.4.9/gems/railties-7.2.3.1/lib/rails/rack/logger.rb:41:in 'Rails::Rack::Logger#call_app'\n/home/mo/.gem/ruby/3.4.9/gems/railties-7.2.3.1/lib/rails/rack/logger.rb:29:in 'Rails::Rack::Logger#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/middleware/remote_ip.rb:96:in 'ActionDispatch::RemoteIp#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/middleware/request_id.rb:33:in 'ActionDispatch::RequestId#call'\n/home/mo/.gem/ruby/3.4.9/gems/rack-3.2.6/lib/rack/method_override.rb:28:in 'Rack::MethodOverride#call'\n/home/mo/.gem/ruby/3.4.9/gems/rack-3.2.6/lib/rack/runtime.rb:24:in 'Rack::Runtime#call'\n/home/mo/.gem/ruby/3.4.9/gems/activesupport-7.2.3.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in 'ActiveSupport::Cache::Strategy::LocalCache::Middleware#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/middleware/executor.rb:16:in 'ActionDispatch::Executor#call'\n/home/mo/.gem/ruby/3.4.9/gems/rack-3.2.6/lib/rack/sendfile.rb:131:in 'Rack::Sendfile#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/middleware/ssl.rb:82:in 'ActionDispatch::SSL#call'\n/home/mo/.gem/ruby/3.4.9/gems/railties-7.2.3.1/lib/rails/engine.rb:535:in 'Rails::Engine#call'\n/home/mo/.gem/ruby/3.4.9/gems/puma-8.0.2/lib/puma/configuration.rb:305:in 'Puma::Configuration::ConfigMiddleware#call'\n/home/mo/.gem/ruby/3.4.9/gems/puma-8.0.2/lib/puma/response.rb:79:in 'block in Puma::Response#handle_request'\n/home/mo/.gem/ruby/3.4.9/gems/puma-8.0.2/lib/puma/thread_pool.rb:434:in 'Puma::ThreadPool#with_force_shutdown'\n/home/mo/.gem/ruby/3.4.9/gems/puma-8.0.2/lib/puma/response.rb:78:in 'Puma::Response#handle_request'\n/home/mo/.gem/ruby/3.4.9/gems/puma-8.0.2/lib/puma/server.rb:508:in 'Puma::Server#process_client'\n/home/mo/.gem/ruby/3.4.9/gems/puma-8.0.2/lib/puma/server.rb:263:in 'block in Puma::Server#run'\n/home/mo/.gem/ruby/3.4.9/gems/puma-8.0.2/lib/puma/thread_pool.rb:246:in 'block in Puma::ThreadPool#spawn_thread'"}], 'run_time': 0.060690659}
_fetch_synonym_data
[]
_fetch_accepted_data
[]
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

---
## Tropicos

Tropicos is a botanical nomenclature database maintained by the Missouri Botanical Garden, covering vascular plants, bryophytes, algae, and fungi. **Requires a `TROPICOS_API_KEY` in your `.env` file.**

**Custom `get_synonyms()` orchestration.** Unlike the base class, which passes raw data through a fixed pipeline, Tropicos resolves the accepted `NameId` explicitly before fetching synonyms. The fetch sequence is:

1. `_fetch_query_data` — name search
2. `_fetch_accepted_list` — `/Name/{id}/AcceptedNames`, used for ID resolution only
3. `_extract_internal_accepted_id` — reads the accepted NameId (no API call)
4. `_fetch_synonym_data` — `/Name/{accepted_id}/Synonyms`
5. `_fetch_accepted_data` — `/Name/Search` by NameId *(only when the queried name is a synonym; otherwise `raw_data` is reused directly to avoid a redundant fetch)*

This two-step ID resolution is necessary because Tropicos's synonym endpoint requires the *accepted* name's ID, not the queried name's ID — and the queried name may itself be a synonym.

In [7]:
from scripts.apis_pipe.tropicos import TropicosAPI

run_queries([(TROPICOS_PORTAL, TropicosAPI(), "Quercus robur", "Quercus pedunculata")])

============================================================
  Tropicos  (TropicosAPI)
  Species:   Quercus robur
  Name type: accepted
============================================================
_fetch_query_data
[{'NameId': 13100004, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur L.', 'Family': 'Fagaceae', 'RankAbbreviation': 'sp.', 'NomenclatureStatusID': 1, 'NomenclatureStatusName': 'Legitimate', 'Symbol': '!', 'Author': 'L.', 'DisplayReference': 'Sp. Pl. 2: 996', 'DisplayDate': '1753', 'TotalRows': 2}, {'NameId': 50280607, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur (Ten.) A. DC.', 'Family': 'Fagaceae', 'RankAbbreviation': 'sp.', 'NomenclatureStatusName': 'No opinion', 'Author': '(Ten.) A. DC.', 'DisplayReference': 'Prodr. 16(2): 5', 'DisplayDate': '1864', 'TotalRows': 2}]
_fetch_accepted_list
[{'Error': 'No accepted names were found'}]
_fetch_synonym_data
[{'SynonymName': {'NameId': 13100434, 'ScientificName': 'Quercus pedunculata', 'ScientificNameWithAuthors': 'Quercus pedunculata Ehrh.', 'Family': 'Fagaceae'}, 'AcceptedName': {'NameId': 13100004, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur L.', 'Family': 'Fagaceae'}, 'Reference': {'ReferenceId': 23908, 'PublicationId': 15422, 'AuthorString': 'Czerepanov, S. K.', 'Collation': '509 pages', 'AbbreviatedTitle': 'Sosud. Rast. SSSR', 'TitlePageYear': '1981'}}, {'SynonymName': {'NameId': 13101404, 'ScientificName': 'Quercus robur subsp. eurobur', 'ScientificNameWithAuthors': 'Quercus robur subsp. eurobur A. Camus', 'Family': 'Fagaceae'}, 'AcceptedName': {'NameId': 13100004, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur L.', 'Family': 'Fagaceae'}, 'Reference': {'ReferenceId': 42480, 'PublicationId': 11746, 'AuthorString': 'Flora of China Editorial Committee', 'ArticleTitle': 'Flora of China (Checklist & Addendum)', 'Collation': 'Unpaginated', 'AbbreviatedTitle': 'Fl. China', 'TitlePageYear': '1988-2013'}}]
_fetch_accepted_data
[{'NameId': 13100004, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur L.', 'Family': 'Fagaceae', 'RankAbbreviation': 'sp.', 'NomenclatureStatusID': 1, 'NomenclatureStatusName': 'Legitimate', 'Symbol': '!', 'Author': 'L.', 'DisplayReference': 'Sp. Pl. 2: 996', 'DisplayDate': '1753', 'TotalRows': 2}, {'NameId': 50280607, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur (Ten.) A. DC.', 'Family': 'Fagaceae', 'RankAbbreviation': 'sp.', 'NomenclatureStatusName': 'No opinion', 'Author': '(Ten.) A. DC.', 'DisplayReference': 'Prodr. 16(2): 5', 'DisplayDate': '1864', 'TotalRows': 2}]
Synonyms returned: 2

============================================================
  Tropicos  (TropicosAPI)
  Species:   Quercus pedunculata
  Name type: synonym  (synonym of: Quercus robur)
============================================================
_fetch_query_data
[{'NameId': 13100434, 'ScientificName': 'Quercus pedunculata', 'ScientificNameWithAuthors': 'Quercus pedunculata Ehrh.', 'Family': 'Fagaceae', 'RankAbbreviation': 'sp.', 'NomenclatureStatusID': 3, 'NomenclatureStatusName': 'Invalid', 'Symbol': '**', 'Author': 'Ehrh.', 'DisplayReference': 'Beitr. Naturk. 5: 161', 'DisplayDate': '1790', 'TotalRows': 2}, {'NameId': 50280903, 'ScientificName': 'Quercus pedunculata', 'ScientificNameWithAuthors': 'Quercus pedunculata Hoffm.', 'Family': 'Fagaceae', 'RankAbbreviation': 'sp.', 'NomenclatureStatusName': 'No opinion', 'Author': 'Hoffm.', 'DisplayReference': 'Deutschl. Fl. 1: 338', 'DisplayDate': '1791', 'TotalRows': 2}]
_fetch_accepted_list
[{'SynonymName': {'NameId': 13100434, 'ScientificName': 'Quercus pedunculata', 'ScientificNameWithAuthors': 'Quercus pedunculata Ehrh.', 'Family': 'Fagaceae'}, 'AcceptedName': {'NameId': 13100004, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur L.', 'Family': 'Fagaceae'}, 'Reference': {'ReferenceId': 23908, 'PublicationId': 15422, 'AuthorString': 'Czerepanov, S. K.', 'Collation': '509 pages', 'AbbreviatedTitle': 'Sosud. Rast. SSSR', 'TitlePageYear': '1981'}}]
_fetch_synonym_data
[{'SynonymName': {'NameId': 13100434, 'ScientificName': 'Quercus pedunculata', 'ScientificNameWithAuthors': 'Quercus pedunculata Ehrh.', 'Family': 'Fagaceae'}, 'AcceptedName': {'NameId': 13100004, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur L.', 'Family': 'Fagaceae'}, 'Reference': {'ReferenceId': 23908, 'PublicationId': 15422, 'AuthorString': 'Czerepanov, S. K.', 'Collation': '509 pages', 'AbbreviatedTitle': 'Sosud. Rast. SSSR', 'TitlePageYear': '1981'}}, {'SynonymName': {'NameId': 13101404, 'ScientificName': 'Quercus robur subsp. eurobur', 'ScientificNameWithAuthors': 'Quercus robur subsp. eurobur A. Camus', 'Family': 'Fagaceae'}, 'AcceptedName': {'NameId': 13100004, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur L.', 'Family': 'Fagaceae'}, 'Reference': {'ReferenceId': 42480, 'PublicationId': 11746, 'AuthorString': 'Flora of China Editorial Committee', 'ArticleTitle': 'Flora of China (Checklist & Addendum)', 'Collation': 'Unpaginated', 'AbbreviatedTitle': 'Fl. China', 'TitlePageYear': '1988-2013'}}]
_fetch_accepted_data
[{'NameId': 13100004, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur L.', 'Family': 'Fagaceae', 'RankAbbreviation': 'sp.', 'NomenclatureStatusID': 1, 'NomenclatureStatusName': 'Legitimate', 'Symbol': '!', 'Author': 'L.', 'DisplayReference': 'Sp. Pl. 2: 996', 'DisplayDate': '1753', 'TotalRows': 1}]
Synonyms returned: 2

============================================================
  Tropicos  (TropicosAPI)
  Species:   Not species
  Name type: not species
============================================================
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

---
## FishBase

FishBase is the world's largest online information system for fish species. It does not expose a public API, so this client scrapes two HTML pages per query: the species summary page (which redirects any name — accepted or synonym — to the accepted species page via a `SpecCode`) and the nomenclature page (which lists all names with status, author, and species code as anchor tag parameters). Subspecific names and misspellings are excluded during compilation.

Uses the **standard base-class** `get_synonyms()` pipeline.

In [8]:
from scripts.apis_pipe.fishbase import FishBaseAPI

run_queries([(FISHBASE_PORTAL, FishBaseAPI(), "Gadus morhua", "Gadus callarias")])

============================================================
  FishBase  (FishBaseAPI)
  Species:   Gadus morhua
  Name type: accepted
============================================================
_fetch_query_data
    <!-- Display Cookie Consent Banner -->
    <link rel="stylesheet" type="text/css" href="/css/cookie-consent.css">

    <div id="cookie-consent-container" style="display:none;">
        <div id="cookie-consent-banner">
            <div class="cookie-consent-banner-item">
                <p>
                   This website uses cookies to enhance your browsing experience and ensure the functionality of our site. For more detailed information about the types of cookies we use and how we protect your privacy, please visit our <a href='../cookieMoreinfo.php' target='_blank'>Privacy Information</a> page.
                </p>
            </div>
            <div class="cookie-consent-banner-item">
                <button id="accept-all">Accept All</button>
                <button id="accept-necessary">Accept Necessary Cookies Only</button>
                <button id="cookie-settings">Cookie Settings</button>
            </div>
        </div>
    </div>

    <!-- Overlay -->
    <div id="overlay"></div>

    <!-- Cookie Settings Dialog -->
    <div id="cookie-settings-dialog">
        <span id="close-dialog">&times;</span>
        <h3>Cookie Settings</h3>
        <p>This website uses different types of cookies to enhance your experience. Please select your preferences below:</p>

        <label>
           <div class="cookie-categ">
                <span>Strictly Necessary</span>
                <label class="switch">

                    <input type="checkbox" id="necessary-toggle" checked disabled>
                    <span class="slider"></span>
                </label>
            </div>
            <p>
                These cookies are essential for the website to function properly. They include session cookies, which help maintain your session while you navigate the site, as well as cookies that remember your language preferences and other essential functionalities. Without these cookies, certain features of the website cannot be provided.
            </p>
        </label>

        <label>
            <div class="cookie-categ">
                <span>Performance</span>
                <label class="switch">
                    <input type="checkbox" id="performance-toggle">
                    <span class="slider"></span>
                </label>
            </div>
            <p>
                These cookies help us understand how visitors interact with our website by collecting and reporting information anonymously. For example, we use Google Analytics to generate web statistics, which helps us improve our website's performance and user experience. These cookies may track information such as the pages visited, time spent on the site, and any errors encountered.
            </p>
        </label>

        <button id="save-close">Save and Close</button>
    </div>
    <script src='/libs/jquery/scripts/cookie.js'></script>
<!DOCTYPE html>
<html xmlns="https://www.w3.org/1999/xhtml" xml:lang="en" lang="en" xmlns:fb="http://ogp.me/ns/fb#">

<head>
	<meta property="og:title" content="Gadus morhua summary page" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="https://www.fishbase.us/summary/Gadus-morhua.html" />
	<meta property="og:image" content="https://www.fishbase.us/images/thumbnails/jpg/tn_Gamor_u3.jpg" />
	<meta property="og:site_name" content="FishBase" />
	<meta property="fb:app_id" content="149230358545215" />

	<meta charset="utf-8">
	<meta name='keywords' content="Gadus morhua, Atlantic cod, , Cods and haddocks, gamefish , maturity">
	<title>Gadus morhua,  Atlantic cod  : fisheries, aquaculture, gamefish</title>
	<link rel="stylesheet" href="/fishbase.css" type="text/css">
	<link rel="stylesheet" href="/css/speciessummary_layout.css" type="text/css">

	<link rel="stylesheet" href="/css/spsum.css" type="text/css">
	<link href="/libs/jquery/css/jquery-ui-custom.css" rel="stylesheet" type="text/css"/>
	<script language="javascript" src="/includes/ajax/ajax.js"></script>
	<script type="text/javascript" src="/libs/jquery/jquery.js"></script>
	<script src='/libs/jquery/jquery-ui-min.js'></script>
	<script src='/libs/jquery/scripts/speciessummary.js'></script>
	<script src="/jquery/ImageAspectRatio.js"></script>
	<!--
	<script>
	  window.fbAsyncInit = function() {
		FB.init({
		  appId      : '149230358545215', // App ID
		  channelUrl : 'https://www.fishbase.us/channel.php', // Channel File
		  status     : true, // check login status
		  cookie     : true, // enable cookies to allow the server to access the session
		  xfbml      : true  // parse XFBML
		});
		// Track likes in google analytics
		FB.Event.subscribe('edge.create', function(targetUrl) {
			_gaq.push(['_trackSocial', 'facebook', 'like', targetUrl]);
		});
		// Track unlikes in google analytics
		FB.Event.subscribe('edge.remove', function(targetUrl) {
		  _gaq.push(['_trackSocial', 'facebook', 'unlike', targetUrl]);
		});
		// Track Share in google analytics
		FB.Event.subscribe('message.send', function(targetUrl) {
		  _gaq.push(['_trackSocial', 'facebook', 'send', targetUrl]);
		});
		// Additional initialization code here
	  };

	  // Load the SDK Asynchronously
	  (function(d){
		 var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
		 if (d.getElementById(id)) {return;}
		 js = d.createElement('script'); js.id = id; js.async = true;
		 js.src = "//connect.facebook.net/en_US/all.js";
		 ref.parentNode.insertBefore(js, ref);
	   }(document));
	</script>

	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=149230358545215";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
	-->
	</head>

<body>
	<!-- AD section -->
	<div id="ss-ad">
			</div>

	<div id="ss-container">
		<!-- Search Box -->
		<div id="search-box" title="Search FishBase" style="display:none">
			<p>Common name (e.g. trout)</p>
			<form name="fn_comnames" action="/ComNames/CommonNameSearchList.php" method="post">
				<input type="hidden" name="crit1_fieldname" value="COMNAMES.ComName">
				<input type="hidden" name="lang" value="English">
				<input type="hidden" name="resultPage" value="1" />
				<input type="hidden" name="crit1_fieldtype" value="CHAR">

				<select name="crit1_operator" size="1">
					<option value="CONTAINS">contains</option>
					<option value="BEGINS_WITH">begins with</option>
					<option value="BEGINS_WITH">begins with</option>
					<option value="ENDS_WITH">ends with</option>
					<option value="EQUAL" selected>is</option>
				</select>
				<input type="text" name="CommonName" id="CommonName" value=""/>
				<input type="submit" value="search" />
			</form>

			<p>Genus + Species (e.g. Gadus morhua)</p>
			<form name="fn_genspec" action="/Nomenclature/ScientificNameSearchList.php?" method="post">
				<input name="gs" id="gs" size="35" value=""/>
				<input type="hidden" name="group" value="summary" />
				<input type="submit" value="search"/>
			</form>
		</div>
		<!-- Top Menu -->
		<div id="ss-topmenu" class="slabel7">
			<!-- <fb:like href="https://www.fishbase.us/summary/Gadus-morhua.html" layout="button_count" width="50" ref="top_sspage"></fb:like> -->
			<!-- Begin Mod 03/15/17 Shelumiel Ortiz
			<a href='https://fishbase.us/donate/donate.php'  ><img src='/images/gifs/DonateButton.gif' width='90' alt=''></a>
			End Mod 03/15/17 Shelumiel Ortiz -->
			<div>

		<div id='ss-heading'>
		<div class='logo'>
		<a href='/search.php'>
			<img src='/images/png/fb3.png' alt='Back to search' title='Go back to Search page'>
		</a>
		</div>
		<nav>
		<ul class='menu-list'>
			<li class='menu-item'>
				<a href='#' title='About this page' style='min-height: 23px;'>About this page <span class='arrow'>▾</span></a>
				<ul class='submenu'>
					<li><a href='/manual/English/fishbasethe_SPECIES_table.htm' title='More Info on species'>More Info</a></li>
					<li><a href='/manual/French/FishBaseNomenclature.htm#00358710' title='Plus d info'>Plus d'info</a></li>
					<li><a href='/manual/Portuguese/Nomenclature.htm#The_Species_table' title='Mais info'>Mais info</a></li>
				</ul>
			</li>
			<li class='menu-item'>
				<a href='#' title='Languages' style='min-height: 23px;'>Languages <span class='arrow'>▾</span></a>
				<ul class='submenu'>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=arabic' title='Arabic'>Arabic</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=bahasa' title='Bahasa Malay/Indonesian'>Bahasa Malay/Indonesian</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=bangla' title='Bangla'>Bangla</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=scchinese' title='Simplified Chinese'>Chinese(Si)</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=chinese' title='Traditional Chinese'>Chinese(Tr)</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=german' title='German'>Deutsch</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=English' title='English'>English</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=spanish' title='Spanish'>Español</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=farsi' title='Farsi'>Farsi</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=french' title='French'>Français</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=greek' title='Greek'>Greek</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=hindi' title='Hindi'>Hindi</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=italian' title='Italian'>Italiano</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=japanese' title='Japanese'>Japanese</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=laos' title='Lao'>Lao</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=dutch' title='Dutch'>Nederlands</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=portuguese' title='Portuguese-Brasil'>Português(Br)</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=portuguese_po' title='Portuguese-Portugal'>Português(Pt)</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=russian' title='Russian'>Russian</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=swedish' title='Swedish'>Swedish</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=thai' title='Thai'>Thai</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=vietnamese' title='Vietnamese'>Vietnamese</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=myanmar' title='Myanmar'>Myanmar</a></li>
				</ul>
			</li>
			<li class='menu-item'>
				<a href='#' title='Send us a Feedback' style='min-height: 23px;'>User feedbacks <span class='arrow'>▾</span></a>
				<ul class='submenu'>
					<li><a href='javascript:document.mailx.submit()' title='Send us your Comments & Corrections'>Comments & Corrections&emsp13;</a></li>
					<li><a href='../facebooklinks.php' title='Explore our community support' target='_blank'>Facebook</a></li>
				</ul>
			</li>
			<li class='menu-item'>
				<a href='../summary/citation.php' title='How to cite FishBase' style='min-height: 23px;'>Citation</a>
			</li>
			<li class='menu-item'>
				<a href='#' title='Uploads Gadus morhua' style='min-height: 23px;'>Uploads <span class='arrow'>▾</span></a>
				<ul class='submenu'>
					<li><a href='https://www.fishbase.us/FishWatcher/url_addform.php?speccode=69' title='Attach your web site to this page'>Attach website</a></li>
					<li><a href='https://www.fishbase.us/tools/UploadPhoto/start.php?speccode=69' title='Upload photo -  Gadus morhua'>Upload photo</a></li>
					<li><a href='/tools/UploadVideo/start_info.php?speccode=69' title='Upload video - Gadus morhua'>Upload video</a></li>
					<li><a href='https://www.fishbase.us/tools/upload-ref/start.php?speccode=69'>Upload references&emsp13;</a></li>
					<li><a href='https://www.fishbase.us/FishWatcher/checkpassword.php?Genus=Gadus&Species=morhua&vtable=contribution_a'>Fish Watcher</a></li>
				</ul>
			</li>
			<li class='menu-item'>
				<a fref='#' title='Restricted - Gadus morhua' style='min-height: 23px;'>Related species <span class='arrow'>▾</span></a>
				<ul class='submenu'>
					<li><a style = 'width:121px;' href='../identification/SpeciesList.php?genus=Gadus' title='Species in Gadus'>Species in <i>Gadus</i></a></li>
					<li><a style = 'width:121px;' href='/identification/SpeciesList.php?famcode=183&areacode=&spines=&fins=' title='Species in Gadidae'>Species in <i>Gadidae</a></i></li>
				<li style='background: #02CDE5; text-align:center;'>- Classification -</li>
						<li><a style = 'width:121px;' href='/summary/FamilySummary.php?ID=183' class='sciname' title='Family'>Gadidae</a></li>
						<li><a style = 'width:121px;' href='/summary/OrdersSummary.php?order=Gadiformes' class='sciname' title='Order'>Gadiformes</a></li>
						<li><a style = 'width:121px; color:#D9D9D9;' href='#' class='sciname' title='Class'>Teleostei</a></li>
						<li><a style = 'width:121px; color:#D9D9D9;' href='#' class='sciname' title='Phylum'>Chordata</a></li>
						<li><a style = 'width:121px; color:#D9D9D9;' href='#' class='sciname' title='Kingdom'>Animalia</a></li>
				</ul>
			</li>
		</ul>
	</nav>
	<div class='logo'>
		<a id='search-button' href='#'>
		<img src='/images/png/search-logo-new.png' alt='Search' title='Search names'>
		</a>
	</div>
	<div  class='logo'>
		<a href='https://www.facebook.com/FishBaseProject/' target='_blank'>
			<img src='/images/png/search-fb.png' height='35' border='0'/>
		</a>
	</div>
	<div  class='logo'>
		<a href='/donate/donate.php'><img src='/images/gifs/DonateButton.gif' width='90' alt=''></a>
	</div>
	</div>			</div>
		</div>

		<!-- Sci name, Author, FBname section -->
		<div id="ss-sciname">
			<h1>
				<span class='sciname'><b><a href='http://researcharchive.calacademy.org/research/ichthyology/catalog/fishcatget.asp?genid=113' alt='Catalog of Fishes - Genera' title='Catalog of Fishes - Genera' target='_blank'>Gadus</a></b></span> <span class='sciname'><b><a href='http://researcharchive.calacademy.org/research/ichthyology/catalog/fishcatget.asp?spid=12302' alt='Catalog of Fishes - Species' title='Catalog of Fishes - Species' target='_blank'>morhua</a></b></span> <span class='sheader6 noLinkDesign'><a href='http://en.wikipedia.org/wiki/Carl_Linnaeus' alt='Wiki' title='Wiki' target='_blank'>Linnaeus</a></span>, <span class='sheader6 noLinkDesign'><a href='http://researcharchive.calacademy.org/research/ichthyology/catalog/getref.asp?id=2787' alt='Catalog of Fishes - References' title='Catalog of Fishes - References' target='_blank'>1758</a></span>			</h1>
			<span class='sheader2'>
				Atlantic cod			</span>
		</div>
		<!-- Map and photo container -->


		<div id="ss-photomap-container">
							<!-- Aquamaps -->
				<div id="ss-map">
					Add your observation in <a href='https://www.fishbase.us/FishWatcher/checkpassword.php?Genus=Gadus&Species=morhua&vtable=contribution_a'>Fish Watcher</a><div class="aquamaps"><center>
<table border='1' cellpadding='2' cellspacing='0' style='font-size : xx-small; font-family : Arial;' width = '350'>
	<tr>
		<td align='center'>
<a href='#' onmouseover='javascript:document.getElementById(&quot;pix&quot;).src=&quot;/images/aquamaps/native/pic_Fis-29394.jpg&quot;'>
Native range</a> |
	<a href='#' onmouseover='javascript:document.getElementById(&quot;pix&quot;).src=&quot;/images/aquamaps/suitable/pic_Fis-29394.jpg&quot;'>
	All suitable habitat</a> |
	<a href='#' onmouseover='javascript:document.getElementById(&quot;pix&quot;).src=&quot;/images/aquamaps/pointmap/pic_Fis-29394.jpg&quot;'>
	Point map</a> |
	<a href='#' onmouseover='javascript:document.getElementById(&quot;pix&quot;).src=&quot;/images/aquamaps/2050/pic_Fis-29394.jpg&quot;'>
	Year 2050</a></td>
	</tr>
	<tr>
		<td align='center'>
			<a target='am_Fis-29394' href='//www.aquamaps.org/preMap.php?cache=1&SpecID=Fis-29394'>
				<img id='pix' src='/images/aquamaps/native/pic_Fis-29394.jpg' alt=''>
			</a>
		</td>
	</tr>
	<tr>
		<td align='center' style='font-size : xx-small;'>This map was computer-generated and has not yet been reviewed.</td>
	</tr>
	<tr>
		<td align='center' style='font-size : xx-small;'><font style='font-family : Arial;'>
		<a target='fb_Fis-29394' href='http:///summary/SpeciesSummary.php?genusname=Gadus&speciesname=morhua'><i>Gadus morhua</i></a>
		&nbsp;
		<a target='am_org' href='http://www.aquamaps.org'>AquaMaps</a>
		&nbsp;
		Data sources: 	<a target='gbif_Fis-29394' href='http://data.gbif.org/occurrences/searchProviders.htm?c[0].s=0&c[0].p=0&c[0].o=Gadus morhua&c[1].s=28&c[1].p=0&c[1].o=0'>GBIF</a>
						<a target='obis_Fis-29394' href='http://www.iobis.org/OBISWEB/ObisControllerServlet?category=all&names=data&tableName=0&searchName=126436&x=51&y=9'>OBIS</a>
		</font></td>
	</tr>
</table></center></div>				</div>

						<!-- Species Photo -->
						<div id="ss-photo">
				<span>
					Upload your <a href='https://www.fishbase.us/tools/UploadPhoto/start.php?speccode=69'>photos</a>&nbsp;and&nbsp;<a href='/tools/UploadVideo/start_info.php?speccode=69'>videos</a><BR />				</span>
				<span class="slabel8">
				<a href='../photos/ThumbnailsSummary.php?ID=69'>Pictures</a> | <a href='/videos/SpeciesVideos.php?speccode=69'>
					Videos |</a> 	<a href='../physiology/FishSoundsList.php?id=69'>
					Sounds
				</a>
			 | <a href='../photos/SpeciesStampsList.php?speccode=69'>Stamps, coins, misc.</a> | <a href='https://www.google.com/images?hl=en&q=Gadus+morhua&btnG=Search+Images&gbv=2'>Google image</a><div><a style='text-decoration:none;' href='/photos/ThumbnailsSummary.php?ID=69'><img style='margin-top: 0; margin-bottom: 0;' name='prefimage' src='/images/thumbnails/jpg/tn_Gamor_u3.jpg' title ='Image of Gadus morhua (Atlantic cod)' alt='Image of Gadus morhua (Atlantic cod)' border='0' ></a></div><span class='sciname slabel8'>Gadus morhua</span><br/><span class='slabelPicAuthor' >
					Picture by
					<a href='/collaborators/CollaboratorSummary.php?ID=40'>
					Morris, P.</a><br />
					</span><!--<script src="/libs/jquery/jquery.js"></script>-->
<link rel="stylesheet" href="/css/swipeslider.css">
<script src="/libs/jquery/swipeslider/swipeslider.min.js"></script>
<script>
$(window).load(function() {
	if($("#ss-photo-full").length > 0){			//the photo is full width
		$('#image-slider').swipeslider({sliderHeight:'27%', autoPlayTimeout: 8000});
	}else{
		$('#image-slider').swipeslider({sliderHeight:'52%', autoPlayTimeout: 8000});
	}
});
</script>
<style>
.swipslider{
	max-width: 310px;
	margin:	auto;
}

</style>					<!--<span class='sciname'>
											</span>
					<br/>
					<span class="slabel8">
											</span>-->
				</span>
			</div> <!-- ss-photo -->
		</div> <!-- ss-photomap-container -->

		<!-- Main Content -->
		<div id="ss-main">
			<p> <!-- CLASSIFICATION / NAMES -->
			<h1 class='slabel sleft bottomBorder'>
				Classification / Names  				<span class="addLinks"> <!-- not bold -->

============================================================
  FishBase  (FishBaseAPI)
  Species:   Gadus callarias
  Name type: synonym  (synonym of: Gadus morhua)
============================================================
_fetch_query_data
    <!-- Display Cookie Consent Banner -->
    <link rel="stylesheet" type="text/css" href="/css/cookie-consent.css">

    <div id="cookie-consent-container" style="display:none;">
        <div id="cookie-consent-banner">
            <div class="cookie-consent-banner-item">
                <p>
                   This website uses cookies to enhance your browsing experience and ensure the functionality of our site. For more detailed information about the types of cookies we use and how we protect your privacy, please visit our <a href='../cookieMoreinfo.php' target='_blank'>Privacy Information</a> page.
                </p>
            </div>
            <div class="cookie-consent-banner-item">
                <button id="accept-all">Accept All</button>
                <button id="accept-necessary">Accept Necessary Cookies Only</button>
                <button id="cookie-settings">Cookie Settings</button>
            </div>
        </div>
    </div>

    <!-- Overlay -->
    <div id="overlay"></div>

    <!-- Cookie Settings Dialog -->
    <div id="cookie-settings-dialog">
        <span id="close-dialog">&times;</span>
        <h3>Cookie Settings</h3>
        <p>This website uses different types of cookies to enhance your experience. Please select your preferences below:</p>

        <label>
           <div class="cookie-categ">
                <span>Strictly Necessary</span>
                <label class="switch">

                    <input type="checkbox" id="necessary-toggle" checked disabled>
                    <span class="slider"></span>
                </label>
            </div>
            <p>
                These cookies are essential for the website to function properly. They include session cookies, which help maintain your session while you navigate the site, as well as cookies that remember your language preferences and other essential functionalities. Without these cookies, certain features of the website cannot be provided.
            </p>
        </label>

        <label>
            <div class="cookie-categ">
                <span>Performance</span>
                <label class="switch">
                    <input type="checkbox" id="performance-toggle">
                    <span class="slider"></span>
                </label>
            </div>
            <p>
                These cookies help us understand how visitors interact with our website by collecting and reporting information anonymously. For example, we use Google Analytics to generate web statistics, which helps us improve our website's performance and user experience. These cookies may track information such as the pages visited, time spent on the site, and any errors encountered.
            </p>
        </label>

        <button id="save-close">Save and Close</button>
    </div>
    <script src='/libs/jquery/scripts/cookie.js'></script>
<!DOCTYPE html>
<html xmlns="https://www.w3.org/1999/xhtml" xml:lang="en" lang="en" xmlns:fb="http://ogp.me/ns/fb#">

<head>
	<meta property="og:title" content="Gadus morhua summary page" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="https://www.fishbase.us/summary/Gadus-morhua.html" />
	<meta property="og:image" content="https://www.fishbase.us/images/thumbnails/jpg/tn_Gamor_u3.jpg" />
	<meta property="og:site_name" content="FishBase" />
	<meta property="fb:app_id" content="149230358545215" />

	<meta charset="utf-8">
	<meta name='keywords' content="Gadus morhua, Atlantic cod, , Cods and haddocks, gamefish , maturity">
	<title>Gadus morhua,  Atlantic cod  : fisheries, aquaculture, gamefish</title>
	<link rel="stylesheet" href="/fishbase.css" type="text/css">
	<link rel="stylesheet" href="/css/speciessummary_layout.css" type="text/css">

	<link rel="stylesheet" href="/css/spsum.css" type="text/css">
	<link href="/libs/jquery/css/jquery-ui-custom.css" rel="stylesheet" type="text/css"/>
	<script language="javascript" src="/includes/ajax/ajax.js"></script>
	<script type="text/javascript" src="/libs/jquery/jquery.js"></script>
	<script src='/libs/jquery/jquery-ui-min.js'></script>
	<script src='/libs/jquery/scripts/speciessummary.js'></script>
	<script src="/jquery/ImageAspectRatio.js"></script>
	<!--
	<script>
	  window.fbAsyncInit = function() {
		FB.init({
		  appId      : '149230358545215', // App ID
		  channelUrl : 'https://www.fishbase.us/channel.php', // Channel File
		  status     : true, // check login status
		  cookie     : true, // enable cookies to allow the server to access the session
		  xfbml      : true  // parse XFBML
		});
		// Track likes in google analytics
		FB.Event.subscribe('edge.create', function(targetUrl) {
			_gaq.push(['_trackSocial', 'facebook', 'like', targetUrl]);
		});
		// Track unlikes in google analytics
		FB.Event.subscribe('edge.remove', function(targetUrl) {
		  _gaq.push(['_trackSocial', 'facebook', 'unlike', targetUrl]);
		});
		// Track Share in google analytics
		FB.Event.subscribe('message.send', function(targetUrl) {
		  _gaq.push(['_trackSocial', 'facebook', 'send', targetUrl]);
		});
		// Additional initialization code here
	  };

	  // Load the SDK Asynchronously
	  (function(d){
		 var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
		 if (d.getElementById(id)) {return;}
		 js = d.createElement('script'); js.id = id; js.async = true;
		 js.src = "//connect.facebook.net/en_US/all.js";
		 ref.parentNode.insertBefore(js, ref);
	   }(document));
	</script>

	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=149230358545215";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
	-->
	</head>

<body>
	<!-- AD section -->
	<div id="ss-ad">
			</div>

	<div id="ss-container">
		<!-- Search Box -->
		<div id="search-box" title="Search FishBase" style="display:none">
			<p>Common name (e.g. trout)</p>
			<form name="fn_comnames" action="/ComNames/CommonNameSearchList.php" method="post">
				<input type="hidden" name="crit1_fieldname" value="COMNAMES.ComName">
				<input type="hidden" name="lang" value="English">
				<input type="hidden" name="resultPage" value="1" />
				<input type="hidden" name="crit1_fieldtype" value="CHAR">

				<select name="crit1_operator" size="1">
					<option value="CONTAINS">contains</option>
					<option value="BEGINS_WITH">begins with</option>
					<option value="BEGINS_WITH">begins with</option>
					<option value="ENDS_WITH">ends with</option>
					<option value="EQUAL" selected>is</option>
				</select>
				<input type="text" name="CommonName" id="CommonName" value=""/>
				<input type="submit" value="search" />
			</form>

			<p>Genus + Species (e.g. Gadus morhua)</p>
			<form name="fn_genspec" action="/Nomenclature/ScientificNameSearchList.php?" method="post">
				<input name="gs" id="gs" size="35" value=""/>
				<input type="hidden" name="group" value="summary" />
				<input type="submit" value="search"/>
			</form>
		</div>
		<!-- Top Menu -->
		<div id="ss-topmenu" class="slabel7">
			<!-- <fb:like href="https://www.fishbase.us/summary/Gadus-morhua.html" layout="button_count" width="50" ref="top_sspage"></fb:like> -->
			<!-- Begin Mod 03/15/17 Shelumiel Ortiz
			<a href='https://fishbase.us/donate/donate.php'  ><img src='/images/gifs/DonateButton.gif' width='90' alt=''></a>
			End Mod 03/15/17 Shelumiel Ortiz -->
			<div>

		<div id='ss-heading'>
		<div class='logo'>
		<a href='/search.php'>
			<img src='/images/png/fb3.png' alt='Back to search' title='Go back to Search page'>
		</a>
		</div>
		<nav>
		<ul class='menu-list'>
			<li class='menu-item'>
				<a href='#' title='About this page' style='min-height: 23px;'>About this page <span class='arrow'>▾</span></a>
				<ul class='submenu'>
					<li><a href='/manual/English/fishbasethe_SPECIES_table.htm' title='More Info on species'>More Info</a></li>
					<li><a href='/manual/French/FishBaseNomenclature.htm#00358710' title='Plus d info'>Plus d'info</a></li>
					<li><a href='/manual/Portuguese/Nomenclature.htm#The_Species_table' title='Mais info'>Mais info</a></li>
				</ul>
			</li>
			<li class='menu-item'>
				<a href='#' title='Languages' style='min-height: 23px;'>Languages <span class='arrow'>▾</span></a>
				<ul class='submenu'>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=arabic' title='Arabic'>Arabic</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=bahasa' title='Bahasa Malay/Indonesian'>Bahasa Malay/Indonesian</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=bangla' title='Bangla'>Bangla</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=scchinese' title='Simplified Chinese'>Chinese(Si)</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=chinese' title='Traditional Chinese'>Chinese(Tr)</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=german' title='German'>Deutsch</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=English' title='English'>English</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=spanish' title='Spanish'>Español</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=farsi' title='Farsi'>Farsi</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=french' title='French'>Français</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=greek' title='Greek'>Greek</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=hindi' title='Hindi'>Hindi</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=italian' title='Italian'>Italiano</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=japanese' title='Japanese'>Japanese</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=laos' title='Lao'>Lao</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=dutch' title='Dutch'>Nederlands</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=portuguese' title='Portuguese-Brasil'>Português(Br)</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=portuguese_po' title='Portuguese-Portugal'>Português(Pt)</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=russian' title='Russian'>Russian</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=swedish' title='Swedish'>Swedish</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=thai' title='Thai'>Thai</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=vietnamese' title='Vietnamese'>Vietnamese</a></li>
					<li><a href='/summary/SpeciesSummary.php?id=69&lang=myanmar' title='Myanmar'>Myanmar</a></li>
				</ul>
			</li>
			<li class='menu-item'>
				<a href='#' title='Send us a Feedback' style='min-height: 23px;'>User feedbacks <span class='arrow'>▾</span></a>
				<ul class='submenu'>
					<li><a href='javascript:document.mailx.submit()' title='Send us your Comments & Corrections'>Comments & Corrections&emsp13;</a></li>
					<li><a href='../facebooklinks.php' title='Explore our community support' target='_blank'>Facebook</a></li>
				</ul>
			</li>
			<li class='menu-item'>
				<a href='../summary/citation.php' title='How to cite FishBase' style='min-height: 23px;'>Citation</a>
			</li>
			<li class='menu-item'>
				<a href='#' title='Uploads Gadus morhua' style='min-height: 23px;'>Uploads <span class='arrow'>▾</span></a>
				<ul class='submenu'>
					<li><a href='https://www.fishbase.us/FishWatcher/url_addform.php?speccode=69' title='Attach your web site to this page'>Attach website</a></li>
					<li><a href='https://www.fishbase.us/tools/UploadPhoto/start.php?speccode=69' title='Upload photo -  Gadus morhua'>Upload photo</a></li>
					<li><a href='/tools/UploadVideo/start_info.php?speccode=69' title='Upload video - Gadus morhua'>Upload video</a></li>
					<li><a href='https://www.fishbase.us/tools/upload-ref/start.php?speccode=69'>Upload references&emsp13;</a></li>
					<li><a href='https://www.fishbase.us/FishWatcher/checkpassword.php?Genus=Gadus&Species=morhua&vtable=contribution_a'>Fish Watcher</a></li>
				</ul>
			</li>
			<li class='menu-item'>
				<a fref='#' title='Restricted - Gadus morhua' style='min-height: 23px;'>Related species <span class='arrow'>▾</span></a>
				<ul class='submenu'>
					<li><a style = 'width:121px;' href='../identification/SpeciesList.php?genus=Gadus' title='Species in Gadus'>Species in <i>Gadus</i></a></li>
					<li><a style = 'width:121px;' href='/identification/SpeciesList.php?famcode=183&areacode=&spines=&fins=' title='Species in Gadidae'>Species in <i>Gadidae</a></i></li>
				<li style='background: #02CDE5; text-align:center;'>- Classification -</li>
						<li><a style = 'width:121px;' href='/summary/FamilySummary.php?ID=183' class='sciname' title='Family'>Gadidae</a></li>
						<li><a style = 'width:121px;' href='/summary/OrdersSummary.php?order=Gadiformes' class='sciname' title='Order'>Gadiformes</a></li>
						<li><a style = 'width:121px; color:#D9D9D9;' href='#' class='sciname' title='Class'>Teleostei</a></li>
						<li><a style = 'width:121px; color:#D9D9D9;' href='#' class='sciname' title='Phylum'>Chordata</a></li>
						<li><a style = 'width:121px; color:#D9D9D9;' href='#' class='sciname' title='Kingdom'>Animalia</a></li>
				</ul>
			</li>
		</ul>
	</nav>
	<div class='logo'>
		<a id='search-button' href='#'>
		<img src='/images/png/search-logo-new.png' alt='Search' title='Search names'>
		</a>
	</div>
	<div  class='logo'>
		<a href='https://www.facebook.com/FishBaseProject/' target='_blank'>
			<img src='/images/png/search-fb.png' height='35' border='0'/>
		</a>
	</div>
	<div  class='logo'>
		<a href='/donate/donate.php'><img src='/images/gifs/DonateButton.gif' width='90' alt=''></a>
	</div>
	</div>			</div>
		</div>

		<!-- Sci name, Author, FBname section -->
		<div id="ss-sciname">
			<h1>
				<span class='sciname'><b><a href='http://researcharchive.calacademy.org/research/ichthyology/catalog/fishcatget.asp?genid=113' alt='Catalog of Fishes - Genera' title='Catalog of Fishes - Genera' target='_blank'>Gadus</a></b></span> <span class='sciname'><b><a href='http://researcharchive.calacademy.org/research/ichthyology/catalog/fishcatget.asp?spid=12302' alt='Catalog of Fishes - Species' title='Catalog of Fishes - Species' target='_blank'>morhua</a></b></span> <span class='sheader6 noLinkDesign'><a href='http://en.wikipedia.org/wiki/Carl_Linnaeus' alt='Wiki' title='Wiki' target='_blank'>Linnaeus</a></span>, <span class='sheader6 noLinkDesign'><a href='http://researcharchive.calacademy.org/research/ichthyology/catalog/getref.asp?id=2787' alt='Catalog of Fishes - References' title='Catalog of Fishes - References' target='_blank'>1758</a></span>			</h1>
			<span class='sheader2'>
				Atlantic cod			</span>
		</div>
		<!-- Map and photo container -->


		<div id="ss-photomap-container">
							<!-- Aquamaps -->
				<div id="ss-map">
					Add your observation in <a href='https://www.fishbase.us/FishWatcher/checkpassword.php?Genus=Gadus&Species=morhua&vtable=contribution_a'>Fish Watcher</a><div class="aquamaps"><center>
<table border='1' cellpadding='2' cellspacing='0' style='font-size : xx-small; font-family : Arial;' width = '350'>
	<tr>
		<td align='center'>
<a href='#' onmouseover='javascript:document.getElementById(&quot;pix&quot;).src=&quot;/images/aquamaps/native/pic_Fis-29394.jpg&quot;'>
Native range</a> |
	<a href='#' onmouseover='javascript:document.getElementById(&quot;pix&quot;).src=&quot;/images/aquamaps/suitable/pic_Fis-29394.jpg&quot;'>
	All suitable habitat</a> |
	<a href='#' onmouseover='javascript:document.getElementById(&quot;pix&quot;).src=&quot;/images/aquamaps/pointmap/pic_Fis-29394.jpg&quot;'>
	Point map</a> |
	<a href='#' onmouseover='javascript:document.getElementById(&quot;pix&quot;).src=&quot;/images/aquamaps/2050/pic_Fis-29394.jpg&quot;'>
	Year 2050</a></td>
	</tr>
	<tr>
		<td align='center'>
			<a target='am_Fis-29394' href='//www.aquamaps.org/preMap.php?cache=1&SpecID=Fis-29394'>
				<img id='pix' src='/images/aquamaps/native/pic_Fis-29394.jpg' alt=''>
			</a>
		</td>
	</tr>
	<tr>
		<td align='center' style='font-size : xx-small;'>This map was computer-generated and has not yet been reviewed.</td>
	</tr>
	<tr>
		<td align='center' style='font-size : xx-small;'><font style='font-family : Arial;'>
		<a target='fb_Fis-29394' href='http:///summary/SpeciesSummary.php?genusname=Gadus&speciesname=morhua'><i>Gadus morhua</i></a>
		&nbsp;
		<a target='am_org' href='http://www.aquamaps.org'>AquaMaps</a>
		&nbsp;
		Data sources: 	<a target='gbif_Fis-29394' href='http://data.gbif.org/occurrences/searchProviders.htm?c[0].s=0&c[0].p=0&c[0].o=Gadus morhua&c[1].s=28&c[1].p=0&c[1].o=0'>GBIF</a>
						<a target='obis_Fis-29394' href='http://www.iobis.org/OBISWEB/ObisControllerServlet?category=all&names=data&tableName=0&searchName=126436&x=51&y=9'>OBIS</a>
		</font></td>
	</tr>
</table></center></div>				</div>

						<!-- Species Photo -->
						<div id="ss-photo">
				<span>
					Upload your <a href='https://www.fishbase.us/tools/UploadPhoto/start.php?speccode=69'>photos</a>&nbsp;and&nbsp;<a href='/tools/UploadVideo/start_info.php?speccode=69'>videos</a><BR />				</span>
				<span class="slabel8">
				<a href='../photos/ThumbnailsSummary.php?ID=69'>Pictures</a> | <a href='/videos/SpeciesVideos.php?speccode=69'>
					Videos |</a> 	<a href='../physiology/FishSoundsList.php?id=69'>
					Sounds
				</a>
			 | <a href='../photos/SpeciesStampsList.php?speccode=69'>Stamps, coins, misc.</a> | <a href='https://www.google.com/images?hl=en&q=Gadus+morhua&btnG=Search+Images&gbv=2'>Google image</a><div><a style='text-decoration:none;' href='/photos/ThumbnailsSummary.php?ID=69'><img style='margin-top: 0; margin-bottom: 0;' name='prefimage' src='/images/thumbnails/jpg/tn_Gamor_u3.jpg' title ='Image of Gadus morhua (Atlantic cod)' alt='Image of Gadus morhua (Atlantic cod)' border='0' ></a></div><span class='sciname slabel8'>Gadus morhua</span><br/><span class='slabelPicAuthor' >
					Picture by
					<a href='/collaborators/CollaboratorSummary.php?ID=40'>
					Morris, P.</a><br />
					</span><!--<script src="/libs/jquery/jquery.js"></script>-->
<link rel="stylesheet" href="/css/swipeslider.css">
<script src="/libs/jquery/swipeslider/swipeslider.min.js"></script>
<script>
$(window).load(function() {
	if($("#ss-photo-full").length > 0){			//the photo is full width
		$('#image-slider').swipeslider({sliderHeight:'27%', autoPlayTimeout: 8000});
	}else{
		$('#image-slider').swipeslider({sliderHeight:'52%', autoPlayTimeout: 8000});
	}
});
</script>
<style>
.swipslider{
	max-width: 310px;
	margin:	auto;
}

</style>					<!--<span class='sciname'>
											</span>
					<br/>
					<span class="slabel8">
											</span>-->
				</span>
			</div> <!-- ss-photo -->
		</div> <!-- ss-photomap-container -->

		<!-- Main Content -->
		<div id="ss-main">
			<p> <!-- CLASSIFICATION / NAMES -->
			<h1 class='slabel sleft bottomBorder'>
				Classification / Names  				<span class="addLinks"> <!-- not bold -->

============================================================
  FishBase  (FishBaseAPI)
  Species:   Not species
  Name type: not species
============================================================
_fetch_query_data
    <!-- Display Cookie Consent Banner -->
    <link rel="stylesheet" type="text/css" href="/css/cookie-consent.css">

    <div id="cookie-consent-container" style="display:none;">
        <div id="cookie-consent-banner">
            <div class="cookie-consent-banner-item">
                <p>
                   This website uses cookies to enhance your browsing experience and ensure the functionality of our site. For more detailed information about the types of cookies we use and how we protect your privacy, please visit our <a href='../cookieMoreinfo.php' target='_blank'>Privacy Information</a> page.
                </p>
            </div>
            <div class="cookie-consent-banner-item">
                <button id="accept-all">Accept All</button>
                <button id="accept-necessary">Accept Necessary Cookies Only</button>
                <button id="cookie-settings">Cookie Settings</button>
            </div>
        </div>
    </div>

    <!-- Overlay -->
    <div id="overlay"></div>

    <!-- Cookie Settings Dialog -->
    <div id="cookie-settings-dialog">
        <span id="close-dialog">&times;</span>
        <h3>Cookie Settings</h3>
        <p>This website uses different types of cookies to enhance your experience. Please select your preferences below:</p>

        <label>
           <div class="cookie-categ">
                <span>Strictly Necessary</span>
                <label class="switch">

                    <input type="checkbox" id="necessary-toggle" checked disabled>
                    <span class="slider"></span>
                </label>
            </div>
            <p>
                These cookies are essential for the website to function properly. They include session cookies, which help maintain your session while you navigate the site, as well as cookies that remember your language preferences and other essential functionalities. Without these cookies, certain features of the website cannot be provided.
            </p>
        </label>

        <label>
            <div class="cookie-categ">
                <span>Performance</span>
                <label class="switch">
                    <input type="checkbox" id="performance-toggle">
                    <span class="slider"></span>
                </label>
            </div>
            <p>
                These cookies help us understand how visitors interact with our website by collecting and reporting information anonymously. For example, we use Google Analytics to generate web statistics, which helps us improve our website's performance and user experience. These cookies may track information such as the pages visited, time spent on the site, and any errors encountered.
            </p>
        </label>

        <button id="save-close">Save and Close</button>
    </div>
    <script src='/libs/jquery/scripts/cookie.js'></script>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "https://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<meta http-equiv="refresh" content="3; URL=http://www.fishbase.se" />
	<title>FishBase</title>
</head>
<body>
	<center>
	<img src="/images/gifs/FBLogo.gif" /> <br/>
	Species name is not in the public version of FishBase.
	</center>
</body>
</html>
_fetch_synonym_data

_fetch_accepted_data
{}
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

---
## ITIS (Integrated Taxonomic Information System)

ITIS is an authoritative database of biological names for plants, animals, fungi, and microbes, maintained by a partnership of US federal agencies.

**Custom `get_synonyms()` orchestration.** ITIS exposes data through many small, single-purpose endpoints rather than one compound query. A single lookup requires at least **4 + N** fetch calls, where N is the number of synonyms:

1. `_fetch_query_data` — `getITISTermsFromScientificName` to get the initial TSN
2. `_extract_internal_accepted_id` — calls `_fetch_internal_accepted_id_data` (`getAcceptedNamesFromTSN`) only if the initial result is not already accepted
3. `_fetch_synonym_data` — `getSynonymNamesFromTSN` to get the synonym TSN list, then one `getFullRecordFromTSN` call per synonym
4. `_fetch_accepted_data` — `getFullRecordFromTSN` for the accepted name
5. `_fetch_hierarchy_data` — `getFullHierarchyFromTSN` for the taxonomic hierarchy

Because so many endpoints must be coordinated and each takes the accepted TSN (not raw query data) as input, the orchestration passes the accepted ID explicitly between steps rather than threading raw data through the base-class pipeline. **Expect this section to be noticeably slow.**

In [9]:
from scripts.apis_pipe.itis import ITISAPI

run_queries([(ITIS_PORTAL, ITISAPI(), "Oncorhynchus mykiss", "Salmo mykiss")])

============================================================
  ITIS  (ITISAPI)
  Species:   Oncorhynchus mykiss
  Name type: accepted
============================================================
_fetch_query_data
{'author': '(Walbaum, 1792)', 'class': 'gov.usgs.itis.itis_service.data.SvcItisTerm', 'commonNames': ['rainbow trout', 'redband trout', 'truite arc-en-ciel', 'steelhead', 'trucha arcoiris'], 'nameUsage': 'valid', 'scientificName': 'Oncorhynchus mykiss', 'tsn': '161989'}
_fetch_synonym_data
[{'acceptedNameList': {'acceptedNames': [{'acceptedName': 'Oncorhynchus mykiss', 'acceptedTsn': '161989', 'author': None, 'class': 'gov.usgs.itis.itis_service.data.SvcAcceptedName'}], 'class': 'gov.usgs.itis.itis_service.data.SvcAcceptedNameList', 'tsn': '161990'}, 'class': 'gov.usgs.itis.itis_service.data.SvcFullRecord', 'commentList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonCommentList', 'comments': [None], 'tsn': '161990'}, 'commonNameList': {'class': 'gov.usgs.itis.itis_service.data.SvcCommonNameList', 'commonNames': [None], 'tsn': '161990'}, 'completenessRating': {'class': 'gov.usgs.itis.itis_service.data.SvcGlobalSpeciesCompleteness', 'completeness': '', 'rankId': 220, 'tsn': '161990'}, 'coreMetadata': {'class': 'gov.usgs.itis.itis_service.data.SvcCoreMetadata', 'credRating': 'TWG standards met', 'rankId': 220, 'taxonCoverage': '', 'taxonCurrency': '', 'taxonUsageRating': 'invalid', 'tsn': '161990', 'unacceptReason': 'original name/combination'}, 'credibilityRating': {'class': 'gov.usgs.itis.itis_service.data.SvcCredibilityData', 'credRating': 'TWG standards met', 'tsn': '161990'}, 'currencyRating': {'class': 'gov.usgs.itis.itis_service.data.SvcCurrencyData', 'rankId': 220, 'taxonCurrency': '', 'tsn': '161990'}, 'dateData': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonDateData', 'initialTimeStamp': '1996-06-13 14:51:08.0', 'tsn': '161990', 'updateDate': '2004-01-22'}, 'expertList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonExpertList', 'experts': [None], 'tsn': '161990'}, 'geographicDivisionList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonGeoDivisionList', 'geoDivisions': [None], 'tsn': '161990'}, 'hierarchyUp': {'author': None, 'class': 'gov.usgs.itis.itis_service.data.SvcHierarchyRecord', 'parentName': None, 'parentTsn': None, 'rankName': None, 'taxonName': None, 'tsn': '161990'}, 'jurisdictionalOriginList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonJurisdictionalOriginList', 'jurisdictionalOrigins': [None], 'tsn': '161990'}, 'kingdom': {'class': 'gov.usgs.itis.itis_service.data.SvcKingdomInfo', 'kingdomId': '5', 'kingdomName': 'Animalia  ', 'tsn': '161990'}, 'otherSourceList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonOtherSourceList', 'otherSources': [{'acquisitionDate': '2003-03-17', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonOtherSource', 'referenceFor': [{'class': 'gov.usgs.itis.itis_service.data.SvcReferenceForElement', 'name': 'Salmo mykiss', 'refLanguage': None, 'referredTsn': '161990'}], 'source': 'Catalog of Fishes, 17-Mar-2003', 'sourceComment': 'http://www.calacademy.org/research/ichthyology/catalog/', 'sourceType': 'website', 'updateDate': '2004-02-11', 'version': '13-Mar-03'}, {'acquisitionDate': '1996-07-29', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonOtherSource', 'referenceFor': [{'class': 'gov.usgs.itis.itis_service.data.SvcReferenceForElement', 'name': 'Salmo mykiss', 'refLanguage': None, 'referredTsn': '161990'}], 'source': 'NODC Taxonomic Code', 'sourceComment': '', 'sourceType': 'database', 'updateDate': '2010-01-14', 'version': '8.0'}], 'tsn': '161990'}, 'parentTSN': {'class': 'gov.usgs.itis.itis_service.data.SvcParentTsn', 'parentTsn': '0', 'tsn': '161990'}, 'publicationList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonPublicationList', 'publications': [{'actualPubDate': '1930-01-01', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonPublication', 'isbn': '', 'issn': '', 'listedPubDate': '1930-01-01', 'pages': '670', 'pubComment': 'Reprinted 1955', 'pubName': 'Report of the United States Commissioner of Fisheries for the fiscal year 1928', 'pubPlace': 'Washington, D.C., USA', 'publisher': 'United States Department of Interior, Fish and Wildlife Service', 'referenceAuthor': 'Jordan, David Starr, Barton Warren Evermann, and Howard Walton Clark', 'referenceFor': [{'class': 'gov.usgs.itis.itis_service.data.SvcReferenceForElement', 'name': 'Salmo mykiss', 'refLanguage': None, 'referredTsn': '161990'}], 'title': 'Checklist of the fishes and fishlike vertebrates of North America north of the northern boundary of Venezuela and Colombia', 'updateDate': '2017-08-28'}], 'tsn': '161990'}, 'scientificName': {'author': 'Walbaum, 1792', 'class': 'gov.usgs.itis.itis_service.data.SvcScientificName', 'combinedName': 'Salmo mykiss', 'kingdom': None, 'tsn': '161990', 'unitInd1': None, 'unitInd2': None, 'unitInd3': None, 'unitInd4': None, 'unitName1': 'Salmo                              ', 'unitName2': 'mykiss', 'unitName3': None, 'unitName4': None}, 'synonymList': {'class': 'gov.usgs.itis.itis_service.data.SvcSynonymNameList', 'synonyms': [None], 'tsn': '161990'}, 'taxRank': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonRankInfo', 'kingdomId': '5', 'kingdomName': 'Animalia  ', 'rankId': '220', 'rankName': 'Species        ', 'tsn': '161990'}, 'taxonAuthor': {'authorship': 'Walbaum, 1792', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonAuthorship', 'tsn': '161990', 'updateDate': '2004-01-22'}, 'tsn': '161990', 'unacceptReason': {'class': 'gov.usgs.itis.itis_service.data.SvcUnacceptData', 'tsn': '161990', 'unacceptReason': 'original name/combination'}, 'usage': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonUsageData', 'taxonUsageRating': 'invalid', 'tsn': '161990'}}, {'acceptedNameList': {'acceptedNames': [{'acceptedName': 'Oncorhynchus mykiss', 'acceptedTsn': '161989', 'author': None, 'class': 'gov.usgs.itis.itis_service.data.SvcAcceptedName'}], 'class': 'gov.usgs.itis.itis_service.data.SvcAcceptedNameList', 'tsn': '633905'}, 'class': 'gov.usgs.itis.itis_service.data.SvcFullRecord', 'commentList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonCommentList', 'comments': [{'class': 'gov.usgs.itis.itis_service.data.SvcTaxonComment', 'commentDetail': 'Common literature misspelling of Oncorhynchus mykiss (Walbaum, 1792)', 'commentId': '11970', 'commentTimeStamp': '2004-07-06 10:52:28.0', 'commentator': 'T.M. Orrell, ITIS Taxonomic Expert', 'updateDate': '2004-07-06'}], 'tsn': '633905'}, 'commonNameList': {'class': 'gov.usgs.itis.itis_service.data.SvcCommonNameList', 'commonNames': [None], 'tsn': '633905'}, 'completenessRating': {'class': 'gov.usgs.itis.itis_service.data.SvcGlobalSpeciesCompleteness', 'completeness': '', 'rankId': 220, 'tsn': '633905'}, 'coreMetadata': {'class': 'gov.usgs.itis.itis_service.data.SvcCoreMetadata', 'credRating': 'TWG standards met', 'rankId': 220, 'taxonCoverage': '', 'taxonCurrency': '', 'taxonUsageRating': 'invalid', 'tsn': '633905', 'unacceptReason': 'unavailable, literature misspelling'}, 'credibilityRating': {'class': 'gov.usgs.itis.itis_service.data.SvcCredibilityData', 'credRating': 'TWG standards met', 'tsn': '633905'}, 'currencyRating': {'class': 'gov.usgs.itis.itis_service.data.SvcCurrencyData', 'rankId': 220, 'taxonCurrency': '', 'tsn': '633905'}, 'dateData': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonDateData', 'initialTimeStamp': '2004-07-06 10:52:07.0', 'tsn': '633905', 'updateDate': '2004-07-06'}, 'expertList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonExpertList', 'experts': [None], 'tsn': '633905'}, 'geographicDivisionList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonGeoDivisionList', 'geoDivisions': [None], 'tsn': '633905'}, 'hierarchyUp': {'author': None, 'class': 'gov.usgs.itis.itis_service.data.SvcHierarchyRecord', 'parentName': None, 'parentTsn': None, 'rankName': None, 'taxonName': None, 'tsn': '633905'}, 'jurisdictionalOriginList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonJurisdictionalOriginList', 'jurisdictionalOrigins': [None], 'tsn': '633905'}, 'kingdom': {'class': 'gov.usgs.itis.itis_service.data.SvcKingdomInfo', 'kingdomId': '5', 'kingdomName': 'Animalia  ', 'tsn': '633905'}, 'otherSourceList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonOtherSourceList', 'otherSources': [None], 'tsn': '633905'}, 'parentTSN': {'class': 'gov.usgs.itis.itis_service.data.SvcParentTsn', 'parentTsn': '0', 'tsn': '633905'}, 'publicationList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonPublicationList', 'publications': [{'actualPubDate': '2003-07-01', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonPublication', 'isbn': '', 'issn': '0013-9351', 'listedPubDate': '2003-07-01', 'pages': '262-270', 'pubComment': '', 'pubName': 'Environmental Research, vol. 92, no. 3', 'pubPlace': '', 'publisher': '', 'referenceAuthor': 'Uguz, Cevdet, Mesude Iscan, Ayse Ergüven, Belgin Isgor, and Inci Togan', 'referenceFor': [{'class': 'gov.usgs.itis.itis_service.data.SvcReferenceForElement', 'name': 'Onchorynchus mykiss', 'refLanguage': None, 'referredTsn': '633905'}], 'title': 'The bioaccumulation of nonyphenol and its adverse effect on the liver of rainbow trout (Onchorynchus mykiss)', 'updateDate': '2004-07-06'}], 'tsn': '633905'}, 'scientificName': {'author': '(Walbaum, 1792)', 'class': 'gov.usgs.itis.itis_service.data.SvcScientificName', 'combinedName': 'Onchorynchus mykiss', 'kingdom': None, 'tsn': '633905', 'unitInd1': None, 'unitInd2': None, 'unitInd3': None, 'unitInd4': None, 'unitName1': 'Onchorynchus                       ', 'unitName2': 'mykiss', 'unitName3': None, 'unitName4': None}, 'synonymList': {'class': 'gov.usgs.itis.itis_service.data.SvcSynonymNameList', 'synonyms': [None], 'tsn': '633905'}, 'taxRank': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonRankInfo', 'kingdomId': '5', 'kingdomName': 'Animalia  ', 'rankId': '220', 'rankName': 'Species        ', 'tsn': '633905'}, 'taxonAuthor': {'authorship': '(Walbaum, 1792)', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonAuthorship', 'tsn': '633905', 'updateDate': '2004-02-23'}, 'tsn': '633905', 'unacceptReason': {'class': 'gov.usgs.itis.itis_service.data.SvcUnacceptData', 'tsn': '633905', 'unacceptReason': 'unavailable, literature misspelling'}, 'usage': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonUsageData', 'taxonUsageRating': 'invalid', 'tsn': '633905'}}, {'acceptedNameList': {'acceptedNames': [{'acceptedName': 'Oncorhynchus mykiss', 'acceptedTsn': '161989', 'author': None, 'class': 'gov.usgs.itis.itis_service.data.SvcAcceptedName'}], 'class': 'gov.usgs.itis.itis_service.data.SvcAcceptedNameList', 'tsn': '914074'}, 'class': 'gov.usgs.itis.itis_service.data.SvcFullRecord', 'commentList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonCommentList', 'comments': [None], 'tsn': '914074'}, 'commonNameList': {'class': 'gov.usgs.itis.itis_service.data.SvcCommonNameList', 'commonNames': [None], 'tsn': '914074'}, 'completenessRating': {'class': 'gov.usgs.itis.itis_service.data.SvcGlobalSpeciesCompleteness', 'completeness': '', 'rankId': 220, 'tsn': '914074'}, 'coreMetadata': {'class': 'gov.usgs.itis.itis_service.data.SvcCoreMetadata', 'credRating': 'TWG standards met', 'rankId': 220, 'taxonCoverage': '', 'taxonCurrency': '', 'taxonUsageRating': 'invalid', 'tsn': '914074', 'unacceptReason': 'junior synonym'}, 'credibilityRating': {'class': 'gov.usgs.itis.itis_service.data.SvcCredibilityData', 'credRating': 'TWG standards met', 'tsn': '914074'}, 'currencyRating': {'class': 'gov.usgs.itis.itis_service.data.SvcCurrencyData', 'rankId': 220, 'taxonCurrency': '', 'tsn': '914074'}, 'dateData': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonDateData', 'initialTimeStamp': '2013-08-14 11:58:29.0', 'tsn': '914074', 'updateDate': '2013-08-14'}, 'expertList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonExpertList', 'experts': [None], 'tsn': '914074'}, 'geographicDivisionList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonGeoDivisionList', 'geoDivisions': [None], 'tsn': '914074'}, 'hierarchyUp': {'author': None, 'class': 'gov.usgs.itis.itis_service.data.SvcHierarchyRecord', 'parentName': None, 'parentTsn': None, 'rankName': None, 'taxonName': None, 'tsn': '914074'}, 'jurisdictionalOriginList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonJurisdictionalOriginList', 'jurisdictionalOrigins': [None], 'tsn': '914074'}, 'kingdom': {'class': 'gov.usgs.itis.itis_service.data.SvcKingdomInfo', 'kingdomId': '5', 'kingdomName': 'Animalia  ', 'tsn': '914074'}, 'otherSourceList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonOtherSourceList', 'otherSources': [{'acquisitionDate': '2013-06-27', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonOtherSource', 'referenceFor': [{'class': 'gov.usgs.itis.itis_service.data.SvcReferenceForElement', 'name': 'Salmo gibbsii', 'refLanguage': None, 'referredTsn': '914074'}], 'source': 'Catalog of Fishes, 10-Jun-2013', 'sourceComment': 'http://research.calacademy.org/research/ichthyology/catalog/fishcatmain.asp', 'sourceType': 'website', 'updateDate': '2013-08-14', 'version': '10-Jun-13'}], 'tsn': '914074'}, 'parentTSN': {'class': 'gov.usgs.itis.itis_service.data.SvcParentTsn', 'parentTsn': '0', 'tsn': '914074'}, 'publicationList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonPublicationList', 'publications': [None], 'tsn': '914074'}, 'scientificName': {'author': 'Suckley, 1859', 'class': 'gov.usgs.itis.itis_service.data.SvcScientificName', 'combinedName': 'Salmo gibbsii', 'kingdom': None, 'tsn': '914074', 'unitInd1': None, 'unitInd2': None, 'unitInd3': None, 'unitInd4': None, 'unitName1': 'Salmo                              ', 'unitName2': 'gibbsii', 'unitName3': None, 'unitName4': None}, 'synonymList': {'class': 'gov.usgs.itis.itis_service.data.SvcSynonymNameList', 'synonyms': [None], 'tsn': '914074'}, 'taxRank': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonRankInfo', 'kingdomId': '5', 'kingdomName': 'Animalia  ', 'rankId': '220', 'rankName': 'Species        ', 'tsn': '914074'}, 'taxonAuthor': {'authorship': 'Suckley, 1859', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonAuthorship', 'tsn': '914074', 'updateDate': '2013-08-14'}, 'tsn': '914074', 'unacceptReason': {'class': 'gov.usgs.itis.itis_service.data.SvcUnacceptData', 'tsn': '914074', 'unacceptReason': 'junior synonym'}, 'usage': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonUsageData', 'taxonUsageRating': 'invalid', 'tsn': '914074'}}, {'acceptedNameList': {'acceptedNames': [{'acceptedName': 'Oncorhynchus mykiss', 'acceptedTsn': '161989', 'author': None, 'class': 'gov.usgs.itis.itis_service.data.SvcAcceptedName'}], 'class': 'gov.usgs.itis.itis_service.data.SvcAcceptedNameList', 'tsn': '914094'}, 'class': 'gov.usgs.itis.itis_service.data.SvcFullRecord', 'commentList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonCommentList', 'comments': [{'class': 'gov.usgs.itis.itis_service.data.SvcTaxonComment', 'commentDetail': 'US ESA: Potential candidate without sufficient data on vulnerability, as published in Federal Register Volume 59, Number 219, Pages 58982 - 59028, November 15, 1994', 'commentId': '21591', 'commentTimeStamp': '2011-05-27 13:26:03.0', 'commentator': 'David F. Mitchell, ITIS Data Development Specialist', 'updateDate': '2026-03-18'}], 'tsn': '914094'}, 'commonNameList': {'class': 'gov.usgs.itis.itis_service.data.SvcCommonNameList', 'commonNames': [{'class': 'gov.usgs.itis.itis_service.data.SvcCommonName', 'commonName': 'interior redband trout', 'language': 'English', 'tsn': '914094'}], 'tsn': '914094'}, 'completenessRating': {'class': 'gov.usgs.itis.itis_service.data.SvcGlobalSpeciesCompleteness', 'completeness': '', 'rankId': 230, 'tsn': '914094'}, 'coreMetadata': {'class': 'gov.usgs.itis.itis_service.data.SvcCoreMetadata', 'credRating': 'TWG standards met', 'rankId': 230, 'taxonCoverage': '', 'taxonCurrency': '', 'taxonUsageRating': 'invalid', 'tsn': '914094', 'unacceptReason': 'junior synonym'}, 'credibilityRating': {'class': 'gov.usgs.itis.itis_service.data.SvcCredibilityData', 'credRating': 'TWG standards met', 'tsn': '914094'}, 'currencyRating': {'class': 'gov.usgs.itis.itis_service.data.SvcCurrencyData', 'rankId': 230, 'taxonCurrency': '', 'tsn': '914094'}, 'dateData': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonDateData', 'initialTimeStamp': '2013-08-14 11:58:34.0', 'tsn': '914094', 'updateDate': '2013-08-14'}, 'expertList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonExpertList', 'experts': [None], 'tsn': '914094'}, 'geographicDivisionList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonGeoDivisionList', 'geoDivisions': [None], 'tsn': '914094'}, 'hierarchyUp': {'author': None, 'class': 'gov.usgs.itis.itis_service.data.SvcHierarchyRecord', 'parentName': None, 'parentTsn': None, 'rankName': None, 'taxonName': None, 'tsn': '914094'}, 'jurisdictionalOriginList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonJurisdictionalOriginList', 'jurisdictionalOrigins': [None], 'tsn': '914094'}, 'kingdom': {'class': 'gov.usgs.itis.itis_service.data.SvcKingdomInfo', 'kingdomId': '5', 'kingdomName': 'Animalia  ', 'tsn': '914094'}, 'otherSourceList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonOtherSourceList', 'otherSources': [None], 'tsn': '914094'}, 'parentTSN': {'class': 'gov.usgs.itis.itis_service.data.SvcParentTsn', 'parentTsn': '0', 'tsn': '914094'}, 'publicationList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonPublicationList', 'publications': [{'actualPubDate': '1994-11-15', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonPublication', 'isbn': '', 'issn': '', 'listedPubDate': '1994-11-15', 'pages': '58982-59028', 'pubComment': '', 'pubName': 'Federal Register, vol. 59, no. 219', 'pubPlace': '', 'publisher': '', 'referenceAuthor': 'U. S. Fish and Wildlife Service', 'referenceFor': [{'class': 'gov.usgs.itis.itis_service.data.SvcReferenceForElement', 'name': 'Oncorhynchus mykiss gibbsi', 'refLanguage': None, 'referredTsn': '914094'}], 'title': 'Endangered and Threatened Wildlife and Plants; Animal Candidate Review for Listing as Endangered or Threatened Species', 'updateDate': '2026-03-18'}], 'tsn': '914094'}, 'scientificName': {'author': '(Suckley, 1859)', 'class': 'gov.usgs.itis.itis_service.data.SvcScientificName', 'combinedName': 'Oncorhynchus mykiss gibbsi', 'kingdom': None, 'tsn': '914094', 'unitInd1': None, 'unitInd2': None, 'unitInd3': None, 'unitInd4': None, 'unitName1': 'Oncorhynchus                       ', 'unitName2': 'mykiss', 'unitName3': 'gibbsi', 'unitName4': None}, 'synonymList': {'class': 'gov.usgs.itis.itis_service.data.SvcSynonymNameList', 'synonyms': [None], 'tsn': '914094'}, 'taxRank': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonRankInfo', 'kingdomId': '5', 'kingdomName': 'Animalia  ', 'rankId': '230', 'rankName': 'Subspecies     ', 'tsn': '914094'}, 'taxonAuthor': {'authorship': '(Suckley, 1859)', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonAuthorship', 'tsn': '914094', 'updateDate': '2004-01-22'}, 'tsn': '914094', 'unacceptReason': {'class': 'gov.usgs.itis.itis_service.data.SvcUnacceptData', 'tsn': '914094', 'unacceptReason': 'junior synonym'}, 'usage': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonUsageData', 'taxonUsageRating': 'invalid', 'tsn': '914094'}}]
_fetch_accepted_data

============================================================
  ITIS  (ITISAPI)
  Species:   Salmo mykiss
  Name type: synonym  (synonym of: Oncorhynchus mykiss)
============================================================
_fetch_query_data
{'author': 'Walbaum, 1792', 'class': 'gov.usgs.itis.itis_service.data.SvcItisTerm', 'commonNames': [None], 'nameUsage': 'invalid', 'scientificName': 'Salmo mykiss', 'tsn': '161990'}
_fetch_synonym_data
[{'acceptedNameList': {'acceptedNames': [{'acceptedName': 'Oncorhynchus mykiss', 'acceptedTsn': '161989', 'author': None, 'class': 'gov.usgs.itis.itis_service.data.SvcAcceptedName'}], 'class': 'gov.usgs.itis.itis_service.data.SvcAcceptedNameList', 'tsn': '161990'}, 'class': 'gov.usgs.itis.itis_service.data.SvcFullRecord', 'commentList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonCommentList', 'comments': [None], 'tsn': '161990'}, 'commonNameList': {'class': 'gov.usgs.itis.itis_service.data.SvcCommonNameList', 'commonNames': [None], 'tsn': '161990'}, 'completenessRating': {'class': 'gov.usgs.itis.itis_service.data.SvcGlobalSpeciesCompleteness', 'completeness': '', 'rankId': 220, 'tsn': '161990'}, 'coreMetadata': {'class': 'gov.usgs.itis.itis_service.data.SvcCoreMetadata', 'credRating': 'TWG standards met', 'rankId': 220, 'taxonCoverage': '', 'taxonCurrency': '', 'taxonUsageRating': 'invalid', 'tsn': '161990', 'unacceptReason': 'original name/combination'}, 'credibilityRating': {'class': 'gov.usgs.itis.itis_service.data.SvcCredibilityData', 'credRating': 'TWG standards met', 'tsn': '161990'}, 'currencyRating': {'class': 'gov.usgs.itis.itis_service.data.SvcCurrencyData', 'rankId': 220, 'taxonCurrency': '', 'tsn': '161990'}, 'dateData': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonDateData', 'initialTimeStamp': '1996-06-13 14:51:08.0', 'tsn': '161990', 'updateDate': '2004-01-22'}, 'expertList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonExpertList', 'experts': [None], 'tsn': '161990'}, 'geographicDivisionList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonGeoDivisionList', 'geoDivisions': [None], 'tsn': '161990'}, 'hierarchyUp': {'author': None, 'class': 'gov.usgs.itis.itis_service.data.SvcHierarchyRecord', 'parentName': None, 'parentTsn': None, 'rankName': None, 'taxonName': None, 'tsn': '161990'}, 'jurisdictionalOriginList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonJurisdictionalOriginList', 'jurisdictionalOrigins': [None], 'tsn': '161990'}, 'kingdom': {'class': 'gov.usgs.itis.itis_service.data.SvcKingdomInfo', 'kingdomId': '5', 'kingdomName': 'Animalia  ', 'tsn': '161990'}, 'otherSourceList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonOtherSourceList', 'otherSources': [{'acquisitionDate': '2003-03-17', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonOtherSource', 'referenceFor': [{'class': 'gov.usgs.itis.itis_service.data.SvcReferenceForElement', 'name': 'Salmo mykiss', 'refLanguage': None, 'referredTsn': '161990'}], 'source': 'Catalog of Fishes, 17-Mar-2003', 'sourceComment': 'http://www.calacademy.org/research/ichthyology/catalog/', 'sourceType': 'website', 'updateDate': '2004-02-11', 'version': '13-Mar-03'}, {'acquisitionDate': '1996-07-29', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonOtherSource', 'referenceFor': [{'class': 'gov.usgs.itis.itis_service.data.SvcReferenceForElement', 'name': 'Salmo mykiss', 'refLanguage': None, 'referredTsn': '161990'}], 'source': 'NODC Taxonomic Code', 'sourceComment': '', 'sourceType': 'database', 'updateDate': '2010-01-14', 'version': '8.0'}], 'tsn': '161990'}, 'parentTSN': {'class': 'gov.usgs.itis.itis_service.data.SvcParentTsn', 'parentTsn': '0', 'tsn': '161990'}, 'publicationList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonPublicationList', 'publications': [{'actualPubDate': '1930-01-01', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonPublication', 'isbn': '', 'issn': '', 'listedPubDate': '1930-01-01', 'pages': '670', 'pubComment': 'Reprinted 1955', 'pubName': 'Report of the United States Commissioner of Fisheries for the fiscal year 1928', 'pubPlace': 'Washington, D.C., USA', 'publisher': 'United States Department of Interior, Fish and Wildlife Service', 'referenceAuthor': 'Jordan, David Starr, Barton Warren Evermann, and Howard Walton Clark', 'referenceFor': [{'class': 'gov.usgs.itis.itis_service.data.SvcReferenceForElement', 'name': 'Salmo mykiss', 'refLanguage': None, 'referredTsn': '161990'}], 'title': 'Checklist of the fishes and fishlike vertebrates of North America north of the northern boundary of Venezuela and Colombia', 'updateDate': '2017-08-28'}], 'tsn': '161990'}, 'scientificName': {'author': 'Walbaum, 1792', 'class': 'gov.usgs.itis.itis_service.data.SvcScientificName', 'combinedName': 'Salmo mykiss', 'kingdom': None, 'tsn': '161990', 'unitInd1': None, 'unitInd2': None, 'unitInd3': None, 'unitInd4': None, 'unitName1': 'Salmo                              ', 'unitName2': 'mykiss', 'unitName3': None, 'unitName4': None}, 'synonymList': {'class': 'gov.usgs.itis.itis_service.data.SvcSynonymNameList', 'synonyms': [None], 'tsn': '161990'}, 'taxRank': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonRankInfo', 'kingdomId': '5', 'kingdomName': 'Animalia  ', 'rankId': '220', 'rankName': 'Species        ', 'tsn': '161990'}, 'taxonAuthor': {'authorship': 'Walbaum, 1792', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonAuthorship', 'tsn': '161990', 'updateDate': '2004-01-22'}, 'tsn': '161990', 'unacceptReason': {'class': 'gov.usgs.itis.itis_service.data.SvcUnacceptData', 'tsn': '161990', 'unacceptReason': 'original name/combination'}, 'usage': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonUsageData', 'taxonUsageRating': 'invalid', 'tsn': '161990'}}, {'acceptedNameList': {'acceptedNames': [{'acceptedName': 'Oncorhynchus mykiss', 'acceptedTsn': '161989', 'author': None, 'class': 'gov.usgs.itis.itis_service.data.SvcAcceptedName'}], 'class': 'gov.usgs.itis.itis_service.data.SvcAcceptedNameList', 'tsn': '633905'}, 'class': 'gov.usgs.itis.itis_service.data.SvcFullRecord', 'commentList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonCommentList', 'comments': [{'class': 'gov.usgs.itis.itis_service.data.SvcTaxonComment', 'commentDetail': 'Common literature misspelling of Oncorhynchus mykiss (Walbaum, 1792)', 'commentId': '11970', 'commentTimeStamp': '2004-07-06 10:52:28.0', 'commentator': 'T.M. Orrell, ITIS Taxonomic Expert', 'updateDate': '2004-07-06'}], 'tsn': '633905'}, 'commonNameList': {'class': 'gov.usgs.itis.itis_service.data.SvcCommonNameList', 'commonNames': [None], 'tsn': '633905'}, 'completenessRating': {'class': 'gov.usgs.itis.itis_service.data.SvcGlobalSpeciesCompleteness', 'completeness': '', 'rankId': 220, 'tsn': '633905'}, 'coreMetadata': {'class': 'gov.usgs.itis.itis_service.data.SvcCoreMetadata', 'credRating': 'TWG standards met', 'rankId': 220, 'taxonCoverage': '', 'taxonCurrency': '', 'taxonUsageRating': 'invalid', 'tsn': '633905', 'unacceptReason': 'unavailable, literature misspelling'}, 'credibilityRating': {'class': 'gov.usgs.itis.itis_service.data.SvcCredibilityData', 'credRating': 'TWG standards met', 'tsn': '633905'}, 'currencyRating': {'class': 'gov.usgs.itis.itis_service.data.SvcCurrencyData', 'rankId': 220, 'taxonCurrency': '', 'tsn': '633905'}, 'dateData': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonDateData', 'initialTimeStamp': '2004-07-06 10:52:07.0', 'tsn': '633905', 'updateDate': '2004-07-06'}, 'expertList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonExpertList', 'experts': [None], 'tsn': '633905'}, 'geographicDivisionList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonGeoDivisionList', 'geoDivisions': [None], 'tsn': '633905'}, 'hierarchyUp': {'author': None, 'class': 'gov.usgs.itis.itis_service.data.SvcHierarchyRecord', 'parentName': None, 'parentTsn': None, 'rankName': None, 'taxonName': None, 'tsn': '633905'}, 'jurisdictionalOriginList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonJurisdictionalOriginList', 'jurisdictionalOrigins': [None], 'tsn': '633905'}, 'kingdom': {'class': 'gov.usgs.itis.itis_service.data.SvcKingdomInfo', 'kingdomId': '5', 'kingdomName': 'Animalia  ', 'tsn': '633905'}, 'otherSourceList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonOtherSourceList', 'otherSources': [None], 'tsn': '633905'}, 'parentTSN': {'class': 'gov.usgs.itis.itis_service.data.SvcParentTsn', 'parentTsn': '0', 'tsn': '633905'}, 'publicationList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonPublicationList', 'publications': [{'actualPubDate': '2003-07-01', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonPublication', 'isbn': '', 'issn': '0013-9351', 'listedPubDate': '2003-07-01', 'pages': '262-270', 'pubComment': '', 'pubName': 'Environmental Research, vol. 92, no. 3', 'pubPlace': '', 'publisher': '', 'referenceAuthor': 'Uguz, Cevdet, Mesude Iscan, Ayse Ergüven, Belgin Isgor, and Inci Togan', 'referenceFor': [{'class': 'gov.usgs.itis.itis_service.data.SvcReferenceForElement', 'name': 'Onchorynchus mykiss', 'refLanguage': None, 'referredTsn': '633905'}], 'title': 'The bioaccumulation of nonyphenol and its adverse effect on the liver of rainbow trout (Onchorynchus mykiss)', 'updateDate': '2004-07-06'}], 'tsn': '633905'}, 'scientificName': {'author': '(Walbaum, 1792)', 'class': 'gov.usgs.itis.itis_service.data.SvcScientificName', 'combinedName': 'Onchorynchus mykiss', 'kingdom': None, 'tsn': '633905', 'unitInd1': None, 'unitInd2': None, 'unitInd3': None, 'unitInd4': None, 'unitName1': 'Onchorynchus                       ', 'unitName2': 'mykiss', 'unitName3': None, 'unitName4': None}, 'synonymList': {'class': 'gov.usgs.itis.itis_service.data.SvcSynonymNameList', 'synonyms': [None], 'tsn': '633905'}, 'taxRank': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonRankInfo', 'kingdomId': '5', 'kingdomName': 'Animalia  ', 'rankId': '220', 'rankName': 'Species        ', 'tsn': '633905'}, 'taxonAuthor': {'authorship': '(Walbaum, 1792)', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonAuthorship', 'tsn': '633905', 'updateDate': '2004-02-23'}, 'tsn': '633905', 'unacceptReason': {'class': 'gov.usgs.itis.itis_service.data.SvcUnacceptData', 'tsn': '633905', 'unacceptReason': 'unavailable, literature misspelling'}, 'usage': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonUsageData', 'taxonUsageRating': 'invalid', 'tsn': '633905'}}, {'acceptedNameList': {'acceptedNames': [{'acceptedName': 'Oncorhynchus mykiss', 'acceptedTsn': '161989', 'author': None, 'class': 'gov.usgs.itis.itis_service.data.SvcAcceptedName'}], 'class': 'gov.usgs.itis.itis_service.data.SvcAcceptedNameList', 'tsn': '914074'}, 'class': 'gov.usgs.itis.itis_service.data.SvcFullRecord', 'commentList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonCommentList', 'comments': [None], 'tsn': '914074'}, 'commonNameList': {'class': 'gov.usgs.itis.itis_service.data.SvcCommonNameList', 'commonNames': [None], 'tsn': '914074'}, 'completenessRating': {'class': 'gov.usgs.itis.itis_service.data.SvcGlobalSpeciesCompleteness', 'completeness': '', 'rankId': 220, 'tsn': '914074'}, 'coreMetadata': {'class': 'gov.usgs.itis.itis_service.data.SvcCoreMetadata', 'credRating': 'TWG standards met', 'rankId': 220, 'taxonCoverage': '', 'taxonCurrency': '', 'taxonUsageRating': 'invalid', 'tsn': '914074', 'unacceptReason': 'junior synonym'}, 'credibilityRating': {'class': 'gov.usgs.itis.itis_service.data.SvcCredibilityData', 'credRating': 'TWG standards met', 'tsn': '914074'}, 'currencyRating': {'class': 'gov.usgs.itis.itis_service.data.SvcCurrencyData', 'rankId': 220, 'taxonCurrency': '', 'tsn': '914074'}, 'dateData': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonDateData', 'initialTimeStamp': '2013-08-14 11:58:29.0', 'tsn': '914074', 'updateDate': '2013-08-14'}, 'expertList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonExpertList', 'experts': [None], 'tsn': '914074'}, 'geographicDivisionList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonGeoDivisionList', 'geoDivisions': [None], 'tsn': '914074'}, 'hierarchyUp': {'author': None, 'class': 'gov.usgs.itis.itis_service.data.SvcHierarchyRecord', 'parentName': None, 'parentTsn': None, 'rankName': None, 'taxonName': None, 'tsn': '914074'}, 'jurisdictionalOriginList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonJurisdictionalOriginList', 'jurisdictionalOrigins': [None], 'tsn': '914074'}, 'kingdom': {'class': 'gov.usgs.itis.itis_service.data.SvcKingdomInfo', 'kingdomId': '5', 'kingdomName': 'Animalia  ', 'tsn': '914074'}, 'otherSourceList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonOtherSourceList', 'otherSources': [{'acquisitionDate': '2013-06-27', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonOtherSource', 'referenceFor': [{'class': 'gov.usgs.itis.itis_service.data.SvcReferenceForElement', 'name': 'Salmo gibbsii', 'refLanguage': None, 'referredTsn': '914074'}], 'source': 'Catalog of Fishes, 10-Jun-2013', 'sourceComment': 'http://research.calacademy.org/research/ichthyology/catalog/fishcatmain.asp', 'sourceType': 'website', 'updateDate': '2013-08-14', 'version': '10-Jun-13'}], 'tsn': '914074'}, 'parentTSN': {'class': 'gov.usgs.itis.itis_service.data.SvcParentTsn', 'parentTsn': '0', 'tsn': '914074'}, 'publicationList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonPublicationList', 'publications': [None], 'tsn': '914074'}, 'scientificName': {'author': 'Suckley, 1859', 'class': 'gov.usgs.itis.itis_service.data.SvcScientificName', 'combinedName': 'Salmo gibbsii', 'kingdom': None, 'tsn': '914074', 'unitInd1': None, 'unitInd2': None, 'unitInd3': None, 'unitInd4': None, 'unitName1': 'Salmo                              ', 'unitName2': 'gibbsii', 'unitName3': None, 'unitName4': None}, 'synonymList': {'class': 'gov.usgs.itis.itis_service.data.SvcSynonymNameList', 'synonyms': [None], 'tsn': '914074'}, 'taxRank': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonRankInfo', 'kingdomId': '5', 'kingdomName': 'Animalia  ', 'rankId': '220', 'rankName': 'Species        ', 'tsn': '914074'}, 'taxonAuthor': {'authorship': 'Suckley, 1859', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonAuthorship', 'tsn': '914074', 'updateDate': '2013-08-14'}, 'tsn': '914074', 'unacceptReason': {'class': 'gov.usgs.itis.itis_service.data.SvcUnacceptData', 'tsn': '914074', 'unacceptReason': 'junior synonym'}, 'usage': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonUsageData', 'taxonUsageRating': 'invalid', 'tsn': '914074'}}, {'acceptedNameList': {'acceptedNames': [{'acceptedName': 'Oncorhynchus mykiss', 'acceptedTsn': '161989', 'author': None, 'class': 'gov.usgs.itis.itis_service.data.SvcAcceptedName'}], 'class': 'gov.usgs.itis.itis_service.data.SvcAcceptedNameList', 'tsn': '914094'}, 'class': 'gov.usgs.itis.itis_service.data.SvcFullRecord', 'commentList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonCommentList', 'comments': [{'class': 'gov.usgs.itis.itis_service.data.SvcTaxonComment', 'commentDetail': 'US ESA: Potential candidate without sufficient data on vulnerability, as published in Federal Register Volume 59, Number 219, Pages 58982 - 59028, November 15, 1994', 'commentId': '21591', 'commentTimeStamp': '2011-05-27 13:26:03.0', 'commentator': 'David F. Mitchell, ITIS Data Development Specialist', 'updateDate': '2026-03-18'}], 'tsn': '914094'}, 'commonNameList': {'class': 'gov.usgs.itis.itis_service.data.SvcCommonNameList', 'commonNames': [{'class': 'gov.usgs.itis.itis_service.data.SvcCommonName', 'commonName': 'interior redband trout', 'language': 'English', 'tsn': '914094'}], 'tsn': '914094'}, 'completenessRating': {'class': 'gov.usgs.itis.itis_service.data.SvcGlobalSpeciesCompleteness', 'completeness': '', 'rankId': 230, 'tsn': '914094'}, 'coreMetadata': {'class': 'gov.usgs.itis.itis_service.data.SvcCoreMetadata', 'credRating': 'TWG standards met', 'rankId': 230, 'taxonCoverage': '', 'taxonCurrency': '', 'taxonUsageRating': 'invalid', 'tsn': '914094', 'unacceptReason': 'junior synonym'}, 'credibilityRating': {'class': 'gov.usgs.itis.itis_service.data.SvcCredibilityData', 'credRating': 'TWG standards met', 'tsn': '914094'}, 'currencyRating': {'class': 'gov.usgs.itis.itis_service.data.SvcCurrencyData', 'rankId': 230, 'taxonCurrency': '', 'tsn': '914094'}, 'dateData': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonDateData', 'initialTimeStamp': '2013-08-14 11:58:34.0', 'tsn': '914094', 'updateDate': '2013-08-14'}, 'expertList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonExpertList', 'experts': [None], 'tsn': '914094'}, 'geographicDivisionList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonGeoDivisionList', 'geoDivisions': [None], 'tsn': '914094'}, 'hierarchyUp': {'author': None, 'class': 'gov.usgs.itis.itis_service.data.SvcHierarchyRecord', 'parentName': None, 'parentTsn': None, 'rankName': None, 'taxonName': None, 'tsn': '914094'}, 'jurisdictionalOriginList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonJurisdictionalOriginList', 'jurisdictionalOrigins': [None], 'tsn': '914094'}, 'kingdom': {'class': 'gov.usgs.itis.itis_service.data.SvcKingdomInfo', 'kingdomId': '5', 'kingdomName': 'Animalia  ', 'tsn': '914094'}, 'otherSourceList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonOtherSourceList', 'otherSources': [None], 'tsn': '914094'}, 'parentTSN': {'class': 'gov.usgs.itis.itis_service.data.SvcParentTsn', 'parentTsn': '0', 'tsn': '914094'}, 'publicationList': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonPublicationList', 'publications': [{'actualPubDate': '1994-11-15', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonPublication', 'isbn': '', 'issn': '', 'listedPubDate': '1994-11-15', 'pages': '58982-59028', 'pubComment': '', 'pubName': 'Federal Register, vol. 59, no. 219', 'pubPlace': '', 'publisher': '', 'referenceAuthor': 'U. S. Fish and Wildlife Service', 'referenceFor': [{'class': 'gov.usgs.itis.itis_service.data.SvcReferenceForElement', 'name': 'Oncorhynchus mykiss gibbsi', 'refLanguage': None, 'referredTsn': '914094'}], 'title': 'Endangered and Threatened Wildlife and Plants; Animal Candidate Review for Listing as Endangered or Threatened Species', 'updateDate': '2026-03-18'}], 'tsn': '914094'}, 'scientificName': {'author': '(Suckley, 1859)', 'class': 'gov.usgs.itis.itis_service.data.SvcScientificName', 'combinedName': 'Oncorhynchus mykiss gibbsi', 'kingdom': None, 'tsn': '914094', 'unitInd1': None, 'unitInd2': None, 'unitInd3': None, 'unitInd4': None, 'unitName1': 'Oncorhynchus                       ', 'unitName2': 'mykiss', 'unitName3': 'gibbsi', 'unitName4': None}, 'synonymList': {'class': 'gov.usgs.itis.itis_service.data.SvcSynonymNameList', 'synonyms': [None], 'tsn': '914094'}, 'taxRank': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonRankInfo', 'kingdomId': '5', 'kingdomName': 'Animalia  ', 'rankId': '230', 'rankName': 'Subspecies     ', 'tsn': '914094'}, 'taxonAuthor': {'authorship': '(Suckley, 1859)', 'class': 'gov.usgs.itis.itis_service.data.SvcTaxonAuthorship', 'tsn': '914094', 'updateDate': '2004-01-22'}, 'tsn': '914094', 'unacceptReason': {'class': 'gov.usgs.itis.itis_service.data.SvcUnacceptData', 'tsn': '914094', 'unacceptReason': 'junior synonym'}, 'usage': {'class': 'gov.usgs.itis.itis_service.data.SvcTaxonUsageData', 'taxonUsageRating': 'invalid', 'tsn': '914094'}}]
_fetch_accepted_data

============================================================
  ITIS  (ITISAPI)
  Species:   Not species
  Name type: not species
============================================================
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

---
## GenBank (NCBI Entrez)

GenBank is the NIH genetic sequence database maintained by NCBI. Its Taxonomy division provides accepted names and synonym lists via the Entrez E-utilities (`esearch` + `efetch`); all responses are XML.

Uses the **standard base-class** `get_synonyms()` pipeline.

The call here passes `sleep_between_species=1.0`. NCBI rate-limits unauthenticated callers to **3 requests/second**, and each `get_synonyms()` call makes 2 requests (`esearch` + `efetch`), so sleeping 1 second between species queries keeps well within that limit. Without the sleep, rapid back-to-back calls will be throttled or blocked by NCBI. This is not needed in the normal pipeline when used with the frontend.

In [10]:
from scripts.apis_pipe.genbank import GenBankAPI

run_queries(
    [(GENBANK_PORTAL, GenBankAPI(), "Amanita muscaria", "Agaricus muscarius")],
    sleep_between_species=1.0,
)

============================================================
  GenBank  (GenBankAPI)
  Species:   Amanita muscaria
  Name type: accepted
============================================================
_fetch_query_data
{'header': {'type': 'esearch', 'version': '0.3'}, 'esearchresult': {'count': '1', 'retmax': '1', 'retstart': '0', 'idlist': ['41956'], 'translationset': [], 'translationstack': [{'term': 'Amanita muscaria[Scientific Name]', 'field': 'Scientific Name', 'count': '1', 'explode': 'N'}, 'GROUP'], 'querytranslation': 'Amanita muscaria[Scientific Name]'}}
_fetch_synonym_data
<TaxaSet><Taxon>
    <TaxId>41956</TaxId>
    <ScientificName>Amanita muscaria</ScientificName>
    <OtherNames>
        <GenbankCommonName>fly agaric</GenbankCommonName>
        <Synonym>Agaricus muscarius</Synonym>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Agaricus muscarius L., 1753</DispName>
        </Name>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Amanita muscaria (L.) Lam., 1783</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria on Nothofagus fusca</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria/Nothofagus fusca</DispName>
        </Name>
    </OtherNames>
    <ParentTaxId>41955</ParentTaxId>
    <Rank>species</Rank>
    <Division>Plants and Fungi</Division>
    <GeneticCode>
        <GCId>1</GCId>
        <GCName>Standard</GCName>
    </GeneticCode>
    <MitoGeneticCode>
        <MGCId>4</MGCId>
        <MGCName>Mold Mitochondrial; Protozoan Mitochondrial; Coelenterate Mitochondrial; Mycoplasma; Spiroplasma</MGCName>
    </MitoGeneticCode>
    <Lineage>cellular organisms; Eukaryota; Opisthokonta; Fungi; Dikarya; Basidiomycota; Agaricomycotina; Agaricomycetes; Agaricomycetidae; Agaricales; Pluteineae; Amanitaceae; Amanita</Lineage>
    <LineageEx>
        <Taxon>
            <TaxId>131567</TaxId>
            <ScientificName>cellular organisms</ScientificName>
            <Rank>cellular root</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2759</TaxId>
            <ScientificName>Eukaryota</ScientificName>
            <Rank>domain</Rank>
        </Taxon>
        <Taxon>
            <TaxId>33154</TaxId>
            <ScientificName>Opisthokonta</ScientificName>
            <Rank>clade</Rank>
        </Taxon>
        <Taxon>
            <TaxId>4751</TaxId>
            <ScientificName>Fungi</ScientificName>
            <Rank>kingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>451864</TaxId>
            <ScientificName>Dikarya</ScientificName>
            <Rank>subkingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5204</TaxId>
            <ScientificName>Basidiomycota</ScientificName>
            <Rank>phylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5302</TaxId>
            <ScientificName>Agaricomycotina</ScientificName>
            <Rank>subphylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>155619</TaxId>
            <ScientificName>Agaricomycetes</ScientificName>
            <Rank>class</Rank>
        </Taxon>
        <Taxon>
            <TaxId>452333</TaxId>
            <ScientificName>Agaricomycetidae</ScientificName>
            <Rank>subclass</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5338</TaxId>
            <ScientificName>Agaricales</ScientificName>
            <Rank>order</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2982306</TaxId>
            <ScientificName>Pluteineae</ScientificName>
            <Rank>suborder</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41954</TaxId>
            <ScientificName>Amanitaceae</ScientificName>
            <Rank>family</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41955</TaxId>
            <ScientificName>Amanita</ScientificName>
            <Rank>genus</Rank>
        </Taxon>
    </LineageEx>
    <CreateDate>1995/08/04 11:19:00</CreateDate>
    <UpdateDate>2025/08/08 10:02:44</UpdateDate>
    <PubDate>1996/10/10 01:00:00</PubDate>
</Taxon>

</TaxaSet>
_fetch_accepted_data
<TaxaSet><Taxon>
    <TaxId>41956</TaxId>
    <ScientificName>Amanita muscaria</ScientificName>
    <OtherNames>
        <GenbankCommonName>fly agaric</GenbankCommonName>
        <Synonym>Agaricus muscarius</Synonym>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Agaricus muscarius L., 1753</DispName>
        </Name>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Amanita muscaria (L.) Lam., 1783</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria on Nothofagus fusca</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria/Nothofagus fusca</DispName>
        </Name>
    </OtherNames>
    <ParentTaxId>41955</ParentTaxId>
    <Rank>species</Rank>
    <Division>Plants and Fungi</Division>
    <GeneticCode>
        <GCId>1</GCId>
        <GCName>Standard</GCName>
    </GeneticCode>
    <MitoGeneticCode>
        <MGCId>4</MGCId>
        <MGCName>Mold Mitochondrial; Protozoan Mitochondrial; Coelenterate Mitochondrial; Mycoplasma; Spiroplasma</MGCName>
    </MitoGeneticCode>
    <Lineage>cellular organisms; Eukaryota; Opisthokonta; Fungi; Dikarya; Basidiomycota; Agaricomycotina; Agaricomycetes; Agaricomycetidae; Agaricales; Pluteineae; Amanitaceae; Amanita</Lineage>
    <LineageEx>
        <Taxon>
            <TaxId>131567</TaxId>
            <ScientificName>cellular organisms</ScientificName>
            <Rank>cellular root</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2759</TaxId>
            <ScientificName>Eukaryota</ScientificName>
            <Rank>domain</Rank>
        </Taxon>
        <Taxon>
            <TaxId>33154</TaxId>
            <ScientificName>Opisthokonta</ScientificName>
            <Rank>clade</Rank>
        </Taxon>
        <Taxon>
            <TaxId>4751</TaxId>
            <ScientificName>Fungi</ScientificName>
            <Rank>kingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>451864</TaxId>
            <ScientificName>Dikarya</ScientificName>
            <Rank>subkingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5204</TaxId>
            <ScientificName>Basidiomycota</ScientificName>
            <Rank>phylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5302</TaxId>
            <ScientificName>Agaricomycotina</ScientificName>
            <Rank>subphylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>155619</TaxId>
            <ScientificName>Agaricomycetes</ScientificName>
            <Rank>class</Rank>
        </Taxon>
        <Taxon>
            <TaxId>452333</TaxId>
            <ScientificName>Agaricomycetidae</ScientificName>
            <Rank>subclass</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5338</TaxId>
            <ScientificName>Agaricales</ScientificName>
            <Rank>order</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2982306</TaxId>
            <ScientificName>Pluteineae</ScientificName>
            <Rank>suborder</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41954</TaxId>
            <ScientificName>Amanitaceae</ScientificName>
            <Rank>family</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41955</TaxId>
            <ScientificName>Amanita</ScientificName>
            <Rank>genus</Rank>
        </Taxon>
    </LineageEx>
    <CreateDate>1995/08/04 11:19:00</CreateDate>
    <UpdateDate>2025/08/08 10:02:44</UpdateDate>
    <PubDate>1996/10/10 01:00:00</PubDate>
</Taxon>

</TaxaSet>
Synonyms returned: 2

============================================================
  GenBank  (GenBankAPI)
  Species:   Agaricus muscarius
  Name type: synonym  (synonym of: Amanita muscaria)
============================================================
_fetch_query_data
{'header': {'type': 'esearch', 'version': '0.3'}, 'esearchresult': {'count': '1', 'retmax': '1', 'retstart': '0', 'idlist': ['41956'], 'translationset': [], 'translationstack': [{'term': 'Agaricus muscarius[All Names]', 'field': 'All Names', 'count': '1', 'explode': 'N'}, 'GROUP'], 'querytranslation': 'Agaricus muscarius[All Names]'}}
_fetch_synonym_data
<TaxaSet><Taxon>
    <TaxId>41956</TaxId>
    <ScientificName>Amanita muscaria</ScientificName>
    <OtherNames>
        <GenbankCommonName>fly agaric</GenbankCommonName>
        <Synonym>Agaricus muscarius</Synonym>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Agaricus muscarius L., 1753</DispName>
        </Name>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Amanita muscaria (L.) Lam., 1783</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria on Nothofagus fusca</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria/Nothofagus fusca</DispName>
        </Name>
    </OtherNames>
    <ParentTaxId>41955</ParentTaxId>
    <Rank>species</Rank>
    <Division>Plants and Fungi</Division>
    <GeneticCode>
        <GCId>1</GCId>
        <GCName>Standard</GCName>
    </GeneticCode>
    <MitoGeneticCode>
        <MGCId>4</MGCId>
        <MGCName>Mold Mitochondrial; Protozoan Mitochondrial; Coelenterate Mitochondrial; Mycoplasma; Spiroplasma</MGCName>
    </MitoGeneticCode>
    <Lineage>cellular organisms; Eukaryota; Opisthokonta; Fungi; Dikarya; Basidiomycota; Agaricomycotina; Agaricomycetes; Agaricomycetidae; Agaricales; Pluteineae; Amanitaceae; Amanita</Lineage>
    <LineageEx>
        <Taxon>
            <TaxId>131567</TaxId>
            <ScientificName>cellular organisms</ScientificName>
            <Rank>cellular root</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2759</TaxId>
            <ScientificName>Eukaryota</ScientificName>
            <Rank>domain</Rank>
        </Taxon>
        <Taxon>
            <TaxId>33154</TaxId>
            <ScientificName>Opisthokonta</ScientificName>
            <Rank>clade</Rank>
        </Taxon>
        <Taxon>
            <TaxId>4751</TaxId>
            <ScientificName>Fungi</ScientificName>
            <Rank>kingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>451864</TaxId>
            <ScientificName>Dikarya</ScientificName>
            <Rank>subkingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5204</TaxId>
            <ScientificName>Basidiomycota</ScientificName>
            <Rank>phylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5302</TaxId>
            <ScientificName>Agaricomycotina</ScientificName>
            <Rank>subphylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>155619</TaxId>
            <ScientificName>Agaricomycetes</ScientificName>
            <Rank>class</Rank>
        </Taxon>
        <Taxon>
            <TaxId>452333</TaxId>
            <ScientificName>Agaricomycetidae</ScientificName>
            <Rank>subclass</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5338</TaxId>
            <ScientificName>Agaricales</ScientificName>
            <Rank>order</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2982306</TaxId>
            <ScientificName>Pluteineae</ScientificName>
            <Rank>suborder</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41954</TaxId>
            <ScientificName>Amanitaceae</ScientificName>
            <Rank>family</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41955</TaxId>
            <ScientificName>Amanita</ScientificName>
            <Rank>genus</Rank>
        </Taxon>
    </LineageEx>
    <CreateDate>1995/08/04 11:19:00</CreateDate>
    <UpdateDate>2025/08/08 10:02:44</UpdateDate>
    <PubDate>1996/10/10 01:00:00</PubDate>
</Taxon>

</TaxaSet>
_fetch_accepted_data
<TaxaSet><Taxon>
    <TaxId>41956</TaxId>
    <ScientificName>Amanita muscaria</ScientificName>
    <OtherNames>
        <GenbankCommonName>fly agaric</GenbankCommonName>
        <Synonym>Agaricus muscarius</Synonym>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Agaricus muscarius L., 1753</DispName>
        </Name>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Amanita muscaria (L.) Lam., 1783</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria on Nothofagus fusca</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria/Nothofagus fusca</DispName>
        </Name>
    </OtherNames>
    <ParentTaxId>41955</ParentTaxId>
    <Rank>species</Rank>
    <Division>Plants and Fungi</Division>
    <GeneticCode>
        <GCId>1</GCId>
        <GCName>Standard</GCName>
    </GeneticCode>
    <MitoGeneticCode>
        <MGCId>4</MGCId>
        <MGCName>Mold Mitochondrial; Protozoan Mitochondrial; Coelenterate Mitochondrial; Mycoplasma; Spiroplasma</MGCName>
    </MitoGeneticCode>
    <Lineage>cellular organisms; Eukaryota; Opisthokonta; Fungi; Dikarya; Basidiomycota; Agaricomycotina; Agaricomycetes; Agaricomycetidae; Agaricales; Pluteineae; Amanitaceae; Amanita</Lineage>
    <LineageEx>
        <Taxon>
            <TaxId>131567</TaxId>
            <ScientificName>cellular organisms</ScientificName>
            <Rank>cellular root</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2759</TaxId>
            <ScientificName>Eukaryota</ScientificName>
            <Rank>domain</Rank>
        </Taxon>
        <Taxon>
            <TaxId>33154</TaxId>
            <ScientificName>Opisthokonta</ScientificName>
            <Rank>clade</Rank>
        </Taxon>
        <Taxon>
            <TaxId>4751</TaxId>
            <ScientificName>Fungi</ScientificName>
            <Rank>kingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>451864</TaxId>
            <ScientificName>Dikarya</ScientificName>
            <Rank>subkingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5204</TaxId>
            <ScientificName>Basidiomycota</ScientificName>
            <Rank>phylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5302</TaxId>
            <ScientificName>Agaricomycotina</ScientificName>
            <Rank>subphylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>155619</TaxId>
            <ScientificName>Agaricomycetes</ScientificName>
            <Rank>class</Rank>
        </Taxon>
        <Taxon>
            <TaxId>452333</TaxId>
            <ScientificName>Agaricomycetidae</ScientificName>
            <Rank>subclass</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5338</TaxId>
            <ScientificName>Agaricales</ScientificName>
            <Rank>order</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2982306</TaxId>
            <ScientificName>Pluteineae</ScientificName>
            <Rank>suborder</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41954</TaxId>
            <ScientificName>Amanitaceae</ScientificName>
            <Rank>family</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41955</TaxId>
            <ScientificName>Amanita</ScientificName>
            <Rank>genus</Rank>
        </Taxon>
    </LineageEx>
    <CreateDate>1995/08/04 11:19:00</CreateDate>
    <UpdateDate>2025/08/08 10:02:44</UpdateDate>
    <PubDate>1996/10/10 01:00:00</PubDate>
</Taxon>

</TaxaSet>
Synonyms returned: 2

============================================================
  GenBank  (GenBankAPI)
  Species:   Not species
  Name type: not species
============================================================
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

---
## Symbiota Portals

Symbiota is open-source biodiversity data management software powering numerous natural history collection portals worldwide. Each portal runs its own instance with independent data but the same API structure. `SymbiotaAPI` is instantiated with the portal name, which resolves the correct base URL from `config.py`.

**Custom `get_synonyms()` orchestration.** Unlike the base class, Symbiota resolves the accepted `tid` explicitly before calling the fetch methods. The fetch sequence is:

1. `_fetch_query_data` — performs two calls: a name search to find the initial `tid`, followed by a full `api/v2/taxonomy/{tid}` fetch; returns a combined taxon record
2. `_extract_internal_accepted_id` — reads the accepted `tid` from the combined record (no API call)
3. `_fetch_synonym_data` — scrapes the `/taxa/index.php` HTML page for the accepted taxon's synonym entries
4. `_fetch_accepted_data` — fetches the full `api/v2/taxonomy/{accepted_tid}` JSON record for taxonomy and authorship *(skipped and `raw_data` reused directly if the queried name is already accepted)*

Symbiota portals do not assign separate IDs to synonym records; a single accepted `tid` is used for both `api_internal_id` and `api_link` across every row.

The portals below all share this implementation and are queried in sequence.

In [11]:
from scripts.apis_pipe.symbiota import SymbiotaAPI

_SYMBIOTA_QUERIES = [
    # (portal, accepted_species, synonym_of_accepted)
    (SYMBIOTA_PORTAL_BY_NAME["MyCoPortal"],                       "Agaricus campestris",     "Psalliota villatica"),
    (SYMBIOTA_PORTAL_BY_NAME["Lichen Portal"],                    "Xanthoria parietina",     "Physcia parietina"),
    (SYMBIOTA_PORTAL_BY_NAME["Bryophyte Portal"],                 "Pohlia nutans",           "Webera nutans"),
    (SYMBIOTA_PORTAL_BY_NAME["CCH2"],                             "Heteromeles arbutifolia", "Photinia arbutifolia"),
    (SYMBIOTA_PORTAL_BY_NAME["SERNEC"],                           "Magnolia grandiflora",    "Magnolia foetida"),
    (SYMBIOTA_PORTAL_BY_NAME["NANSH"],                            "Rudbeckia hirta",         "Coreopsis hirta"),
    (SYMBIOTA_PORTAL_BY_NAME["Algae Herbarium Portal"],           "Ulva intestinalis",       "Ilea intestinalis"),
    (SYMBIOTA_PORTAL_BY_NAME["Pterido Portal"],                   "Dryopteris filix-mas",    "Nephrodium filix-mas"),
    (SYMBIOTA_PORTAL_BY_NAME["CNH"],                              "Impatiens capensis",      "Impatiens biflora"),
    (SYMBIOTA_PORTAL_BY_NAME["Mid-Atlantic Herbaria Consortium"], "Quercus rubra",           "Quercus maxima"),
    (SYMBIOTA_PORTAL_BY_NAME["swbiodiversity"],                   "Larrea tridentata",       "Larrea mexicana"),
]

run_queries([
    (portal, SymbiotaAPI(portal.display_name), accepted, synonym)
    for portal, accepted, synonym in _SYMBIOTA_QUERIES
])

============================================================
  MyCoPortal  (SymbiotaAPI)
  Species:   Agaricus campestris
  Name type: accepted
============================================================
[MyCoPortal] 'api/v2/taxonomy/search' returned results for 'Agaricus campestris'.
_fetch_query_data
{'tid': 214862, 'kingdomName': 'Fungi', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Agaricus', 'unitInd2': None, 'unitName2': 'campestris', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'L.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2011-11-18 23:38:57', 'parentTid': 11736, 'status': 'accepted', 'classification': [{'tid': 7, 'scientificName': 'Fungi', 'author': 'R.T. Moore', 'rankid': 10}, {'tid': 188, 'scientificName': 'Basidiomycota', 'author': 'R.T. Moore', 'rankid': 30}, {'tid': 1128, 'scientificName': 'Agaricomycotina', 'author': 'Doweld', 'rankid': 40}, {'tid': 1431, 'scientificName': 'Agaricomycetes', 'author': 'Doweld', 'rankid': 60}, {'tid': 5489, 'scientificName': 'Agaricomycetidae', 'author': 'Parmasto', 'rankid': 70}, {'tid': 6519, 'scientificName': 'Agaricales', 'author': 'Underw.', 'rankid': 100}, {'tid': 7158, 'scientificName': 'Polyporales', 'author': '', 'rankid': 100}, {'tid': 7561, 'scientificName': 'Agaricaceae', 'author': 'Chevall.', 'rankid': 140}, {'tid': 7600, 'scientificName': 'Amanitaceae', 'author': '', 'rankid': 140}, {'tid': 8610, 'scientificName': 'Fomitopsidaceae', 'author': '', 'rankid': 140}, {'tid': 11736, 'scientificName': 'Agaricus (d2)', 'author': 'L.', 'rankid': 180}], 'scientificName': 'Agaricus campestris'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Mycology Collections Portal  - Agaricus campestris</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<!-- Responsive viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/accessibility-compliant.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" disabled >
	<link href="/portal/css/symbiota/condensed.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" >

<link href="/portal/assets/custom/css/main.css" type="text/css" rel="stylesheet" />

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>
<script src="/portal/assets/custom/js/main.js" type="text/javascript"></script>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-1036HJZLL9"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-1036HJZLL9');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>

<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="contactUs">
						<button class="button button-tertiary bottom-breathing-room-rel left-breathing-room-rel" onclick="window.location.href='#'">Contact Us</button>
					</span>
					<span id="login">
						<form name="loginForm" method="post" action="/portal/profile/index.php">
							<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=214862">
							<button class="button button-secondary bottom-breathing-room-rel left-breathing-room-rel" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
						<div class="top-brand custom">
				<a href="/portal">
					<div class="image-container">
					</div>
				</a>
                				<div class="brand-name">
                    <h1 class="header-mast-title light"><span class="dark">Mycology</span> Collections Portal</h1>
					<h2></h2>
				</div>
			</div>

		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					                    <li class="search-menu">
                        <a href="/portal/collections/index.php">Explore</a>
                        <ul>
                            <li class="search-menu">
                                <a href="/portal/collections/index.php">Search</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/collections/search/index.php">Advanced Search</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/collections/map/index.php">Map Search</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/collections/exsiccati/index.php">Exsicatti</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/imagelib/search.php">Media Search</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/imagelib/index.php">Media Browser</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/imagelib/contributors.php">Media Providers</a>
                            </li>
                        </ul>
                    </li>

					                    <li class="crowdsource-menu">
                        <a href="/portal/collections/specprocessor/crowdsource/central.php">Crowdsource</a>
                        <ul>
                            <li class="crowdsource-menu">
                                <a href="/portal/misc/crowdsource.php">Get Involved</a>
                            </li>
                            <li class="crowdsource-menu">
                                <a href="/portal/collections/specprocessor/crowdsource/central.php">Score Board</a>
                            </li>
                        </ul>
                    </li>

					                    <li class="checklists-menu">
                        <a href="/portal/projects/index.php?">Checklist Projects</a>
                        <ul>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=13">Fungi (World): Historic</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=4">Fungi (North America): Historic</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=3">Macrofungi (North America): Groups</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=8">Macrofungi (North America): Local</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=2">Macrofungi (North America): Regions</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=7">Macrofungi (World): Countries</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=11">Microfungi (North America): Regions</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=12">Microfungi (World): Countries</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/checklists/dynamicmap.php?interface=checklist">Dynamic Checklist</a>
                            </li>
                        </ul>
                    </li>


					                    <li class="other-menu">
                        <a href="#">Other Resources</a>
                        <ul>
                            <li class="other-menu">
                                <a href="/portal/collections/misc/collstats.php">Collection Statistics</a>
                            </li>
                            <li class="other-menu">
                                <a href="/portal/tk/?/taxonomy-report">Collection taxonomy report</a>
                            </li>
                            <li class="other-menu">
                                <a href="/portal/tk/?/genbank">GenBank source modifiers</a>
                            </li>
                            <li class="other-menu">
                                <a href="/portal/tk/?/">Symbiota toolkit</a>
                            </li>
                            <li class="other-menu">
                                <a href="/portal/misc/links.php">Document Links</a>
                            </li>
                            <li class="other-menu">
                                <a href="https://bryophyteportal.org/portal" target="_blank" rel="noopener noreferrer">Bryophyte Portal</a>
                            </li>
                            <li class="other-menu">
                                <a href="https://lichenportal.org/portal" target="_blank" rel="noopener noreferrer">Lichen Portal</a>
                            </li>
                            <li class="other-menu">
                                <a href="https://swbiodiversity.org/seinet" target="_blank" rel="noopener noreferrer">Vascular Plant Portal</a>
                            </li>
                            <li class="other-menu">
                                <a href="https://symbiota.org" target="_blank" rel="noopener noreferrer">Symbiota Help Page</a>
                            </li>
                        </ul>
                    </li>

										<li class="acknowledgements-menu">
                        <a href="/portal/misc/acknowledgements.php">Acknowledgements</a>
					</li>

					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>

					<li id="lang-select-li">
						<label for="language-selection">Select Language: </label>
						<select oninput="setLanguage(this)" id="language-selection" name="language-selection">
							<option value="en">English</option>
							<option value="es" >Español</option>
							<option value="fr" >Français</option>
							<option value="pt" >Português</option>
						</select>
					</li>
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Agaricus campestris</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Agaricus campestris</i></span>							<span id="author">L.</span>
							&nbsp;<a href="index.php?tid=11736&amp;clid=0&amp;pid=2&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Agaricaceae</div>
						<div id="synonymDiv" title="Synonyms">[<i>Psalliota villatica</i> (Brond.) Bres.]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../imagelib/imgdetails.php?mediaid=43107');return false;"><img src="http://images.mushroomobserver.org/1280/210023.jpg" title="" alt="Agaricus campestris image" /></a></div><div class="creator">NAMA Voucher Collection Project</div></div>					</td>
					<td class="desc">
						<div id="desctabs" class="ui-tabs" style="display:none"><ul class="ui-tabs-nav"><li><a href="resourcetab.php?tid=214862">Resources</a></li></ul>					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="img-div" style="height:300px;overflow:hidden;">

============================================================
  MyCoPortal  (SymbiotaAPI)
  Species:   Psalliota villatica
  Name type: synonym  (synonym of: Agaricus campestris)
============================================================
[MyCoPortal] 'api/v2/taxonomy/search' returned results for 'Psalliota villatica'.
_fetch_query_data
{'tid': 527987, 'kingdomName': 'Fungi', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Psalliota', 'unitInd2': None, 'unitName2': 'villatica', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(Brond.) Bres.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'Index Fungorum', 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2011-11-19 14:07:42', 'parentTid': 17617, 'status': 'synonym', 'accepted': {'tid': 214862, 'scientificName': 'Agaricus campestris', 'scientificNameAuthorship': 'L.', 'taxonomicSource': None, 'unacceptabilityReason': None, 'taxonRemarks': None}, 'classification': [{'tid': 7, 'scientificName': 'Fungi', 'author': 'R.T. Moore', 'rankid': 10}, {'tid': 188, 'scientificName': 'Basidiomycota', 'author': 'R.T. Moore', 'rankid': 30}, {'tid': 1128, 'scientificName': 'Agaricomycotina', 'author': 'Doweld', 'rankid': 40}, {'tid': 1431, 'scientificName': 'Agaricomycetes', 'author': 'Doweld', 'rankid': 60}, {'tid': 5489, 'scientificName': 'Agaricomycetidae', 'author': 'Parmasto', 'rankid': 70}, {'tid': 6519, 'scientificName': 'Agaricales', 'author': 'Underw.', 'rankid': 100}, {'tid': 7561, 'scientificName': 'Agaricaceae', 'author': 'Chevall.', 'rankid': 140}, {'tid': 17617, 'scientificName': 'Psalliota', 'author': '(Fr.) P. Kumm.', 'rankid': 180}], 'scientificName': 'Psalliota villatica'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Mycology Collections Portal  - Agaricus campestris</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<!-- Responsive viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/accessibility-compliant.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" disabled >
	<link href="/portal/css/symbiota/condensed.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" >

<link href="/portal/assets/custom/css/main.css" type="text/css" rel="stylesheet" />

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>
<script src="/portal/assets/custom/js/main.js" type="text/javascript"></script>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-1036HJZLL9"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-1036HJZLL9');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>

<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="contactUs">
						<button class="button button-tertiary bottom-breathing-room-rel left-breathing-room-rel" onclick="window.location.href='#'">Contact Us</button>
					</span>
					<span id="login">
						<form name="loginForm" method="post" action="/portal/profile/index.php">
							<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=214862">
							<button class="button button-secondary bottom-breathing-room-rel left-breathing-room-rel" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
						<div class="top-brand custom">
				<a href="/portal">
					<div class="image-container">
					</div>
				</a>
                				<div class="brand-name">
                    <h1 class="header-mast-title light"><span class="dark">Mycology</span> Collections Portal</h1>
					<h2></h2>
				</div>
			</div>

		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					                    <li class="search-menu">
                        <a href="/portal/collections/index.php">Explore</a>
                        <ul>
                            <li class="search-menu">
                                <a href="/portal/collections/index.php">Search</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/collections/search/index.php">Advanced Search</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/collections/map/index.php">Map Search</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/collections/exsiccati/index.php">Exsicatti</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/imagelib/search.php">Media Search</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/imagelib/index.php">Media Browser</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/imagelib/contributors.php">Media Providers</a>
                            </li>
                        </ul>
                    </li>

					                    <li class="crowdsource-menu">
                        <a href="/portal/collections/specprocessor/crowdsource/central.php">Crowdsource</a>
                        <ul>
                            <li class="crowdsource-menu">
                                <a href="/portal/misc/crowdsource.php">Get Involved</a>
                            </li>
                            <li class="crowdsource-menu">
                                <a href="/portal/collections/specprocessor/crowdsource/central.php">Score Board</a>
                            </li>
                        </ul>
                    </li>

					                    <li class="checklists-menu">
                        <a href="/portal/projects/index.php?">Checklist Projects</a>
                        <ul>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=13">Fungi (World): Historic</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=4">Fungi (North America): Historic</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=3">Macrofungi (North America): Groups</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=8">Macrofungi (North America): Local</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=2">Macrofungi (North America): Regions</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=7">Macrofungi (World): Countries</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=11">Microfungi (North America): Regions</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=12">Microfungi (World): Countries</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/checklists/dynamicmap.php?interface=checklist">Dynamic Checklist</a>
                            </li>
                        </ul>
                    </li>


					                    <li class="other-menu">
                        <a href="#">Other Resources</a>
                        <ul>
                            <li class="other-menu">
                                <a href="/portal/collections/misc/collstats.php">Collection Statistics</a>
                            </li>
                            <li class="other-menu">
                                <a href="/portal/tk/?/taxonomy-report">Collection taxonomy report</a>
                            </li>
                            <li class="other-menu">
                                <a href="/portal/tk/?/genbank">GenBank source modifiers</a>
                            </li>
                            <li class="other-menu">
                                <a href="/portal/tk/?/">Symbiota toolkit</a>
                            </li>
                            <li class="other-menu">
                                <a href="/portal/misc/links.php">Document Links</a>
                            </li>
                            <li class="other-menu">
                                <a href="https://bryophyteportal.org/portal" target="_blank" rel="noopener noreferrer">Bryophyte Portal</a>
                            </li>
                            <li class="other-menu">
                                <a href="https://lichenportal.org/portal" target="_blank" rel="noopener noreferrer">Lichen Portal</a>
                            </li>
                            <li class="other-menu">
                                <a href="https://swbiodiversity.org/seinet" target="_blank" rel="noopener noreferrer">Vascular Plant Portal</a>
                            </li>
                            <li class="other-menu">
                                <a href="https://symbiota.org" target="_blank" rel="noopener noreferrer">Symbiota Help Page</a>
                            </li>
                        </ul>
                    </li>

										<li class="acknowledgements-menu">
                        <a href="/portal/misc/acknowledgements.php">Acknowledgements</a>
					</li>

					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>

					<li id="lang-select-li">
						<label for="language-selection">Select Language: </label>
						<select oninput="setLanguage(this)" id="language-selection" name="language-selection">
							<option value="en">English</option>
							<option value="es" >Español</option>
							<option value="fr" >Français</option>
							<option value="pt" >Português</option>
						</select>
					</li>
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Agaricus campestris</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Agaricus campestris</i></span>							<span id="author">L.</span>
							&nbsp;<a href="index.php?tid=11736&amp;clid=0&amp;pid=2&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Agaricaceae</div>
						<div id="synonymDiv" title="Synonyms">[<i>Psalliota villatica</i> (Brond.) Bres.]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../imagelib/imgdetails.php?mediaid=43107');return false;"><img src="http://images.mushroomobserver.org/1280/210023.jpg" title="" alt="Agaricus campestris image" /></a></div><div class="creator">NAMA Voucher Collection Project</div></div>					</td>
					<td class="desc">
						<div id="desctabs" class="ui-tabs" style="display:none"><ul class="ui-tabs-nav"><li><a href="resourcetab.php?tid=214862">Resources</a></li></ul>					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="img-div" style="height:300px;overflow:hidden;">

============================================================
  MyCoPortal  (SymbiotaAPI)
  Species:   Not species
  Name type: not species
============================================================
[MyCoPortal] Search endpoint returned no results for 'Not species'. Attempting autocomplete search.
[MyCoPortal] All searches failed or returned no results for 'Not species'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

============================================================
  Lichen Portal  (SymbiotaAPI)
  Species:   Xanthoria parietina
  Name type: accepted
============================================================
[Lichen Portal] 'api/v2/taxonomy' returned results for 'Xanthoria parietina'.
_fetch_query_data
{'tid': 56389, 'kingdomName': 'Fungi', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Xanthoria', 'unitInd2': None, 'unitName2': 'parietina', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(L.) Th. Fr.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'USDA PLANTS DB', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2008-09-29 12:52:57', 'parentTid': 52249, 'status': 'accepted', 'classification': [{'tid': 51657, 'scientificName': 'Fungi', 'author': 'R.T. Moore', 'rankid': 10}, {'tid': 51658, 'scientificName': 'Ascomycota', 'author': 'Caval.-Sm.', 'rankid': 30}, {'tid': 51685, 'scientificName': 'Teloschistales', 'author': 'D. Hawksw. & O.E. Erikss.', 'rankid': 100}, {'tid': 51789, 'scientificName': 'Teloschistaceae', 'author': 'Zahlbr.', 'rankid': 140}, {'tid': 52249, 'scientificName': 'Xanthoria', 'author': '(Fr.) Th. Fr.', 'rankid': 180}, {'tid': 127110, 'scientificName': 'Pezizomycotina', 'author': 'O.E. Erikss & Winka', 'rankid': 40}, {'tid': 127138, 'scientificName': 'Lecanoromycetes', 'author': 'O.E. Erikss. & Winka', 'rankid': 60}, {'tid': 127302, 'scientificName': 'Lecanoromycetidae', 'author': 'P.M. Kirk, P.F. Cannon, J.C. David & Stalpers ex Miądl., Lutzoni & Lumbsch', 'rankid': 70}, {'tid': 257522, 'scientificName': 'Teloschistineae', 'author': 'Gaya & Lutzoni', 'rankid': 110}, {'tid': 257526, 'scientificName': 'Xanthorioideae', 'author': 'Arup, Søchting & Frödén', 'rankid': 150}, {'tid': 265256, 'scientificName': 'Dikarya', 'author': 'Hibbett, T.Y. James & Vilgalys', 'rankid': 20}], 'scientificName': 'Xanthoria parietina'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Consortium of Lichen Herbaria - Xanthoria parietina</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<!-- Responsive viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

	<link href="/portal/css/symbiota/accessibility-compliant.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" disabled >
	<link href="/portal/css/symbiota/condensed.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" >

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-DSWZB4DVH3"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-DSWZB4DVH3');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="login">
						<form name="loginForm" method="post" action="/portal/profile/index.php">
							<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=56389">
							<button class="button button-secondary bottom-breathing-room-rel left-breathing-room-rel" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
			<div class="top-brand">
				<a href="https://symbiota.org">
					<div class="image-container">
											</div>
				</a>
				<div class="brand-name">
					<h1>Consortium of Lichen Herbaria</h1>
					<h2>building a Global Consortium of Bryophytes and Lichens as keystones of cryptobiotic communities</h2>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					<li>
						<a href="#">
							Search						</a>
						<ul>
							<li>
								<a href="/portal/collections/index.php">Classic Search</a>
							</li>
							<li>
								<a href="/portal/collections/search/index.php">Advanced Search</a>
							</li>
							<li>
								<a href="/portal/collections/map/mapinterface.php" target="_blank">Map Search</a>
							</li>
							<li>
								<a href="/portal/collections/exsiccati/index.php">Exsiccatae</a>
							</li>
							<li>
								<a href="/portal/checklists/dynamicmap.php?interface=checklist">Dynamic Species List</a>
							</li>
							<li>
								<a href="/portal/checklists/dynamicmap.php?interface=key">Dynamic Identification Key</a>
							</li>
							<li>
								<a href="/portal/taxa/taxonomy/taxonomydynamicdisplay.php">Taxonomic Explorer</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Media</a>
						<ul>
							<li>
								<a href="/portal/imagelib/index.php?target=genus">Media Browser</a>
							</li>
							<li>
								<a href="/portal/imagelib/search.php">Media Search</a>
							</li>
						</ul>
					</li>
										<li>
						<a href="#">Species Checklists</a>
						<ul>
							<li>
							<a href="/portal/projects/index.php">Inventory Projects</a>
							</li>
							<li>
                                <a href="#">Global Checklists</a>
								<ul>
									<li>
										<a href="/portal/projects/index.php?pid=519">North America</a>
									</li>
									<li>
										<a href="/portal/projects/index.php?pid=558">Global Checklists of Lichens & Lichenicolous Fungi</a>
									</li>
									<li>
										<a href="/portal/projects/index.php?pid=556">Global IUCN Red-Lists</a>
									</li>
								</ul>
							</li>
							<li>
                               <a href="/portal/projects/index.php?pid=512">Arctic</a>
							</li>
							<li>
                                <a href="/portal/projects/index.php?pid=519">North America</a>
 							</li>
							<li>
								<a href="/portal/projects/index.php?pid=514">Canada</a>
							</li>
							<li>
									<a href="/portal/projects/index.php?pid=555">Mexico</a>
							</li>
							<li>
								<a href="#">US States: A-L</a>
								<ul>
									<li>
										<a href="/portal/projects/index.php?pid=513">Alaska</a>
									</li>
									<li>
										<a href="/portal/projects/index.php?pid=100">Arizona</a>
									</li>
									<li>
										<a href="/portal/projects/index.php?pid=533">Arkansas</a>
									</li>
									<li>
										<a href="/portal/projects/index.php?pid=101">California</a>
									</li>
									<li>
										<a href="/portal/projects/index.php?pid=510">Colorado</a>
									</li>
                		            <li>
                                		<a href="/portal/projects/index.php?pid=509">Florida</a>
                                    </li>
		                            <li>
                		                <a href="/portal/projects/index.php?pid=530">Georgia</a>
                                	</li>
                                    <li>
		                                <a href="/portal/projects/index.php?pid=550">Hawai'i</a>
                		            </li>
                                	<li>
                                        <a href="/portal/projects/index.php?pid=540">Idaho</a>
		                            </li>
                		            <li>
                                	    <a href="/portal/projects/index.php?pid=554">Illinois</a>
                                    </li>
		                            <li>
                		                <a href="/portal/projects/index.php?pid=552">Indiana</a>
                                	</li>
                                    <li>
                                    	<a href="/portal/projects/index.php?pid=518">Iowa</a>
		                            </li>
                		            <li>
                                	    <a href="/portal/projects/index.php?pid=553">Kansas</a>
                                    </li>
                		            <li>
		                                <a href="/portal/projects/index.php?pid=534">Kentucky</a>
                                	</li>
								</ul>
							</li>
                            <li>
                               <a href="#">US States: M-N</a>
                               <ul>
		                            <li>
        		                       <a href="/portal/projects/index.php?pid=528">Maine</a>
                		           </li>
                        		    <li>
                                       <a href="/portal/projects/index.php?pid=531">Maryland</a>
                                   </li>
                                   <li>
                                       <a href="/portal/projects/index.php?pid=511">Massachusetts</a>
	                               </li>
	        	                    <li>
        	        	               <a href="/portal/projects/index.php?pid=551">Michigan</a>
                	        	   </li>
                        	       <li>
                                       <a href="/portal/projects/index.php?pid=539">Missouri</a>
                                   </li>
								   <li>
        	                	        <a href="/portal/projects/index.php?pid=546">Minnesota</a>
                	               </li>
                        	       <li>
                                       <a href="/portal/projects/index.php?pid=547">Mississippi</a>
                                   </li>
                                   <li>
	                                   <a href="/portal/projects/index.php?pid=545">Montana</a>
        	                       </li>
	                               <li>
        	                           <a href="/portal/projects/index.php?pid=529">Nebraska</a>
                	               </li>
	                        	    <li>
        	                           <a href="/portal/projects/index.php?pid=521">Nevada</a>
                	               </li>
                        	       <li>
                                       <a href="/portal/projects/index.php?pid=542">New Jersey</a>
	                               </li>
        	                       <li>
                	                   <a href="/portal/projects/index.php?pid=527">New Mexico</a>
                        	       </li>
	                               <li>
        	                           <a href="/portal/projects/index.php?pid=543">New York</a>
                	               </li>
								   <li>
										<a href="/portal/projects/index.php?pid=103">North Carolina</a>
								   </li>
        	                       <li>
                	                    <a href="/portal/projects/index.php?pid=544">North Dakota</a>
                        	       </li>
								   </li>
                               </ul>
                             </li>
                             <li>
                               <a href="#">US States: O-Z</a>
                               <ul>
							   		<li>
        	                            <a href="/portal/projects/index.php?pid=541">Ohio</a>
                	               </li>
                        	       <li>
                                		<a href="/portal/projects/index.php?pid=538">Oklahoma</a>
	                               </li>
        	                       <li>
                	                    <a href="/portal/projects/index.php?pid=525">Oregon</a>
                        	       </li>
	                               <li>
        	                            <a href="/portal/projects/index.php?pid=535">Pennsylvania</a>
                	               </li>
									<li>
        	                            <a href="/portal/projects/index.php?pid=537">South Carolina</a>
									</li>
                                    <li>
                                  		<a href="/portal/projects/index.php?pid=532">South Dakota</a>
		                            </li>
                		            <li>
                               	        <a href="/portal/projects/index.php?pid=515">Tennessee</a>
                                    </li>
		                            <li>
                		                <a href="/portal/projects/index.php?pid=526">Texas</a>
                                	</li>
                                    <li>
		                                <a href="/portal/projects/index.php?pid=524">Utah</a>
                		            </li>
                                	<li>
                                        <a href="/portal/projects/index.php?pid=523">Virginia</a>
		                            </li>
                		            <li>
                              	        <a href="/portal/projects/index.php?pid=548">Washington, D.C.</a>
                                    </li>
		                            <li>
                		                <a href="/portal/projects/index.php?pid=549">Washington</a>
                                	</li>
                                    <li>
                                  		<a href="/portal/projects/index.php?pid=536">West Virginia</a>
		                            </li>
                		            <li>
                              	        <a href="/portal/projects/index.php?pid=102">Wisconsin</a>
                                    </li>
		                            <li>
                		                <a href="/portal/projects/index.php?pid=522">Wyoming</a>
                                	</li>
								</ul>
                              </li>
                              <li>
                               <a href="/portal/projects/index.php?pid=500">US National Parks</a>
	                          </li>
							  <li>
                                <a href="/portal/projects/index.php?pid=51">Central America</a>
								<ul>
								<li>
									<a href="/portal/projects/index.php?pid=516">Panama</a>
								</li>
								</ul>
 							</li>
							 <li>
                                <a href="/portal/projects/index.php?pid=575">South America</a>
								<ul>
								<li>
									<a href="/portal/projects/index.php?pid=517">Ecuador</a>
								</li>
								</ul>
 							</li>
							 <li>
                               <a href="/portal/projects/index.php?pid=500">US National Parks</a>
	                          </li>
               	              <li>
                               <a href="/portal/projects/index.php?pid=505">Southern Subpolar Region</a>
                              </li>
						</ul>
					</li>
										<li>
						<a href="/portal/collections/specprocessor/crowdsource/index.php">Crowdsourcing</a>
					</li>
					<li>
						<a href="#">Associated Projects</a>
						<ul>
							<li>
								<a href="http://bryophyteportal.org" target="_blank">Consortium of Bryophyte Herbaria</a>
							</li>
							<li>
								<a href="https://globaltcn.utk.edu/">GLOBAL Bryophytes and Lichens Network</a>
							</li>
							<li>
								<a href="http://mycoportal.org" target="_blank">MyCoPortal</a>
							</li>
							<li>
								<a href="https://nhm2.uio.no/botanisk/lav/RLL/RLL.HTM" target="_blank">Recent Literature on Lichens</a>
							</li>
						</ul>
					</li>
					<li>
					<a href="#">More Information</a>
						<ul>
							<li>
								<a href="/portal/includes/usagepolicy.php">Data Use</a>
							</li>
							<li>
								<a href="/portal/misc/endorsements.php">Endorsements</a>
							</li>
							<li>
								<a href="/portal/collections/misc/collprofiles.php">Partners</a>
							</li>
						</ul>
					</li>
					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>
					<li>
						<a href="#">Help & Resources</a>
						<ul>
						<li>
															<a href="https://help.lichenportal.org/index.php/en/cnalh-help-resources/" target="_blank">Consortium Resources</a>
														</li>
							<li>
								<a href='/portal/glossary/index.php'>
									Glossary								</a>
							</li>
							<li>
																	<a href="https://docs.symbiota.org/docs/about/" target="_blank">Symbiota Help</a>
															</li>
						</ul>
					</li>
					<li id="lang-select-li">
						<label for="language-selection">Select Language: </label>
						<select oninput="setLanguage(this)" id="language-selection" name="language-selection">
							<option value="en">English</option>
							<option value="es" >Español</option>
							<option value="fr" >Français</option>
						</select>
					</li>
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Xanthoria parietina</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Xanthoria parietina</i></span>							<span id="author">(L.) Th. Fr.</span>
							&nbsp;<a href="index.php?tid=52249&amp;clid=0&amp;pid=&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Teloschistaceae</div>

============================================================
  Lichen Portal  (SymbiotaAPI)
  Species:   Physcia parietina
  Name type: synonym  (synonym of: Xanthoria parietina)
============================================================
[Lichen Portal] 'api/v2/taxonomy' returned results for 'Physcia parietina'.
_fetch_query_data
{'tid': 173703, 'kingdomName': 'Fungi', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Physcia', 'unitInd2': None, 'unitName2': 'parietina', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(L.) De Not.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': "Zahlbruckner's Cat. Lich. Univ. 7: 293 | Lamb's Index nom. lich.: 562", 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2013-02-02 03:36:24', 'parentTid': 52097, 'status': 'synonym', 'accepted': {'tid': 56389, 'scientificName': 'Xanthoria parietina', 'scientificNameAuthorship': '(L.) Th. Fr.', 'taxonomicSource': None, 'unacceptabilityReason': 'http://www.speciesfungorum.org/Names/SynSpecies.asp?RecordID=533795', 'taxonRemarks': None}, 'classification': [{'tid': 51657, 'scientificName': 'Fungi', 'author': 'R.T. Moore', 'rankid': 10}, {'tid': 51658, 'scientificName': 'Ascomycota', 'author': 'Caval.-Sm.', 'rankid': 30}, {'tid': 51664, 'scientificName': 'Caliciales', 'author': 'Bessey', 'rankid': 100}, {'tid': 51752, 'scientificName': 'Physciaceae', 'author': 'Zahlbr.', 'rankid': 140}, {'tid': 52097, 'scientificName': 'Physcia', 'author': '(Schreb.) Michaux', 'rankid': 180}, {'tid': 127110, 'scientificName': 'Pezizomycotina', 'author': 'O.E. Erikss & Winka', 'rankid': 40}, {'tid': 127138, 'scientificName': 'Lecanoromycetes', 'author': 'O.E. Erikss. & Winka', 'rankid': 60}, {'tid': 127302, 'scientificName': 'Lecanoromycetidae', 'author': 'P.M. Kirk, P.F. Cannon, J.C. David & Stalpers ex Miądl., Lutzoni & Lumbsch', 'rankid': 70}, {'tid': 265256, 'scientificName': 'Dikarya', 'author': 'Hibbett, T.Y. James & Vilgalys', 'rankid': 20}], 'scientificName': 'Physcia parietina'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Consortium of Lichen Herbaria - Xanthoria parietina</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<!-- Responsive viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

	<link href="/portal/css/symbiota/accessibility-compliant.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" disabled >
	<link href="/portal/css/symbiota/condensed.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" >

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-DSWZB4DVH3"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-DSWZB4DVH3');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="login">
						<form name="loginForm" method="post" action="/portal/profile/index.php">
							<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=56389">
							<button class="button button-secondary bottom-breathing-room-rel left-breathing-room-rel" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
			<div class="top-brand">
				<a href="https://symbiota.org">
					<div class="image-container">
											</div>
				</a>
				<div class="brand-name">
					<h1>Consortium of Lichen Herbaria</h1>
					<h2>building a Global Consortium of Bryophytes and Lichens as keystones of cryptobiotic communities</h2>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					<li>
						<a href="#">
							Search						</a>
						<ul>
							<li>
								<a href="/portal/collections/index.php">Classic Search</a>
							</li>
							<li>
								<a href="/portal/collections/search/index.php">Advanced Search</a>
							</li>
							<li>
								<a href="/portal/collections/map/mapinterface.php" target="_blank">Map Search</a>
							</li>
							<li>
								<a href="/portal/collections/exsiccati/index.php">Exsiccatae</a>
							</li>
							<li>
								<a href="/portal/checklists/dynamicmap.php?interface=checklist">Dynamic Species List</a>
							</li>
							<li>
								<a href="/portal/checklists/dynamicmap.php?interface=key">Dynamic Identification Key</a>
							</li>
							<li>
								<a href="/portal/taxa/taxonomy/taxonomydynamicdisplay.php">Taxonomic Explorer</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Media</a>
						<ul>
							<li>
								<a href="/portal/imagelib/index.php?target=genus">Media Browser</a>
							</li>
							<li>
								<a href="/portal/imagelib/search.php">Media Search</a>
							</li>
						</ul>
					</li>
										<li>
						<a href="#">Species Checklists</a>
						<ul>
							<li>
							<a href="/portal/projects/index.php">Inventory Projects</a>
							</li>
							<li>
                                <a href="#">Global Checklists</a>
								<ul>
									<li>
										<a href="/portal/projects/index.php?pid=519">North America</a>
									</li>
									<li>
										<a href="/portal/projects/index.php?pid=558">Global Checklists of Lichens & Lichenicolous Fungi</a>
									</li>
									<li>
										<a href="/portal/projects/index.php?pid=556">Global IUCN Red-Lists</a>
									</li>
								</ul>
							</li>
							<li>
                               <a href="/portal/projects/index.php?pid=512">Arctic</a>
							</li>
							<li>
                                <a href="/portal/projects/index.php?pid=519">North America</a>
 							</li>
							<li>
								<a href="/portal/projects/index.php?pid=514">Canada</a>
							</li>
							<li>
									<a href="/portal/projects/index.php?pid=555">Mexico</a>
							</li>
							<li>
								<a href="#">US States: A-L</a>
								<ul>
									<li>
										<a href="/portal/projects/index.php?pid=513">Alaska</a>
									</li>
									<li>
										<a href="/portal/projects/index.php?pid=100">Arizona</a>
									</li>
									<li>
										<a href="/portal/projects/index.php?pid=533">Arkansas</a>
									</li>
									<li>
										<a href="/portal/projects/index.php?pid=101">California</a>
									</li>
									<li>
										<a href="/portal/projects/index.php?pid=510">Colorado</a>
									</li>
                		            <li>
                                		<a href="/portal/projects/index.php?pid=509">Florida</a>
                                    </li>
		                            <li>
                		                <a href="/portal/projects/index.php?pid=530">Georgia</a>
                                	</li>
                                    <li>
		                                <a href="/portal/projects/index.php?pid=550">Hawai'i</a>
                		            </li>
                                	<li>
                                        <a href="/portal/projects/index.php?pid=540">Idaho</a>
		                            </li>
                		            <li>
                                	    <a href="/portal/projects/index.php?pid=554">Illinois</a>
                                    </li>
		                            <li>
                		                <a href="/portal/projects/index.php?pid=552">Indiana</a>
                                	</li>
                                    <li>
                                    	<a href="/portal/projects/index.php?pid=518">Iowa</a>
		                            </li>
                		            <li>
                                	    <a href="/portal/projects/index.php?pid=553">Kansas</a>
                                    </li>
                		            <li>
		                                <a href="/portal/projects/index.php?pid=534">Kentucky</a>
                                	</li>
								</ul>
							</li>
                            <li>
                               <a href="#">US States: M-N</a>
                               <ul>
		                            <li>
        		                       <a href="/portal/projects/index.php?pid=528">Maine</a>
                		           </li>
                        		    <li>
                                       <a href="/portal/projects/index.php?pid=531">Maryland</a>
                                   </li>
                                   <li>
                                       <a href="/portal/projects/index.php?pid=511">Massachusetts</a>
	                               </li>
	        	                    <li>
        	        	               <a href="/portal/projects/index.php?pid=551">Michigan</a>
                	        	   </li>
                        	       <li>
                                       <a href="/portal/projects/index.php?pid=539">Missouri</a>
                                   </li>
								   <li>
        	                	        <a href="/portal/projects/index.php?pid=546">Minnesota</a>
                	               </li>
                        	       <li>
                                       <a href="/portal/projects/index.php?pid=547">Mississippi</a>
                                   </li>
                                   <li>
	                                   <a href="/portal/projects/index.php?pid=545">Montana</a>
        	                       </li>
	                               <li>
        	                           <a href="/portal/projects/index.php?pid=529">Nebraska</a>
                	               </li>
	                        	    <li>
        	                           <a href="/portal/projects/index.php?pid=521">Nevada</a>
                	               </li>
                        	       <li>
                                       <a href="/portal/projects/index.php?pid=542">New Jersey</a>
	                               </li>
        	                       <li>
                	                   <a href="/portal/projects/index.php?pid=527">New Mexico</a>
                        	       </li>
	                               <li>
        	                           <a href="/portal/projects/index.php?pid=543">New York</a>
                	               </li>
								   <li>
										<a href="/portal/projects/index.php?pid=103">North Carolina</a>
								   </li>
        	                       <li>
                	                    <a href="/portal/projects/index.php?pid=544">North Dakota</a>
                        	       </li>
								   </li>
                               </ul>
                             </li>
                             <li>
                               <a href="#">US States: O-Z</a>
                               <ul>
							   		<li>
        	                            <a href="/portal/projects/index.php?pid=541">Ohio</a>
                	               </li>
                        	       <li>
                                		<a href="/portal/projects/index.php?pid=538">Oklahoma</a>
	                               </li>
        	                       <li>
                	                    <a href="/portal/projects/index.php?pid=525">Oregon</a>
                        	       </li>
	                               <li>
        	                            <a href="/portal/projects/index.php?pid=535">Pennsylvania</a>
                	               </li>
									<li>
        	                            <a href="/portal/projects/index.php?pid=537">South Carolina</a>
									</li>
                                    <li>
                                  		<a href="/portal/projects/index.php?pid=532">South Dakota</a>
		                            </li>
                		            <li>
                               	        <a href="/portal/projects/index.php?pid=515">Tennessee</a>
                                    </li>
		                            <li>
                		                <a href="/portal/projects/index.php?pid=526">Texas</a>
                                	</li>
                                    <li>
		                                <a href="/portal/projects/index.php?pid=524">Utah</a>
                		            </li>
                                	<li>
                                        <a href="/portal/projects/index.php?pid=523">Virginia</a>
		                            </li>
                		            <li>
                              	        <a href="/portal/projects/index.php?pid=548">Washington, D.C.</a>
                                    </li>
		                            <li>
                		                <a href="/portal/projects/index.php?pid=549">Washington</a>
                                	</li>
                                    <li>
                                  		<a href="/portal/projects/index.php?pid=536">West Virginia</a>
		                            </li>
                		            <li>
                              	        <a href="/portal/projects/index.php?pid=102">Wisconsin</a>
                                    </li>
		                            <li>
                		                <a href="/portal/projects/index.php?pid=522">Wyoming</a>
                                	</li>
								</ul>
                              </li>
                              <li>
                               <a href="/portal/projects/index.php?pid=500">US National Parks</a>
	                          </li>
							  <li>
                                <a href="/portal/projects/index.php?pid=51">Central America</a>
								<ul>
								<li>
									<a href="/portal/projects/index.php?pid=516">Panama</a>
								</li>
								</ul>
 							</li>
							 <li>
                                <a href="/portal/projects/index.php?pid=575">South America</a>
								<ul>
								<li>
									<a href="/portal/projects/index.php?pid=517">Ecuador</a>
								</li>
								</ul>
 							</li>
							 <li>
                               <a href="/portal/projects/index.php?pid=500">US National Parks</a>
	                          </li>
               	              <li>
                               <a href="/portal/projects/index.php?pid=505">Southern Subpolar Region</a>
                              </li>
						</ul>
					</li>
										<li>
						<a href="/portal/collections/specprocessor/crowdsource/index.php">Crowdsourcing</a>
					</li>
					<li>
						<a href="#">Associated Projects</a>
						<ul>
							<li>
								<a href="http://bryophyteportal.org" target="_blank">Consortium of Bryophyte Herbaria</a>
							</li>
							<li>
								<a href="https://globaltcn.utk.edu/">GLOBAL Bryophytes and Lichens Network</a>
							</li>
							<li>
								<a href="http://mycoportal.org" target="_blank">MyCoPortal</a>
							</li>
							<li>
								<a href="https://nhm2.uio.no/botanisk/lav/RLL/RLL.HTM" target="_blank">Recent Literature on Lichens</a>
							</li>
						</ul>
					</li>
					<li>
					<a href="#">More Information</a>
						<ul>
							<li>
								<a href="/portal/includes/usagepolicy.php">Data Use</a>
							</li>
							<li>
								<a href="/portal/misc/endorsements.php">Endorsements</a>
							</li>
							<li>
								<a href="/portal/collections/misc/collprofiles.php">Partners</a>
							</li>
						</ul>
					</li>
					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>
					<li>
						<a href="#">Help & Resources</a>
						<ul>
						<li>
															<a href="https://help.lichenportal.org/index.php/en/cnalh-help-resources/" target="_blank">Consortium Resources</a>
														</li>
							<li>
								<a href='/portal/glossary/index.php'>
									Glossary								</a>
							</li>
							<li>
																	<a href="https://docs.symbiota.org/docs/about/" target="_blank">Symbiota Help</a>
															</li>
						</ul>
					</li>
					<li id="lang-select-li">
						<label for="language-selection">Select Language: </label>
						<select oninput="setLanguage(this)" id="language-selection" name="language-selection">
							<option value="en">English</option>
							<option value="es" >Español</option>
							<option value="fr" >Français</option>
						</select>
					</li>
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Xanthoria parietina</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Xanthoria parietina</i></span>							<span id="author">(L.) Th. Fr.</span>
							&nbsp;<a href="index.php?tid=52249&amp;clid=0&amp;pid=&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Teloschistaceae</div>

============================================================
  Lichen Portal  (SymbiotaAPI)
  Species:   Not species
  Name type: not species
============================================================
[Lichen Portal] Search endpoint returned no results for 'Not species'. Attempting autocomplete search.
[Lichen Portal] All searches failed or returned no results for 'Not species'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

============================================================
  Bryophyte Portal  (SymbiotaAPI)
  Species:   Pohlia nutans
  Name type: accepted
============================================================
[Bryophyte Portal] 'api/v2/taxonomy' returned results for 'Pohlia nutans'.
_fetch_query_data
{'tid': 160406, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Pohlia', 'unitInd2': None, 'unitName2': 'nutans', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(Hedw.) Lindb.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'tropicos;usda', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2010-09-21 05:27:39', 'parentTid': 157098, 'status': 'accepted', 'classification': [{'tid': 5571, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 16600, 'scientificName': 'Bryophyta', 'author': 'Schimp.', 'rankid': 30}, {'tid': 16698, 'scientificName': 'Bryopsida', 'author': 'McClatchie', 'rankid': 60}, {'tid': 16814, 'scientificName': 'Bryidae', 'author': 'Engl.', 'rankid': 70}, {'tid': 16841, 'scientificName': 'Bryales', 'author': 'Limpr.', 'rankid': 100}, {'tid': 16965, 'scientificName': 'Mniaceae', 'author': 'Schwägr.', 'rankid': 140}, {'tid': 157098, 'scientificName': 'Pohlia', 'author': 'Hedw.', 'rankid': 180}, {'tid': 254632, 'scientificName': 'Bryobiotina', 'author': '', 'rankid': 20}, {'tid': 254644, 'scientificName': 'Bryanae', 'author': 'Goffinet & W.R. Buck', 'rankid': 90}], 'scientificName': 'Pohlia nutans'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Bryophyte Portal - Pohlia nutans</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<!-- Responsive viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

	<link href="/portal/css/symbiota/accessibility-compliant.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" disabled >
	<link href="/portal/css/symbiota/condensed.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" >

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-C2W7NKLDE2"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-C2W7NKLDE2');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="login">
						<form name="loginForm" method="post" action="/portal/profile/index.php">
							<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=160406">
							<button class="button button-secondary bottom-breathing-room-rel left-breathing-room-rel" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
			<div class="top-brand">
				<div class="brand-name">
					<h1>Consortium of Bryophyte Herbaria</h1>
					<h2>building a Consortium of Bryophytes and Lichens as keystones of cryptobiotic communities</h2>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					<li>
						<a href="#">
							Search						</a>
						<ul>
							<li>
								<a href="/portal/collections/search/index.php">Search Collections</a>
							</li>
							<li>
								<a href="/portal/collections/index.php">Classic Search</a>
							</li>
							<li>
								<a href="/portal/collections/map/index.php" target="_blank">Map Search</a>
							</li>
							<li>
								<a href="/portal/collections/exsiccati/index.php" >Exsiccatae</a>
							</li>
							<li>
								<a href="/portal/checklists/dynamicmap.php?interface=checklist" >Dynamic Species List</a>
							</li>
							<li>
								<a href="/portal/checklists/dynamicmap.php?interface=key" >Identification Keys</a>
							</li>
							<li>
								<a href="/portal/taxa/taxonomy/taxonomydynamicdisplay.php" >Taxonomic Explorer</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#" >Images</a>
						<ul>
							<li>
								<a href="/portal/imagelib/index.php" >Media Browser</a>
							</li>
							<li>
								<a href="/portal/imagelib/search.php" >Media</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/portal/projects/index.php?" >Species Checklists</a>
						<ul>
   							<li>
								<a href="/portal/projects/index.php?proj=24">North America</a>
							</li>
							<li>
								<a href="#">United States></a>
								<ul>
									  <li>
									  <a href="/portal/projects/index.php?proj=23">Arizona</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=15">California</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=4">Illinois</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=13">Iowa</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=8">Maine</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=3">Missouri</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=18">Montana</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=22">New Mexico</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=21">New York</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=1">North Carolina</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=20">Ohio</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=6">Pennsylvania</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=19">Washington</a>
									  </li>
								  <li>
									  <a href="/portal/projects/index.php?proj=27">Wyoming</a>
									  </li>
								</ul>
							</li>
							<li>
								<a href="#">Beyond North America></a>
								<ul>
									  <li>
									  <a href="/portal/projects/index.php?proj=9">Chile</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=11">Falkland Islands</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=5">Fiji</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=10">Guatemala</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=16">Indonesia</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=17">Malaysia</a>
									  </li>
								</ul>
							</li>
							<li>
								<a href="#">Species Groups></a>
								<ul>
									<li>
										<a href="/portal/projects/index.php?proj=2">Frullania</a>
									</li>
									<li>
										<a href="/portal/projects/index.php?proj=28">Plagiochila</a>
									</li>
									<li>
										<a href="/portal/projects/index.php?proj=25">Sphagnum</a>
									</li>
								</ul>
							</li>
							<li>
								<a href="/portal/projects/index.php?proj=12">US National Parks</a>
							</li>
							<!--
							<li>
								<a href="/portal/projects/index.php?proj=26">Teaching Checklists</a>
							</li>
							-->
						</ul>
					</li>
					<li>
						<a href="/portal/collections/specprocessor/crowdsource/index.php">Crowdsourcing</a>
					</li>
					<li>
						<a href="#" >Associated Projects</a>
						<ul>
							<li>
								<a href="https://lichenportal.org/portal/">Consortium of Lichen Herbaria</a>
							</li>
							<!--
							<li>
								<a href="https://bryophyteportal.org/frullania/">Frullania Portal (CNABH)</a>
							</li>
							-->
							<li>
								<a href="https://globaltcn.utk.edu/">GLOBAL Bryophytes and Lichens Network</a>
							</li>
							<li>
								<a href="https://mycoportal.org/portal/">MyCoPortal</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#" >More Information</a>
						<ul>
							<li>
								<a href="/portal/includes/usagepolicy.php">Data Use</a>
							</li>
							<li>
								<a href="/portal/collections/misc/collprofiles.php">Partners</a>
							</li>
							<li>
								<a href="/portal/misc/endorsements.php">Endorsements</a>
							</li>

						</ul>
					</li>
					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>
					<li id="lang-select-li">
						<label for="language-selection">Select Language: </label>
						<select oninput="setLanguage(this)" id="language-selection" name="language-selection">
							<option value="en">English</option>
							<option value="es" >Español</option>
							<option value="fr" >Français</option>
						</select>
					</li>
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div><div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Pohlia nutans</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Pohlia nutans</i></span>							<span id="author">(Hedw.) Lindb.</span>
							&nbsp;<a href="index.php?tid=157098&amp;clid=0&amp;pid=&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Mniaceae</div>
													<div id="vernacularDiv">
								bryum moss, <span class="verns"><a href="#" onclick="toggle('verns')" title="Click here to show more common names">more...</a></span><span class="verns" onclick="toggle('verns');" style="display:none;">pohlia moss</span>							</div>
							<div id="synonymDiv" title="Synonyms">[<i>Bryum afronutans</i> Müll. Hal., <span class="synSpan"><a href="#" onclick="toggle('synSpan')" title="Click here to show more synonyms">more</a></span><span class="synSpan" onclick="toggle('synSpan')" style="display:none"><i>Bryum austronutans</i> Müll. Hal., <i>Bryum basalticum</i> Warnst. & Geh., <i>Bryum bealeyense</i> (Huebener) Delogne, <i>Bryum beccarii</i> Müll. Hal., <i>Bryum caespitosum</i> (Hoppe & Hornsch.) Brid., <i>Bryum canaliculatum</i> (Müll. Hal. & Kindb.) Müll. Hal., <i>Bryum claviforme</i> Hampe, <i>Bryum compactum</i> Dicks., <i>Bryum cucullatiforme</i> Kindb., <i>Bryum ecklonianum</i> Müll. Hal., <i>Bryum gelidum</i> I. Hagen, <i>Bryum gypsophilum</i> Wallr., <i>Bryum humidulum</i> Sull. & Lesq., <i>Bryum interruptum</i> Dicks., <i>Bryum laxum</i> Reichardt, <i>Bryum leptopelmatum</i> Müll. Hal., <i>Bryum montanum</i> Müll. Hal., <i>Bryum nigricans</i> Dicks., <i>Bryum nutans</i> (Hedw.) Turner, <i>Bryum nutans subsp. canaliculatum</i> (Müll. Hal. & Kindb.) Kindb., <i>Bryum nutans subsp. schimperi</i> (Müll. Hal.) Kindb., <i>Bryum nutans var. bicolor</i> Bruch & Schimp., <i>Bryum nutans var. caespitosum</i> (Hoppe & Hornsch.) Bruch & Schimp., <i>Bryum nutans var. longisetum</i> (Brid.) Bruch & Schimp., <i>Bryum nutans var. strangulatum</i> (Nees) Rabenh., <i>Bryum nutans var. subdenticulatum</i> (Brid.) Bruch & Schimp., <i>Bryum pertenellum</i> Bryhn & Ryan, <i>Bryum rutilans</i> Brid., <i>Bryum schimperi</i> Müll. Hal., <i>Bryum sphagnadelphus</i> Müll. Hal., <i>Bryum subdenticulatum</i> Brid., <i>Bryum torlessense</i> R. Br. bis, <i>Bryum umbrosum</i> Wallr., <i>Hypnum nutans</i> (Hedw.) F. Weber & D. Mohr, <i>Lamprophyllum nutans</i> (Hedw.) Lindb., <i>Mniobryum compactum</i> (Dicks.) Baehni, <i>Mnium compactum</i> (Dicks.) P. Beauv., <i>Mnium nigricans</i> (Dicks.) Brid., <i>Pohlia beccarii</i> (Müll. Hal.) Watts & Whitel., <i>Pohlia caespitosa</i> (Hoppe & Hornsch.) Lazarenko, <i>Pohlia claviformis</i> (Hampe) Broth., <i>Pohlia elatior</i> (Dixon & Sainsbury) Sainsbury, <i>Pohlia leptopelmata</i> (Müll. Hal.) Watts & Whitel., <i>Pohlia longifolia</i> (A. Jaeger) Watts & Whitel., <i>Pohlia montana</i> (Müll. Hal.) Watts & Whitel., <i>Pohlia nutans f. basaltica</i> (Warnst. & Geh.) Podp., <i>Pohlia nutans f. bicolor</i> (Hoppe & Hornsch.) Podp., <i>Pohlia nutans f. caespitosa</i> (Hoppe & Hornsch.) Podp., <i>Pohlia nutans f. strangulata</i> (Nees) Kopsch, <i>Pohlia nutans f. subdenticulata</i> (Brid.) Podp., <i>Pohlia nutans subsp. rutilans</i> Lindb., <i>Pohlia nutans subsp. schimperi</i> (C. Müll.) Nyh., <i>Pohlia nutans var. bicolor</i> (Hoppe & Hornsch.) Hult, <i>Pohlia nutans var. caespitosa</i> (Hoppe & Hornsch.) Podp., <i>Pohlia nutans var. gypsophila</i> (Wallr.) Wijk & Margad., <i>Pohlia nutans var. longiseta</i> (Brid.) Delogne, <i>Pohlia nutans var. rutilans</i> C.E.O. Jensen, <i>Pohlia nutans var. strangulata</i> (Nees) Delogne, <i>Pohlia nutans var. subdenticulata</i> (Brid.) Delogne, <i>Pohlia polygama</i> Kindb., <i>Pohlia pulvinata</i> (Kindb.) Broth., <i>Pohlia racovitzae</i> (Cardot) Broth., <i>Pohlia rutilans</i> (Schimp.) Lindb., <i>Pohlia schimperi</i> (C. Müll.) Andrews in Grout, <i>Pohlia suzukii</i> Ochi, <i>Pohlia tomentosocaespitosa</i> Ochi, <i>Pohlia yanoi</i> Ochi, <i>Pseudopohlia merrillii</i> Broth., <i>Webera afronutans</i> (Müll. Hal.) Paris, <i>Webera austronutans</i> (Müll. Hal.) Kindb., <i>Webera beccarii</i> (Müll. Hal.) Paris, <i>Webera bicolor</i> Hoppe & Hornsch., <i>Webera caespitosa</i> Hoppe & Hornsch., <i>Webera canaliculata</i> Müll. Hal. & Kindb., <i>Webera claviformis</i> (Hampe) A. Jaeger, <i>Webera cucullatiformis</i> (Kindb.) Paris, <i>Webera duriuscula</i> Broth., <i>Webera eckloniana</i> (Müll. Hal.) A. Jaeger, <i>Webera elatior</i> Dixon & Sainsbury, <i>Webera longifolia</i> A. Jaeger, <i>Webera longiseta</i> Brid., <i>Webera montana</i> (Müll. Hal.) Paris, <i>Webera nigricans</i> (Dicks.) Buse, <i>Webera nutans</i> Hedw., <i>Webera nutans subsp. schimperi</i> (Müll. Hal.) J.J. Amann, <i>Webera nutans var. bicolor</i> (Hoppe & Hornsch.) Fürnr., <i>Webera nutans var. caespitosa</i> Fürnr., <i>Webera nutans var. gypsophila</i> (Wallr.) Huebener, <i>Webera nutans var. longiseta</i> Huebener, <i>Webera nutans var. strangulata</i> (Nees) Schimp., <i>Webera nutans var. subdenticulata</i> (Brid.) Huebener, <i>Webera pendula</i> Hornsch., <i>Webera polygama</i> (Kindb.) Broth., <i>Webera pulvinata</i> Kindb., <i>Webera racovitzae</i> Cardot, <i>Webera rutilans</i> Schimp., <i>Webera schimperi</i> (Müll. Hal.) Schimp., <i>Webera sphagnadelphus</i> (Müll. Hal.) Besch., <i>Webera strangulata</i> Nees, <i>Webera subdenticulata</i> (Brid.) Brid.</span>]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../imagelib/imgdetails.php?mediaid=998');return false;"><img src="http://www.biopix.com/photos/jcs-pohlia-nutans-24349.jpg" title="" alt="Pohlia nutans image" /></a></div><div class="creator">Biopix: JC Schou</div></div>					</td>
					<td class="desc">

============================================================
  Bryophyte Portal  (SymbiotaAPI)
  Species:   Webera nutans
  Name type: synonym  (synonym of: Pohlia nutans)
============================================================
[Bryophyte Portal] 'api/v2/taxonomy' returned results for 'Webera nutans'.
_fetch_query_data
{'tid': 237892, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Webera', 'unitInd2': None, 'unitName2': 'nutans', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'Hedw.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'tropicos', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2012-12-29 07:59:05', 'parentTid': 220599, 'status': 'synonym', 'accepted': {'tid': 160406, 'scientificName': 'Pohlia nutans', 'scientificNameAuthorship': '(Hedw.) Lindb.', 'taxonomicSource': None, 'unacceptabilityReason': None, 'taxonRemarks': None}, 'classification': [{'tid': 5571, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 16600, 'scientificName': 'Bryophyta', 'author': 'Schimp.', 'rankid': 30}, {'tid': 16698, 'scientificName': 'Bryopsida', 'author': 'McClatchie', 'rankid': 60}, {'tid': 16814, 'scientificName': 'Bryidae', 'author': 'Engl.', 'rankid': 70}, {'tid': 16841, 'scientificName': 'Bryales', 'author': 'Limpr.', 'rankid': 100}, {'tid': 16965, 'scientificName': 'Mniaceae', 'author': 'Schwägr.', 'rankid': 140}, {'tid': 220599, 'scientificName': 'Webera', 'author': 'Hedw.', 'rankid': 180}, {'tid': 254632, 'scientificName': 'Bryobiotina', 'author': '', 'rankid': 20}, {'tid': 254644, 'scientificName': 'Bryanae', 'author': 'Goffinet & W.R. Buck', 'rankid': 90}], 'scientificName': 'Webera nutans'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Bryophyte Portal - Pohlia nutans</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<!-- Responsive viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

	<link href="/portal/css/symbiota/accessibility-compliant.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" disabled >
	<link href="/portal/css/symbiota/condensed.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" >

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-C2W7NKLDE2"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-C2W7NKLDE2');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="login">
						<form name="loginForm" method="post" action="/portal/profile/index.php">
							<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=160406">
							<button class="button button-secondary bottom-breathing-room-rel left-breathing-room-rel" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
			<div class="top-brand">
				<div class="brand-name">
					<h1>Consortium of Bryophyte Herbaria</h1>
					<h2>building a Consortium of Bryophytes and Lichens as keystones of cryptobiotic communities</h2>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					<li>
						<a href="#">
							Search						</a>
						<ul>
							<li>
								<a href="/portal/collections/search/index.php">Search Collections</a>
							</li>
							<li>
								<a href="/portal/collections/index.php">Classic Search</a>
							</li>
							<li>
								<a href="/portal/collections/map/index.php" target="_blank">Map Search</a>
							</li>
							<li>
								<a href="/portal/collections/exsiccati/index.php" >Exsiccatae</a>
							</li>
							<li>
								<a href="/portal/checklists/dynamicmap.php?interface=checklist" >Dynamic Species List</a>
							</li>
							<li>
								<a href="/portal/checklists/dynamicmap.php?interface=key" >Identification Keys</a>
							</li>
							<li>
								<a href="/portal/taxa/taxonomy/taxonomydynamicdisplay.php" >Taxonomic Explorer</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#" >Images</a>
						<ul>
							<li>
								<a href="/portal/imagelib/index.php" >Media Browser</a>
							</li>
							<li>
								<a href="/portal/imagelib/search.php" >Media</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/portal/projects/index.php?" >Species Checklists</a>
						<ul>
   							<li>
								<a href="/portal/projects/index.php?proj=24">North America</a>
							</li>
							<li>
								<a href="#">United States></a>
								<ul>
									  <li>
									  <a href="/portal/projects/index.php?proj=23">Arizona</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=15">California</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=4">Illinois</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=13">Iowa</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=8">Maine</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=3">Missouri</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=18">Montana</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=22">New Mexico</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=21">New York</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=1">North Carolina</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=20">Ohio</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=6">Pennsylvania</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=19">Washington</a>
									  </li>
								  <li>
									  <a href="/portal/projects/index.php?proj=27">Wyoming</a>
									  </li>
								</ul>
							</li>
							<li>
								<a href="#">Beyond North America></a>
								<ul>
									  <li>
									  <a href="/portal/projects/index.php?proj=9">Chile</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=11">Falkland Islands</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=5">Fiji</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=10">Guatemala</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=16">Indonesia</a>
									  </li>
									  <li>
									  <a href="/portal/projects/index.php?proj=17">Malaysia</a>
									  </li>
								</ul>
							</li>
							<li>
								<a href="#">Species Groups></a>
								<ul>
									<li>
										<a href="/portal/projects/index.php?proj=2">Frullania</a>
									</li>
									<li>
										<a href="/portal/projects/index.php?proj=28">Plagiochila</a>
									</li>
									<li>
										<a href="/portal/projects/index.php?proj=25">Sphagnum</a>
									</li>
								</ul>
							</li>
							<li>
								<a href="/portal/projects/index.php?proj=12">US National Parks</a>
							</li>
							<!--
							<li>
								<a href="/portal/projects/index.php?proj=26">Teaching Checklists</a>
							</li>
							-->
						</ul>
					</li>
					<li>
						<a href="/portal/collections/specprocessor/crowdsource/index.php">Crowdsourcing</a>
					</li>
					<li>
						<a href="#" >Associated Projects</a>
						<ul>
							<li>
								<a href="https://lichenportal.org/portal/">Consortium of Lichen Herbaria</a>
							</li>
							<!--
							<li>
								<a href="https://bryophyteportal.org/frullania/">Frullania Portal (CNABH)</a>
							</li>
							-->
							<li>
								<a href="https://globaltcn.utk.edu/">GLOBAL Bryophytes and Lichens Network</a>
							</li>
							<li>
								<a href="https://mycoportal.org/portal/">MyCoPortal</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#" >More Information</a>
						<ul>
							<li>
								<a href="/portal/includes/usagepolicy.php">Data Use</a>
							</li>
							<li>
								<a href="/portal/collections/misc/collprofiles.php">Partners</a>
							</li>
							<li>
								<a href="/portal/misc/endorsements.php">Endorsements</a>
							</li>

						</ul>
					</li>
					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>
					<li id="lang-select-li">
						<label for="language-selection">Select Language: </label>
						<select oninput="setLanguage(this)" id="language-selection" name="language-selection">
							<option value="en">English</option>
							<option value="es" >Español</option>
							<option value="fr" >Français</option>
						</select>
					</li>
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div><div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Pohlia nutans</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Pohlia nutans</i></span>							<span id="author">(Hedw.) Lindb.</span>
							&nbsp;<a href="index.php?tid=157098&amp;clid=0&amp;pid=&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Mniaceae</div>
													<div id="vernacularDiv">
								bryum moss, <span class="verns"><a href="#" onclick="toggle('verns')" title="Click here to show more common names">more...</a></span><span class="verns" onclick="toggle('verns');" style="display:none;">pohlia moss</span>							</div>
							<div id="synonymDiv" title="Synonyms">[<i>Bryum afronutans</i> Müll. Hal., <span class="synSpan"><a href="#" onclick="toggle('synSpan')" title="Click here to show more synonyms">more</a></span><span class="synSpan" onclick="toggle('synSpan')" style="display:none"><i>Bryum austronutans</i> Müll. Hal., <i>Bryum basalticum</i> Warnst. & Geh., <i>Bryum bealeyense</i> (Huebener) Delogne, <i>Bryum beccarii</i> Müll. Hal., <i>Bryum caespitosum</i> (Hoppe & Hornsch.) Brid., <i>Bryum canaliculatum</i> (Müll. Hal. & Kindb.) Müll. Hal., <i>Bryum claviforme</i> Hampe, <i>Bryum compactum</i> Dicks., <i>Bryum cucullatiforme</i> Kindb., <i>Bryum ecklonianum</i> Müll. Hal., <i>Bryum gelidum</i> I. Hagen, <i>Bryum gypsophilum</i> Wallr., <i>Bryum humidulum</i> Sull. & Lesq., <i>Bryum interruptum</i> Dicks., <i>Bryum laxum</i> Reichardt, <i>Bryum leptopelmatum</i> Müll. Hal., <i>Bryum montanum</i> Müll. Hal., <i>Bryum nigricans</i> Dicks., <i>Bryum nutans</i> (Hedw.) Turner, <i>Bryum nutans subsp. canaliculatum</i> (Müll. Hal. & Kindb.) Kindb., <i>Bryum nutans subsp. schimperi</i> (Müll. Hal.) Kindb., <i>Bryum nutans var. bicolor</i> Bruch & Schimp., <i>Bryum nutans var. caespitosum</i> (Hoppe & Hornsch.) Bruch & Schimp., <i>Bryum nutans var. longisetum</i> (Brid.) Bruch & Schimp., <i>Bryum nutans var. strangulatum</i> (Nees) Rabenh., <i>Bryum nutans var. subdenticulatum</i> (Brid.) Bruch & Schimp., <i>Bryum pertenellum</i> Bryhn & Ryan, <i>Bryum rutilans</i> Brid., <i>Bryum schimperi</i> Müll. Hal., <i>Bryum sphagnadelphus</i> Müll. Hal., <i>Bryum subdenticulatum</i> Brid., <i>Bryum torlessense</i> R. Br. bis, <i>Bryum umbrosum</i> Wallr., <i>Hypnum nutans</i> (Hedw.) F. Weber & D. Mohr, <i>Lamprophyllum nutans</i> (Hedw.) Lindb., <i>Mniobryum compactum</i> (Dicks.) Baehni, <i>Mnium compactum</i> (Dicks.) P. Beauv., <i>Mnium nigricans</i> (Dicks.) Brid., <i>Pohlia beccarii</i> (Müll. Hal.) Watts & Whitel., <i>Pohlia caespitosa</i> (Hoppe & Hornsch.) Lazarenko, <i>Pohlia claviformis</i> (Hampe) Broth., <i>Pohlia elatior</i> (Dixon & Sainsbury) Sainsbury, <i>Pohlia leptopelmata</i> (Müll. Hal.) Watts & Whitel., <i>Pohlia longifolia</i> (A. Jaeger) Watts & Whitel., <i>Pohlia montana</i> (Müll. Hal.) Watts & Whitel., <i>Pohlia nutans f. basaltica</i> (Warnst. & Geh.) Podp., <i>Pohlia nutans f. bicolor</i> (Hoppe & Hornsch.) Podp., <i>Pohlia nutans f. caespitosa</i> (Hoppe & Hornsch.) Podp., <i>Pohlia nutans f. strangulata</i> (Nees) Kopsch, <i>Pohlia nutans f. subdenticulata</i> (Brid.) Podp., <i>Pohlia nutans subsp. rutilans</i> Lindb., <i>Pohlia nutans subsp. schimperi</i> (C. Müll.) Nyh., <i>Pohlia nutans var. bicolor</i> (Hoppe & Hornsch.) Hult, <i>Pohlia nutans var. caespitosa</i> (Hoppe & Hornsch.) Podp., <i>Pohlia nutans var. gypsophila</i> (Wallr.) Wijk & Margad., <i>Pohlia nutans var. longiseta</i> (Brid.) Delogne, <i>Pohlia nutans var. rutilans</i> C.E.O. Jensen, <i>Pohlia nutans var. strangulata</i> (Nees) Delogne, <i>Pohlia nutans var. subdenticulata</i> (Brid.) Delogne, <i>Pohlia polygama</i> Kindb., <i>Pohlia pulvinata</i> (Kindb.) Broth., <i>Pohlia racovitzae</i> (Cardot) Broth., <i>Pohlia rutilans</i> (Schimp.) Lindb., <i>Pohlia schimperi</i> (C. Müll.) Andrews in Grout, <i>Pohlia suzukii</i> Ochi, <i>Pohlia tomentosocaespitosa</i> Ochi, <i>Pohlia yanoi</i> Ochi, <i>Pseudopohlia merrillii</i> Broth., <i>Webera afronutans</i> (Müll. Hal.) Paris, <i>Webera austronutans</i> (Müll. Hal.) Kindb., <i>Webera beccarii</i> (Müll. Hal.) Paris, <i>Webera bicolor</i> Hoppe & Hornsch., <i>Webera caespitosa</i> Hoppe & Hornsch., <i>Webera canaliculata</i> Müll. Hal. & Kindb., <i>Webera claviformis</i> (Hampe) A. Jaeger, <i>Webera cucullatiformis</i> (Kindb.) Paris, <i>Webera duriuscula</i> Broth., <i>Webera eckloniana</i> (Müll. Hal.) A. Jaeger, <i>Webera elatior</i> Dixon & Sainsbury, <i>Webera longifolia</i> A. Jaeger, <i>Webera longiseta</i> Brid., <i>Webera montana</i> (Müll. Hal.) Paris, <i>Webera nigricans</i> (Dicks.) Buse, <i>Webera nutans</i> Hedw., <i>Webera nutans subsp. schimperi</i> (Müll. Hal.) J.J. Amann, <i>Webera nutans var. bicolor</i> (Hoppe & Hornsch.) Fürnr., <i>Webera nutans var. caespitosa</i> Fürnr., <i>Webera nutans var. gypsophila</i> (Wallr.) Huebener, <i>Webera nutans var. longiseta</i> Huebener, <i>Webera nutans var. strangulata</i> (Nees) Schimp., <i>Webera nutans var. subdenticulata</i> (Brid.) Huebener, <i>Webera pendula</i> Hornsch., <i>Webera polygama</i> (Kindb.) Broth., <i>Webera pulvinata</i> Kindb., <i>Webera racovitzae</i> Cardot, <i>Webera rutilans</i> Schimp., <i>Webera schimperi</i> (Müll. Hal.) Schimp., <i>Webera sphagnadelphus</i> (Müll. Hal.) Besch., <i>Webera strangulata</i> Nees, <i>Webera subdenticulata</i> (Brid.) Brid.</span>]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../imagelib/imgdetails.php?mediaid=998');return false;"><img src="http://www.biopix.com/photos/jcs-pohlia-nutans-24349.jpg" title="" alt="Pohlia nutans image" /></a></div><div class="creator">Biopix: JC Schou</div></div>					</td>
					<td class="desc">

============================================================
  Bryophyte Portal  (SymbiotaAPI)
  Species:   Not species
  Name type: not species
============================================================
[Bryophyte Portal] Search endpoint returned no results for 'Not species'. Attempting autocomplete search.
[Bryophyte Portal] All searches failed or returned no results for 'Not species'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

============================================================
  CCH2  (SymbiotaAPI)
  Species:   Heteromeles arbutifolia
  Name type: accepted
============================================================
[CCH2] 'api/v2/taxonomy' returned results for 'Heteromeles arbutifolia'.
_fetch_query_data
{'tid': 22929, 'kingdomName': 'Plantae', 'rankID': 220, 'unitInd1': None, 'unitName1': 'Heteromeles', 'unitInd2': None, 'unitName2': 'arbutifolia', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(Lindl.) M. Roem.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'parentTid': 5720, 'status': 'accepted', 'classification': [{'tid': 1, 'scientificName': 'Organism', 'author': '', 'rankid': 1}, {'tid': 4, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 7, 'scientificName': 'Viridiplantae', 'author': '', 'rankid': 15}, {'tid': 3418, 'scientificName': 'Streptophyta', 'author': '', 'rankid': 25}, {'tid': 3425, 'scientificName': 'Embryophyta', 'author': '', 'rankid': 27}, {'tid': 3428, 'scientificName': 'Tracheophyta', 'author': '', 'rankid': 30}, {'tid': 3429, 'scientificName': 'Spermatophytina', 'author': '', 'rankid': 40}, {'tid': 3430, 'scientificName': 'Magnoliopsida', 'author': '', 'rankid': 60}, {'tid': 3436, 'scientificName': 'Rosanae', 'author': '', 'rankid': 90}, {'tid': 3634, 'scientificName': 'Rosales', 'author': '', 'rankid': 100}, {'tid': 4134, 'scientificName': 'Rosaceae', 'author': '', 'rankid': 140}, {'tid': 5720, 'scientificName': 'Heteromeles', 'author': '', 'rankid': 180}], 'scientificName': 'Heteromeles arbutifolia'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>CCH2 Portal - Heteromeles arbutifolia</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<!-- Responsive viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

	<link href="/portal/css/symbiota/accessibility-compliant.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" disabled >
	<link href="/portal/css/symbiota/condensed.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" >

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-2SETT3ZZFE"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-2SETT3ZZFE');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="login">
						<form name="loginForm" method="post" action="/portal/profile/index.php">
							<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=22929">
							<button class="button button-secondary bottom-breathing-room-rel left-breathing-room-rel" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
			<div class="top-brand">
				<a href="https://cch2.org">
					<div class="image-container">
						<img src="/portal/images/layout/CCH.png" alt="CCH2 logo">
					</div>
				</a>
				<div class="brand-name">
					<h1>CCH2</h1>
					<h2>Specimen data from the Consortium of California Herbaria</h2>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					<li>
						<a href="/portal/collections/misc/collprofiles.php">
							Collections
						</a>
					</li>
					<li>
						<a href="/portal/collections/search/index.php">
							Search						</a>
					</li>
					<li>
						<a href="/portal/collections/map/index.php" rel="noopener noreferrer">
							Map Search						</a>
					</li>
					<li>
						<a href="/portal/checklists/index.php">
							Checklists
						</a>
					</li>
					<li>
						<a href="/portal/imagelib/search.php">
							Media						</a>
					</li>
					<li>
						<a href="/portal/includes/usagepolicy.php">
							Data Use						</a>
					</li>
					<li>
						<a href="/portal/includes/aboutpage.php">About CCH</a>
					</li>
					<li>
						<a href="https://www.capturingcaliforniasflowers.org/symbiota.html" target="_blank">Help & Resources</a>
					</li>
					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Heteromeles arbutifolia</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Heteromeles arbutifolia</i></span>							<span id="author">(Lindl.) M. Roem.</span>
							&nbsp;<a href="index.php?tid=5720&amp;clid=0&amp;pid=&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Rosaceae</div>
													<div id="vernacularDiv">
								Toyon, <span class="verns"><a href="#" onclick="toggle('verns')" title="Click here to show more common names">more...</a></span><span class="verns" onclick="toggle('verns');" style="display:none;">toyon, toyon, toyon</span>							</div>
							<div id="synonymDiv" title="Synonyms">[<i>Heteromeles arbutifolia var. arbutifolia</i>, <span class="synSpan"><a href="#" onclick="toggle('synSpan')" title="Click here to show more synonyms">more</a></span><span class="synSpan" onclick="toggle('synSpan')" style="display:none"><i>Heteromeles arbutifolia var. cerina</i> (Jeps.) E. Murray, <i>Heteromeles arbutifolia var. macrocarpa</i> (Munz) Munz, <i>Heteromeles fremontiana</i> Decne., <i>Heteromeles salicifolia</i> (C. Presl) Abrams, <i>Photinia arbutifolia</i> Lindl., <i>Photinia arbutifolia var. cerina</i> Jeps., <i>Photinia salicifolia</i> C. Presl</span>]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../collections/individual/index.php?occid=128424');return false;"><img src="https://media01.symbiota.org/media/cch2/SBBG/SBBG166/SBBG166144.jpg" title="" alt="Heteromeles arbutifolia image" /></a></div><div class="creator"></div></div>					</td>
					<td class="desc">
						<div id="desctabs" class="ui-tabs" style="display:none"><ul class="ui-tabs-nav"><li><a href="plottab.php?tid=22929">Traits Plots</a></li><li><a href="resourcetab.php?tid=22929">Resources</a></li></ul></div>					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="img-div" style="height:300px;overflow:hidden;">

============================================================
  CCH2  (SymbiotaAPI)
  Species:   Photinia arbutifolia
  Name type: synonym  (synonym of: Heteromeles arbutifolia)
============================================================
[CCH2] 'api/v2/taxonomy' returned results for 'Photinia arbutifolia'.
_fetch_query_data
{'tid': 27893, 'kingdomName': 'Plantae', 'rankID': 220, 'unitInd1': None, 'unitName1': 'Photinia', 'unitInd2': None, 'unitName2': 'arbutifolia', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'Lindl.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'parentTid': 6295, 'status': 'synonym', 'accepted': {'tid': 22929, 'scientificName': 'Heteromeles arbutifolia', 'scientificNameAuthorship': '(Lindl.) M. Roem.', 'taxonomicSource': None, 'unacceptabilityReason': None, 'taxonRemarks': None}, 'classification': [{'tid': 1, 'scientificName': 'Organism', 'author': '', 'rankid': 1}, {'tid': 4, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 7, 'scientificName': 'Viridiplantae', 'author': '', 'rankid': 15}, {'tid': 3418, 'scientificName': 'Streptophyta', 'author': '', 'rankid': 25}, {'tid': 3425, 'scientificName': 'Embryophyta', 'author': '', 'rankid': 27}, {'tid': 3428, 'scientificName': 'Tracheophyta', 'author': '', 'rankid': 30}, {'tid': 3429, 'scientificName': 'Spermatophytina', 'author': '', 'rankid': 40}, {'tid': 3430, 'scientificName': 'Magnoliopsida', 'author': '', 'rankid': 60}, {'tid': 3436, 'scientificName': 'Rosanae', 'author': '', 'rankid': 90}, {'tid': 3634, 'scientificName': 'Rosales', 'author': '', 'rankid': 100}, {'tid': 4134, 'scientificName': 'Rosaceae', 'author': '', 'rankid': 140}, {'tid': 6295, 'scientificName': 'Photinia', 'author': '', 'rankid': 180}], 'scientificName': 'Photinia arbutifolia'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>CCH2 Portal - Heteromeles arbutifolia</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<!-- Responsive viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

	<link href="/portal/css/symbiota/accessibility-compliant.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" disabled >
	<link href="/portal/css/symbiota/condensed.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" >

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-2SETT3ZZFE"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-2SETT3ZZFE');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="login">
						<form name="loginForm" method="post" action="/portal/profile/index.php">
							<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=22929">
							<button class="button button-secondary bottom-breathing-room-rel left-breathing-room-rel" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
			<div class="top-brand">
				<a href="https://cch2.org">
					<div class="image-container">
						<img src="/portal/images/layout/CCH.png" alt="CCH2 logo">
					</div>
				</a>
				<div class="brand-name">
					<h1>CCH2</h1>
					<h2>Specimen data from the Consortium of California Herbaria</h2>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					<li>
						<a href="/portal/collections/misc/collprofiles.php">
							Collections
						</a>
					</li>
					<li>
						<a href="/portal/collections/search/index.php">
							Search						</a>
					</li>
					<li>
						<a href="/portal/collections/map/index.php" rel="noopener noreferrer">
							Map Search						</a>
					</li>
					<li>
						<a href="/portal/checklists/index.php">
							Checklists
						</a>
					</li>
					<li>
						<a href="/portal/imagelib/search.php">
							Media						</a>
					</li>
					<li>
						<a href="/portal/includes/usagepolicy.php">
							Data Use						</a>
					</li>
					<li>
						<a href="/portal/includes/aboutpage.php">About CCH</a>
					</li>
					<li>
						<a href="https://www.capturingcaliforniasflowers.org/symbiota.html" target="_blank">Help & Resources</a>
					</li>
					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Heteromeles arbutifolia</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Heteromeles arbutifolia</i></span>							<span id="author">(Lindl.) M. Roem.</span>
							&nbsp;<a href="index.php?tid=5720&amp;clid=0&amp;pid=&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Rosaceae</div>
													<div id="vernacularDiv">
								Toyon, <span class="verns"><a href="#" onclick="toggle('verns')" title="Click here to show more common names">more...</a></span><span class="verns" onclick="toggle('verns');" style="display:none;">toyon, toyon, toyon</span>							</div>
							<div id="synonymDiv" title="Synonyms">[<i>Heteromeles arbutifolia var. arbutifolia</i>, <span class="synSpan"><a href="#" onclick="toggle('synSpan')" title="Click here to show more synonyms">more</a></span><span class="synSpan" onclick="toggle('synSpan')" style="display:none"><i>Heteromeles arbutifolia var. cerina</i> (Jeps.) E. Murray, <i>Heteromeles arbutifolia var. macrocarpa</i> (Munz) Munz, <i>Heteromeles fremontiana</i> Decne., <i>Heteromeles salicifolia</i> (C. Presl) Abrams, <i>Photinia arbutifolia</i> Lindl., <i>Photinia arbutifolia var. cerina</i> Jeps., <i>Photinia salicifolia</i> C. Presl</span>]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../collections/individual/index.php?occid=5291467');return false;"><img src="https://media01.symbiota.org/media/cch2/IRVC/IRVC117/IRVC117244.jpg" title="" alt="Heteromeles arbutifolia image" /></a></div><div class="creator"></div></div>					</td>
					<td class="desc">
						<div id="desctabs" class="ui-tabs" style="display:none"><ul class="ui-tabs-nav"><li><a href="plottab.php?tid=22929">Traits Plots</a></li><li><a href="resourcetab.php?tid=22929">Resources</a></li></ul></div>					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="img-div" style="height:300px;overflow:hidden;">

============================================================
  CCH2  (SymbiotaAPI)
  Species:   Not species
  Name type: not species
============================================================
[CCH2] Search endpoint returned no results for 'Not species'. Attempting autocomplete search.
[CCH2] All searches failed or returned no results for 'Not species'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

============================================================
  SERNEC  (SymbiotaAPI)
  Species:   Magnolia grandiflora
  Name type: accepted
============================================================
[SERNEC] 'api/v2/taxonomy' returned results for 'Magnolia grandiflora'.
_fetch_query_data
{'tid': 17263, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Magnolia', 'unitInd2': None, 'unitName2': 'grandiflora', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'L.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'Martin_092306', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2006-12-25 06:25:43', 'parentTid': 17119, 'status': 'accepted', 'classification': [{'tid': 5570, 'scientificName': 'Magnoliophyta', 'author': '', 'rankid': 30}, {'tid': 5571, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 16366, 'scientificName': 'Magnoliaceae', 'author': '', 'rankid': 140}, {'tid': 16469, 'scientificName': 'Magnoliales', 'author': '', 'rankid': 100}, {'tid': 17119, 'scientificName': 'Magnolia', 'author': 'L.', 'rankid': 180}, {'tid': 170361, 'scientificName': 'Tracheophyta', 'author': '', 'rankid': 20}, {'tid': 170633, 'scientificName': 'Spermatophyta', 'author': '', 'rankid': 20}, {'tid': 170683, 'scientificName': 'Magnoliids', 'author': '', 'rankid': 75}], 'scientificName': 'Magnolia grandiflora'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>SERNEC Portal - Magnolia grandiflora</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-M54KGCMR9S"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-M54KGCMR9S');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="login">
						<form name="loginForm" method="post" action="/portal/profile/index.php">
							<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=17263">
							<button class="button button-secondary" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
			<div class="top-brand">
				<!--
				<a href="/portal">
					<div class="image-container">
						<img src="/portal/images/layout/logo_symbiota.png" alt="Symbiota logo">
					</div>
				</a>
				-->
				<div class="brand-name">
					<h1>SERNEC</h1>
					<h2>Southeast Regional Network of Expertise and Collections</h2>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					<li>
						<a href="#">Specimen Search</a>
						<ul>
							<li>
								<a href="/portal/collections/search/index.php">Search Collections</a>
							</li>
							<li>
								<a href="/portal/collections/map/index.php" rel="noopener noreferrer">Map Search</a>
							</li>
							<li>
								<a href="/portal/collections/exsiccati/index.php">Exsiccati Search</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Images</a>
						<ul>
							<li>
								<a href="/portal/collections/search/index.php">Image Library</a>
							</li>
							<li>
								<a href="/portal/imagelib/search.php">Search Images</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Inventories</a>
						<ul>
							<li>
								<a href="/portal/projects/index.php?proj=84">State Floras</a>
							</li>
							<li>
								<a href="/portal/projects/index.php?proj=106">Kentucky Flora</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Dynamic Tools</a>
						<ul>
							<li>
								<a href="/portal/checklists/dynamicmap.php?interface=checklist">Dynamic Checklist</a>
							</li>
							<li>
								<a href="/portal/checklists/dynamicmap.php?interface=checklist">Dynamic Key</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/portal/includes/usagepolicy.php">
							Data Use						</a>
					</li>
					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>
					<!--
					<li id="lang-select-li">
						<label for="language-selection">Select Language: </label>
						<select oninput="setLanguage(this)" id="language-selection" name="language-selection">
							<option value="en">English</option>
							<option value="es" >Español</option>
							<option value="fr" >Français</option>
						</select>
					</li>
					-->
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Magnolia grandiflora</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Magnolia grandiflora</i></span>							<span id="author">L.</span>
							&nbsp;<a href="index.php?tid=17119&amp;clid=0&amp;pid=84&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Magnoliaceae</div>
													<div id="vernacularDiv">
								Southern Magnolia							</div>
							<div id="synonymDiv" title="Synonyms">[<i>Magnolia foetida</i>, <span class="synSpan"><a href="#" onclick="toggle('synSpan')" title="Click here to show more synonyms">more</a></span><span class="synSpan" onclick="toggle('synSpan')" style="display:none"><i>Magnolia grandiflora var. praecox</i> Loudon, <i>Magnolia tomentosa</i> Ser.</span>]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../imagelib/imgdetails.php?mediaid=10953694');return false;"><img src="https://media01.symbiota.org/media/storage/portals/seinet/midwest/Magnoliaceae/201808/Magnolia_grandiflora_1535713057.jpg" title="fruit before dehiscing" alt="Magnolia grandiflora image" /></a></div><div class="creator">Paul Rothrock</div></div>					</td>
					<td class="desc">
						<div id="desctabs" class="ui-tabs" style="display:none"><ul class="ui-tabs-nav"><li><a href="#tab11654">FNA</a></li><li><a href="#tab39642">Gleason &amp; Cronquist</a></li><li><a href="resourcetab.php?tid=17263">Resources</a></li></ul><div id="tab11654" class="sptab"><div id="descsource" style="float:right;"><a href="http://floranorthamerica.org/Magnolia_grandiflora" target="_blank">Frederick G. Meyer in Flora of North America (vol. 3)</a></div><div style="clear:both;">Trees , evergreen, single-trunked, to 37 m.  Bark  gray, rough, thick, furrowed in thick plates.  Pith  diaphragmed.  Twigs and foliar buds  densely red- or white-hairy.  Leaves  distinctly alternate, not in terminal whorl-like clusters; stipules 2, free, 4.5-13 × 1.5-3.5 cm, abaxially densely brown-silky, sometimes deeply notched.  Leaf blade  narrowly to broadly elliptic or oblanceolate, (7.5-)13-20(-26) × (4.5-)6-10(-12.5) cm, thick-leathery, base narrowly cuneate, apex abruptly tapered and acute to short-acuminate, rarely obtuse; surfaces abaxially glabrous to densely red-brown felted, adaxially bright green, lustrous, glabrous.  Flowers  strongly lemony fragrant, 15-30(-45) cm across; spathaceous bracts 2, leathery, outer bract abaxially brown to grayish pilose, deeply notched, smaller, inner bract adaxially densely brown to grayish pilose, shallowly notched, larger; tepals creamy white; stamens (179-)213-383(-405), 16-29 mm; filaments purple; pistils (45-)55-81(-89).  Follicetums  cylindric to somewhat obovoid, 7-10 × 3.5-5 cm; follicles beaked, sparsely to densely silky-villous.  Seeds  lenticular to narrowly ellipsoid, (9-)12-14 mm, adaxially slightly grooved, aril red. 2 n =114. <br><br>Flowering spring. Wooded dunes, hammocks, river bottoms, mesic woods, and ravine slopes; coastal plain; 0-120m; Ala., Ark., Fla., Ga., La., Miss., N.C., S.C., Tex. <br><br>Magnolia grandiflora (a hexaploid) is highly variable, especially the leaves, which range from glabrous to densely red-brown felted on the abaxial surface. It is the only magnolia species in the flora with free stipules, and the inner spathaceous bract is unique among Magnolia taxa in the flora. Curled filiform trichomes occur on the abaxial leaf surface. In the wild, hybrids with M. virginiana (a diploid) have been reported but not confirmed by the present author. The compatibility of these taxa is well known from the Freeman hybrid, a highly sterile tetraploid growing at the U.S. National Arboretum in Washington, D.C. In crosses using the hexaploid M. grandiflora , this parent is dominant and nearly masks the other parent. <br><br>Magnolia grandiflora is an escape, and it naturalizes in the tidewater area of Virginia and locally elsewhere beyond its natural range in the southeastern United States. It ranks among the noblest of North American broadleaved trees and is cultivated widely in the United States and in many other countries. A large number of cultivars have been introduced to horticulture.<p>Southern magnolia ( Magnolia grandiflora ) is the state tree of both Louisiana and Mississippi.<P>The largest known tree of Magnolia grandiflora, 37.2m in height with a trunk diameter of 1.97m, is recorded from Smith County, Mississippi (American Forestry Association 1994).<P>The Choctaw and Koasati tribes used the bark of Magnolia grandiflora as dermatological and kidney aids (D.A. Moerman 1986).<p></div></div><div id="tab39642" class="sptab"><div id="descsource" style="float:right;"><a href="http://sweetgum.nybg.org/science/world-flora/details.php?irn=5104" target="_blank">Vascular plants of NE US and adjacent Canada</a></div><div style="clear:both;">Handsome tree to 30 m; winter terminal bud 1-2.5 cm, evidently hairy; lvs scattered or somewhat clustered toward the ends of the twigs, leathery, evergreen, elliptic, 12-25 cm, a third or half as wide, acute to obtuse, basally acute to rounded-obtuse, the lower surface conspicuously rusty with a  ±persistent, thin, villous tomentum; fls fragrant, creamy-white, cup-shaped, ca 10 cm thick; pet 6-12, obovate or spatulate, broadly rounded distally, concave, 7-13 cm; fr cone ellipsoid, 6-10 cm, the follicles woolly- villous; 2n=ca 114. Rich woods and moist bottomlands; coastal plain from se. Va. to Fla. and Tex. Apr.-June.<br/><br/>Gleason, Henry A. & Cronquist, Arthur J. 1991. Manual of vascular plants of northeastern United States and adjacent Canada. lxxv + 910 pp.<br/><br/><b>&copy;The New York Botanical Garden. All rights reserved. Used by permission.</b></div></div></div>					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="img-div" style="height:300px;overflow:hidden;">

============================================================
  SERNEC  (SymbiotaAPI)
  Species:   Magnolia foetida
  Name type: synonym  (synonym of: Magnolia grandiflora)
============================================================
[SERNEC] 'api/v2/taxonomy' returned results for 'Magnolia foetida'.
_fetch_query_data
{'tid': 214261, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Magnolia', 'unitInd2': None, 'unitName2': 'foetida', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2015-12-13 07:49:14', 'parentTid': 17119, 'status': 'synonym', 'accepted': {'tid': 17263, 'scientificName': 'Magnolia grandiflora', 'scientificNameAuthorship': 'L.', 'taxonomicSource': None, 'unacceptabilityReason': None, 'taxonRemarks': None}, 'classification': [{'tid': 5570, 'scientificName': 'Magnoliophyta', 'author': '', 'rankid': 30}, {'tid': 5571, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 16366, 'scientificName': 'Magnoliaceae', 'author': '', 'rankid': 140}, {'tid': 16469, 'scientificName': 'Magnoliales', 'author': '', 'rankid': 100}, {'tid': 17119, 'scientificName': 'Magnolia', 'author': 'L.', 'rankid': 180}, {'tid': 170361, 'scientificName': 'Tracheophyta', 'author': '', 'rankid': 20}, {'tid': 170633, 'scientificName': 'Spermatophyta', 'author': '', 'rankid': 20}, {'tid': 170683, 'scientificName': 'Magnoliids', 'author': '', 'rankid': 75}], 'scientificName': 'Magnolia foetida'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>SERNEC Portal - Magnolia grandiflora</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-M54KGCMR9S"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-M54KGCMR9S');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="login">
						<form name="loginForm" method="post" action="/portal/profile/index.php">
							<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=17263">
							<button class="button button-secondary" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
			<div class="top-brand">
				<!--
				<a href="/portal">
					<div class="image-container">
						<img src="/portal/images/layout/logo_symbiota.png" alt="Symbiota logo">
					</div>
				</a>
				-->
				<div class="brand-name">
					<h1>SERNEC</h1>
					<h2>Southeast Regional Network of Expertise and Collections</h2>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					<li>
						<a href="#">Specimen Search</a>
						<ul>
							<li>
								<a href="/portal/collections/search/index.php">Search Collections</a>
							</li>
							<li>
								<a href="/portal/collections/map/index.php" rel="noopener noreferrer">Map Search</a>
							</li>
							<li>
								<a href="/portal/collections/exsiccati/index.php">Exsiccati Search</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Images</a>
						<ul>
							<li>
								<a href="/portal/collections/search/index.php">Image Library</a>
							</li>
							<li>
								<a href="/portal/imagelib/search.php">Search Images</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Inventories</a>
						<ul>
							<li>
								<a href="/portal/projects/index.php?proj=84">State Floras</a>
							</li>
							<li>
								<a href="/portal/projects/index.php?proj=106">Kentucky Flora</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Dynamic Tools</a>
						<ul>
							<li>
								<a href="/portal/checklists/dynamicmap.php?interface=checklist">Dynamic Checklist</a>
							</li>
							<li>
								<a href="/portal/checklists/dynamicmap.php?interface=checklist">Dynamic Key</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/portal/includes/usagepolicy.php">
							Data Use						</a>
					</li>
					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>
					<!--
					<li id="lang-select-li">
						<label for="language-selection">Select Language: </label>
						<select oninput="setLanguage(this)" id="language-selection" name="language-selection">
							<option value="en">English</option>
							<option value="es" >Español</option>
							<option value="fr" >Français</option>
						</select>
					</li>
					-->
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Magnolia grandiflora</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Magnolia grandiflora</i></span>							<span id="author">L.</span>
							&nbsp;<a href="index.php?tid=17119&amp;clid=0&amp;pid=84&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Magnoliaceae</div>
													<div id="vernacularDiv">
								Southern Magnolia							</div>
							<div id="synonymDiv" title="Synonyms">[<i>Magnolia foetida</i>, <span class="synSpan"><a href="#" onclick="toggle('synSpan')" title="Click here to show more synonyms">more</a></span><span class="synSpan" onclick="toggle('synSpan')" style="display:none"><i>Magnolia grandiflora var. praecox</i> Loudon, <i>Magnolia tomentosa</i> Ser.</span>]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../imagelib/imgdetails.php?mediaid=10953694');return false;"><img src="https://media01.symbiota.org/media/storage/portals/seinet/midwest/Magnoliaceae/201808/Magnolia_grandiflora_1535713057.jpg" title="fruit before dehiscing" alt="Magnolia grandiflora image" /></a></div><div class="creator">Paul Rothrock</div></div>					</td>
					<td class="desc">
						<div id="desctabs" class="ui-tabs" style="display:none"><ul class="ui-tabs-nav"><li><a href="#tab11654">FNA</a></li><li><a href="#tab39642">Gleason &amp; Cronquist</a></li><li><a href="resourcetab.php?tid=17263">Resources</a></li></ul><div id="tab11654" class="sptab"><div id="descsource" style="float:right;"><a href="http://floranorthamerica.org/Magnolia_grandiflora" target="_blank">Frederick G. Meyer in Flora of North America (vol. 3)</a></div><div style="clear:both;">Trees , evergreen, single-trunked, to 37 m.  Bark  gray, rough, thick, furrowed in thick plates.  Pith  diaphragmed.  Twigs and foliar buds  densely red- or white-hairy.  Leaves  distinctly alternate, not in terminal whorl-like clusters; stipules 2, free, 4.5-13 × 1.5-3.5 cm, abaxially densely brown-silky, sometimes deeply notched.  Leaf blade  narrowly to broadly elliptic or oblanceolate, (7.5-)13-20(-26) × (4.5-)6-10(-12.5) cm, thick-leathery, base narrowly cuneate, apex abruptly tapered and acute to short-acuminate, rarely obtuse; surfaces abaxially glabrous to densely red-brown felted, adaxially bright green, lustrous, glabrous.  Flowers  strongly lemony fragrant, 15-30(-45) cm across; spathaceous bracts 2, leathery, outer bract abaxially brown to grayish pilose, deeply notched, smaller, inner bract adaxially densely brown to grayish pilose, shallowly notched, larger; tepals creamy white; stamens (179-)213-383(-405), 16-29 mm; filaments purple; pistils (45-)55-81(-89).  Follicetums  cylindric to somewhat obovoid, 7-10 × 3.5-5 cm; follicles beaked, sparsely to densely silky-villous.  Seeds  lenticular to narrowly ellipsoid, (9-)12-14 mm, adaxially slightly grooved, aril red. 2 n =114. <br><br>Flowering spring. Wooded dunes, hammocks, river bottoms, mesic woods, and ravine slopes; coastal plain; 0-120m; Ala., Ark., Fla., Ga., La., Miss., N.C., S.C., Tex. <br><br>Magnolia grandiflora (a hexaploid) is highly variable, especially the leaves, which range from glabrous to densely red-brown felted on the abaxial surface. It is the only magnolia species in the flora with free stipules, and the inner spathaceous bract is unique among Magnolia taxa in the flora. Curled filiform trichomes occur on the abaxial leaf surface. In the wild, hybrids with M. virginiana (a diploid) have been reported but not confirmed by the present author. The compatibility of these taxa is well known from the Freeman hybrid, a highly sterile tetraploid growing at the U.S. National Arboretum in Washington, D.C. In crosses using the hexaploid M. grandiflora , this parent is dominant and nearly masks the other parent. <br><br>Magnolia grandiflora is an escape, and it naturalizes in the tidewater area of Virginia and locally elsewhere beyond its natural range in the southeastern United States. It ranks among the noblest of North American broadleaved trees and is cultivated widely in the United States and in many other countries. A large number of cultivars have been introduced to horticulture.<p>Southern magnolia ( Magnolia grandiflora ) is the state tree of both Louisiana and Mississippi.<P>The largest known tree of Magnolia grandiflora, 37.2m in height with a trunk diameter of 1.97m, is recorded from Smith County, Mississippi (American Forestry Association 1994).<P>The Choctaw and Koasati tribes used the bark of Magnolia grandiflora as dermatological and kidney aids (D.A. Moerman 1986).<p></div></div><div id="tab39642" class="sptab"><div id="descsource" style="float:right;"><a href="http://sweetgum.nybg.org/science/world-flora/details.php?irn=5104" target="_blank">Vascular plants of NE US and adjacent Canada</a></div><div style="clear:both;">Handsome tree to 30 m; winter terminal bud 1-2.5 cm, evidently hairy; lvs scattered or somewhat clustered toward the ends of the twigs, leathery, evergreen, elliptic, 12-25 cm, a third or half as wide, acute to obtuse, basally acute to rounded-obtuse, the lower surface conspicuously rusty with a  ±persistent, thin, villous tomentum; fls fragrant, creamy-white, cup-shaped, ca 10 cm thick; pet 6-12, obovate or spatulate, broadly rounded distally, concave, 7-13 cm; fr cone ellipsoid, 6-10 cm, the follicles woolly- villous; 2n=ca 114. Rich woods and moist bottomlands; coastal plain from se. Va. to Fla. and Tex. Apr.-June.<br/><br/>Gleason, Henry A. & Cronquist, Arthur J. 1991. Manual of vascular plants of northeastern United States and adjacent Canada. lxxv + 910 pp.<br/><br/><b>&copy;The New York Botanical Garden. All rights reserved. Used by permission.</b></div></div></div>					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="img-div" style="height:300px;overflow:hidden;">

============================================================
  SERNEC  (SymbiotaAPI)
  Species:   Not species
  Name type: not species
============================================================
[SERNEC] Search endpoint returned no results for 'Not species'. Attempting autocomplete search.
[SERNEC] All searches failed or returned no results for 'Not species'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

============================================================
  NANSH  (SymbiotaAPI)
  Species:   Rudbeckia hirta
  Name type: accepted
============================================================
[NANSH] 'api/v2/taxonomy' returned results for 'Rudbeckia hirta'.
_fetch_query_data
{'tid': 17308, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Rudbeckia', 'unitInd2': None, 'unitName2': 'hirta', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'L.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'Martin_092306', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2006-12-25 06:25:43', 'parentTid': 5000, 'status': 'accepted', 'classification': [{'tid': 5000, 'scientificName': 'Rudbeckia', 'author': 'L.', 'rankid': 180}, {'tid': 5378, 'scientificName': 'Asteraceae', 'author': 'Bercht. & J. Presl', 'rankid': 140}, {'tid': 5505, 'scientificName': 'Asterales', 'author': '', 'rankid': 100}, {'tid': 5570, 'scientificName': 'Magnoliophyta', 'author': '', 'rankid': 30}, {'tid': 5571, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 170361, 'scientificName': 'Tracheophyta', 'author': '', 'rankid': 20}, {'tid': 170633, 'scientificName': 'Spermatophyta', 'author': '', 'rankid': 20}, {'tid': 170692, 'scientificName': 'Eudicots', 'author': '', 'rankid': 45}, {'tid': 170726, 'scientificName': 'Core Eudicots', 'author': '', 'rankid': 65}, {'tid': 170749, 'scientificName': 'Asterids', 'author': '', 'rankid': 75}, {'tid': 170772, 'scientificName': 'Campanulids', 'author': '', 'rankid': 75}], 'scientificName': 'Rudbeckia hirta'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>NANSH Portal - Rudbeckia hirta</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-85L6HL6NJ4"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-85L6HL6NJ4');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="login">
						<form name="loginForm" method="post" action="/portal/profile/index.php">
							<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=17308">
							<button class="button button-secondary" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
			<div class="top-brand">
				<!--<a href="/portal">
					<div class="image-container">
						<img src="/portal/images/layout/logo_symbiota.png" alt="Symbiota logo">
					</div>
				</a>
				-->
				<div class="brand-name">
					<h1>North American Network of Small Herbaria</h1>
					<h2></h2>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					<li>
						<a href="/portal/collections/search/index.php">
							Search						</a>
					</li>
					<li>
						<a href="/portal/collections/exsiccati/index.php">
							Exsiccati
						</a>
					</li>
					<li>
						<a href="/portal/checklists/dynamicmap.php?interface=checklist">
							Dynamic Checklist
						</a>
					</li>
					<li>
						<a href="/portal/checklists/dynamicmap.php?interface=key">
							Dynamic Key
						</a>
					</li>
					<li>
						<a href="/portal/imagelib/index.php">
							Image Library
						</a>
					</li>
					<li>
						<a href="https://docs.symbiota.org/docs/about/" target="_blank" rel="noopener noreferrer">
							Symbiota Help						</a>
					</li>
					<li>
						<a href="/portal/includes/usagepolicy.php">
							Data Use						</a>
					</li>
					<li>
						<a href="#">Other Networks</a>
						<ul>
							<li>
								<a href="http://ngpherbaria.org/">Northern Great Plains</a>
							</li>
							<li>
								<a href="http://intermountainbiota.org/">Intermountain Herbaria</a>
							</li>
							<li>
								<a href="http://www.madrean.org/maba/symbflora/">MABA Flora</a>
							</li>
							<li>
								<a href="http://swbiodiversity.org/">SEINet</a>
							</li>
							<li>
								<a href="http://sernecportal.org/">SERNEC</a>
							</li>
						</ul>
					</li>
					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>
					<!--
					<li id="lang-select-li">
						<label for="language-selection">Select Language: </label>
						<select oninput="setLanguage(this)" id="language-selection" name="language-selection">
							<option value="en">English</option>
							<option value="es" >Español</option>
							<option value="fr" >Français</option>
						</select>
					</li>
					-->
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Rudbeckia hirta</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Rudbeckia hirta</i></span>							<span id="author">L.</span>
							&nbsp;<a href="index.php?tid=5000&amp;clid=0&amp;pid=1&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Asteraceae</div>
													<div id="vernacularDiv">
								Black-Eyed-Susan, <span class="verns"><a href="#" onclick="toggle('verns')" title="Click here to show more common names">more...</a></span><span class="verns" onclick="toggle('verns');" style="display:none;">blackeyed Susan</span>							</div>
							<div id="synonymDiv" title="Synonyms">[<i>Coreopsis hirta</i>]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../imagelib/imgdetails.php?mediaid=10298300');return false;"><img src="https://media01.symbiota.org/media/storage/portals/seinet/midwest/Asteraceae/201805/Rudbeckia_hirta_habit_er_1526053737.jpg" title="" alt="Rudbeckia hirta image" /></a></div><div class="creator">Paul Rothrock</div></div>					</td>
					<td class="desc">
						<div id="desctabs" class="ui-tabs" style="display:none"><ul class="ui-tabs-nav"><li><a href="#tab13483">FNA</a></li><li><a href="#tab40903">Gleason &amp; Cronquist</a></li><li><a href="resourcetab.php?tid=17308">Resources</a></li></ul><div id="tab13483" class="sptab"><div id="descsource" style="float:right;"><a href="http://floranorthamerica.org/Rudbeckia_hirta" target="_blank">Lowell E. Urbatsch, Patricia B. Cox in Flora of North America (vol. 21)</a></div><div style="clear:both;"><b>Annuals, biennials, or perennials,</b> to 100 cm (taprooted or roots fibrous). <b>Stems</b> hispid to hirsute (hairs spreading, 1+ mm). <b>Leaves:</b> blades elliptic, lanceolate, or ovate (not lobed), bases attenuate to cuneate, margins entire or serrate, apices acute, faces hispid to hirsute; basal petiolate, blades 8-30 × 0.5-7 cm; cauline petiolate or sessile, blades (sometimes pandurate) 3-20 × 0.4-4 cm. <b>Heads</b> borne singly or (2-5) in loose, corymbiform arrays. <b>Phyllaries</b> to 3 cm (faces hispid to hirsute). <b>Receptacles</b> hemispheric to ovoid; paleae 4-6 mm, apices acute, often attenuate, abaxial tips hirsute to hispid. <b>Ray florets</b> 8-16; laminae (usually uniformly yellow to yellow-orange or with a basal maroon splotch, sometimes mostly maroon) elliptic to oblong or oblanceolate, 15-45 × 5-10 mm, abaxially hispid to hirsute. <b>Discs</b> 12-22 × 10-20 mm. <b>Disc florets</b> 250-500+; corollas proximally yellowish green, distally brown-purple, 3-4.2 mm; style branches ca. 1.5 mm, apices subulate. <b>Cypselae</b> 1.5-2.7 mm; <b>pappi</b> 0. <br><br>Some strains of <i>Rudbeckia hirta</i> are cultivated and/or used in seed mixes for 're-naturalization' and erosion control.<p></div></div><div id="tab40903" class="sptab"><div id="descsource" style="float:right;"><a href="http://sweetgum.nybg.org/science/world-flora/details.php?irn=9684" target="_blank">Vascular plants of NE US and adjacent Canada</a></div><div style="clear:both;">Biennial or short-lived perennial 3-10 dm,  ±hispid or hirsute throughout; lvs variable, the lower mostly oblanceolate to elliptic and long-petiolate, the others lance-linear to oblong or ovate, mostly sessile; heads mostly long-pedunculate, the hemispheric or ovoid disk 12-20 mm wide, dark purple or brown (yellow); invol bracts copiously hirsute or hispid, sometimes much elongate; rays 8-21, orange or orange-yellow, sometimes darker or marked with purple at base, 2-4 cm; receptacular bracts acute,  ±hispid or hispidulous near the tip; style-appendages elongate, subulate; pappus none; 2n=38. Various habitats; Nf. to Fla., w. to B.C. and Mex. June-Oct. Var. hirta occurs mostly in relatively undisturbed habitats in the mts. from Pa. to Ga. and Ala., and sparingly n. to Me. and w. to Ill.; it has coarsely toothed lvs, the basal ones with the blade 2.5-7 cm wide and about twice as long, the cauline ones lance-ovate to ovate or pandurate. Var. pulcherrima Farw. (R. serotina) is widespread especially in disturbed habitats; it has entire or finely toothed lvs, the basal ones with lanceolate or oblanceolate blade 1-2.5(-5) cm wide and (3-)4-5 times as long, the cauline ones spatulate or oblanceolate to broadly linear.<br/><br/>Gleason, Henry A. & Cronquist, Arthur J. 1991. Manual of vascular plants of northeastern United States and adjacent Canada. lxxv + 910 pp.<br/><br/><b>&copy;The New York Botanical Garden. All rights reserved. Used by permission.</b></div></div></div>					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="img-div" style="height:300px;overflow:hidden;">

============================================================
  NANSH  (SymbiotaAPI)
  Species:   Coreopsis hirta
  Name type: synonym  (synonym of: Rudbeckia hirta)
============================================================
[NANSH] 'api/v2/taxonomy' returned results for 'Coreopsis hirta'.
_fetch_query_data
{'tid': 207014, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Coreopsis', 'unitInd2': None, 'unitName2': 'hirta', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2015-12-13 07:49:14', 'parentTid': 5181, 'status': 'synonym', 'accepted': {'tid': 17308, 'scientificName': 'Rudbeckia hirta', 'scientificNameAuthorship': 'L.', 'taxonomicSource': None, 'unacceptabilityReason': None, 'taxonRemarks': None}, 'classification': [{'tid': 5181, 'scientificName': 'Coreopsis', 'author': 'L.', 'rankid': 180}, {'tid': 5378, 'scientificName': 'Asteraceae', 'author': 'Bercht. & J. Presl', 'rankid': 140}, {'tid': 5505, 'scientificName': 'Asterales', 'author': '', 'rankid': 100}, {'tid': 5570, 'scientificName': 'Magnoliophyta', 'author': '', 'rankid': 30}, {'tid': 5571, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 170361, 'scientificName': 'Tracheophyta', 'author': '', 'rankid': 20}, {'tid': 170633, 'scientificName': 'Spermatophyta', 'author': '', 'rankid': 20}, {'tid': 170692, 'scientificName': 'Eudicots', 'author': '', 'rankid': 45}, {'tid': 170726, 'scientificName': 'Core Eudicots', 'author': '', 'rankid': 65}, {'tid': 170749, 'scientificName': 'Asterids', 'author': '', 'rankid': 75}, {'tid': 170772, 'scientificName': 'Campanulids', 'author': '', 'rankid': 75}], 'scientificName': 'Coreopsis hirta'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>NANSH Portal - Rudbeckia hirta</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-85L6HL6NJ4"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-85L6HL6NJ4');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="login">
						<form name="loginForm" method="post" action="/portal/profile/index.php">
							<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=17308">
							<button class="button button-secondary" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
			<div class="top-brand">
				<!--<a href="/portal">
					<div class="image-container">
						<img src="/portal/images/layout/logo_symbiota.png" alt="Symbiota logo">
					</div>
				</a>
				-->
				<div class="brand-name">
					<h1>North American Network of Small Herbaria</h1>
					<h2></h2>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					<li>
						<a href="/portal/collections/search/index.php">
							Search						</a>
					</li>
					<li>
						<a href="/portal/collections/exsiccati/index.php">
							Exsiccati
						</a>
					</li>
					<li>
						<a href="/portal/checklists/dynamicmap.php?interface=checklist">
							Dynamic Checklist
						</a>
					</li>
					<li>
						<a href="/portal/checklists/dynamicmap.php?interface=key">
							Dynamic Key
						</a>
					</li>
					<li>
						<a href="/portal/imagelib/index.php">
							Image Library
						</a>
					</li>
					<li>
						<a href="https://docs.symbiota.org/docs/about/" target="_blank" rel="noopener noreferrer">
							Symbiota Help						</a>
					</li>
					<li>
						<a href="/portal/includes/usagepolicy.php">
							Data Use						</a>
					</li>
					<li>
						<a href="#">Other Networks</a>
						<ul>
							<li>
								<a href="http://ngpherbaria.org/">Northern Great Plains</a>
							</li>
							<li>
								<a href="http://intermountainbiota.org/">Intermountain Herbaria</a>
							</li>
							<li>
								<a href="http://www.madrean.org/maba/symbflora/">MABA Flora</a>
							</li>
							<li>
								<a href="http://swbiodiversity.org/">SEINet</a>
							</li>
							<li>
								<a href="http://sernecportal.org/">SERNEC</a>
							</li>
						</ul>
					</li>
					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>
					<!--
					<li id="lang-select-li">
						<label for="language-selection">Select Language: </label>
						<select oninput="setLanguage(this)" id="language-selection" name="language-selection">
							<option value="en">English</option>
							<option value="es" >Español</option>
							<option value="fr" >Français</option>
						</select>
					</li>
					-->
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Rudbeckia hirta</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Rudbeckia hirta</i></span>							<span id="author">L.</span>
							&nbsp;<a href="index.php?tid=5000&amp;clid=0&amp;pid=1&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Asteraceae</div>
													<div id="vernacularDiv">
								Black-Eyed-Susan, <span class="verns"><a href="#" onclick="toggle('verns')" title="Click here to show more common names">more...</a></span><span class="verns" onclick="toggle('verns');" style="display:none;">blackeyed Susan</span>							</div>
							<div id="synonymDiv" title="Synonyms">[<i>Coreopsis hirta</i>]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../imagelib/imgdetails.php?mediaid=10298300');return false;"><img src="https://media01.symbiota.org/media/storage/portals/seinet/midwest/Asteraceae/201805/Rudbeckia_hirta_habit_er_1526053737.jpg" title="" alt="Rudbeckia hirta image" /></a></div><div class="creator">Paul Rothrock</div></div>					</td>
					<td class="desc">
						<div id="desctabs" class="ui-tabs" style="display:none"><ul class="ui-tabs-nav"><li><a href="#tab13483">FNA</a></li><li><a href="#tab40903">Gleason &amp; Cronquist</a></li><li><a href="resourcetab.php?tid=17308">Resources</a></li></ul><div id="tab13483" class="sptab"><div id="descsource" style="float:right;"><a href="http://floranorthamerica.org/Rudbeckia_hirta" target="_blank">Lowell E. Urbatsch, Patricia B. Cox in Flora of North America (vol. 21)</a></div><div style="clear:both;"><b>Annuals, biennials, or perennials,</b> to 100 cm (taprooted or roots fibrous). <b>Stems</b> hispid to hirsute (hairs spreading, 1+ mm). <b>Leaves:</b> blades elliptic, lanceolate, or ovate (not lobed), bases attenuate to cuneate, margins entire or serrate, apices acute, faces hispid to hirsute; basal petiolate, blades 8-30 × 0.5-7 cm; cauline petiolate or sessile, blades (sometimes pandurate) 3-20 × 0.4-4 cm. <b>Heads</b> borne singly or (2-5) in loose, corymbiform arrays. <b>Phyllaries</b> to 3 cm (faces hispid to hirsute). <b>Receptacles</b> hemispheric to ovoid; paleae 4-6 mm, apices acute, often attenuate, abaxial tips hirsute to hispid. <b>Ray florets</b> 8-16; laminae (usually uniformly yellow to yellow-orange or with a basal maroon splotch, sometimes mostly maroon) elliptic to oblong or oblanceolate, 15-45 × 5-10 mm, abaxially hispid to hirsute. <b>Discs</b> 12-22 × 10-20 mm. <b>Disc florets</b> 250-500+; corollas proximally yellowish green, distally brown-purple, 3-4.2 mm; style branches ca. 1.5 mm, apices subulate. <b>Cypselae</b> 1.5-2.7 mm; <b>pappi</b> 0. <br><br>Some strains of <i>Rudbeckia hirta</i> are cultivated and/or used in seed mixes for 're-naturalization' and erosion control.<p></div></div><div id="tab40903" class="sptab"><div id="descsource" style="float:right;"><a href="http://sweetgum.nybg.org/science/world-flora/details.php?irn=9684" target="_blank">Vascular plants of NE US and adjacent Canada</a></div><div style="clear:both;">Biennial or short-lived perennial 3-10 dm,  ±hispid or hirsute throughout; lvs variable, the lower mostly oblanceolate to elliptic and long-petiolate, the others lance-linear to oblong or ovate, mostly sessile; heads mostly long-pedunculate, the hemispheric or ovoid disk 12-20 mm wide, dark purple or brown (yellow); invol bracts copiously hirsute or hispid, sometimes much elongate; rays 8-21, orange or orange-yellow, sometimes darker or marked with purple at base, 2-4 cm; receptacular bracts acute,  ±hispid or hispidulous near the tip; style-appendages elongate, subulate; pappus none; 2n=38. Various habitats; Nf. to Fla., w. to B.C. and Mex. June-Oct. Var. hirta occurs mostly in relatively undisturbed habitats in the mts. from Pa. to Ga. and Ala., and sparingly n. to Me. and w. to Ill.; it has coarsely toothed lvs, the basal ones with the blade 2.5-7 cm wide and about twice as long, the cauline ones lance-ovate to ovate or pandurate. Var. pulcherrima Farw. (R. serotina) is widespread especially in disturbed habitats; it has entire or finely toothed lvs, the basal ones with lanceolate or oblanceolate blade 1-2.5(-5) cm wide and (3-)4-5 times as long, the cauline ones spatulate or oblanceolate to broadly linear.<br/><br/>Gleason, Henry A. & Cronquist, Arthur J. 1991. Manual of vascular plants of northeastern United States and adjacent Canada. lxxv + 910 pp.<br/><br/><b>&copy;The New York Botanical Garden. All rights reserved. Used by permission.</b></div></div></div>					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="img-div" style="height:300px;overflow:hidden;">

============================================================
  NANSH  (SymbiotaAPI)
  Species:   Not species
  Name type: not species
============================================================
[NANSH] Search endpoint returned no results for 'Not species'. Attempting autocomplete search.
[NANSH] All searches failed or returned no results for 'Not species'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

============================================================
  Algae Herbarium Portal  (SymbiotaAPI)
  Species:   Ulva intestinalis
  Name type: accepted
============================================================
[Algae Herbarium Portal] 'api/v2/taxonomy' returned results for 'Ulva intestinalis'.
_fetch_query_data
{'tid': 76122, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Ulva', 'unitInd2': None, 'unitName2': 'intestinalis', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'Linnaeus', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'sourceIdentifier': None, 'notes': 'Woolwich, London, England?', 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2014-04-25 18:37:07', 'parentTid': 8467, 'status': 'accepted', 'classification': [{'tid': 1766, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 1772, 'scientificName': 'Chlorophyta', 'author': '', 'rankid': 30}, {'tid': 1866, 'scientificName': 'Ulvophyceae', 'author': '', 'rankid': 60}, {'tid': 2128, 'scientificName': 'Ulvales', 'author': '', 'rankid': 100}, {'tid': 2678, 'scientificName': 'Ulvaceae', 'author': '', 'rankid': 140}, {'tid': 8467, 'scientificName': 'Ulva', 'author': 'Linnaeus, 1753', 'rankid': 180}], 'scientificName': 'Ulva intestinalis'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Macro-Algae Portal - Ulva intestinalis</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<!-- Responsive viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-DYQ4WCWFRV"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-DYQ4WCWFRV');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span class="button button-secondary">
						<a href="/portal/profile/index.php?refurl=/portal/taxa/index.php?tid=76122">
							Sign In						</a>
					</span>
								</nav>
			<div class="top-brand">
				<!-- <a href="/portal">
					<div class="image-container">
						<img src="/portal/images/layout/logo_symbiota.png" alt="Symbiota logo">
					</div>
				</a>
				-->
				<div class="brand-name">
					<h1>Algae Herbarium Portal</h1>
					<h2>A consortium of algae collections</h2>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					<li>
						<a href="/portal/collections/search/index.php">
							Search						</a>
					</li>
					<li>
						<a href="/portal/collections/map/index.php" rel="noopener noreferrer">
							Map Search						</a>
					</li>
                                        <li>
                                                <a href="/portal/collections/exsiccati/index.php">Exsiccatae</a>
                                        </li>
					<li>
						<a href="/portal/checklists/index.php">Flora Projects</a>
					</li>
					<li>
						<a href="/portal/imagelib/search.php">
							Media						</a>
					</li>
					<li>
                                                <a href="/portal/checklists/dynamicmap.php?interface=checklist">Dynamic Checklist</a>
                                        </li>
					<li>
						<a href="/portal/includes/usagepolicy.php">
							Data Use						</a>
					</li>
					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Ulva intestinalis</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Ulva intestinalis</i></span>							<span id="author">Linnaeus</span>
							&nbsp;<a href="index.php?tid=8467&amp;clid=0&amp;pid=1&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Ulvaceae</div>
						<div id="synonymDiv" title="Synonyms">[<i>Enteromorpha compressa var. intestinalis</i> (Linnaeus) Hamel, <span class="synSpan"><a href="#" onclick="toggle('synSpan')" title="Click here to show more synonyms">more</a></span><span class="synSpan" onclick="toggle('synSpan')" style="display:none"><i>Enteromorpha intestinalis f. maxima</i> J.Agardh, <i>Ilea intestinalis</i> (Linnaeus) Leiblein, <i>Scytosiphon intestinalis var. nematodes</i> Wallroth, <i>Tetraspora intestinalis</i> (Linnaeus) Desvaux, <i>Ulva bulbosa var. intestinalis</i> (Linnaeus) Hariot, <i>Ulva enteromorpha var. intestinalis</i> (Linnaeus) Le Jolis</span>]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../collections/individual/index.php?occid=1403598');return false;"><img src="https://library.ucsd.edu/dc/object/bb37004929/_1_1.png" title="" alt="Ulva intestinalis image" /></a></div><div class="creator"></div></div>					</td>
					<td class="desc">
						<div id="desctabs" class="ui-tabs" style="display:none"><ul class="ui-tabs-nav"><li><a href="resourcetab.php?tid=76122">Resources</a></li></ul></div>					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="img-div" style="height:300px;overflow:hidden;">

============================================================
  Algae Herbarium Portal  (SymbiotaAPI)
  Species:   Ilea intestinalis
  Name type: synonym  (synonym of: Ulva intestinalis)
============================================================
[Algae Herbarium Portal] 'api/v2/taxonomy' returned results for 'Ilea intestinalis'.
_fetch_query_data
{'tid': 189555, 'kingdomName': 'Chromista', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Ilea', 'unitInd2': None, 'unitName2': 'intestinalis', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(Linnaeus) Leiblein', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2014-04-25 19:14:57', 'parentTid': 6012, 'status': 'synonym', 'accepted': {'tid': 76122, 'scientificName': 'Ulva intestinalis', 'scientificNameAuthorship': 'Linnaeus', 'taxonomicSource': None, 'unacceptabilityReason': None, 'taxonRemarks': None}, 'classification': [{'tid': 1762, 'scientificName': 'Chromista', 'author': '', 'rankid': 10}, {'tid': 1783, 'scientificName': 'Heterokontophyta', 'author': '', 'rankid': 30}, {'tid': 1850, 'scientificName': 'Phaeophyceae', 'author': '', 'rankid': 60}, {'tid': 2003, 'scientificName': 'Ectocarpales', 'author': '', 'rankid': 100}, {'tid': 2613, 'scientificName': 'Scytosiphonaceae', 'author': '', 'rankid': 140}, {'tid': 6012, 'scientificName': 'Ilea', 'author': 'E.M.Fries, 1835', 'rankid': 180}], 'scientificName': 'Ilea intestinalis'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Macro-Algae Portal - Ulva intestinalis</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<!-- Responsive viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-DYQ4WCWFRV"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-DYQ4WCWFRV');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span class="button button-secondary">
						<a href="/portal/profile/index.php?refurl=/portal/taxa/index.php?tid=76122">
							Sign In						</a>
					</span>
								</nav>
			<div class="top-brand">
				<!-- <a href="/portal">
					<div class="image-container">
						<img src="/portal/images/layout/logo_symbiota.png" alt="Symbiota logo">
					</div>
				</a>
				-->
				<div class="brand-name">
					<h1>Algae Herbarium Portal</h1>
					<h2>A consortium of algae collections</h2>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					<li>
						<a href="/portal/collections/search/index.php">
							Search						</a>
					</li>
					<li>
						<a href="/portal/collections/map/index.php" rel="noopener noreferrer">
							Map Search						</a>
					</li>
                                        <li>
                                                <a href="/portal/collections/exsiccati/index.php">Exsiccatae</a>
                                        </li>
					<li>
						<a href="/portal/checklists/index.php">Flora Projects</a>
					</li>
					<li>
						<a href="/portal/imagelib/search.php">
							Media						</a>
					</li>
					<li>
                                                <a href="/portal/checklists/dynamicmap.php?interface=checklist">Dynamic Checklist</a>
                                        </li>
					<li>
						<a href="/portal/includes/usagepolicy.php">
							Data Use						</a>
					</li>
					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Ulva intestinalis</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Ulva intestinalis</i></span>							<span id="author">Linnaeus</span>
							&nbsp;<a href="index.php?tid=8467&amp;clid=0&amp;pid=1&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Ulvaceae</div>
						<div id="synonymDiv" title="Synonyms">[<i>Enteromorpha compressa var. intestinalis</i> (Linnaeus) Hamel, <span class="synSpan"><a href="#" onclick="toggle('synSpan')" title="Click here to show more synonyms">more</a></span><span class="synSpan" onclick="toggle('synSpan')" style="display:none"><i>Enteromorpha intestinalis f. maxima</i> J.Agardh, <i>Ilea intestinalis</i> (Linnaeus) Leiblein, <i>Scytosiphon intestinalis var. nematodes</i> Wallroth, <i>Tetraspora intestinalis</i> (Linnaeus) Desvaux, <i>Ulva bulbosa var. intestinalis</i> (Linnaeus) Hariot, <i>Ulva enteromorpha var. intestinalis</i> (Linnaeus) Le Jolis</span>]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../collections/individual/index.php?occid=1403584');return false;"><img src="https://library.ucsd.edu/dc/object/bb3086153n/_1_1.png" title="" alt="Ulva intestinalis image" /></a></div><div class="creator"></div></div>					</td>
					<td class="desc">
						<div id="desctabs" class="ui-tabs" style="display:none"><ul class="ui-tabs-nav"><li><a href="resourcetab.php?tid=76122">Resources</a></li></ul></div>					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="img-div" style="height:300px;overflow:hidden;">

============================================================
  Algae Herbarium Portal  (SymbiotaAPI)
  Species:   Not species
  Name type: not species
============================================================
[Algae Herbarium Portal] Search endpoint returned no results for 'Not species'. Attempting autocomplete search.
[Algae Herbarium Portal] All searches failed or returned no results for 'Not species'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

============================================================
  Pterido Portal  (SymbiotaAPI)
  Species:   Dryopteris filix-mas
  Name type: accepted
============================================================
[Pterido Portal] 'api/v2/taxonomy' returned results for 'Dryopteris filix-mas'.
_fetch_query_data
{'tid': 386, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Dryopteris', 'unitInd2': None, 'unitName2': 'filix-mas', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'World Ferns: Checklist of Ferns and Lycophytes of the World (added via CoL API)', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2018-09-21 06:27:10', 'parentTid': 325, 'status': 'accepted', 'classification': [{'tid': 1, 'scientificName': 'Organism', 'author': '', 'rankid': 1}, {'tid': 4, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 7, 'scientificName': 'Tracheophyta', 'author': '', 'rankid': 30}, {'tid': 8, 'scientificName': 'Polypodiopsida', 'author': '', 'rankid': 60}, {'tid': 14, 'scientificName': 'Polypodiales', 'author': '', 'rankid': 100}, {'tid': 25, 'scientificName': 'Dryopteridaceae', 'author': '', 'rankid': 140}, {'tid': 325, 'scientificName': 'Dryopteris', 'author': '', 'rankid': 180}, {'tid': 12090, 'scientificName': 'Polypodiidae', 'author': 'Cronquist, Takht. & W. Zimm.', 'rankid': 70}, {'tid': 19546, 'scientificName': 'Polypodiineae', 'author': 'Bessey', 'rankid': 110}, {'tid': 60888, 'scientificName': 'Dryopteridoideae', 'author': 'Link', 'rankid': 150}, {'tid': 60917, 'scientificName': 'Polypodiophytina', 'author': '', 'rankid': 40}], 'scientificName': 'Dryopteris filix-mas'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>PteridoPortal - Dryopteris filix-mas</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<!-- Responsive viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-0MYL6EXPWT"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-0MYL6EXPWT');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
										<span id="login">
							<form name="loginForm" method="post" action="/portal/profile/index.php">
								<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=386">
								<button class="button button-secondary bottom-breathing-room-rel left-breathing-room-rel" name="loginButton" type="submit">Sign In</button>
							</form>
						</span>
									</nav>
			<div class="top-brand">
				<div class="image-container">
					<img src="/portal/images/layout/PCC_logo_banner.png" alt="Pteridophyte Collections Consortium logo">
				</div>
				<div class="brand-name">
					<h1>Pteridophyte Collections Consortium</h1>
					<h2>Ferns, lycophytes, and their extinct free-sporing relatives</h2>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					<li>
						<a href="#" >
							Search						</a>
						<ul>
							<li>
								<a href="/portal/collections/search/index.php" >Search Collections</a>
							</li>
							<li>
							<a href="/portal/collections/map/index.php" rel="noopener noreferrer">
								Map Search							</a>
							</li>
							<li>
								<a href="/portal/checklists/dynamicmap.php?interface=checklist" >Dynamic Species List</a>
							</li>
							<li>
								<a href="/portal/collections/exsiccati/index.php" >Exsiccati</a>
							</li>
							<li>
								<a href="/portal/taxa/taxonomy/taxonomydynamicdisplay.php" >Taxonomic Explorer</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#" >Images</a>
						<ul>
							<li>
								<a href="/portal/imagelib/index.php" >Media Browser</a>
							</li>
							<li>
							<a href="/portal/imagelib/search.php">
							Media Search						</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/portal/projects/index.php?pid=1" >Species Checklists</a>
						<ul>
							<li>
								<a href="/portal/projects/index.php?pid=1">North America</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/portal/collections/specprocessor/crowdsource/index.php" >Crowdsource</a>
					</li>
					<li>
						<a href="#" >Contacts</a>
						<ul>
							<li>
								<a href="/portal/collections/misc/collprofiles.php" >Partners</a>
							</li>
							<!--
							<li>
								<a href="/portal/misc/contacts.php" >Contacts</a>
							</li>
							-->
						</ul>
					</li>
					<li>
						<a href="#" >About</a>
							<ul>
							<li>
								<a href="/portal/misc/acknowledgements.php" >Acknowledgements</a>
							</li>
														<li>
								<a href="/portal/includes/usagepolicy.php" >Data Use & Citation</a>
							</li>
						</ul>
					</li>
					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>
					<li id="lang-select-li">
						<label for="language-selection">Select Language: </label>
						<select oninput="setLanguage(this)" id="language-selection" name="language-selection">
							<option value="en">English</option>
							<option value="es" >Español</option>
							<option value="fr" >Français</option>
						</select>
					</li>
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Dryopteris filix-mas</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Dryopteris filix-mas</i></span>							<span id="author"></span>
							&nbsp;<a href="index.php?tid=325&amp;clid=0&amp;pid=1&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Dryopteridaceae</div>
						<div id="synonymDiv" title="Synonyms">[<i>Filix filix-mas</i>, <span class="synSpan"><a href="#" onclick="toggle('synSpan')" title="Click here to show more synonyms">more</a></span><span class="synSpan" onclick="toggle('synSpan')" style="display:none"><i>Filix-mas filix-mas</i> Farw., <i>Filix-mas vulgaris</i> Hill ex Farw., <i>Nephrodium filix-mas</i> (L.) Rich., <i>Polypodium umbilicatum</i> Poir., <i>Polystichum filix-mas</i> Roth, <i>Polystichum polysorum</i> Tod.</span>]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../imagelib/imgdetails.php?mediaid=196813');return false;"><img src="https://media01.symbiota.org/media/h_seinet/seinet/Pteridophytes/photos/Dryopteris_filix-mas_020207_1.jpg" title="" alt="Dryopteris filix-mas image" /></a></div><div class="creator">Max Licher</div></div>					</td>
					<td class="desc">
						<div id="desctabs" class="ui-tabs" style="display:none"><ul class="ui-tabs-nav"><li><a href="#tab51">FNA</a></li><li><a href="#tab52">Gleason &amp; Cronquist</a></li><li><a href="#wikitab">Wikipedia</a></li><li><a href="resourcetab.php?tid=386">Resources</a></li></ul><div id="tab51" class="sptab"><div id="descsource" style="float:right;"><a href="http://www.efloras.org/florataxon.aspx?flora_id=1&amp;taxon_id=200004423" target="_blank">James D. Montgomery &lt;BR&gt; Warren H. Wagner Jr. in Flora of North America (vol. 2)</a></div><div style="clear:both;">Leaves  monomorphic, dying back in winter, 28--120 × 10--30 cm.  Petiole  less than 1/4 length of leaf, scaly at least at base; scales scattered, brown, of 2 distinct kinds, 1 broad, 1 hairlike (only this species has 2 distinct forms of scales without intermediates).  Blade  green, ovate-lanceolate, pinnate-pinnatifid to 2-pinnate at base, firm but not leathery, not glandular.  Pinnae  ± in plane of blade, lanceolate; basal pinnae ovate-lanceolate, much reduced, basal pinnules or segments ± same length as adjacent pinnules, basal basiscopic pinnule and basal acroscopic pinnule equal; pinnule margins serrate to lobed.  Sori  midway between midvein and margin of segments.  Indusia  lacking glands. 2 n  = 164. Dense woods and talus slopes on limestone (ne North America); open woods among boulders and talus of granite or igneous rock (Rocky Mountains); 200--2500 m; Greenland; Alta., B.C., Nfld., N.S., Ont., Que., Sask.; Ariz., Calif., Colo., Idaho, Mich., Mont., N.Mex., Nev., Okla., Oreg., Tex., Utah, Wash., Wis., Wyo.; Europe; Asia. The taxonomy of Dryopteris filix-mas is not well understood. In North America, this fern has been considered both an auto- and an allopolyploid and may be composed of at least two closely related taxa. Plants in the northeast and northwest are tetraploid. These differ morphologically and ecologically from a taxon of unknown chromosome number in the southwestern Rocky Mountains. The Rocky Mountain taxon closely resembles the Mexican D . pseudofilix-mas (Fée) Rothmaler. Dryopteris filix-mas also occurs in Europe, and it is known to be an allopolyploid of D . caucasica (A. Braun) Fraser-Jenkins & Corley × oreades Fomin.<p></div></div><div id="tab52" class="sptab"><div id="descsource" style="float:right;"><a href="http://sweetgum.nybg.org/science/world-flora/details.php?irn=5013" target="_blank">Vascular plants of NE US and adjacent Canada</a></div><div style="clear:both;">Rhizome ascending or erect; lvs mostly deciduous, appearing more delicate and finely divided than in spp. 5 and 6; petiole a third as long as the blade, its numerous scales pale, concolored, the broad, toothed ones intermingled with narrow, hair-like ones; blade to 10+ dm, mostly 1.5-3 dm wide; pinnate-pinnatifid with numerous (mostly 20-30 pairs) of pinnae to 15 נ4 cm, the largest pinnae near or a little below the middle and with (15)20+ pairs of segments, many of the segments evidently contracted at the base; larger ultimate segments (0.7-)1-1.5(-2) cm; ramentum  ±plentiful on the rachis and costae, sometimes on the lower surface of the blade, chiefly of narrow, elongate, hair-like scales, that of the rachis sometimes partly of more evident (but still narrow) scales; 2n=164. Thickets, moist woods, and streambanks; circumboreal, extending s. to Vt., n. Mich., ne. Ill., S.D., and Mex.<br/><br/>Gleason, Henry A. & Cronquist, Arthur J. 1991. Manual of vascular plants of northeastern United States and adjacent Canada. lxxv + 910 pp.<br/><br/><b>&copy;The New York Botanical Garden. All rights reserved. Used by permission.</b></div></div><div id="wikitab" class="sptab"><p><a href="https://en.wikipedia.org/wiki/Dryopteris_filix-mas" style="float:right; margin-right: 1rem" target="_blank" class="more-info-btn">Wikipedia Source Page</a></p><h3>Summary</h3><p>Dryopteris filix-mas, the male fern, is a common fern of the temperate Northern Hemisphere, native to much of Europe, Asia, and North America. It favours damp shaded areas in the understory of woodlands, but also shady places on hedge-banks, and rocks, and screes. Near the northern limit of its distribution it prefers sunny, well-drained sites. It is much less abundant in North America than in Europe.</p><h3>Description</h3><p>19th century illustration
<p>The semi-evergreen leaves have an upright habit and reach a maximum length of 150&#160;cm (59&#160;in), with a single crown on each rootstock. The bipinnate leaves consist of 20–35 pinnae on each side of the rachis. The leaves taper at both ends, with the basal pinnae about half the length of the middle pinnae. The pinules are rather blunt and equally lobed all around. The stalks are covered with orange-brown scales. On the abaxial surface of the mature blade five or six sori develop in two rows. When the spores ripen in August to November, the indusium starts to shrivel, leading to the release of the spores.
</p><p>This species hybridises easily with Dryopteris affinis (scaly male fern) and Dryopteris oreades (mountain male fern).
</p></p><h3>Names</h3><p><p>The plant is sometimes referred to in ancient literature as worm fern, reflecting its former use against tapeworm.
</p>
 Unrolling leaf of a Dryopteris filix-mas.
<p>Its specific epithet filix-mas means "male fern" (filix "fern", mas "male"), as the plant was thought to be the male version of the common lady fern Athyrium filix-femina. being robust in appearance and vigorous in growth.
</p><p>The Finnish name kivikkoalvejuuri refers to the anti-cestoda (tapeworm) medical use it has had (see Culture section), as alve is an old word for cestoda.
</p></p></div></div>					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="img-div" style="height:300px;overflow:hidden;">

============================================================
  Pterido Portal  (SymbiotaAPI)
  Species:   Nephrodium filix-mas
  Name type: synonym  (synonym of: Dryopteris filix-mas)
============================================================
[Pterido Portal] 'api/v2/taxonomy' returned results for 'Nephrodium filix-mas'.
_fetch_query_data
{'tid': 45458, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Nephrodium', 'unitInd2': None, 'unitName2': 'filix-mas', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(L.) Rich.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'World Ferns: Checklist of Ferns and Lycophytes of the World (added via CoL API)', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2018-12-13 15:38:46', 'parentTid': 3653, 'status': 'synonym', 'accepted': {'tid': 386, 'scientificName': 'Dryopteris filix-mas', 'scientificNameAuthorship': '', 'taxonomicSource': None, 'unacceptabilityReason': None, 'taxonRemarks': None}, 'classification': [{'tid': 1, 'scientificName': 'Organism', 'author': '', 'rankid': 1}, {'tid': 4, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 7, 'scientificName': 'Tracheophyta', 'author': '', 'rankid': 30}, {'tid': 8, 'scientificName': 'Polypodiopsida', 'author': '', 'rankid': 60}, {'tid': 172, 'scientificName': 'Cyatheales', 'author': '', 'rankid': 100}, {'tid': 173, 'scientificName': 'Cyatheaceae', 'author': '', 'rankid': 140}, {'tid': 3653, 'scientificName': 'Nephrodium', 'author': '', 'rankid': 180}, {'tid': 12090, 'scientificName': 'Polypodiidae', 'author': 'Cronquist, Takht. & W. Zimm.', 'rankid': 70}, {'tid': 60917, 'scientificName': 'Polypodiophytina', 'author': '', 'rankid': 40}], 'scientificName': 'Nephrodium filix-mas'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>PteridoPortal - Dryopteris filix-mas</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<!-- Responsive viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-0MYL6EXPWT"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-0MYL6EXPWT');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
										<span id="login">
							<form name="loginForm" method="post" action="/portal/profile/index.php">
								<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=386">
								<button class="button button-secondary bottom-breathing-room-rel left-breathing-room-rel" name="loginButton" type="submit">Sign In</button>
							</form>
						</span>
									</nav>
			<div class="top-brand">
				<div class="image-container">
					<img src="/portal/images/layout/PCC_logo_banner.png" alt="Pteridophyte Collections Consortium logo">
				</div>
				<div class="brand-name">
					<h1>Pteridophyte Collections Consortium</h1>
					<h2>Ferns, lycophytes, and their extinct free-sporing relatives</h2>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					<li>
						<a href="#" >
							Search						</a>
						<ul>
							<li>
								<a href="/portal/collections/search/index.php" >Search Collections</a>
							</li>
							<li>
							<a href="/portal/collections/map/index.php" rel="noopener noreferrer">
								Map Search							</a>
							</li>
							<li>
								<a href="/portal/checklists/dynamicmap.php?interface=checklist" >Dynamic Species List</a>
							</li>
							<li>
								<a href="/portal/collections/exsiccati/index.php" >Exsiccati</a>
							</li>
							<li>
								<a href="/portal/taxa/taxonomy/taxonomydynamicdisplay.php" >Taxonomic Explorer</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#" >Images</a>
						<ul>
							<li>
								<a href="/portal/imagelib/index.php" >Media Browser</a>
							</li>
							<li>
							<a href="/portal/imagelib/search.php">
							Media Search						</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/portal/projects/index.php?pid=1" >Species Checklists</a>
						<ul>
							<li>
								<a href="/portal/projects/index.php?pid=1">North America</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/portal/collections/specprocessor/crowdsource/index.php" >Crowdsource</a>
					</li>
					<li>
						<a href="#" >Contacts</a>
						<ul>
							<li>
								<a href="/portal/collections/misc/collprofiles.php" >Partners</a>
							</li>
							<!--
							<li>
								<a href="/portal/misc/contacts.php" >Contacts</a>
							</li>
							-->
						</ul>
					</li>
					<li>
						<a href="#" >About</a>
							<ul>
							<li>
								<a href="/portal/misc/acknowledgements.php" >Acknowledgements</a>
							</li>
														<li>
								<a href="/portal/includes/usagepolicy.php" >Data Use & Citation</a>
							</li>
						</ul>
					</li>
					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>
					<li id="lang-select-li">
						<label for="language-selection">Select Language: </label>
						<select oninput="setLanguage(this)" id="language-selection" name="language-selection">
							<option value="en">English</option>
							<option value="es" >Español</option>
							<option value="fr" >Français</option>
						</select>
					</li>
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Dryopteris filix-mas</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Dryopteris filix-mas</i></span>							<span id="author"></span>
							&nbsp;<a href="index.php?tid=325&amp;clid=0&amp;pid=1&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Dryopteridaceae</div>
						<div id="synonymDiv" title="Synonyms">[<i>Filix filix-mas</i>, <span class="synSpan"><a href="#" onclick="toggle('synSpan')" title="Click here to show more synonyms">more</a></span><span class="synSpan" onclick="toggle('synSpan')" style="display:none"><i>Filix-mas filix-mas</i> Farw., <i>Filix-mas vulgaris</i> Hill ex Farw., <i>Nephrodium filix-mas</i> (L.) Rich., <i>Polypodium umbilicatum</i> Poir., <i>Polystichum filix-mas</i> Roth, <i>Polystichum polysorum</i> Tod.</span>]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../imagelib/imgdetails.php?mediaid=196813');return false;"><img src="https://media01.symbiota.org/media/h_seinet/seinet/Pteridophytes/photos/Dryopteris_filix-mas_020207_1.jpg" title="" alt="Dryopteris filix-mas image" /></a></div><div class="creator">Max Licher</div></div>					</td>
					<td class="desc">
						<div id="desctabs" class="ui-tabs" style="display:none"><ul class="ui-tabs-nav"><li><a href="#tab51">FNA</a></li><li><a href="#tab52">Gleason &amp; Cronquist</a></li><li><a href="resourcetab.php?tid=386">Resources</a></li></ul><div id="tab51" class="sptab"><div id="descsource" style="float:right;"><a href="http://www.efloras.org/florataxon.aspx?flora_id=1&amp;taxon_id=200004423" target="_blank">James D. Montgomery &lt;BR&gt; Warren H. Wagner Jr. in Flora of North America (vol. 2)</a></div><div style="clear:both;">Leaves  monomorphic, dying back in winter, 28--120 × 10--30 cm.  Petiole  less than 1/4 length of leaf, scaly at least at base; scales scattered, brown, of 2 distinct kinds, 1 broad, 1 hairlike (only this species has 2 distinct forms of scales without intermediates).  Blade  green, ovate-lanceolate, pinnate-pinnatifid to 2-pinnate at base, firm but not leathery, not glandular.  Pinnae  ± in plane of blade, lanceolate; basal pinnae ovate-lanceolate, much reduced, basal pinnules or segments ± same length as adjacent pinnules, basal basiscopic pinnule and basal acroscopic pinnule equal; pinnule margins serrate to lobed.  Sori  midway between midvein and margin of segments.  Indusia  lacking glands. 2 n  = 164. Dense woods and talus slopes on limestone (ne North America); open woods among boulders and talus of granite or igneous rock (Rocky Mountains); 200--2500 m; Greenland; Alta., B.C., Nfld., N.S., Ont., Que., Sask.; Ariz., Calif., Colo., Idaho, Mich., Mont., N.Mex., Nev., Okla., Oreg., Tex., Utah, Wash., Wis., Wyo.; Europe; Asia. The taxonomy of Dryopteris filix-mas is not well understood. In North America, this fern has been considered both an auto- and an allopolyploid and may be composed of at least two closely related taxa. Plants in the northeast and northwest are tetraploid. These differ morphologically and ecologically from a taxon of unknown chromosome number in the southwestern Rocky Mountains. The Rocky Mountain taxon closely resembles the Mexican D . pseudofilix-mas (Fée) Rothmaler. Dryopteris filix-mas also occurs in Europe, and it is known to be an allopolyploid of D . caucasica (A. Braun) Fraser-Jenkins & Corley × oreades Fomin.<p></div></div><div id="tab52" class="sptab"><div id="descsource" style="float:right;"><a href="http://sweetgum.nybg.org/science/world-flora/details.php?irn=5013" target="_blank">Vascular plants of NE US and adjacent Canada</a></div><div style="clear:both;">Rhizome ascending or erect; lvs mostly deciduous, appearing more delicate and finely divided than in spp. 5 and 6; petiole a third as long as the blade, its numerous scales pale, concolored, the broad, toothed ones intermingled with narrow, hair-like ones; blade to 10+ dm, mostly 1.5-3 dm wide; pinnate-pinnatifid with numerous (mostly 20-30 pairs) of pinnae to 15 נ4 cm, the largest pinnae near or a little below the middle and with (15)20+ pairs of segments, many of the segments evidently contracted at the base; larger ultimate segments (0.7-)1-1.5(-2) cm; ramentum  ±plentiful on the rachis and costae, sometimes on the lower surface of the blade, chiefly of narrow, elongate, hair-like scales, that of the rachis sometimes partly of more evident (but still narrow) scales; 2n=164. Thickets, moist woods, and streambanks; circumboreal, extending s. to Vt., n. Mich., ne. Ill., S.D., and Mex.<br/><br/>Gleason, Henry A. & Cronquist, Arthur J. 1991. Manual of vascular plants of northeastern United States and adjacent Canada. lxxv + 910 pp.<br/><br/><b>&copy;The New York Botanical Garden. All rights reserved. Used by permission.</b></div></div></div>					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="img-div" style="height:300px;overflow:hidden;">

============================================================
  Pterido Portal  (SymbiotaAPI)
  Species:   Not species
  Name type: not species
============================================================
[Pterido Portal] Search endpoint returned no results for 'Not species'. Attempting autocomplete search.
[Pterido Portal] All searches failed or returned no results for 'Not species'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

============================================================
  CNH  (SymbiotaAPI)
  Species:   Impatiens capensis
  Name type: accepted
============================================================
[CNH] 'api/v2/taxonomy' returned results for 'Impatiens capensis'.
_fetch_query_data
{'tid': 824846, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Impatiens', 'unitInd2': None, 'unitName2': 'capensis', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'Meerb.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2011-04-14 02:15:53', 'parentTid': 812651, 'status': 'accepted', 'classification': [{'tid': 9417, 'scientificName': 'Charophyta', 'author': '', 'rankid': 30}, {'tid': 23443, 'scientificName': 'Ericales', 'author': 'Bercht. & J.Presl', 'rankid': 100}, {'tid': 29180, 'scientificName': 'Balsaminaceae', 'author': 'A. Rich.', 'rankid': 140}, {'tid': 811021, 'scientificName': 'Streptophytina', 'author': '', 'rankid': 40}, {'tid': 811022, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 811023, 'scientificName': 'Equisetopsida', 'author': 'C.Agardh', 'rankid': 60}, {'tid': 811031, 'scientificName': 'Magnoliidae', 'author': 'Novák ex Takht.', 'rankid': 70}, {'tid': 812651, 'scientificName': 'Impatiens', 'author': 'L.', 'rankid': 180}], 'scientificName': 'Impatiens capensis'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>CNH Portal - Impatiens capensis</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-83X7YGFEFJ"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-83X7YGFEFJ');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="login">
						<form name="loginForm" method="post" action="/portal/profile/index.php">
							<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=824846">
							<button class="button button-secondary bottom-breathing-room-rel left-breathing-room-rel" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
			<div class="top-brand">
				<!--
				<a href="/portal">
					<div class="image-container">
						<img src="/portal/images/layout/CNH_logo.png" alt="Consortium of Northeastern Herbaria logo">
					</div>
				</a>
				-->
				<div class="brand-name">
					<h1>CNH</h1>
					<h2>Consortium of Northeastern Herbaria</h2>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					<li>
						<a href="#">Search</a>
						<ul>
							<li>
								<a href="/portal/collections/search/index.php">Text-based Search</a>
							</li>
							<li>
								<a href="/portal/collections/map/index.php" rel="noopener noreferrer">Map Search</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/portal/includes/about.php">About</a>
						<ul>
							<li>
								<a href="/portal/includes/about.php">About the CNH</a>
							</li>
							<li>
								<a href="/portal/includes/governance.php">Governance</a>
							</li>
							<li>
								<a href="/portal/collections/misc/collprofiles.php">Collections</a>
							</li>
							<li>
								<a href="/portal/includes/meetings.php">Meetings</a>
							</li>
							<li>
								<a href="/portal/includes/membership.php">Membership</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/portal/checklists/index.php">Species Lists</a>
					</li>
					<!--
					<li>
						<a href="/portal/collections/specprocessor/crowdsource/central.php">Crowdsourcing</a>
					</li>
					-->
					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Impatiens capensis</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Impatiens capensis</i></span>							<span id="author">Meerb.</span>
							&nbsp;<a href="index.php?tid=812651&amp;clid=0&amp;pid=1&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Balsaminaceae</div>
						<div id="synonymDiv" title="Synonyms">[<i>Impatiens biflora</i> Walter, <span class="synSpan"><a href="#" onclick="toggle('synSpan')" title="Click here to show more synonyms">more</a></span><span class="synSpan" onclick="toggle('synSpan')" style="display:none"><i>Impatiens fulva</i> Nutt., <i>Impatiens noli-tangere ssp. biflora</i> (Walter) Hultén, <i>Impatiens nortonii</i> Rydb.</span>]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../collections/individual/index.php?occid=3481758');return false;"><img src="https://digitallibrary.vassar.edu/_flysystem/fedora/ENHP000028_0.jp2" title="" alt="Impatiens capensis image" /></a></div><div class="creator"></div></div>					</td>
					<td class="desc">
						<div id="desctabs" class="ui-tabs" style="display:none"><ul class="ui-tabs-nav"><li><a href="resourcetab.php?tid=824846">Resources</a></li></ul></div>					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="img-div" style="height:300px;overflow:hidden;">

============================================================
  CNH  (SymbiotaAPI)
  Species:   Impatiens biflora
  Name type: synonym  (synonym of: Impatiens capensis)
============================================================
[CNH] 'api/v2/taxonomy' returned results for 'Impatiens biflora'.
_fetch_query_data
{'tid': 853296, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Impatiens', 'unitInd2': None, 'unitName2': 'biflora', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'Walter', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2011-04-14 15:07:47', 'parentTid': 812651, 'status': 'synonym', 'accepted': {'tid': 824846, 'scientificName': 'Impatiens capensis', 'scientificNameAuthorship': 'Meerb.', 'taxonomicSource': None, 'unacceptabilityReason': None, 'taxonRemarks': None}, 'classification': [{'tid': 9417, 'scientificName': 'Charophyta', 'author': '', 'rankid': 30}, {'tid': 23443, 'scientificName': 'Ericales', 'author': 'Bercht. & J.Presl', 'rankid': 100}, {'tid': 29180, 'scientificName': 'Balsaminaceae', 'author': 'A. Rich.', 'rankid': 140}, {'tid': 811021, 'scientificName': 'Streptophytina', 'author': '', 'rankid': 40}, {'tid': 811022, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 811023, 'scientificName': 'Equisetopsida', 'author': 'C.Agardh', 'rankid': 60}, {'tid': 811031, 'scientificName': 'Magnoliidae', 'author': 'Novák ex Takht.', 'rankid': 70}, {'tid': 812651, 'scientificName': 'Impatiens', 'author': 'L.', 'rankid': 180}], 'scientificName': 'Impatiens biflora'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>CNH Portal - Impatiens capensis</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-83X7YGFEFJ"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-83X7YGFEFJ');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="login">
						<form name="loginForm" method="post" action="/portal/profile/index.php">
							<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=824846">
							<button class="button button-secondary bottom-breathing-room-rel left-breathing-room-rel" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
			<div class="top-brand">
				<!--
				<a href="/portal">
					<div class="image-container">
						<img src="/portal/images/layout/CNH_logo.png" alt="Consortium of Northeastern Herbaria logo">
					</div>
				</a>
				-->
				<div class="brand-name">
					<h1>CNH</h1>
					<h2>Consortium of Northeastern Herbaria</h2>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					<li>
						<a href="#">Search</a>
						<ul>
							<li>
								<a href="/portal/collections/search/index.php">Text-based Search</a>
							</li>
							<li>
								<a href="/portal/collections/map/index.php" rel="noopener noreferrer">Map Search</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/portal/includes/about.php">About</a>
						<ul>
							<li>
								<a href="/portal/includes/about.php">About the CNH</a>
							</li>
							<li>
								<a href="/portal/includes/governance.php">Governance</a>
							</li>
							<li>
								<a href="/portal/collections/misc/collprofiles.php">Collections</a>
							</li>
							<li>
								<a href="/portal/includes/meetings.php">Meetings</a>
							</li>
							<li>
								<a href="/portal/includes/membership.php">Membership</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/portal/checklists/index.php">Species Lists</a>
					</li>
					<!--
					<li>
						<a href="/portal/collections/specprocessor/crowdsource/central.php">Crowdsourcing</a>
					</li>
					-->
					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Impatiens capensis</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Impatiens capensis</i></span>							<span id="author">Meerb.</span>
							&nbsp;<a href="index.php?tid=812651&amp;clid=0&amp;pid=1&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Balsaminaceae</div>
						<div id="synonymDiv" title="Synonyms">[<i>Impatiens biflora</i> Walter, <span class="synSpan"><a href="#" onclick="toggle('synSpan')" title="Click here to show more synonyms">more</a></span><span class="synSpan" onclick="toggle('synSpan')" style="display:none"><i>Impatiens fulva</i> Nutt., <i>Impatiens noli-tangere ssp. biflora</i> (Walter) Hultén, <i>Impatiens nortonii</i> Rydb.</span>]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../collections/individual/index.php?occid=3481758');return false;"><img src="https://digitallibrary.vassar.edu/_flysystem/fedora/ENHP000028_0.jp2" title="" alt="Impatiens capensis image" /></a></div><div class="creator"></div></div>					</td>
					<td class="desc">
						<div id="desctabs" class="ui-tabs" style="display:none"><ul class="ui-tabs-nav"><li><a href="resourcetab.php?tid=824846">Resources</a></li></ul></div>					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="img-div" style="height:300px;overflow:hidden;">

============================================================
  CNH  (SymbiotaAPI)
  Species:   Not species
  Name type: not species
============================================================
[CNH] Search endpoint returned no results for 'Not species'. Attempting autocomplete search.
[CNH] All searches failed or returned no results for 'Not species'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

============================================================
  Mid-Atlantic Herbaria Consortium  (SymbiotaAPI)
  Species:   Quercus rubra
  Name type: accepted
============================================================
[Mid-Atlantic Herbaria Consortium] 'api/v2/taxonomy' returned results for 'Quercus rubra'.
_fetch_query_data
{'tid': 46960, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Quercus', 'unitInd2': None, 'unitName2': 'rubra', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'L.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'Tropicos', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2008-09-28 20:57:25', 'parentTid': 4358, 'status': 'accepted', 'classification': [{'tid': 4358, 'scientificName': 'Quercus', 'author': 'L.', 'rankid': 180}, {'tid': 5438, 'scientificName': 'Fagaceae', 'author': '', 'rankid': 140}, {'tid': 5531, 'scientificName': 'Fagales', 'author': '', 'rankid': 100}, {'tid': 5570, 'scientificName': 'Magnoliophyta', 'author': '', 'rankid': 30}, {'tid': 5571, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 170361, 'scientificName': 'Tracheophyta', 'author': '', 'rankid': 20}, {'tid': 170633, 'scientificName': 'Spermatophyta', 'author': '', 'rankid': 20}, {'tid': 170692, 'scientificName': 'Eudicots', 'author': '', 'rankid': 45}, {'tid': 170726, 'scientificName': 'Core Eudicots', 'author': '', 'rankid': 65}, {'tid': 170757, 'scientificName': 'Rosids', 'author': '', 'rankid': 75}, {'tid': 170764, 'scientificName': 'Fabids', 'author': '', 'rankid': 75}], 'scientificName': 'Quercus rubra'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Mid-Atlantic Herbaria - Quercus rubra</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-0KFHNVS8T9"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-0KFHNVS8T9');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="login">
						<form name="loginForm" method="post" action="/portal/profile/index.php">
							<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=46960">
							<button class="button button-secondary" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
			<div class="top-brand">
				<!--
					<div class="image-container">
						<!--
						<img src="/portal/images/layout/logo_symbiota.png" alt="Symbiota logo">
					</div>
				-->
				<div class="brand-name">
					<h1>MID-ATLANTIC HERBARIA CONSORTIUM</h1>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					<li>
						<a href="#">Search</a>
						<ul>
							<li>
								<a href="/portal/collections/search/index.php">Search Collections</a>
							</li>
							<li>
								<a href="/portal/collections/map/mapinterface.php" target="_blank">Map Search</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Images</a>
						<ul>
							<li>
								<a href="/portal/imagelib/index.php">Image Browser</a>
							</li>
							<li>
							<a href="/portal/imagelib/search.php">Search Images</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Mid-Atlantic Floras</a>
						<ul>
							<li>
								<a href="/portal/projects/index.php?pid=117">Delaware</a>
							</li>
							<li>
								<a href="/portal/projects/index.php?pid=118">Maryland</a>
							</li>
							<li>
								<a href="/portal/projects/index.php?pid=119">New Jersey</a>
							</li>
							<li>
								<a href="/portal/projects/index.php?pid=120">New York</a>
							</li>
							<li>
								<a href="/portal/projects/index.php?pid=121">Pennsylvania</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/portal/projects/index.php?pid=115#">NYC EcoFlora</a>
						<ul>
							<li>
								<a href="/portal/checklists/checklist.php?cl=5058&pid=115">Vascular Checklist</a>
							</li>
							<li>
								<a href="/portal/ident/key.php?cl=4905&proj=115&taxon=All+Species">Identification Key</a>
							</li>
							<li>
								<a href="/portal/checklists/checklist.php?cl=4423&pid=115">Central Park</a>
							</li>
							<li>
								<a href="/portal/projects/index.php?pid=115">Additional Local Lists</a>
							</li>
							<li>
								<a href="https://www.nybg.org/science-project/new-york-city-ecoflora/">More Details About Project</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#" >Interactive Tools</a>
						<ul>
							<li>
								<a href="/portal/checklists/dynamicmap.php?interface=checklist" >Dynamic Checklist</a>
							</li>
							<li>
								<a href="/portal/checklists/dynamicmap.php?interface=key" >Dynamic Key</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/portal/collections/specprocessor/crowdsource/central.php">
							Crowdsource Data Entry
						</a>
					</li>
					<li>
						<a href="#">Other SEINet Portals</a>
						<ul>
							<li>
								<a href="http://swbiodiversity.org/">Arizona-New Mexico Chapter</a>
							</li>
							<li>
								<a href="https://midwestherbaria.org/">Consortium of Midwest Herbaria</a>
							</li>
							<li>
								<a href="https://www.soroherbaria.org/">Consortium of Southern Rocky Mountain Herbaria</a>
							</li>
							<li>
								<a href="https://intermountainbiota.org/">Intermountain Region Herbaria Network (IRHN)</a>
							</li>
							<li>
								<a href="https://nansh.org/">North American Network of Small Herbaria (NANSH)</a>
							</li>
							<li>
								<a href="https://ngpherbaria.org/">Northern Great Plains Herbaria</a>
							</li>
							<li>
								<a href="http://madrean.org/symbflora/projects/index.php?proj=74">Madrean Archipelago Biodiversity Assessment (MABA) Flora</a>
							</li>
							<li>
								<a href="https://herbanwmex.net/">Red de Herbarios Mexicanos</a>
							</li>
							<li>
								<a href="https://sernecportal.org/">SERNEC - Southeastern USA</a>
							</li>
							<li>
								<a href="https://portal.torcherbaria.org/">Texas Oklahoma Regional Consortium of Herbaria (TORCH)</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/portal/includes/usagepolicy.php">
							Data Use						</a>
					</li>
					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>
					<!--
					<li id="lang-select-li">
						<label for="language-selection">Select Language: </label>
						<select oninput="setLanguage(this)" id="language-selection" name="language-selection">
							<option value="en">English</option>
							<option value="es" >Español</option>
							<option value="fr" >Français</option>
						</select>
					</li>
					-->
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Quercus rubra</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Quercus rubra</i></span>							<span id="author">L.</span>
							&nbsp;<a href="index.php?tid=4358&amp;clid=0&amp;pid=1&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Fagaceae</div>
													<div id="vernacularDiv">
								Northern Red Oak							</div>
							<div id="synonymDiv" title="Synonyms">[<i>Quercus borealis</i> Michx. f., <span class="synSpan"><a href="#" onclick="toggle('synSpan')" title="Click here to show more synonyms">more</a></span><span class="synSpan" onclick="toggle('synSpan')" style="display:none"><i>Quercus borealis var. flabellata</i> , <i>Quercus borealis var. maxima</i> (Marsh.) Ashe, <i>Quercus maxima</i> (Marsh.) Ashe, <i>Quercus rubra var. maxima</i> Marshall, <i>Quercus rubra var. ramosissima</i> Marshall</span>]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../imagelib/imgdetails.php?mediaid=15820054');return false;"><img src="https://media01.symbiota.org/media/seinet/midwest/Fagaceae/202003/Quercus_rubra_ROTHROCK_0494_1585004563.jpg" title="" alt="Quercus rubra image" /></a></div><div class="creator">Paul Rothrock</div></div>					</td>
					<td class="desc">

============================================================
  Mid-Atlantic Herbaria Consortium  (SymbiotaAPI)
  Species:   Quercus maxima
  Name type: synonym  (synonym of: Quercus rubra)
============================================================
[Mid-Atlantic Herbaria Consortium] 'api/v2/taxonomy' returned results for 'Quercus maxima'.
_fetch_query_data
{'tid': 97586, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Quercus', 'unitInd2': None, 'unitName2': 'maxima', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(Marsh.) Ashe', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2008-11-27 01:08:47', 'parentTid': 4358, 'status': 'synonym', 'accepted': {'tid': 46960, 'scientificName': 'Quercus rubra', 'scientificNameAuthorship': 'L.', 'taxonomicSource': None, 'unacceptabilityReason': None, 'taxonRemarks': None}, 'classification': [{'tid': 4358, 'scientificName': 'Quercus', 'author': 'L.', 'rankid': 180}, {'tid': 5438, 'scientificName': 'Fagaceae', 'author': '', 'rankid': 140}, {'tid': 5531, 'scientificName': 'Fagales', 'author': '', 'rankid': 100}, {'tid': 5570, 'scientificName': 'Magnoliophyta', 'author': '', 'rankid': 30}, {'tid': 5571, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 170361, 'scientificName': 'Tracheophyta', 'author': '', 'rankid': 20}, {'tid': 170633, 'scientificName': 'Spermatophyta', 'author': '', 'rankid': 20}, {'tid': 170692, 'scientificName': 'Eudicots', 'author': '', 'rankid': 45}, {'tid': 170726, 'scientificName': 'Core Eudicots', 'author': '', 'rankid': 65}, {'tid': 170757, 'scientificName': 'Rosids', 'author': '', 'rankid': 75}, {'tid': 170764, 'scientificName': 'Fabids', 'author': '', 'rankid': 75}], 'scientificName': 'Quercus maxima'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Mid-Atlantic Herbaria - Quercus rubra</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-0KFHNVS8T9"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-0KFHNVS8T9');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="login">
						<form name="loginForm" method="post" action="/portal/profile/index.php">
							<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=46960">
							<button class="button button-secondary" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
			<div class="top-brand">
				<!--
					<div class="image-container">
						<!--
						<img src="/portal/images/layout/logo_symbiota.png" alt="Symbiota logo">
					</div>
				-->
				<div class="brand-name">
					<h1>MID-ATLANTIC HERBARIA CONSORTIUM</h1>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					<li>
						<a href="#">Search</a>
						<ul>
							<li>
								<a href="/portal/collections/search/index.php">Search Collections</a>
							</li>
							<li>
								<a href="/portal/collections/map/mapinterface.php" target="_blank">Map Search</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Images</a>
						<ul>
							<li>
								<a href="/portal/imagelib/index.php">Image Browser</a>
							</li>
							<li>
							<a href="/portal/imagelib/search.php">Search Images</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Mid-Atlantic Floras</a>
						<ul>
							<li>
								<a href="/portal/projects/index.php?pid=117">Delaware</a>
							</li>
							<li>
								<a href="/portal/projects/index.php?pid=118">Maryland</a>
							</li>
							<li>
								<a href="/portal/projects/index.php?pid=119">New Jersey</a>
							</li>
							<li>
								<a href="/portal/projects/index.php?pid=120">New York</a>
							</li>
							<li>
								<a href="/portal/projects/index.php?pid=121">Pennsylvania</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/portal/projects/index.php?pid=115#">NYC EcoFlora</a>
						<ul>
							<li>
								<a href="/portal/checklists/checklist.php?cl=5058&pid=115">Vascular Checklist</a>
							</li>
							<li>
								<a href="/portal/ident/key.php?cl=4905&proj=115&taxon=All+Species">Identification Key</a>
							</li>
							<li>
								<a href="/portal/checklists/checklist.php?cl=4423&pid=115">Central Park</a>
							</li>
							<li>
								<a href="/portal/projects/index.php?pid=115">Additional Local Lists</a>
							</li>
							<li>
								<a href="https://www.nybg.org/science-project/new-york-city-ecoflora/">More Details About Project</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#" >Interactive Tools</a>
						<ul>
							<li>
								<a href="/portal/checklists/dynamicmap.php?interface=checklist" >Dynamic Checklist</a>
							</li>
							<li>
								<a href="/portal/checklists/dynamicmap.php?interface=key" >Dynamic Key</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/portal/collections/specprocessor/crowdsource/central.php">
							Crowdsource Data Entry
						</a>
					</li>
					<li>
						<a href="#">Other SEINet Portals</a>
						<ul>
							<li>
								<a href="http://swbiodiversity.org/">Arizona-New Mexico Chapter</a>
							</li>
							<li>
								<a href="https://midwestherbaria.org/">Consortium of Midwest Herbaria</a>
							</li>
							<li>
								<a href="https://www.soroherbaria.org/">Consortium of Southern Rocky Mountain Herbaria</a>
							</li>
							<li>
								<a href="https://intermountainbiota.org/">Intermountain Region Herbaria Network (IRHN)</a>
							</li>
							<li>
								<a href="https://nansh.org/">North American Network of Small Herbaria (NANSH)</a>
							</li>
							<li>
								<a href="https://ngpherbaria.org/">Northern Great Plains Herbaria</a>
							</li>
							<li>
								<a href="http://madrean.org/symbflora/projects/index.php?proj=74">Madrean Archipelago Biodiversity Assessment (MABA) Flora</a>
							</li>
							<li>
								<a href="https://herbanwmex.net/">Red de Herbarios Mexicanos</a>
							</li>
							<li>
								<a href="https://sernecportal.org/">SERNEC - Southeastern USA</a>
							</li>
							<li>
								<a href="https://portal.torcherbaria.org/">Texas Oklahoma Regional Consortium of Herbaria (TORCH)</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/portal/includes/usagepolicy.php">
							Data Use						</a>
					</li>
					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>
					<!--
					<li id="lang-select-li">
						<label for="language-selection">Select Language: </label>
						<select oninput="setLanguage(this)" id="language-selection" name="language-selection">
							<option value="en">English</option>
							<option value="es" >Español</option>
							<option value="fr" >Français</option>
						</select>
					</li>
					-->
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Quercus rubra</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Quercus rubra</i></span>							<span id="author">L.</span>
							&nbsp;<a href="index.php?tid=4358&amp;clid=0&amp;pid=1&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Fagaceae</div>
													<div id="vernacularDiv">
								Northern Red Oak							</div>
							<div id="synonymDiv" title="Synonyms">[<i>Quercus borealis</i> Michx. f., <span class="synSpan"><a href="#" onclick="toggle('synSpan')" title="Click here to show more synonyms">more</a></span><span class="synSpan" onclick="toggle('synSpan')" style="display:none"><i>Quercus borealis var. flabellata</i> , <i>Quercus borealis var. maxima</i> (Marsh.) Ashe, <i>Quercus maxima</i> (Marsh.) Ashe, <i>Quercus rubra var. maxima</i> Marshall, <i>Quercus rubra var. ramosissima</i> Marshall</span>]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../imagelib/imgdetails.php?mediaid=15820054');return false;"><img src="https://media01.symbiota.org/media/seinet/midwest/Fagaceae/202003/Quercus_rubra_ROTHROCK_0494_1585004563.jpg" title="" alt="Quercus rubra image" /></a></div><div class="creator">Paul Rothrock</div></div>					</td>
					<td class="desc">

============================================================
  Mid-Atlantic Herbaria Consortium  (SymbiotaAPI)
  Species:   Not species
  Name type: not species
============================================================
[Mid-Atlantic Herbaria Consortium] Search endpoint returned no results for 'Not species'. Attempting autocomplete search.
[Mid-Atlantic Herbaria Consortium] All searches failed or returned no results for 'Not species'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

============================================================
  swbiodiversity  (SymbiotaAPI)
  Species:   Larrea tridentata
  Name type: accepted
============================================================
[swbiodiversity] 'api/v2/taxonomy' returned results for 'Larrea tridentata'.
_fetch_query_data
{'tid': 2671, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Larrea', 'unitInd2': None, 'unitName2': 'tridentata', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(Sessé & Moc. ex DC.) Coville', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '1996-06-13 20:51:08', 'parentTid': 4965, 'status': 'accepted', 'classification': [{'tid': 4965, 'scientificName': 'Larrea', 'author': 'Cav.', 'rankid': 180}, {'tid': 5327, 'scientificName': 'Zygophyllaceae', 'author': '', 'rankid': 140}, {'tid': 5570, 'scientificName': 'Magnoliophyta', 'author': '', 'rankid': 30}, {'tid': 5571, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 170361, 'scientificName': 'Tracheophyta', 'author': '', 'rankid': 20}, {'tid': 170633, 'scientificName': 'Spermatophyta', 'author': '', 'rankid': 20}, {'tid': 170692, 'scientificName': 'Eudicots', 'author': '', 'rankid': 45}, {'tid': 170726, 'scientificName': 'Core Eudicots', 'author': '', 'rankid': 65}, {'tid': 170757, 'scientificName': 'Rosids', 'author': '', 'rankid': 75}, {'tid': 170764, 'scientificName': 'Fabids', 'author': '', 'rankid': 75}, {'tid': 170780, 'scientificName': 'Zygophyllales', 'author': '', 'rankid': 100}], 'scientificName': 'Larrea tridentata'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>SEINet - AZ/NM Node - Larrea tridentata</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/seinet/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/seinet/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/seinet/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<!-- Responsive viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/seinet/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/seinet/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/seinet/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/seinet/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

<script src="/seinet/js/symb/lang.js" type="text/javascript"></script>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-B5PK9G20TY"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-B5PK9G20TY');
	</script>
		<script src="/seinet/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/seinet/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="login">
						<form name="loginForm" method="post" action="/seinet/profile/index.php">
							<input name="refurl" type="hidden" value="/seinet/taxa/index.php?tid=2671">
							<button class="button button-secondary" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
			<div class="top-brand">
				<!--
				<a href="/seinet">
					<div class="image-container">
						<img src="/seinet/images/layout/logo_symbiota.png" alt="Symbiota logo">
					</div>
				</a>
				-->
				<div class="brand-name">
					<h1>SEINet</h1>
					<h2>Arizona - New Mexico Chapter</h2>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/seinet/index.php">
							Home						</a>
					</li>
					<li>
						<a href="#">Specimen Search</a>
						<ul>
							<li>
								<a href="/seinet/collections/search/index.php">Search Collections</a>
							</li>
							<li>
								<a href="/seinet/collections/map/index.php">Map Search</a>
							</li>
							<li>
								<a href="/seinet/collections/exsiccati/index.php">Exsiccati Search</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Images</a>
						<ul>
							<li>
								<a href="/seinet/imagelib/index.php">Image Browser</a>
							</li>
							<li>
								<a href="/seinet/imagelib/search.php">Search Images</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/seinet/projects/index.php">Flora Projects</a>
						<ul>
							<li>
								<a href="/seinet/projects/index.php?pid=1">Arizona</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=2">New Mexico</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=21">Colorado Plateau</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=75">Plant Atlas of Arizona (PAPAZ)</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=3">Sonoran Desert</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=4">Teaching Checklists</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Agency Floras</a>
						<ul>
							<li>
								<a href="/seinet/projects/index.php?pid=5">NPS - Intermountain</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=24">USFWS - Region 2</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=148">USFS - Southwestern Region</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=82">BLM Flora</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=83">Coronado NF</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=144">Tonto NF</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Dynamic Floras</a>
						<ul>
							<li>
								<a href="/seinet/checklists/dynamicmap.php?interface=checklist">Dynamic Checklist</a>
							</li>
							<li>
								<a href="/seinet/checklists/dynamicmap.php?interface=key">Dynamic Key</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Additional Websites</a>
						<ul>
							<li>
								<a href="http://newmexicoflores.com/">New Mexico Flores</a>
							</li>
							<li>
								<a href="https://aznps.com/papaz-project/">Plant Atlas Project of Arizona (PAPAZ)</a>
							</li>
							<li>
								<a href="https://www.swcoloradowildflowers.com/">Southwest Colorado Wildflowers</a>
							</li>
							<li>
								<a href="http://gilaflora.com/">Vascular Plants of the Gila Wilderness</a>
							</li>
							<li>
								<a href="https://midwestherbaria.org/">Consortium of Midwest Herbaria</a>
							</li>
							<li>
								<a href="https://www.soroherbaria.org/">Consortium of Southern Rocky Mountain Herbaria</a>
							</li>
							<li>
								<a href="https://intermountainbiota.org/">Intermountain Region Herbaria Network (IRHN)</a>
							</li>
							<li>
								<a href="https://midatlanticherbaria.org/">Mid-Atlantic Herbaria Consortium</a>
							</li>
							<li>
								<a href="https://nansh.org/">North American Network of Small Herbaria (NANSH)</a>
							</li>
							<li>
								<a href="https://ngpherbaria.org/">Northern Great Plains Herbaria</a>
							</li>
							<li>
								<a href="https://herbanwmex.net/">Red de Herbarios Mexicanos</a>
							</li>
							<li>
								<a href="https://sernecportal.org/">SERNEC - Southeastern USA</a>
							</li>
							<li>
								<a href="https://portal.torcherbaria.org/">Texas Oklahoma Regional Consortium of Herbaria (TORCH)</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Resources</a>
						<ul>
							<li>
								<a href="https://docs.symbiota.org/docs/about/">Symbiota Docs</a>
							</li>
							<li>
								<a href="https://www.youtube.com/channel/UC7glMVLRnTA6ES3VTsci7iQ">Video Tutorials</a>
							</li>
							<li>
								<a href="/seinet/collections/misc/collprofiles.php">Collections in SEINet</a>
							</li>
							<li>
								<a href="https://symbiota.org/symbiota-portals/">Joining a Portal</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/seinet/includes/usagepolicy.php">
							Data Use						</a>
					</li>
					<li>
						<a href='/seinet/sitemap.php'>
							Sitemap						</a>
					</li>
					<!--
					<li id="lang-select-li">
						<label for="language-selection">Select Language: </label>
						<select oninput="setLanguage(this)" id="language-selection" name="language-selection">
							<option value="en">English</option>
							<option value="es" >Español</option>
							<option value="fr" >Français</option>
						</select>
					</li>
					-->
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Larrea tridentata</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Larrea tridentata</i></span>							<span id="author">(Sessé & Moc. ex DC.) Coville</span>
							&nbsp;<a href="index.php?tid=4965&amp;clid=0&amp;pid=&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Zygophyllaceae</div>
													<div id="vernacularDiv">
								creosote bush, <span class="verns"><a href="#" onclick="toggle('verns')" title="Click here to show more common names">more...</a></span><span class="verns" onclick="toggle('verns');" style="display:none;">Creosote-Bush, creosotebush, Creosote (es: hediondilla, gobernadora, guamis)</span>							</div>
							<div id="synonymDiv" title="Synonyms">[<i>Larrea divaricata subsp. tridentata</i> (Sesse & Moc. ex DC.) Felger & Lowe, <span class="synSpan"><a href="#" onclick="toggle('synSpan')" title="Click here to show more synonyms">more</a></span><span class="synSpan" onclick="toggle('synSpan')" style="display:none"><i>Larrea mexicana</i> Moric.</span>]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../imagelib/imgdetails.php?mediaid=219232');return false;"><img src="https://media01.symbiota.org/media/h_seinet/seinet/Zygophyllaceae/photos/Larrea-tridentata-F-web-N.jpg" title="" alt="Larrea tridentata image" /></a></div><div class="creator">Max Licher</div></div>					</td>
					<td class="desc">
						<div id="desctabs" class="ui-tabs" style="display:none"><ul class="ui-tabs-nav"><li><a href="#tab42565">SW Field Guide</a></li><li><a href="resourcetab.php?tid=2671">Resources</a></li></ul><div id="tab42565" class="sptab"><div id="descsource" style="float:right;">Wiggins 1964, McDougall 1973, Kearney and Peebles 1961</div><div style="clear:both;"><b>Common Name</b>: creosote bush <b>Duration</b>: Perennial <b>Nativity</b>: Native <b>Lifeform</b>: Shrub <b>General</b>: Aromatic, much branched evergreen shrub up to 3.5 m; with dark, glandular bands at the nodes and densely leafy toward the end of the branches. <b>Leaves</b>: Opposite and evergreen; each leaf consists of a pair of leaflets united at the base; leaflets are elliptical, 1 cm long, dark green, shiny, and strongly-scented (especially after rain).&nbsp; <b>Flowers</b>: Yellow, showy, solitary on pedicels from the leaf axils; with 5 petals 7-11 mm long. <b>Fruits</b>: Globose capsule splitting into 5 nutlets, covered in white silky hairs. <b>Ecology</b>: Widespread and common on dry plains and mesas below 5,000 ft (1676 m); flowers any time after adequate rain (minimum 12 mm of precipitation) but mostly flowers February to April. <b>Distribution</b>: s and c CA, s UT, AZ, NM, TX; south to s MEX, and in S. Amer. <b>Notes</b>: The most common and widespread shrub in warm deserts of North America, ordinarily untouched by livestock; causes dermatitis in some people. Distinguished by the strong, distinct creosote scent; the paired, dark green, lustrous leaves, 1 cm long; and the yellow flowers followed by globose, white-hairy fruits. <b>Ethnobotany</b>: Used to treat arthritis and allergies. As a salve it is a strongly antimicrobial and a moderate sunblock. <b>Etymology</b>: Larrea is named for Bishop Juan Antonio Hernandez Perez de Larrea (1731-1803) in Valladolid, Spain, while tridentata means three-toothed, the appearance of the leaves being three-toothed.  <b>Synonyms</b>: Larrea mexicana, Larrea divaricata subsp. tridentata <b>Editor</b>: SBuckley 2010, FSCoburn 2015, AHazelton 2015</div></div></div>					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="img-div" style="height:300px;overflow:hidden;">

============================================================
  swbiodiversity  (SymbiotaAPI)
  Species:   Larrea mexicana
  Name type: synonym  (synonym of: Larrea tridentata)
============================================================
[swbiodiversity] 'api/v2/taxonomy' returned results for 'Larrea mexicana'.
_fetch_query_data
{'tid': 10527, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Larrea', 'unitInd2': None, 'unitName2': 'mexicana', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'Moric.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '1996-11-04 23:57:08', 'parentTid': 4965, 'status': 'synonym', 'accepted': {'tid': 2671, 'scientificName': 'Larrea tridentata', 'scientificNameAuthorship': '(Sessé & Moc. ex DC.) Coville', 'taxonomicSource': None, 'unacceptabilityReason': None, 'taxonRemarks': None}, 'classification': [{'tid': 4965, 'scientificName': 'Larrea', 'author': 'Cav.', 'rankid': 180}, {'tid': 5327, 'scientificName': 'Zygophyllaceae', 'author': '', 'rankid': 140}, {'tid': 5570, 'scientificName': 'Magnoliophyta', 'author': '', 'rankid': 30}, {'tid': 5571, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 170361, 'scientificName': 'Tracheophyta', 'author': '', 'rankid': 20}, {'tid': 170633, 'scientificName': 'Spermatophyta', 'author': '', 'rankid': 20}, {'tid': 170692, 'scientificName': 'Eudicots', 'author': '', 'rankid': 45}, {'tid': 170726, 'scientificName': 'Core Eudicots', 'author': '', 'rankid': 65}, {'tid': 170757, 'scientificName': 'Rosids', 'author': '', 'rankid': 75}, {'tid': 170764, 'scientificName': 'Fabids', 'author': '', 'rankid': 75}, {'tid': 170780, 'scientificName': 'Zygophyllales', 'author': '', 'rankid': 100}], 'scientificName': 'Larrea mexicana'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>SEINet - AZ/NM Node - Larrea tridentata</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/seinet/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/seinet/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/seinet/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<!-- Responsive viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/seinet/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/seinet/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/seinet/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/seinet/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">

<script src="/seinet/js/symb/lang.js" type="text/javascript"></script>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-B5PK9G20TY"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-B5PK9G20TY');
	</script>
		<script src="/seinet/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/seinet/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>
<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="login">
						<form name="loginForm" method="post" action="/seinet/profile/index.php">
							<input name="refurl" type="hidden" value="/seinet/taxa/index.php?tid=2671">
							<button class="button button-secondary" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
			<div class="top-brand">
				<!--
				<a href="/seinet">
					<div class="image-container">
						<img src="/seinet/images/layout/logo_symbiota.png" alt="Symbiota logo">
					</div>
				</a>
				-->
				<div class="brand-name">
					<h1>SEINet</h1>
					<h2>Arizona - New Mexico Chapter</h2>
				</div>
			</div>
		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/seinet/index.php">
							Home						</a>
					</li>
					<li>
						<a href="#">Specimen Search</a>
						<ul>
							<li>
								<a href="/seinet/collections/search/index.php">Search Collections</a>
							</li>
							<li>
								<a href="/seinet/collections/map/index.php">Map Search</a>
							</li>
							<li>
								<a href="/seinet/collections/exsiccati/index.php">Exsiccati Search</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Images</a>
						<ul>
							<li>
								<a href="/seinet/imagelib/index.php">Image Browser</a>
							</li>
							<li>
								<a href="/seinet/imagelib/search.php">Search Images</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/seinet/projects/index.php">Flora Projects</a>
						<ul>
							<li>
								<a href="/seinet/projects/index.php?pid=1">Arizona</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=2">New Mexico</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=21">Colorado Plateau</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=75">Plant Atlas of Arizona (PAPAZ)</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=3">Sonoran Desert</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=4">Teaching Checklists</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Agency Floras</a>
						<ul>
							<li>
								<a href="/seinet/projects/index.php?pid=5">NPS - Intermountain</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=24">USFWS - Region 2</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=148">USFS - Southwestern Region</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=82">BLM Flora</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=83">Coronado NF</a>
							</li>
							<li>
								<a href="/seinet/projects/index.php?pid=144">Tonto NF</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Dynamic Floras</a>
						<ul>
							<li>
								<a href="/seinet/checklists/dynamicmap.php?interface=checklist">Dynamic Checklist</a>
							</li>
							<li>
								<a href="/seinet/checklists/dynamicmap.php?interface=key">Dynamic Key</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Additional Websites</a>
						<ul>
							<li>
								<a href="http://newmexicoflores.com/">New Mexico Flores</a>
							</li>
							<li>
								<a href="https://aznps.com/papaz-project/">Plant Atlas Project of Arizona (PAPAZ)</a>
							</li>
							<li>
								<a href="https://www.swcoloradowildflowers.com/">Southwest Colorado Wildflowers</a>
							</li>
							<li>
								<a href="http://gilaflora.com/">Vascular Plants of the Gila Wilderness</a>
							</li>
							<li>
								<a href="https://midwestherbaria.org/">Consortium of Midwest Herbaria</a>
							</li>
							<li>
								<a href="https://www.soroherbaria.org/">Consortium of Southern Rocky Mountain Herbaria</a>
							</li>
							<li>
								<a href="https://intermountainbiota.org/">Intermountain Region Herbaria Network (IRHN)</a>
							</li>
							<li>
								<a href="https://midatlanticherbaria.org/">Mid-Atlantic Herbaria Consortium</a>
							</li>
							<li>
								<a href="https://nansh.org/">North American Network of Small Herbaria (NANSH)</a>
							</li>
							<li>
								<a href="https://ngpherbaria.org/">Northern Great Plains Herbaria</a>
							</li>
							<li>
								<a href="https://herbanwmex.net/">Red de Herbarios Mexicanos</a>
							</li>
							<li>
								<a href="https://sernecportal.org/">SERNEC - Southeastern USA</a>
							</li>
							<li>
								<a href="https://portal.torcherbaria.org/">Texas Oklahoma Regional Consortium of Herbaria (TORCH)</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="#">Resources</a>
						<ul>
							<li>
								<a href="https://docs.symbiota.org/docs/about/">Symbiota Docs</a>
							</li>
							<li>
								<a href="https://www.youtube.com/channel/UC7glMVLRnTA6ES3VTsci7iQ">Video Tutorials</a>
							</li>
							<li>
								<a href="/seinet/collections/misc/collprofiles.php">Collections in SEINet</a>
							</li>
							<li>
								<a href="https://symbiota.org/symbiota-portals/">Joining a Portal</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="/seinet/includes/usagepolicy.php">
							Data Use						</a>
					</li>
					<li>
						<a href='/seinet/sitemap.php'>
							Sitemap						</a>
					</li>
					<!--
					<li id="lang-select-li">
						<label for="language-selection">Select Language: </label>
						<select oninput="setLanguage(this)" id="language-selection" name="language-selection">
							<option value="en">English</option>
							<option value="es" >Español</option>
							<option value="fr" >Français</option>
						</select>
					</li>
					-->
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Larrea tridentata</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Larrea tridentata</i></span>							<span id="author">(Sessé & Moc. ex DC.) Coville</span>
							&nbsp;<a href="index.php?tid=4965&amp;clid=0&amp;pid=&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Zygophyllaceae</div>
													<div id="vernacularDiv">
								creosote bush, <span class="verns"><a href="#" onclick="toggle('verns')" title="Click here to show more common names">more...</a></span><span class="verns" onclick="toggle('verns');" style="display:none;">Creosote-Bush, creosotebush, Creosote (es: hediondilla, gobernadora, guamis)</span>							</div>
							<div id="synonymDiv" title="Synonyms">[<i>Larrea divaricata subsp. tridentata</i> (Sesse & Moc. ex DC.) Felger & Lowe, <span class="synSpan"><a href="#" onclick="toggle('synSpan')" title="Click here to show more synonyms">more</a></span><span class="synSpan" onclick="toggle('synSpan')" style="display:none"><i>Larrea mexicana</i> Moric.</span>]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../imagelib/imgdetails.php?mediaid=219232');return false;"><img src="https://media01.symbiota.org/media/h_seinet/seinet/Zygophyllaceae/photos/Larrea-tridentata-F-web-N.jpg" title="" alt="Larrea tridentata image" /></a></div><div class="creator">Max Licher</div></div>					</td>
					<td class="desc">
						<div id="desctabs" class="ui-tabs" style="display:none"><ul class="ui-tabs-nav"><li><a href="#tab42565">SW Field Guide</a></li><li><a href="resourcetab.php?tid=2671">Resources</a></li></ul><div id="tab42565" class="sptab"><div id="descsource" style="float:right;">Wiggins 1964, McDougall 1973, Kearney and Peebles 1961</div><div style="clear:both;"><b>Common Name</b>: creosote bush <b>Duration</b>: Perennial <b>Nativity</b>: Native <b>Lifeform</b>: Shrub <b>General</b>: Aromatic, much branched evergreen shrub up to 3.5 m; with dark, glandular bands at the nodes and densely leafy toward the end of the branches. <b>Leaves</b>: Opposite and evergreen; each leaf consists of a pair of leaflets united at the base; leaflets are elliptical, 1 cm long, dark green, shiny, and strongly-scented (especially after rain).&nbsp; <b>Flowers</b>: Yellow, showy, solitary on pedicels from the leaf axils; with 5 petals 7-11 mm long. <b>Fruits</b>: Globose capsule splitting into 5 nutlets, covered in white silky hairs. <b>Ecology</b>: Widespread and common on dry plains and mesas below 5,000 ft (1676 m); flowers any time after adequate rain (minimum 12 mm of precipitation) but mostly flowers February to April. <b>Distribution</b>: s and c CA, s UT, AZ, NM, TX; south to s MEX, and in S. Amer. <b>Notes</b>: The most common and widespread shrub in warm deserts of North America, ordinarily untouched by livestock; causes dermatitis in some people. Distinguished by the strong, distinct creosote scent; the paired, dark green, lustrous leaves, 1 cm long; and the yellow flowers followed by globose, white-hairy fruits. <b>Ethnobotany</b>: Used to treat arthritis and allergies. As a salve it is a strongly antimicrobial and a moderate sunblock. <b>Etymology</b>: Larrea is named for Bishop Juan Antonio Hernandez Perez de Larrea (1731-1803) in Valladolid, Spain, while tridentata means three-toothed, the appearance of the leaves being three-toothed.  <b>Synonyms</b>: Larrea mexicana, Larrea divaricata subsp. tridentata <b>Editor</b>: SBuckley 2010, FSCoburn 2015, AHazelton 2015</div></div></div>					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="img-div" style="height:300px;overflow:hidden;">

============================================================
  swbiodiversity  (SymbiotaAPI)
  Species:   Not species
  Name type: not species
============================================================
[swbiodiversity] Search endpoint returned no results for 'Not species'. Attempting autocomplete search.
[swbiodiversity] All searches failed or returned no results for 'Not species'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []