# Test: `get_synonyms()` for all APIs_pipe clients

Run from the **project root** so that `scripts/` is on the Python path.

Covers:
- COL, GBIF, GenBank, Index Fungorum, ITIS, MushroomObserver, Tropicos
- FishBase
- Symbiota portals: MyCoPortal, Lichen, Bryophyte, CCH2, SERNEC, NANSH, Macroalgae, Pterido, NE Herbaria, Mid-Atlantic, SW Biodiversity

In [1]:
import time
import sys, os
# Ensure the project root is on sys.path when running from notebooks.apis_pipe/
project_root = os.path.abspath(os.path.join(os.getcwd(), "../.."))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from IPython.display import display

from scripts.apis_pipe.col import COLAPI
from scripts.apis_pipe.gbif import GBIFAPI
from scripts.apis_pipe.genbank import GenBankAPI
from scripts.apis_pipe.index_fungorum import IndexFungorumAPI
from scripts.apis_pipe.itis import ITISAPI
from scripts.apis_pipe.mushroomobs import MushroomObserverAPI
from scripts.apis_pipe.symbiota import SymbiotaAPI
from scripts.apis_pipe.tropicos import TropicosAPI
from scripts.apis_pipe.fishbase import FishBaseAPI

In [2]:
import pandas as pd

pd.set_option("display.max_colwidth", None)


def show(df):
    """Display a synonym DataFrame with api_link rendered as a clickable anchor."""
    if df.empty:
        display(df)
        return
    display(
        df.style.format(
            {
                "api_link": lambda url: (
                    f'<a href="{url}" target="_blank">{url}</a>'
                    if url and url not in ("U", "")
                    else url
                )
            }
        )
    )

---
## Standard APIs

In [3]:
from scripts.config import (
    COL_PORTAL,
    GBIF_PORTAL,
    INDEX_FUNGORUM_PORTAL,
    ITIS_PORTAL,
    MUSHROOM_OBSERVER_PORTAL,
    TROPICOS_PORTAL,
    FISHBASE_PORTAL
)

STANDARD_QUERIES = [
    # (portal, client, accepted_species, synonym_of_accepted)
    # (COL_PORTAL,               COLAPI(),              "Quercus robur",    "Quercus atrosanguinea"),
    # (GBIF_PORTAL,              GBIFAPI(),             "Amanita muscaria", "Agaricus muscarius"),
    # (INDEX_FUNGORUM_PORTAL,    IndexFungorumAPI(),    "Amanita muscaria", "Agaricus muscarius"),
    # (MUSHROOM_OBSERVER_PORTAL, MushroomObserverAPI(), "Amanita muscaria", "Amanita amerimuscaria"),
    (TROPICOS_PORTAL,          TropicosAPI(),         "Quercus robur",    "Quercus pedunculata"),
    # (FISHBASE_PORTAL,          FishBaseAPI(),         "Gadus morhua",     "Gadus callarias"),
    # (ITIS_PORTAL,              ITISAPI(),             "Quercus rubra",    "Quercus borealis"),
]

In [4]:
# display(GBIFAPI().get_synonyms("Agaricus muscarius"))

In [5]:
for portal, client, accepted, synonym in STANDARD_QUERIES:
    for species, name_type in [(accepted, "accepted"), (synonym, "synonym"), ("Not species", "not species")]:
        print(f"\n{'='*60}")
        print(f"  {portal.display_name}  ({client.__class__.__name__})")
        print(f"  Species:   {species}")
        print(f"  Name type: {name_type}  (synonym of: {accepted})" if name_type == "synonym" else f"  Name type: {name_type}")
        print(f"{'='*60}")
        try:
            result = client.get_synonyms(species)
            print(f"Synonyms returned: {len(result)}")
            show(result)
        except Exception as e:
            print(f"ERROR: {e}")

============================================================
  Tropicos  (TropicosAPI)
  Species:   Quercus robur
  Name type: accepted
============================================================
raw_data
[{'NameId': 13100004, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur L.', 'Family': 'Fagaceae', 'RankAbbreviation': 'sp.', 'NomenclatureStatusID': 1, 'NomenclatureStatusName': 'Legitimate', 'Symbol': '!', 'Author': 'L.', 'DisplayReference': 'Sp. Pl. 2: 996', 'DisplayDate': '1753', 'TotalRows': 2}, {'NameId': 50280607, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur (Ten.) A. DC.', 'Family': 'Fagaceae', 'RankAbbreviation': 'sp.', 'NomenclatureStatusName': 'No opinion', 'Author': '(Ten.) A. DC.', 'DisplayReference': 'Prodr. 16(2): 5', 'DisplayDate': '1864', 'TotalRows': 2}]
synonym_data
[{'SynonymName': {'NameId': 13100434, 'ScientificName': 'Quercus pedunculata', 'ScientificNameWithAuthors': 'Quercus pedunculata Ehrh.', 'Family': 'Fagaceae'}, 'AcceptedName': {'NameId': 13100004, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur L.', 'Family': 'Fagaceae'}, 'Reference': {'ReferenceId': 23908, 'PublicationId': 15422, 'AuthorString': 'Czerepanov, S. K.', 'Collation': '509 pages', 'AbbreviatedTitle': 'Sosud. Rast. SSSR', 'TitlePageYear': '1981'}}, {'SynonymName': {'NameId': 13101404, 'ScientificName': 'Quercus robur subsp. eurobur', 'ScientificNameWithAuthors': 'Quercus robur subsp. eurobur A. Camus', 'Family': 'Fagaceae'}, 'AcceptedName': {'NameId': 13100004, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur L.', 'Family': 'Fagaceae'}, 'Reference': {'ReferenceId': 42480, 'PublicationId': 11746, 'AuthorString': 'Flora of China Editorial Committee', 'ArticleTitle': 'Flora of China (Checklist & Addendum)', 'Collation': 'Unpaginated', 'AbbreviatedTitle': 'Fl. China', 'TitlePageYear': '1988-2013'}}]
synonym_search_term_data
[{'NameId': 13100004, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur L.', 'Family': 'Fagaceae', 'RankAbbreviation': 'sp.', 'NomenclatureStatusID': 1, 'NomenclatureStatusName': 'Legitimate', 'Symbol': '!', 'Author': 'L.', 'DisplayReference': 'Sp. Pl. 2: 996', 'DisplayDate': '1753', 'TotalRows': 2}, {'NameId': 50280607, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur (Ten.) A. DC.', 'Family': 'Fagaceae', 'RankAbbreviation': 'sp.', 'NomenclatureStatusName': 'No opinion', 'Author': '(Ten.) A. DC.', 'DisplayReference': 'Prodr. 16(2): 5', 'DisplayDate': '1864', 'TotalRows': 2}]
Synonyms returned: 2

============================================================
  Tropicos  (TropicosAPI)
  Species:   Quercus pedunculata
  Name type: synonym  (synonym of: Quercus robur)
============================================================
raw_data
[{'NameId': 13100434, 'ScientificName': 'Quercus pedunculata', 'ScientificNameWithAuthors': 'Quercus pedunculata Ehrh.', 'Family': 'Fagaceae', 'RankAbbreviation': 'sp.', 'NomenclatureStatusID': 3, 'NomenclatureStatusName': 'Invalid', 'Symbol': '**', 'Author': 'Ehrh.', 'DisplayReference': 'Beitr. Naturk. 5: 161', 'DisplayDate': '1790', 'TotalRows': 2}, {'NameId': 50280903, 'ScientificName': 'Quercus pedunculata', 'ScientificNameWithAuthors': 'Quercus pedunculata Hoffm.', 'Family': 'Fagaceae', 'RankAbbreviation': 'sp.', 'NomenclatureStatusName': 'No opinion', 'Author': 'Hoffm.', 'DisplayReference': 'Deutschl. Fl. 1: 338', 'DisplayDate': '1791', 'TotalRows': 2}]
synonym_data
[{'SynonymName': {'NameId': 13100434, 'ScientificName': 'Quercus pedunculata', 'ScientificNameWithAuthors': 'Quercus pedunculata Ehrh.', 'Family': 'Fagaceae'}, 'AcceptedName': {'NameId': 13100004, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur L.', 'Family': 'Fagaceae'}, 'Reference': {'ReferenceId': 23908, 'PublicationId': 15422, 'AuthorString': 'Czerepanov, S. K.', 'Collation': '509 pages', 'AbbreviatedTitle': 'Sosud. Rast. SSSR', 'TitlePageYear': '1981'}}, {'SynonymName': {'NameId': 13101404, 'ScientificName': 'Quercus robur subsp. eurobur', 'ScientificNameWithAuthors': 'Quercus robur subsp. eurobur A. Camus', 'Family': 'Fagaceae'}, 'AcceptedName': {'NameId': 13100004, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur L.', 'Family': 'Fagaceae'}, 'Reference': {'ReferenceId': 42480, 'PublicationId': 11746, 'AuthorString': 'Flora of China Editorial Committee', 'ArticleTitle': 'Flora of China (Checklist & Addendum)', 'Collation': 'Unpaginated', 'AbbreviatedTitle': 'Fl. China', 'TitlePageYear': '1988-2013'}}]
synonym_search_term_data
[{'NameId': 13100004, 'ScientificName': 'Quercus robur', 'ScientificNameWithAuthors': 'Quercus robur L.', 'Family': 'Fagaceae', 'SynonymCount': '2', 'AcceptedNameCount': '0', 'Rank': 'species', 'RankAbbreviation': 'sp.', 'NomenclatureStatusID': 1, 'NomenclatureStatusName': 'Legitimate', 'Symbol': '!', 'Genus': 'Quercus', 'SpeciesEpithet': 'robur', 'Source': 'http://www.tropicos.org/Name/13100004', 'Citation': 'Tropicos.org. Missouri Botanical Garden. 16 Jun 2026 &lt;http://www.tropicos.org/Name/13100004&gt;', 'Copyright': '© 2026 Missouri Botanical Garden - 4344 Shaw Boulevard - Saint Louis, Missouri 63110', 'Author': 'L.', 'NamePublishedCitation': 'Species Plantarum 2: 996. 1753. (1 May 1753) (Sp. Pl.) ', 'TypeSpecimens': [{'KindOfTypeAbbrev': 'LT', 'KindOfTypeName': 'Lectotype', 'Institution': 'UPS', 'TypeNote': 'LT designated by Jonsell & Jarvis, Regnum Veg. 127: 80 (1993).'}]}]
Synonyms returned: 2

============================================================
  Tropicos  (TropicosAPI)
  Species:   Not species
  Name type: not species
============================================================
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, subfamily, genus, species, author, publication_name, publication_year, status, source_name, api_link, api_internal_id]
Index: []

In [6]:
from scripts.config import GENBANK_PORTAL

# GenBank is run separately because NCBI rate-limits unauthenticated callers
# to 3 req/s. Each get_synonyms() makes 2 requests (esearch + efetch), so we
# sleep 1s between calls to stay well under the limit.
GENBANK_QUERIES = [
    ("Amanita muscaria",   "accepted"),
    ("Agaricus muscarius", "synonym"),
    ("Not species",        "not species"),
]
genbank_client = GenBankAPI()
for species, name_type in GENBANK_QUERIES:
    print(f"\n{'='*60}")
    print(f"  {GENBANK_PORTAL.display_name}  (GenBankAPI)")
    print(f"  Species:   {species}")
    print(f"  Name type: {name_type}")
    print(f"{'='*60}")
    try:
        result = genbank_client.get_synonyms(species)
        print(f"Synonyms returned: {len(result)}")
        show(result)
    except Exception as e:
        print(f"ERROR: {e}")
    time.sleep(1.0)  # NCBI rate limit: max 3 req/s; each call makes 2 requests

============================================================
  GenBank  (GenBankAPI)
  Species:   Amanita muscaria
  Name type: accepted
============================================================
raw_data
{'header': {'type': 'esearch', 'version': '0.3'}, 'esearchresult': {'count': '1', 'retmax': '1', 'retstart': '0', 'idlist': ['41956'], 'translationset': [], 'translationstack': [{'term': 'Amanita muscaria[Scientific Name]', 'field': 'Scientific Name', 'count': '1', 'explode': 'N'}, 'GROUP'], 'querytranslation': 'Amanita muscaria[Scientific Name]'}}
synonym_data
<TaxaSet><Taxon>
    <TaxId>41956</TaxId>
    <ScientificName>Amanita muscaria</ScientificName>
    <OtherNames>
        <GenbankCommonName>fly agaric</GenbankCommonName>
        <Synonym>Agaricus muscarius</Synonym>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Agaricus muscarius L., 1753</DispName>
        </Name>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Amanita muscaria (L.) Lam., 1783</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria on Nothofagus fusca</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria/Nothofagus fusca</DispName>
        </Name>
    </OtherNames>
    <ParentTaxId>41955</ParentTaxId>
    <Rank>species</Rank>
    <Division>Plants and Fungi</Division>
    <GeneticCode>
        <GCId>1</GCId>
        <GCName>Standard</GCName>
    </GeneticCode>
    <MitoGeneticCode>
        <MGCId>4</MGCId>
        <MGCName>Mold Mitochondrial; Protozoan Mitochondrial; Coelenterate Mitochondrial; Mycoplasma; Spiroplasma</MGCName>
    </MitoGeneticCode>
    <Lineage>cellular organisms; Eukaryota; Opisthokonta; Fungi; Dikarya; Basidiomycota; Agaricomycotina; Agaricomycetes; Agaricomycetidae; Agaricales; Pluteineae; Amanitaceae; Amanita</Lineage>
    <LineageEx>
        <Taxon>
            <TaxId>131567</TaxId>
            <ScientificName>cellular organisms</ScientificName>
            <Rank>cellular root</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2759</TaxId>
            <ScientificName>Eukaryota</ScientificName>
            <Rank>domain</Rank>
        </Taxon>
        <Taxon>
            <TaxId>33154</TaxId>
            <ScientificName>Opisthokonta</ScientificName>
            <Rank>clade</Rank>
        </Taxon>
        <Taxon>
            <TaxId>4751</TaxId>
            <ScientificName>Fungi</ScientificName>
            <Rank>kingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>451864</TaxId>
            <ScientificName>Dikarya</ScientificName>
            <Rank>subkingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5204</TaxId>
            <ScientificName>Basidiomycota</ScientificName>
            <Rank>phylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5302</TaxId>
            <ScientificName>Agaricomycotina</ScientificName>
            <Rank>subphylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>155619</TaxId>
            <ScientificName>Agaricomycetes</ScientificName>
            <Rank>class</Rank>
        </Taxon>
        <Taxon>
            <TaxId>452333</TaxId>
            <ScientificName>Agaricomycetidae</ScientificName>
            <Rank>subclass</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5338</TaxId>
            <ScientificName>Agaricales</ScientificName>
            <Rank>order</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2982306</TaxId>
            <ScientificName>Pluteineae</ScientificName>
            <Rank>suborder</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41954</TaxId>
            <ScientificName>Amanitaceae</ScientificName>
            <Rank>family</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41955</TaxId>
            <ScientificName>Amanita</ScientificName>
            <Rank>genus</Rank>
        </Taxon>
    </LineageEx>
    <CreateDate>1995/08/04 11:19:00</CreateDate>
    <UpdateDate>2025/08/08 10:02:44</UpdateDate>
    <PubDate>1996/10/10 01:00:00</PubDate>
</Taxon>

</TaxaSet>
synonym_search_term_data
<TaxaSet><Taxon>
    <TaxId>41956</TaxId>
    <ScientificName>Amanita muscaria</ScientificName>
    <OtherNames>
        <GenbankCommonName>fly agaric</GenbankCommonName>
        <Synonym>Agaricus muscarius</Synonym>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Agaricus muscarius L., 1753</DispName>
        </Name>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Amanita muscaria (L.) Lam., 1783</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria on Nothofagus fusca</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria/Nothofagus fusca</DispName>
        </Name>
    </OtherNames>
    <ParentTaxId>41955</ParentTaxId>
    <Rank>species</Rank>
    <Division>Plants and Fungi</Division>
    <GeneticCode>
        <GCId>1</GCId>
        <GCName>Standard</GCName>
    </GeneticCode>
    <MitoGeneticCode>
        <MGCId>4</MGCId>
        <MGCName>Mold Mitochondrial; Protozoan Mitochondrial; Coelenterate Mitochondrial; Mycoplasma; Spiroplasma</MGCName>
    </MitoGeneticCode>
    <Lineage>cellular organisms; Eukaryota; Opisthokonta; Fungi; Dikarya; Basidiomycota; Agaricomycotina; Agaricomycetes; Agaricomycetidae; Agaricales; Pluteineae; Amanitaceae; Amanita</Lineage>
    <LineageEx>
        <Taxon>
            <TaxId>131567</TaxId>
            <ScientificName>cellular organisms</ScientificName>
            <Rank>cellular root</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2759</TaxId>
            <ScientificName>Eukaryota</ScientificName>
            <Rank>domain</Rank>
        </Taxon>
        <Taxon>
            <TaxId>33154</TaxId>
            <ScientificName>Opisthokonta</ScientificName>
            <Rank>clade</Rank>
        </Taxon>
        <Taxon>
            <TaxId>4751</TaxId>
            <ScientificName>Fungi</ScientificName>
            <Rank>kingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>451864</TaxId>
            <ScientificName>Dikarya</ScientificName>
            <Rank>subkingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5204</TaxId>
            <ScientificName>Basidiomycota</ScientificName>
            <Rank>phylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5302</TaxId>
            <ScientificName>Agaricomycotina</ScientificName>
            <Rank>subphylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>155619</TaxId>
            <ScientificName>Agaricomycetes</ScientificName>
            <Rank>class</Rank>
        </Taxon>
        <Taxon>
            <TaxId>452333</TaxId>
            <ScientificName>Agaricomycetidae</ScientificName>
            <Rank>subclass</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5338</TaxId>
            <ScientificName>Agaricales</ScientificName>
            <Rank>order</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2982306</TaxId>
            <ScientificName>Pluteineae</ScientificName>
            <Rank>suborder</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41954</TaxId>
            <ScientificName>Amanitaceae</ScientificName>
            <Rank>family</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41955</TaxId>
            <ScientificName>Amanita</ScientificName>
            <Rank>genus</Rank>
        </Taxon>
    </LineageEx>
    <CreateDate>1995/08/04 11:19:00</CreateDate>
    <UpdateDate>2025/08/08 10:02:44</UpdateDate>
    <PubDate>1996/10/10 01:00:00</PubDate>
</Taxon>

</TaxaSet>
Synonyms returned: 2

============================================================
  GenBank  (GenBankAPI)
  Species:   Agaricus muscarius
  Name type: synonym
============================================================
raw_data
{'header': {'type': 'esearch', 'version': '0.3'}, 'esearchresult': {'count': '1', 'retmax': '1', 'retstart': '0', 'idlist': ['41956'], 'translationset': [], 'translationstack': [{'term': 'Agaricus muscarius[All Names]', 'field': 'All Names', 'count': '1', 'explode': 'N'}, 'GROUP'], 'querytranslation': 'Agaricus muscarius[All Names]'}}
synonym_data
<TaxaSet><Taxon>
    <TaxId>41956</TaxId>
    <ScientificName>Amanita muscaria</ScientificName>
    <OtherNames>
        <GenbankCommonName>fly agaric</GenbankCommonName>
        <Synonym>Agaricus muscarius</Synonym>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Agaricus muscarius L., 1753</DispName>
        </Name>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Amanita muscaria (L.) Lam., 1783</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria on Nothofagus fusca</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria/Nothofagus fusca</DispName>
        </Name>
    </OtherNames>
    <ParentTaxId>41955</ParentTaxId>
    <Rank>species</Rank>
    <Division>Plants and Fungi</Division>
    <GeneticCode>
        <GCId>1</GCId>
        <GCName>Standard</GCName>
    </GeneticCode>
    <MitoGeneticCode>
        <MGCId>4</MGCId>
        <MGCName>Mold Mitochondrial; Protozoan Mitochondrial; Coelenterate Mitochondrial; Mycoplasma; Spiroplasma</MGCName>
    </MitoGeneticCode>
    <Lineage>cellular organisms; Eukaryota; Opisthokonta; Fungi; Dikarya; Basidiomycota; Agaricomycotina; Agaricomycetes; Agaricomycetidae; Agaricales; Pluteineae; Amanitaceae; Amanita</Lineage>
    <LineageEx>
        <Taxon>
            <TaxId>131567</TaxId>
            <ScientificName>cellular organisms</ScientificName>
            <Rank>cellular root</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2759</TaxId>
            <ScientificName>Eukaryota</ScientificName>
            <Rank>domain</Rank>
        </Taxon>
        <Taxon>
            <TaxId>33154</TaxId>
            <ScientificName>Opisthokonta</ScientificName>
            <Rank>clade</Rank>
        </Taxon>
        <Taxon>
            <TaxId>4751</TaxId>
            <ScientificName>Fungi</ScientificName>
            <Rank>kingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>451864</TaxId>
            <ScientificName>Dikarya</ScientificName>
            <Rank>subkingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5204</TaxId>
            <ScientificName>Basidiomycota</ScientificName>
            <Rank>phylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5302</TaxId>
            <ScientificName>Agaricomycotina</ScientificName>
            <Rank>subphylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>155619</TaxId>
            <ScientificName>Agaricomycetes</ScientificName>
            <Rank>class</Rank>
        </Taxon>
        <Taxon>
            <TaxId>452333</TaxId>
            <ScientificName>Agaricomycetidae</ScientificName>
            <Rank>subclass</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5338</TaxId>
            <ScientificName>Agaricales</ScientificName>
            <Rank>order</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2982306</TaxId>
            <ScientificName>Pluteineae</ScientificName>
            <Rank>suborder</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41954</TaxId>
            <ScientificName>Amanitaceae</ScientificName>
            <Rank>family</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41955</TaxId>
            <ScientificName>Amanita</ScientificName>
            <Rank>genus</Rank>
        </Taxon>
    </LineageEx>
    <CreateDate>1995/08/04 11:19:00</CreateDate>
    <UpdateDate>2025/08/08 10:02:44</UpdateDate>
    <PubDate>1996/10/10 01:00:00</PubDate>
</Taxon>

</TaxaSet>
synonym_search_term_data
<TaxaSet><Taxon>
    <TaxId>41956</TaxId>
    <ScientificName>Amanita muscaria</ScientificName>
    <OtherNames>
        <GenbankCommonName>fly agaric</GenbankCommonName>
        <Synonym>Agaricus muscarius</Synonym>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Agaricus muscarius L., 1753</DispName>
        </Name>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Amanita muscaria (L.) Lam., 1783</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria on Nothofagus fusca</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria/Nothofagus fusca</DispName>
        </Name>
    </OtherNames>
    <ParentTaxId>41955</ParentTaxId>
    <Rank>species</Rank>
    <Division>Plants and Fungi</Division>
    <GeneticCode>
        <GCId>1</GCId>
        <GCName>Standard</GCName>
    </GeneticCode>
    <MitoGeneticCode>
        <MGCId>4</MGCId>
        <MGCName>Mold Mitochondrial; Protozoan Mitochondrial; Coelenterate Mitochondrial; Mycoplasma; Spiroplasma</MGCName>
    </MitoGeneticCode>
    <Lineage>cellular organisms; Eukaryota; Opisthokonta; Fungi; Dikarya; Basidiomycota; Agaricomycotina; Agaricomycetes; Agaricomycetidae; Agaricales; Pluteineae; Amanitaceae; Amanita</Lineage>
    <LineageEx>
        <Taxon>
            <TaxId>131567</TaxId>
            <ScientificName>cellular organisms</ScientificName>
            <Rank>cellular root</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2759</TaxId>
            <ScientificName>Eukaryota</ScientificName>
            <Rank>domain</Rank>
        </Taxon>
        <Taxon>
            <TaxId>33154</TaxId>
            <ScientificName>Opisthokonta</ScientificName>
            <Rank>clade</Rank>
        </Taxon>
        <Taxon>
            <TaxId>4751</TaxId>
            <ScientificName>Fungi</ScientificName>
            <Rank>kingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>451864</TaxId>
            <ScientificName>Dikarya</ScientificName>
            <Rank>subkingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5204</TaxId>
            <ScientificName>Basidiomycota</ScientificName>
            <Rank>phylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5302</TaxId>
            <ScientificName>Agaricomycotina</ScientificName>
            <Rank>subphylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>155619</TaxId>
            <ScientificName>Agaricomycetes</ScientificName>
            <Rank>class</Rank>
        </Taxon>
        <Taxon>
            <TaxId>452333</TaxId>
            <ScientificName>Agaricomycetidae</ScientificName>
            <Rank>subclass</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5338</TaxId>
            <ScientificName>Agaricales</ScientificName>
            <Rank>order</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2982306</TaxId>
            <ScientificName>Pluteineae</ScientificName>
            <Rank>suborder</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41954</TaxId>
            <ScientificName>Amanitaceae</ScientificName>
            <Rank>family</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41955</TaxId>
            <ScientificName>Amanita</ScientificName>
            <Rank>genus</Rank>
        </Taxon>
    </LineageEx>
    <CreateDate>1995/08/04 11:19:00</CreateDate>
    <UpdateDate>2025/08/08 10:02:44</UpdateDate>
    <PubDate>1996/10/10 01:00:00</PubDate>
</Taxon>

</TaxaSet>
Synonyms returned: 2

============================================================
  GenBank  (GenBankAPI)
  Species:   Not species
  Name type: not species
============================================================
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, subfamily, genus, species, author, publication_name, publication_year, status, source_name, api_link, api_internal_id]
Index: []

---
## Symbiota Portals

In [7]:
from scripts.config import SYMBIOTA_PORTAL_BY_NAME

_SYMBIOTA_QUERIES = [
    # (portal, accepted_species, synonym_of_accepted)
    (SYMBIOTA_PORTAL_BY_NAME["MyCoPortal"],                       "Agaricus campestris",     "Psalliota villatica"),
    (SYMBIOTA_PORTAL_BY_NAME["Lichen Portal"],                    "Xanthoria parietina",     "Physcia parietina"),
    (SYMBIOTA_PORTAL_BY_NAME["Bryophyte Portal"],                 "Pohlia nutans",           "Webera nutans"),
    (SYMBIOTA_PORTAL_BY_NAME["CCH2"],                             "Heteromeles arbutifolia", "Photinia arbutifolia"),
    (SYMBIOTA_PORTAL_BY_NAME["SERNEC"],                           "Magnolia grandiflora",    "Magnolia foetida"),
    (SYMBIOTA_PORTAL_BY_NAME["NANSH"],                            "Rudbeckia hirta",         "Coreopsis hirta"),
    (SYMBIOTA_PORTAL_BY_NAME["Algae Herbarium Portal"],           "Ulva intestinalis",       "Ilea intestinalis"),
    (SYMBIOTA_PORTAL_BY_NAME["Pterido Portal"],                   "Dryopteris filix-mas",    "Nephrodium filix-mas"),
    (SYMBIOTA_PORTAL_BY_NAME["CNH"],                              "Impatiens capensis",      "Impatiens biflora"),
    (SYMBIOTA_PORTAL_BY_NAME["Mid-Atlantic Herbaria Consortium"], "Quercus rubra",           "Quercus maxima"),
    (SYMBIOTA_PORTAL_BY_NAME["swbiodiversity"],                   "Larrea tridentata",       "Larrea mexicana"),
]

In [ ]:
for portal, accepted, synonym in _SYMBIOTA_QUERIES:
    for species, name_type in [(accepted, "accepted"), (synonym, "synonym"), ("Not species", "not species")]:
        print(f"\n{'='*60}")
        print(f"  symbiota / {portal.display_name}")
        print(f"  URL:       {portal.base_url}")
        print(f"  Species:   {species}")
        print(f"  Name type: {name_type}  (synonym of: {accepted})" if name_type == "synonym" else f"  Name type: {name_type}")
        print(f"{'='*60}")
        try:
            client = SymbiotaAPI(portal.display_name)
            result = client.get_synonyms(species)
            print(f"Synonyms returned: {len(result)}")
            show(result)
        except Exception as e:
            print(f"ERROR: {e}")

============================================================
  symbiota / MyCoPortal
  URL:       https://mycoportal.org/portal
  Species:   Agaricus campestris
  Name type: accepted
============================================================
[MyCoPortal] 'api/v2/taxonomy/search' returned results for 'Agaricus campestris'.
raw_data
{'tid': 214862, 'kingdomName': 'Fungi', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Agaricus', 'unitInd2': None, 'unitName2': 'campestris', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'L.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2011-11-18 23:38:57', 'scientificName': 'Agaricus campestris'}
synonym_data
[{'name': 'Psalliota villatica', 'author': '(Brond.) Bres.]'}]
synonym_search_term_data
{'tid': 214862, 'kingdomName': 'Fungi', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Agaricus', 'unitInd2': None, 'unitName2': 'campestris', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'L.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2011-11-18 23:38:57', 'scientificName': 'Agaricus campestris'}
Synonyms returned: 2

============================================================
  symbiota / MyCoPortal
  URL:       https://mycoportal.org/portal
  Species:   Psalliota villatica
  Name type: synonym  (synonym of: Agaricus campestris)
============================================================
[MyCoPortal] 'api/v2/taxonomy/search' returned results for 'Psalliota villatica'.
raw_data
{'tid': 527987, 'kingdomName': 'Fungi', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Psalliota', 'unitInd2': None, 'unitName2': 'villatica', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(Brond.) Bres.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'Index Fungorum', 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2011-11-19 14:07:42', 'scientificName': 'Psalliota villatica'}
synonym_data
[{'name': 'Psalliota villatica', 'author': '(Brond.) Bres.]'}]
synonym_search_term_data
{'tid': 214862, 'kingdomName': 'Fungi', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Agaricus', 'unitInd2': None, 'unitName2': 'campestris', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'L.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2011-11-18 23:38:57', 'parentTid': 11736, 'status': 'accepted', 'classification': [{'tid': 7, 'scientificName': 'Fungi', 'author': 'R.T. Moore', 'rankid': 10}, {'tid': 188, 'scientificName': 'Basidiomycota', 'author': 'R.T. Moore', 'rankid': 30}, {'tid': 1128, 'scientificName': 'Agaricomycotina', 'author': 'Doweld', 'rankid': 40}, {'tid': 1431, 'scientificName': 'Agaricomycetes', 'author': 'Doweld', 'rankid': 60}, {'tid': 5489, 'scientificName': 'Agaricomycetidae', 'author': 'Parmasto', 'rankid': 70}, {'tid': 6519, 'scientificName': 'Agaricales', 'author': 'Underw.', 'rankid': 100}, {'tid': 7158, 'scientificName': 'Polyporales', 'author': '', 'rankid': 100}, {'tid': 7561, 'scientificName': 'Agaricaceae', 'author': 'Chevall.', 'rankid': 140}, {'tid': 7600, 'scientificName': 'Amanitaceae', 'author': '', 'rankid': 140}, {'tid': 8610, 'scientificName': 'Fomitopsidaceae', 'author': '', 'rankid': 140}, {'tid': 11736, 'scientificName': 'Agaricus (d2)', 'author': 'L.', 'rankid': 180}], 'scientificName': 'Agaricus campestris'}
Synonyms returned: 2

============================================================
  symbiota / MyCoPortal
  URL:       https://mycoportal.org/portal
  Species:   Not species
  Name type: not species
============================================================
[MyCoPortal] 'api/v2/taxonomy/search' returned no results for 'Not species'.
[MyCoPortal] 'api/v2/taxonomy' returned results for 'Not species'.
raw_data
{'tid': 1, 'kingdomName': 'Algae', 'rankID': 10, 'rankName': None, 'unitInd1': None, 'unitName1': 'Algae', 'unitInd2': None, 'unitName2': None, 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'Index Fungorum', 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2011-11-15 19:32:56', 'scientificName': 'Algae'}
synonym_data
[]
synonym_search_term_data
{'tid': 1, 'kingdomName': 'Algae', 'rankID': 10, 'rankName': None, 'unitInd1': None, 'unitName1': 'Algae', 'unitInd2': None, 'unitName2': None, 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'Index Fungorum', 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2011-11-15 19:32:56', 'scientificName': 'Algae'}
ERROR: Expected at least two tokens in scientific name, got 'Algae'

============================================================
  symbiota / Lichen Portal
  URL:       https://lichenportal.org/portal
  Species:   Xanthoria parietina
  Name type: accepted
============================================================
[Lichen Portal] 'api/v2/taxonomy/search' returned no results for 'Xanthoria parietina'.
[Lichen Portal] 'api/v2/taxonomy' returned results for 'Xanthoria parietina'.
raw_data
{'tid': 56389, 'kingdomName': 'Fungi', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Xanthoria', 'unitInd2': None, 'unitName2': 'parietina', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(L.) Th. Fr.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'USDA PLANTS DB', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2008-09-29 12:52:57', 'scientificName': 'Xanthoria parietina'}
synonym_data
[{'name': 'Blasteniospora parietina', 'author': '(L.) Trevis.'}, {'name': 'Geissodea parietina', 'author': '(L.) J. St.-Hill.'}, {'name': 'Imbricaria parietina', 'author': '(L.) DC.'}, {'name': 'Lecanora rutilans', 'author': '(Ach.) Ach.'}, {'name': 'Lichen rutilans', 'author': 'Ach.'}, {'name': 'Lobaria parietina', 'author': '(L.) Hoffm.'}, {'name': 'Parmelia rutilans', 'author': '(Ach.) Ach.'}, {'name': 'Physcia ectanea', 'author': '(Ach.) Linds.'}, {'name': 'Physcia parietina', 'author': '(L.) De Not.'}, {'name': 'Platysma parietinum', 'author': '(L.) Frege'}, {'name': 'Teloschistes parietinus', 'author': '(Ach.) F. Wilson'}, {'name': 'Xanthoria coomae', 'author': 'S.Y. Kondr. & Kärnefelt'}, {'name': 'Xanthoria ectanea', 'author': '(Ach.) Räsänen ex Filson'}, {'name': 'Xanthoria polessica', 'author': 'S. Y. Kondr. et A. P. Yatsyna'}]
synonym_search_term_data
{'tid': 56389, 'kingdomName': 'Fungi', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Xanthoria', 'unitInd2': None, 'unitName2': 'parietina', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(L.) Th. Fr.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'USDA PLANTS DB', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2008-09-29 12:52:57', 'scientificName': 'Xanthoria parietina'}
Synonyms returned: 15

============================================================
  symbiota / Lichen Portal
  URL:       https://lichenportal.org/portal
  Species:   Physcia parietina
  Name type: synonym  (synonym of: Xanthoria parietina)
============================================================
[Lichen Portal] 'api/v2/taxonomy/search' returned no results for 'Physcia parietina'.
[Lichen Portal] 'api/v2/taxonomy' returned results for 'Physcia parietina'.
raw_data
{'tid': 173703, 'kingdomName': 'Fungi', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Physcia', 'unitInd2': None, 'unitName2': 'parietina', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(L.) De Not.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': "Zahlbruckner's Cat. Lich. Univ. 7: 293 | Lamb's Index nom. lich.: 562", 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2013-02-02 03:36:24', 'scientificName': 'Physcia parietina'}
synonym_data
[{'name': 'Blasteniospora parietina', 'author': '(L.) Trevis.'}, {'name': 'Geissodea parietina', 'author': '(L.) J. St.-Hill.'}, {'name': 'Imbricaria parietina', 'author': '(L.) DC.'}, {'name': 'Lecanora rutilans', 'author': '(Ach.) Ach.'}, {'name': 'Lichen rutilans', 'author': 'Ach.'}, {'name': 'Lobaria parietina', 'author': '(L.) Hoffm.'}, {'name': 'Parmelia rutilans', 'author': '(Ach.) Ach.'}, {'name': 'Physcia ectanea', 'author': '(Ach.) Linds.'}, {'name': 'Physcia parietina', 'author': '(L.) De Not.'}, {'name': 'Platysma parietinum', 'author': '(L.) Frege'}, {'name': 'Teloschistes parietinus', 'author': '(Ach.) F. Wilson'}, {'name': 'Xanthoria coomae', 'author': 'S.Y. Kondr. & Kärnefelt'}, {'name': 'Xanthoria ectanea', 'author': '(Ach.) Räsänen ex Filson'}, {'name': 'Xanthoria polessica', 'author': 'S. Y. Kondr. et A. P. Yatsyna'}]
synonym_search_term_data
{'tid': 56389, 'kingdomName': 'Fungi', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Xanthoria', 'unitInd2': None, 'unitName2': 'parietina', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(L.) Th. Fr.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'USDA PLANTS DB', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2008-09-29 12:52:57', 'parentTid': 52249, 'status': 'accepted', 'classification': [{'tid': 51657, 'scientificName': 'Fungi', 'author': 'R.T. Moore', 'rankid': 10}, {'tid': 51658, 'scientificName': 'Ascomycota', 'author': 'Caval.-Sm.', 'rankid': 30}, {'tid': 51685, 'scientificName': 'Teloschistales', 'author': 'D. Hawksw. & O.E. Erikss.', 'rankid': 100}, {'tid': 51789, 'scientificName': 'Teloschistaceae', 'author': 'Zahlbr.', 'rankid': 140}, {'tid': 52249, 'scientificName': 'Xanthoria', 'author': '(Fr.) Th. Fr.', 'rankid': 180}, {'tid': 127110, 'scientificName': 'Pezizomycotina', 'author': 'O.E. Erikss & Winka', 'rankid': 40}, {'tid': 127138, 'scientificName': 'Lecanoromycetes', 'author': 'O.E. Erikss. & Winka', 'rankid': 60}, {'tid': 127302, 'scientificName': 'Lecanoromycetidae', 'author': 'P.M. Kirk, P.F. Cannon, J.C. David & Stalpers ex Miądl., Lutzoni & Lumbsch', 'rankid': 70}, {'tid': 257522, 'scientificName': 'Teloschistineae', 'author': 'Gaya & Lutzoni', 'rankid': 110}, {'tid': 257526, 'scientificName': 'Xanthorioideae', 'author': 'Arup, Søchting & Frödén', 'rankid': 150}, {'tid': 265256, 'scientificName': 'Dikarya', 'author': 'Hibbett, T.Y. James & Vilgalys', 'rankid': 20}], 'scientificName': 'Xanthoria parietina'}
Synonyms returned: 15

============================================================
  symbiota / Lichen Portal
  URL:       https://lichenportal.org/portal
  Species:   Not species
  Name type: not species
============================================================
[Lichen Portal] 'api/v2/taxonomy/search' returned no results for 'Not species'.
[Lichen Portal] 'api/v2/taxonomy' returned no results for 'Not species'.
[Lichen Portal] All search endpoints returned no results for 'Not species'. Attempting autocomplete search.
[Lichen Portal] All searches failed or returned no results for 'Not species'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, subfamily, genus, species, author, publication_name, publication_year, status, source_name, api_link, api_internal_id]
Index: []

============================================================
  symbiota / Bryophyte Portal
  URL:       https://bryophyteportal.org/portal
  Species:   Pohlia nutans
  Name type: accepted
============================================================
[Bryophyte Portal] 'api/v2/taxonomy/search' returned no results for 'Pohlia nutans'.
[Bryophyte Portal] 'api/v2/taxonomy' returned results for 'Pohlia nutans'.
raw_data
{'tid': 160406, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Pohlia', 'unitInd2': None, 'unitName2': 'nutans', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(Hedw.) Lindb.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'tropicos;usda', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2010-09-21 05:27:39', 'scientificName': 'Pohlia nutans'}
synonym_data
[{'name': 'Bryum afronutans', 'author': 'Müll. Hal.'}, {'name': 'Bryum austronutans', 'author': 'Müll. Hal.'}, {'name': 'Bryum basalticum', 'author': 'Warnst. & Geh.'}, {'name': 'Bryum bealeyense', 'author': '(Huebener) Delogne'}, {'name': 'Bryum beccarii', 'author': 'Müll. Hal.'}, {'name': 'Bryum caespitosum', 'author': '(Hoppe & Hornsch.) Brid.'}, {'name': 'Bryum canaliculatum', 'author': '(Müll. Hal. & Kindb.) Müll. Hal.'}, {'name': 'Bryum claviforme', 'author': 'Hampe'}, {'name': 'Bryum compactum', 'author': 'Dicks.'}, {'name': 'Bryum cucullatiforme', 'author': 'Kindb.'}, {'name': 'Bryum ecklonianum', 'author': 'Müll. Hal.'}, {'name': 'Bryum gelidum', 'author': 'I. Hagen'}, {'name': 'Bryum gypsophilum', 'author': 'Wallr.'}, {'name': 'Bryum humidulum', 'author': 'Sull. & Lesq.'}, {'name': 'Bryum interruptum', 'author': 'Dicks.'}, {'name': 'Bryum laxum', 'author': 'Reichardt'}, {'name': 'Bryum leptopelmatum', 'author': 'Müll. Hal.'}, {'name': 'Bryum montanum', 'author': 'Müll. Hal.'}, {'name': 'Bryum nigricans', 'author': 'Dicks.'}, {'name': 'Bryum nutans', 'author': '(Hedw.) Turner'}, {'name': 'Bryum pertenellum', 'author': 'Bryhn & Ryan'}, {'name': 'Bryum rutilans', 'author': 'Brid.'}, {'name': 'Bryum schimperi', 'author': 'Müll. Hal.'}, {'name': 'Bryum sphagnadelphus', 'author': 'Müll. Hal.'}, {'name': 'Bryum subdenticulatum', 'author': 'Brid.'}, {'name': 'Bryum torlessense', 'author': 'R. Br. bis'}, {'name': 'Bryum umbrosum', 'author': 'Wallr.'}, {'name': 'Hypnum nutans', 'author': '(Hedw.) F. Weber & D. Mohr'}, {'name': 'Lamprophyllum nutans', 'author': '(Hedw.) Lindb.'}, {'name': 'Mniobryum compactum', 'author': '(Dicks.) Baehni'}, {'name': 'Mnium compactum', 'author': '(Dicks.) P. Beauv.'}, {'name': 'Mnium nigricans', 'author': '(Dicks.) Brid.'}, {'name': 'Pohlia beccarii', 'author': '(Müll. Hal.) Watts & Whitel.'}, {'name': 'Pohlia caespitosa', 'author': '(Hoppe & Hornsch.) Lazarenko'}, {'name': 'Pohlia claviformis', 'author': '(Hampe) Broth.'}, {'name': 'Pohlia elatior', 'author': '(Dixon & Sainsbury) Sainsbury'}, {'name': 'Pohlia leptopelmata', 'author': '(Müll. Hal.) Watts & Whitel.'}, {'name': 'Pohlia longifolia', 'author': '(A. Jaeger) Watts & Whitel.'}, {'name': 'Pohlia montana', 'author': '(Müll. Hal.) Watts & Whitel.'}, {'name': 'Pohlia polygama', 'author': 'Kindb.'}, {'name': 'Pohlia pulvinata', 'author': '(Kindb.) Broth.'}, {'name': 'Pohlia racovitzae', 'author': '(Cardot) Broth.'}, {'name': 'Pohlia rutilans', 'author': '(Schimp.) Lindb.'}, {'name': 'Pohlia schimperi', 'author': '(C. Müll.) Andrews in Grout'}, {'name': 'Pohlia suzukii', 'author': 'Ochi'}, {'name': 'Pohlia tomentosocaespitosa', 'author': 'Ochi'}, {'name': 'Pohlia yanoi', 'author': 'Ochi'}, {'name': 'Pseudopohlia merrillii', 'author': 'Broth.'}, {'name': 'Webera afronutans', 'author': '(Müll. Hal.) Paris'}, {'name': 'Webera austronutans', 'author': '(Müll. Hal.) Kindb.'}, {'name': 'Webera beccarii', 'author': '(Müll. Hal.) Paris'}, {'name': 'Webera bicolor', 'author': 'Hoppe & Hornsch.'}, {'name': 'Webera caespitosa', 'author': 'Hoppe & Hornsch.'}, {'name': 'Webera canaliculata', 'author': 'Müll. Hal. & Kindb.'}, {'name': 'Webera claviformis', 'author': '(Hampe) A. Jaeger'}, {'name': 'Webera cucullatiformis', 'author': '(Kindb.) Paris'}, {'name': 'Webera duriuscula', 'author': 'Broth.'}, {'name': 'Webera eckloniana', 'author': '(Müll. Hal.) A. Jaeger'}, {'name': 'Webera elatior', 'author': 'Dixon & Sainsbury'}, {'name': 'Webera longifolia', 'author': 'A. Jaeger'}, {'name': 'Webera longiseta', 'author': 'Brid.'}, {'name': 'Webera montana', 'author': '(Müll. Hal.) Paris'}, {'name': 'Webera nigricans', 'author': '(Dicks.) Buse'}, {'name': 'Webera nutans', 'author': 'Hedw.'}, {'name': 'Webera pendula', 'author': 'Hornsch.'}, {'name': 'Webera polygama', 'author': '(Kindb.) Broth.'}, {'name': 'Webera pulvinata', 'author': 'Kindb.'}, {'name': 'Webera racovitzae', 'author': 'Cardot'}, {'name': 'Webera rutilans', 'author': 'Schimp.'}, {'name': 'Webera schimperi', 'author': '(Müll. Hal.) Schimp.'}, {'name': 'Webera sphagnadelphus', 'author': '(Müll. Hal.) Besch.'}, {'name': 'Webera strangulata', 'author': 'Nees'}, {'name': 'Webera subdenticulata', 'author': '(Brid.) Brid.'}]
synonym_search_term_data
{'tid': 160406, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Pohlia', 'unitInd2': None, 'unitName2': 'nutans', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(Hedw.) Lindb.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'tropicos;usda', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2010-09-21 05:27:39', 'scientificName': 'Pohlia nutans'}
Synonyms returned: 74

============================================================
  symbiota / Bryophyte Portal
  URL:       https://bryophyteportal.org/portal
  Species:   Webera nutans
  Name type: synonym  (synonym of: Pohlia nutans)
============================================================
[Bryophyte Portal] 'api/v2/taxonomy/search' returned no results for 'Webera nutans'.
[Bryophyte Portal] 'api/v2/taxonomy' returned results for 'Webera nutans'.
raw_data
{'tid': 237892, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Webera', 'unitInd2': None, 'unitName2': 'nutans', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'Hedw.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'tropicos', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2012-12-29 07:59:05', 'scientificName': 'Webera nutans'}
synonym_data
[{'name': 'Bryum afronutans', 'author': 'Müll. Hal.'}, {'name': 'Bryum austronutans', 'author': 'Müll. Hal.'}, {'name': 'Bryum basalticum', 'author': 'Warnst. & Geh.'}, {'name': 'Bryum bealeyense', 'author': '(Huebener) Delogne'}, {'name': 'Bryum beccarii', 'author': 'Müll. Hal.'}, {'name': 'Bryum caespitosum', 'author': '(Hoppe & Hornsch.) Brid.'}, {'name': 'Bryum canaliculatum', 'author': '(Müll. Hal. & Kindb.) Müll. Hal.'}, {'name': 'Bryum claviforme', 'author': 'Hampe'}, {'name': 'Bryum compactum', 'author': 'Dicks.'}, {'name': 'Bryum cucullatiforme', 'author': 'Kindb.'}, {'name': 'Bryum ecklonianum', 'author': 'Müll. Hal.'}, {'name': 'Bryum gelidum', 'author': 'I. Hagen'}, {'name': 'Bryum gypsophilum', 'author': 'Wallr.'}, {'name': 'Bryum humidulum', 'author': 'Sull. & Lesq.'}, {'name': 'Bryum interruptum', 'author': 'Dicks.'}, {'name': 'Bryum laxum', 'author': 'Reichardt'}, {'name': 'Bryum leptopelmatum', 'author': 'Müll. Hal.'}, {'name': 'Bryum montanum', 'author': 'Müll. Hal.'}, {'name': 'Bryum nigricans', 'author': 'Dicks.'}, {'name': 'Bryum nutans', 'author': '(Hedw.) Turner'}, {'name': 'Bryum pertenellum', 'author': 'Bryhn & Ryan'}, {'name': 'Bryum rutilans', 'author': 'Brid.'}, {'name': 'Bryum schimperi', 'author': 'Müll. Hal.'}, {'name': 'Bryum sphagnadelphus', 'author': 'Müll. Hal.'}, {'name': 'Bryum subdenticulatum', 'author': 'Brid.'}, {'name': 'Bryum torlessense', 'author': 'R. Br. bis'}, {'name': 'Bryum umbrosum', 'author': 'Wallr.'}, {'name': 'Hypnum nutans', 'author': '(Hedw.) F. Weber & D. Mohr'}, {'name': 'Lamprophyllum nutans', 'author': '(Hedw.) Lindb.'}, {'name': 'Mniobryum compactum', 'author': '(Dicks.) Baehni'}, {'name': 'Mnium compactum', 'author': '(Dicks.) P. Beauv.'}, {'name': 'Mnium nigricans', 'author': '(Dicks.) Brid.'}, {'name': 'Pohlia beccarii', 'author': '(Müll. Hal.) Watts & Whitel.'}, {'name': 'Pohlia caespitosa', 'author': '(Hoppe & Hornsch.) Lazarenko'}, {'name': 'Pohlia claviformis', 'author': '(Hampe) Broth.'}, {'name': 'Pohlia elatior', 'author': '(Dixon & Sainsbury) Sainsbury'}, {'name': 'Pohlia leptopelmata', 'author': '(Müll. Hal.) Watts & Whitel.'}, {'name': 'Pohlia longifolia', 'author': '(A. Jaeger) Watts & Whitel.'}, {'name': 'Pohlia montana', 'author': '(Müll. Hal.) Watts & Whitel.'}, {'name': 'Pohlia polygama', 'author': 'Kindb.'}, {'name': 'Pohlia pulvinata', 'author': '(Kindb.) Broth.'}, {'name': 'Pohlia racovitzae', 'author': '(Cardot) Broth.'}, {'name': 'Pohlia rutilans', 'author': '(Schimp.) Lindb.'}, {'name': 'Pohlia schimperi', 'author': '(C. Müll.) Andrews in Grout'}, {'name': 'Pohlia suzukii', 'author': 'Ochi'}, {'name': 'Pohlia tomentosocaespitosa', 'author': 'Ochi'}, {'name': 'Pohlia yanoi', 'author': 'Ochi'}, {'name': 'Pseudopohlia merrillii', 'author': 'Broth.'}, {'name': 'Webera afronutans', 'author': '(Müll. Hal.) Paris'}, {'name': 'Webera austronutans', 'author': '(Müll. Hal.) Kindb.'}, {'name': 'Webera beccarii', 'author': '(Müll. Hal.) Paris'}, {'name': 'Webera bicolor', 'author': 'Hoppe & Hornsch.'}, {'name': 'Webera caespitosa', 'author': 'Hoppe & Hornsch.'}, {'name': 'Webera canaliculata', 'author': 'Müll. Hal. & Kindb.'}, {'name': 'Webera claviformis', 'author': '(Hampe) A. Jaeger'}, {'name': 'Webera cucullatiformis', 'author': '(Kindb.) Paris'}, {'name': 'Webera duriuscula', 'author': 'Broth.'}, {'name': 'Webera eckloniana', 'author': '(Müll. Hal.) A. Jaeger'}, {'name': 'Webera elatior', 'author': 'Dixon & Sainsbury'}, {'name': 'Webera longifolia', 'author': 'A. Jaeger'}, {'name': 'Webera longiseta', 'author': 'Brid.'}, {'name': 'Webera montana', 'author': '(Müll. Hal.) Paris'}, {'name': 'Webera nigricans', 'author': '(Dicks.) Buse'}, {'name': 'Webera nutans', 'author': 'Hedw.'}, {'name': 'Webera pendula', 'author': 'Hornsch.'}, {'name': 'Webera polygama', 'author': '(Kindb.) Broth.'}, {'name': 'Webera pulvinata', 'author': 'Kindb.'}, {'name': 'Webera racovitzae', 'author': 'Cardot'}, {'name': 'Webera rutilans', 'author': 'Schimp.'}, {'name': 'Webera schimperi', 'author': '(Müll. Hal.) Schimp.'}, {'name': 'Webera sphagnadelphus', 'author': '(Müll. Hal.) Besch.'}, {'name': 'Webera strangulata', 'author': 'Nees'}, {'name': 'Webera subdenticulata', 'author': '(Brid.) Brid.'}]
synonym_search_term_data
{'tid': 160406, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Pohlia', 'unitInd2': None, 'unitName2': 'nutans', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(Hedw.) Lindb.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'tropicos;usda', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2010-09-21 05:27:39', 'parentTid': 157098, 'status': 'accepted', 'classification': [{'tid': 5571, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 16600, 'scientificName': 'Bryophyta', 'author': 'Schimp.', 'rankid': 30}, {'tid': 16698, 'scientificName': 'Bryopsida', 'author': 'McClatchie', 'rankid': 60}, {'tid': 16814, 'scientificName': 'Bryidae', 'author': 'Engl.', 'rankid': 70}, {'tid': 16841, 'scientificName': 'Bryales', 'author': 'Limpr.', 'rankid': 100}, {'tid': 16965, 'scientificName': 'Mniaceae', 'author': 'Schwägr.', 'rankid': 140}, {'tid': 157098, 'scientificName': 'Pohlia', 'author': 'Hedw.', 'rankid': 180}, {'tid': 254632, 'scientificName': 'Bryobiotina', 'author': '', 'rankid': 20}, {'tid': 254644, 'scientificName': 'Bryanae', 'author': 'Goffinet & W.R. Buck', 'rankid': 90}], 'scientificName': 'Pohlia nutans'}
Synonyms returned: 74

============================================================
  symbiota / Bryophyte Portal
  URL:       https://bryophyteportal.org/portal
  Species:   Not species
  Name type: not species
============================================================
[Bryophyte Portal] 'api/v2/taxonomy/search' returned no results for 'Not species'.
[Bryophyte Portal] 'api/v2/taxonomy' returned no results for 'Not species'.
[Bryophyte Portal] All search endpoints returned no results for 'Not species'. Attempting autocomplete search.
[Bryophyte Portal] All searches failed or returned no results for 'Not species'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, subfamily, genus, species, author, publication_name, publication_year, status, source_name, api_link, api_internal_id]
Index: []

============================================================
  symbiota / CCH2
  URL:       https://cch2.org/portal
  Species:   Heteromeles arbutifolia
  Name type: accepted
============================================================
[CCH2] 'api/v2/taxonomy/search' returned no results for 'Heteromeles arbutifolia'.
[CCH2] 'api/v2/taxonomy' returned results for 'Heteromeles arbutifolia'.
raw_data
{'tid': 22929, 'kingdomName': 'Plantae', 'rankID': 220, 'unitInd1': None, 'unitName1': 'Heteromeles', 'unitInd2': None, 'unitName2': 'arbutifolia', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(Lindl.) M. Roem.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'scientificName': 'Heteromeles arbutifolia'}
synonym_data
[{'name': 'Heteromeles fremontiana', 'author': 'Decne.'}, {'name': 'Heteromeles salicifolia', 'author': '(C. Presl) Abrams'}, {'name': 'Photinia arbutifolia', 'author': 'Lindl.'}, {'name': 'Photinia salicifolia', 'author': 'C. Presl'}]
synonym_search_term_data
{'tid': 22929, 'kingdomName': 'Plantae', 'rankID': 220, 'unitInd1': None, 'unitName1': 'Heteromeles', 'unitInd2': None, 'unitName2': 'arbutifolia', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(Lindl.) M. Roem.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'scientificName': 'Heteromeles arbutifolia'}
Synonyms returned: 5

============================================================
  symbiota / CCH2
  URL:       https://cch2.org/portal
  Species:   Photinia arbutifolia
  Name type: synonym  (synonym of: Heteromeles arbutifolia)
============================================================
[CCH2] 'api/v2/taxonomy/search' returned no results for 'Photinia arbutifolia'.
[CCH2] 'api/v2/taxonomy' returned results for 'Photinia arbutifolia'.
raw_data
{'tid': 27893, 'kingdomName': 'Plantae', 'rankID': 220, 'unitInd1': None, 'unitName1': 'Photinia', 'unitInd2': None, 'unitName2': 'arbutifolia', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'Lindl.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'scientificName': 'Photinia arbutifolia'}
synonym_data
[{'name': 'Heteromeles fremontiana', 'author': 'Decne.'}, {'name': 'Heteromeles salicifolia', 'author': '(C. Presl) Abrams'}, {'name': 'Photinia arbutifolia', 'author': 'Lindl.'}, {'name': 'Photinia salicifolia', 'author': 'C. Presl'}]
synonym_search_term_data
{'tid': 22929, 'kingdomName': 'Plantae', 'rankID': 220, 'unitInd1': None, 'unitName1': 'Heteromeles', 'unitInd2': None, 'unitName2': 'arbutifolia', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(Lindl.) M. Roem.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'parentTid': 5720, 'status': 'accepted', 'classification': [{'tid': 1, 'scientificName': 'Organism', 'author': '', 'rankid': 1}, {'tid': 4, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 7, 'scientificName': 'Viridiplantae', 'author': '', 'rankid': 15}, {'tid': 3418, 'scientificName': 'Streptophyta', 'author': '', 'rankid': 25}, {'tid': 3425, 'scientificName': 'Embryophyta', 'author': '', 'rankid': 27}, {'tid': 3428, 'scientificName': 'Tracheophyta', 'author': '', 'rankid': 30}, {'tid': 3429, 'scientificName': 'Spermatophytina', 'author': '', 'rankid': 40}, {'tid': 3430, 'scientificName': 'Magnoliopsida', 'author': '', 'rankid': 60}, {'tid': 3436, 'scientificName': 'Rosanae', 'author': '', 'rankid': 90}, {'tid': 3634, 'scientificName': 'Rosales', 'author': '', 'rankid': 100}, {'tid': 4134, 'scientificName': 'Rosaceae', 'author': '', 'rankid': 140}, {'tid': 5720, 'scientificName': 'Heteromeles', 'author': '', 'rankid': 180}], 'scientificName': 'Heteromeles arbutifolia'}
Synonyms returned: 5

============================================================
  symbiota / CCH2
  URL:       https://cch2.org/portal
  Species:   Not species
  Name type: not species
============================================================
[CCH2] 'api/v2/taxonomy/search' returned no results for 'Not species'.
[CCH2] 'api/v2/taxonomy' returned no results for 'Not species'.
[CCH2] All search endpoints returned no results for 'Not species'. Attempting autocomplete search.
[CCH2] All searches failed or returned no results for 'Not species'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, subfamily, genus, species, author, publication_name, publication_year, status, source_name, api_link, api_internal_id]
Index: []

============================================================
  symbiota / SERNEC
  URL:       https://sernecportal.org/portal
  Species:   Magnolia grandiflora
  Name type: accepted
============================================================
[SERNEC] 'api/v2/taxonomy/search' returned no results for 'Magnolia grandiflora'.
[SERNEC] 'api/v2/taxonomy' returned results for 'Magnolia grandiflora'.
raw_data
{'tid': 17263, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Magnolia', 'unitInd2': None, 'unitName2': 'grandiflora', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'L.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'Martin_092306', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2006-12-25 06:25:43', 'scientificName': 'Magnolia grandiflora'}
synonym_data
[{'name': 'Magnolia foetida', 'author': ''}, {'name': 'Magnolia tomentosa', 'author': 'Ser.'}]
synonym_search_term_data
{'tid': 17263, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Magnolia', 'unitInd2': None, 'unitName2': 'grandiflora', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'L.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'Martin_092306', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2006-12-25 06:25:43', 'scientificName': 'Magnolia grandiflora'}
Synonyms returned: 3

============================================================
  symbiota / SERNEC
  URL:       https://sernecportal.org/portal
  Species:   Magnolia foetida
  Name type: synonym  (synonym of: Magnolia grandiflora)
============================================================
[SERNEC] 'api/v2/taxonomy/search' returned no results for 'Magnolia foetida'.
[SERNEC] 'api/v2/taxonomy' returned results for 'Magnolia foetida'.
raw_data
{'tid': 214261, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Magnolia', 'unitInd2': None, 'unitName2': 'foetida', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2015-12-13 07:49:14', 'scientificName': 'Magnolia foetida'}
synonym_data
[{'name': 'Magnolia foetida', 'author': ''}, {'name': 'Magnolia tomentosa', 'author': 'Ser.'}]
synonym_search_term_data
{'tid': 17263, 'kingdomName': 'Plantae', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Magnolia', 'unitInd2': None, 'unitName2': 'grandiflora', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'L.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'Martin_092306', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2006-12-25 06:25:43', 'parentTid': 17119, 'status': 'accepted', 'classification': [{'tid': 5570, 'scientificName': 'Magnoliophyta', 'author': '', 'rankid': 30}, {'tid': 5571, 'scientificName': 'Plantae', 'author': '', 'rankid': 10}, {'tid': 16366, 'scientificName': 'Magnoliaceae', 'author': '', 'rankid': 140}, {'tid': 16469, 'scientificName': 'Magnoliales', 'author': '', 'rankid': 100}, {'tid': 17119, 'scientificName': 'Magnolia', 'author': 'L.', 'rankid': 180}, {'tid': 170361, 'scientificName': 'Tracheophyta', 'author': '', 'rankid': 20}, {'tid': 170633, 'scientificName': 'Spermatophyta', 'author': '', 'rankid': 20}, {'tid': 170683, 'scientificName': 'Magnoliids', 'author': '', 'rankid': 75}], 'scientificName': 'Magnolia grandiflora'}
Synonyms returned: 3

============================================================
  symbiota / SERNEC
  URL:       https://sernecportal.org/portal
  Species:   Not species
  Name type: not species
============================================================
[SERNEC] 'api/v2/taxonomy/search' returned no results for 'Not species'.
[SERNEC] 'api/v2/taxonomy' returned no results for 'Not species'.
[SERNEC] All search endpoints returned no results for 'Not species'. Attempting autocomplete search.
[SERNEC] All searches failed or returned no results for 'Not species'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, subfamily, genus, species, author, publication_name, publication_year, status, source_name, api_link, api_internal_id]
Index: []