# Test: `get_synonyms()` for all APIs_pipe clients

Run from the **project root** so that `scripts/` is on the Python path.

Covers:
- COL, GBIF, GenBank, Index Fungorum, ITIS, MushroomObserver, Tropicos
- FishBase
- Symbiota portals: MyCoPortal, Lichen, Bryophyte, CCH2, SERNEC, NANSH, Macroalgae, Pterido, NE Herbaria, Mid-Atlantic, SW Biodiversity

In [1]:
import time
import sys, os
# Ensure the project root is on sys.path when running from notebooks.apis_pipe/
project_root = os.path.abspath(os.path.join(os.getcwd(), "../.."))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from IPython.display import display

from scripts.apis_pipe.col import COLAPI
from scripts.apis_pipe.gbif import GBIFAPI
from scripts.apis_pipe.genbank import GenBankAPI
from scripts.apis_pipe.index_fungorum import IndexFungorumAPI
from scripts.apis_pipe.itis import ITISAPI
from scripts.apis_pipe.mushroomobs import MushroomObserverAPI
from scripts.apis_pipe.symbiota import SymbiotaAPI
from scripts.apis_pipe.tropicos import TropicosAPI
from scripts.apis_pipe.fishbase import FishBaseAPI

In [2]:
import pandas as pd

pd.set_option("display.max_colwidth", None)


def show(df):
    """Display a synonym DataFrame with api_link rendered as a clickable anchor."""
    if df.empty:
        display(df)
        return
    display(
        df.style.format(
            {
                "api_link": lambda url: (
                    f'<a href="{url}" target="_blank">{url}</a>'
                    if url and url not in ("U", "")
                    else url
                )
            }
        )
    )

---
## Standard APIs

In [3]:
from scripts.config import (
    COL_PORTAL,
    GBIF_PORTAL,
    INDEX_FUNGORUM_PORTAL,
    ITIS_PORTAL,
    MUSHROOM_OBSERVER_PORTAL,
    TROPICOS_PORTAL,
    FISHBASE_PORTAL
)

STANDARD_QUERIES = [
    # (portal, client, accepted_species, synonym_of_accepted)
    # (COL_PORTAL,               COLAPI(),              "Quercus robur",    "Quercus atrosanguinea"),
    # (GBIF_PORTAL,              GBIFAPI(),             "Amanita muscaria", "Agaricus muscarius"),
    # (INDEX_FUNGORUM_PORTAL,    IndexFungorumAPI(),    "Amanita muscaria", "Agaricus muscarius"),
    (MUSHROOM_OBSERVER_PORTAL, MushroomObserverAPI(), "Amanita muscaria", "Amanita amerimuscaria"),
    # (TROPICOS_PORTAL,          TropicosAPI(),         "Quercus robur",    "Quercus pedunculata"),
    # (FISHBASE_PORTAL,          FishBaseAPI(),         "Gadus morhua",     "Gadus callarias"),
    # (ITIS_PORTAL,              ITISAPI(),             "Oncorhynchus mykiss",    "Salmo mykiss"),
]

In [4]:
# display(GBIFAPI().get_synonyms("Agaricus muscarius"))

In [5]:
for portal, client, accepted, synonym in STANDARD_QUERIES:
    for species, name_type in [(accepted, "accepted"), (synonym, "synonym"), ("Not species", "not species")]:
        print(f"\n{'='*60}")
        print(f"  {portal.display_name}  ({client.__class__.__name__})")
        print(f"  Species:   {species}")
        print(f"  Name type: {name_type}  (synonym of: {accepted})" if name_type == "synonym" else f"  Name type: {name_type}")
        print(f"{'='*60}")
        try:
            result = client.get_synonyms(species)
            print(f"Synonyms returned: {len(result)}")
            show(result)
        except Exception as e:
            print(f"ERROR: {e}")

============================================================
  Mushroom Observer  (MushroomObserverAPI)
  Species:   Amanita muscaria
  Name type: accepted
============================================================
_fetch_query_data
{'version': 2.0, 'run_date': '2026-06-23T04:25:45.576Z', 'query': 'SELECT DISTINCT `names`.* FROM `names` WHERE (`names`.`id` IN (374, 5066, 16015, 28495, 41324, 59384, 373, 31199, 59289, 109028, 110413, 111780)) AND (`names`.`correct_spelling_id` IS NULL) AND (`names`.`correct_spelling_id` IS NULL) ORDER BY `names`.`id` ASC', 'number_of_records': 7, 'number_of_pages': 1, 'page_number': 1, 'results': [{'id': 373, 'type': 'name', 'name': 'Amanita muscaria', 'author': '(L.) Lam.', 'rank': 'species', 'deprecated': False, 'misspelled': False, 'citation': '<a href="https://biodiversitylibrary.org/page/716703"><cite>Encycl. Méth. Bot.</cite> (Paris) 1: 111</a> (1783)', 'created_at': '2007-01-10T05:03:59.000Z', 'updated_at': '2025-04-02T17:58:46.000Z', 'number_of_views': 7427, 'last_viewed': '2026-06-22T19:14:25.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 31199, 'name': 'Amanita muscarea', 'rank': 'species', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}, {'id': 59289, 'name': 'Amanita mascaria', 'rank': 'species', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}, {'id': 109028, 'name': 'Aminata mascura', 'rank': 'species', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}, {'id': 110413, 'name': 'Aminita muscaria', 'rank': 'species', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}, {'id': 111780, 'name': 'Amanita', 'author': 'Musccaria', 'rank': 'genus', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}], 'comments': [{'id': 43620, 'summary': 'Approved', 'content': 'I understand that the botanical code says that you should use the infra-species autonym, but there is still value in have a page the species as a whole. Consequently, I am approving this name.', 'created_at': '2011-11-02T21:02:01.000Z', 'updated_at': '2011-11-02T21:02:01.000Z', 'owner': {'id': 1, 'login_name': 'nathan', 'legal_name': 'Nathan Wilson'}}]}, {'id': 374, 'type': 'name', 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'misspelled': False, 'citation': 'Bibliotheca Mycologica 57: 56 (1977) [MB#487346]', 'created_at': '2007-01-10T05:03:59.000Z', 'updated_at': '2025-05-23T22:24:35.000Z', 'number_of_views': 1024, 'last_viewed': '2025-12-17T19:19:52.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}], 'comments': [{'id': 45557, 'summary': 'Deprecated', 'content': 'Technically both <a href="https://mushroomobserver.org/lookups/lookup_name/Amanita+muscaria+var.+flavivolvata"><i>Amanita muscaria var. flavivolvata</i></a> and <a href="https://mushroomobserver.org/lookups/lookup_name/Amanita+muscaria+subsp.+flavivolvata"><i>Amanita muscaria subsp. flavivolvata</i></a> are valid. However, to ensure that we aren&#8217;t exporting both to third parties like EOL, I&#8217;m suggesting that we prefer the subspecies. This follows what Rod is currently doing on Amanitaceae.org and I believe there is good evidence that this is a distinct species that will eventually be published as <a href="https://mushroomobserver.org/lookups/lookup_name/Amanita+amerimuscaria"><i>Amanita amerimuscaria</i></a>. Given this subspecies status seems more appropriate than a variety.', 'created_at': '2011-12-13T14:57:29.000Z', 'updated_at': '2011-12-13T14:57:29.000Z', 'owner': {'id': 1, 'login_name': 'nathan', 'legal_name': 'Nathan Wilson'}}]}, {'id': 5066, 'type': 'name', 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'deprecated': False, 'misspelled': False, 'citation': '<a href="https://www.zobodat.at/pdf/Sydowia_11_0354-0374.pdf#page=21"><cite>Sydowia</cite> 11(1-6): 374</a> (1958) [1957]', 'created_at': '2007-09-23T01:34:49.000Z', 'updated_at': '2025-04-02T18:28:07.000Z', 'number_of_views': 3112, 'last_viewed': '2026-05-27T17:26:30.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}]}, {'id': 16015, 'type': 'name', 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'misspelled': False, 'created_at': '2009-02-13T03:42:08.000Z', 'updated_at': '2025-05-23T22:24:33.000Z', 'number_of_views': 3182, 'last_viewed': '2026-06-22T19:14:41.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}], 'comments': [{'id': 167081, 'summary': 'What ever happened to this name?', 'content': '<p>What ever happened to this name?   Was it decided that it didn&#8217;t need to be published because Amanita muscaria subsp. flavivolvata is a good name for this taxon?</p>', 'created_at': '2019-02-20T17:59:29.000Z', 'updated_at': '2019-02-20T17:59:29.000Z', 'owner': {'id': 123, 'login_name': 'Alan Rockefeller', 'legal_name': 'Alan Rockefeller'}}]}, {'id': 28495, 'type': 'name', 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'misspelled': False, 'created_at': '2011-08-10T22:18:52.000Z', 'updated_at': '2025-05-24T22:12:18.000Z', 'number_of_views': 614, 'last_viewed': '2026-06-11T06:55:46.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}]}, {'id': 41324, 'type': 'name', 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'misspelled': False, 'created_at': '2013-11-13T09:11:24.000Z', 'updated_at': '2025-04-02T22:12:09.000Z', 'number_of_views': 84, 'last_viewed': '2024-10-31T03:37:51.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}]}, {'id': 59384, 'type': 'name', 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'misspelled': False, 'notes': '<p>Geographic origin: Santa Cruz Island, California, USA</p>\n<p>Geml, J., Tulloss, R.E., Laursen, G.A., Sazanova, N.A. and Taylor, D.L., 2010. Phylogeographic analyses of a boreal-temperate ectomycorrhizal basidiomycete, Amanita muscaria, suggest forest refugia in Alaska during the last glacial maximum. In Relict Species (pp. 173-186). Springer Berlin Heidelberg.</p>\n<p><a href="http://taylorlabunm.weebly.com/uploads/2/5/0/2/25029144/geml_relict-species-phylogeography-and-conservation-biology_2010.pdf">http://taylorlabunm.weebly.com/...</a></p>', 'created_at': '2016-10-17T14:30:57.000Z', 'updated_at': '2026-04-28T18:32:58.000Z', 'number_of_views': 72, 'last_viewed': '2022-08-31T14:51:37.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}]}], 'run_time': 0.319482722}
_fetch_synonym_data
[{'id': 31199, 'name': 'Amanita muscarea', 'rank': 'species', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}, {'id': 59289, 'name': 'Amanita mascaria', 'rank': 'species', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}, {'id': 109028, 'name': 'Aminata mascura', 'rank': 'species', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}, {'id': 110413, 'name': 'Aminita muscaria', 'rank': 'species', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}, {'id': 111780, 'name': 'Amanita', 'author': 'Musccaria', 'rank': 'genus', 'deprecated': True, 'misspelled': True, 'synonym_id': 9473}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}]
_fetch_accepted_data

============================================================
  Mushroom Observer  (MushroomObserverAPI)
  Species:   Amanita amerimuscaria
  Name type: synonym  (synonym of: Amanita muscaria)
============================================================
_fetch_query_data
{'version': 2.0, 'run_date': '2026-06-23T04:25:46.578Z', 'query': 'SELECT DISTINCT `names`.* FROM `names` WHERE (`names`.`id` IN (374, 5066, 16015, 28495, 41324, 59384)) AND (`names`.`correct_spelling_id` IS NULL) AND (`names`.`correct_spelling_id` IS NULL) ORDER BY `names`.`id` ASC', 'number_of_records': 6, 'number_of_pages': 1, 'page_number': 1, 'results': [{'id': 374, 'type': 'name', 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'misspelled': False, 'citation': 'Bibliotheca Mycologica 57: 56 (1977) [MB#487346]', 'created_at': '2007-01-10T05:03:59.000Z', 'updated_at': '2025-05-23T22:24:35.000Z', 'number_of_views': 1024, 'last_viewed': '2025-12-17T19:19:52.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}], 'comments': [{'id': 45557, 'summary': 'Deprecated', 'content': 'Technically both <a href="https://mushroomobserver.org/lookups/lookup_name/Amanita+muscaria+var.+flavivolvata"><i>Amanita muscaria var. flavivolvata</i></a> and <a href="https://mushroomobserver.org/lookups/lookup_name/Amanita+muscaria+subsp.+flavivolvata"><i>Amanita muscaria subsp. flavivolvata</i></a> are valid. However, to ensure that we aren&#8217;t exporting both to third parties like EOL, I&#8217;m suggesting that we prefer the subspecies. This follows what Rod is currently doing on Amanitaceae.org and I believe there is good evidence that this is a distinct species that will eventually be published as <a href="https://mushroomobserver.org/lookups/lookup_name/Amanita+amerimuscaria"><i>Amanita amerimuscaria</i></a>. Given this subspecies status seems more appropriate than a variety.', 'created_at': '2011-12-13T14:57:29.000Z', 'updated_at': '2011-12-13T14:57:29.000Z', 'owner': {'id': 1, 'login_name': 'nathan', 'legal_name': 'Nathan Wilson'}}]}, {'id': 5066, 'type': 'name', 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'deprecated': False, 'misspelled': False, 'citation': '<a href="https://www.zobodat.at/pdf/Sydowia_11_0354-0374.pdf#page=21"><cite>Sydowia</cite> 11(1-6): 374</a> (1958) [1957]', 'created_at': '2007-09-23T01:34:49.000Z', 'updated_at': '2025-04-02T18:28:07.000Z', 'number_of_views': 3112, 'last_viewed': '2026-05-27T17:26:30.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}]}, {'id': 16015, 'type': 'name', 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'misspelled': False, 'created_at': '2009-02-13T03:42:08.000Z', 'updated_at': '2025-05-23T22:24:33.000Z', 'number_of_views': 3182, 'last_viewed': '2026-06-22T19:14:41.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}], 'comments': [{'id': 167081, 'summary': 'What ever happened to this name?', 'content': '<p>What ever happened to this name?   Was it decided that it didn&#8217;t need to be published because Amanita muscaria subsp. flavivolvata is a good name for this taxon?</p>', 'created_at': '2019-02-20T17:59:29.000Z', 'updated_at': '2019-02-20T17:59:29.000Z', 'owner': {'id': 123, 'login_name': 'Alan Rockefeller', 'legal_name': 'Alan Rockefeller'}}]}, {'id': 28495, 'type': 'name', 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'misspelled': False, 'created_at': '2011-08-10T22:18:52.000Z', 'updated_at': '2025-05-24T22:12:18.000Z', 'number_of_views': 614, 'last_viewed': '2026-06-11T06:55:46.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}]}, {'id': 41324, 'type': 'name', 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'misspelled': False, 'created_at': '2013-11-13T09:11:24.000Z', 'updated_at': '2025-04-02T22:12:09.000Z', 'number_of_views': 84, 'last_viewed': '2024-10-31T03:37:51.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}]}, {'id': 59384, 'type': 'name', 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'misspelled': False, 'notes': '<p>Geographic origin: Santa Cruz Island, California, USA</p>\n<p>Geml, J., Tulloss, R.E., Laursen, G.A., Sazanova, N.A. and Taylor, D.L., 2010. Phylogeographic analyses of a boreal-temperate ectomycorrhizal basidiomycete, Amanita muscaria, suggest forest refugia in Alaska during the last glacial maximum. In Relict Species (pp. 173-186). Springer Berlin Heidelberg.</p>\n<p><a href="http://taylorlabunm.weebly.com/uploads/2/5/0/2/25029144/geml_relict-species-phylogeography-and-conservation-biology_2010.pdf">http://taylorlabunm.weebly.com/...</a></p>', 'created_at': '2016-10-17T14:30:57.000Z', 'updated_at': '2026-04-28T18:32:58.000Z', 'number_of_views': 72, 'last_viewed': '2022-08-31T14:51:37.000Z', 'ok_for_export': True, 'parents': [{'name': 'Eukarya', 'rank': 'domain'}, {'name': 'Fungi', 'rank': 'kingdom'}, {'name': 'Basidiomycota', 'rank': 'phylum'}, {'name': 'Agaricomycotina', 'rank': 'subphylum'}, {'name': 'Agaricomycetes', 'rank': 'class'}, {'name': 'Agaricomycetidae', 'rank': 'subclass'}, {'name': 'Agaricales', 'rank': 'order'}, {'name': 'Amanitineae', 'rank': 'suborder'}, {'name': 'Amanitaceae', 'rank': 'family'}], 'synonyms': [{'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}]}], 'run_time': 0.293306739}
_fetch_synonym_data
[{'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 59384, 'name': "Amanita sp. 'LG882'", 'author': 'Tulloss crypt. temp.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 374, 'name': 'Amanita muscaria var. flavivolvata', 'author': '(Singer) Dav. T. Jenkins', 'rank': 'variety', 'deprecated': True, 'synonym_id': 4383}, {'id': 5066, 'name': 'Amanita muscaria subsp. flavivolvata', 'author': 'Singer', 'rank': 'subspecies', 'synonym_id': 4383}, {'id': 16015, 'name': 'Amanita amerimuscaria', 'author': 'Tulloss & Geml nom. prov.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 28495, 'name': 'Amanita muscaria', 'author': 'sensu auct. amer.', 'rank': 'species', 'deprecated': True, 'synonym_id': 4383}, {'id': 41324, 'name': 'Amanita muscaria f. flavivolvata', 'author': '(Singer) Neville & Poumarat', 'rank': 'form', 'deprecated': True, 'synonym_id': 4383}]
_fetch_accepted_data

============================================================
  Mushroom Observer  (MushroomObserverAPI)
  Species:   Not species
  Name type: not species
============================================================
_fetch_query_data
{'version': 2.0, 'run_date': '2026-06-23T04:25:47.575Z', 'errors': [{'code': 'API2::ObjectNotFoundByString', 'details': 'Name "Not species" does not exist, or someone has deleted it.', 'fatal': 'true', 'trace': "/var/web/mo/app/classes/api2/parsers/name_parser.rb:23:in 'API2::Parsers::NameParser#try_finding_by_string'\n/var/web/mo/app/classes/api2/parsers/name_parser.rb:13:in 'API2::Parsers::NameParser#find_object'\n/var/web/mo/app/classes/api2/parsers/object_base.rb:10:in 'API2::Parsers::ObjectBase#parse'\n/var/web/mo/app/classes/api2/parsers/base.rb:25:in 'API2::Parsers::Base#parse_scalar'\n/var/web/mo/app/classes/api2/parsers/base.rb:45:in 'API2::Parsers::Base#parse_array'\n/var/web/mo/app/classes/api2/core/parameters.rb:94:in 'API2::Parameters#parse_array'\n/var/web/mo/app/classes/api2/name_api.rb:23:in 'API2::NameAPI#query_params'\n/var/web/mo/app/classes/api2/model_api.rb:39:in 'API2::ModelAPI#build_query'\n/var/web/mo/app/classes/api2/model_api.rb:11:in 'API2::ModelAPI#get'\n/var/web/mo/app/classes/api2/core/base.rb:295:in 'API2::Base#process_request'\n/var/web/mo/app/classes/api2/core/base.rb:226:in 'API2::Base::ClassMethods#execute'\n/var/web/mo/app/controllers/api2_controller.rb:155:in 'API2Controller#render_api_results'\n/var/web/mo/app/controllers/api2_controller.rb:120:in 'API2Controller#rest_query'\n/var/web/mo/app/controllers/api2_controller.rb:69:in 'API2Controller#names'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_controller/metal/basic_implicit_render.rb:8:in 'ActionController::BasicImplicitRender#send_action'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/abstract_controller/base.rb:215:in 'AbstractController::Base#process_action'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_controller/metal/rendering.rb:193:in 'ActionController::Rendering#process_action'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/abstract_controller/callbacks.rb:261:in 'block in AbstractController::Callbacks#process_action'\n/home/mo/.gem/ruby/3.4.9/gems/activesupport-7.2.3.1/lib/active_support/callbacks.rb:121:in 'block in ActiveSupport::Callbacks#run_callbacks'\n/var/web/mo/app/controllers/application_controller.rb:148:in 'ApplicationController#catch_errors_and_log_request_stats'\n/home/mo/.gem/ruby/3.4.9/gems/activesupport-7.2.3.1/lib/active_support/callbacks.rb:130:in 'block in ActiveSupport::Callbacks#run_callbacks'\n/home/mo/.gem/ruby/3.4.9/gems/turbo-rails-2.0.23/lib/turbo-rails.rb:24:in 'Turbo.with_request_id'\n/home/mo/.gem/ruby/3.4.9/gems/turbo-rails-2.0.23/app/controllers/concerns/turbo/request_id_tracking.rb:10:in 'Turbo::RequestIdTracking#turbo_tracking_request_id'\n/home/mo/.gem/ruby/3.4.9/gems/activesupport-7.2.3.1/lib/active_support/callbacks.rb:130:in 'block in ActiveSupport::Callbacks#run_callbacks'\n/home/mo/.gem/ruby/3.4.9/gems/activesupport-7.2.3.1/lib/active_support/callbacks.rb:141:in 'ActiveSupport::Callbacks#run_callbacks'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/abstract_controller/callbacks.rb:260:in 'AbstractController::Callbacks#process_action'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_controller/metal/rescue.rb:27:in 'ActionController::Rescue#process_action'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_controller/metal/instrumentation.rb:77:in 'block in ActionController::Instrumentation#process_action'\n/home/mo/.gem/ruby/3.4.9/gems/activesupport-7.2.3.1/lib/active_support/notifications.rb:210:in 'block in ActiveSupport::Notifications.instrument'\n/home/mo/.gem/ruby/3.4.9/gems/activesupport-7.2.3.1/lib/active_support/notifications/instrumenter.rb:58:in 'ActiveSupport::Notifications::Instrumenter#instrument'\n/home/mo/.gem/ruby/3.4.9/gems/activesupport-7.2.3.1/lib/active_support/notifications.rb:210:in 'ActiveSupport::Notifications.instrument'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_controller/metal/instrumentation.rb:76:in 'ActionController::Instrumentation#process_action'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_controller/metal/params_wrapper.rb:259:in 'ActionController::ParamsWrapper#process_action'\n/home/mo/.gem/ruby/3.4.9/gems/activerecord-7.2.3.1/lib/active_record/railties/controller_runtime.rb:39:in 'ActiveRecord::Railties::ControllerRuntime#process_action'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/abstract_controller/base.rb:152:in 'AbstractController::Base#process'\n/home/mo/.gem/ruby/3.4.9/gems/actionview-7.2.3.1/lib/action_view/rendering.rb:40:in 'ActionView::Rendering#process'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_controller/metal.rb:252:in 'ActionController::Metal#dispatch'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_controller/metal.rb:335:in 'ActionController::Metal.dispatch'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/routing/route_set.rb:67:in 'ActionDispatch::Routing::RouteSet::Dispatcher#dispatch'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/routing/route_set.rb:50:in 'ActionDispatch::Routing::RouteSet::Dispatcher#serve'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/journey/router.rb:53:in 'block in ActionDispatch::Journey::Router#serve'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/journey/router.rb:133:in 'block in ActionDispatch::Journey::Router#find_routes'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/journey/router.rb:126:in 'Array#each'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/journey/router.rb:126:in 'ActionDispatch::Journey::Router#find_routes'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/journey/router.rb:34:in 'ActionDispatch::Journey::Router#serve'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/routing/route_set.rb:896:in 'ActionDispatch::Routing::RouteSet#call'\n/home/mo/.gem/ruby/3.4.9/gems/rack-3.2.6/lib/rack/tempfile_reaper.rb:20:in 'Rack::TempfileReaper#call'\n/home/mo/.gem/ruby/3.4.9/gems/rack-3.2.6/lib/rack/etag.rb:29:in 'Rack::ETag#call'\n/home/mo/.gem/ruby/3.4.9/gems/rack-3.2.6/lib/rack/conditional_get.rb:31:in 'Rack::ConditionalGet#call'\n/home/mo/.gem/ruby/3.4.9/gems/rack-3.2.6/lib/rack/head.rb:15:in 'Rack::Head#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/http/permissions_policy.rb:38:in 'ActionDispatch::PermissionsPolicy::Middleware#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/http/content_security_policy.rb:38:in 'ActionDispatch::ContentSecurityPolicy::Middleware#call'\n/home/mo/.gem/ruby/3.4.9/gems/rack-session-2.1.2/lib/rack/session/abstract/id.rb:274:in 'Rack::Session::Abstract::Persisted#context'\n/home/mo/.gem/ruby/3.4.9/gems/rack-session-2.1.2/lib/rack/session/abstract/id.rb:268:in 'Rack::Session::Abstract::Persisted#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/middleware/cookies.rb:704:in 'ActionDispatch::Cookies#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/middleware/callbacks.rb:31:in 'block in ActionDispatch::Callbacks#call'\n/home/mo/.gem/ruby/3.4.9/gems/activesupport-7.2.3.1/lib/active_support/callbacks.rb:101:in 'ActiveSupport::Callbacks#run_callbacks'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/middleware/callbacks.rb:30:in 'ActionDispatch::Callbacks#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/middleware/debug_exceptions.rb:31:in 'ActionDispatch::DebugExceptions#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/middleware/show_exceptions.rb:32:in 'ActionDispatch::ShowExceptions#call'\n/home/mo/.gem/ruby/3.4.9/gems/railties-7.2.3.1/lib/rails/rack/logger.rb:41:in 'Rails::Rack::Logger#call_app'\n/home/mo/.gem/ruby/3.4.9/gems/railties-7.2.3.1/lib/rails/rack/logger.rb:29:in 'Rails::Rack::Logger#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/middleware/remote_ip.rb:96:in 'ActionDispatch::RemoteIp#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/middleware/request_id.rb:33:in 'ActionDispatch::RequestId#call'\n/home/mo/.gem/ruby/3.4.9/gems/rack-3.2.6/lib/rack/method_override.rb:28:in 'Rack::MethodOverride#call'\n/home/mo/.gem/ruby/3.4.9/gems/rack-3.2.6/lib/rack/runtime.rb:24:in 'Rack::Runtime#call'\n/home/mo/.gem/ruby/3.4.9/gems/activesupport-7.2.3.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in 'ActiveSupport::Cache::Strategy::LocalCache::Middleware#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/middleware/executor.rb:16:in 'ActionDispatch::Executor#call'\n/home/mo/.gem/ruby/3.4.9/gems/rack-3.2.6/lib/rack/sendfile.rb:131:in 'Rack::Sendfile#call'\n/home/mo/.gem/ruby/3.4.9/gems/actionpack-7.2.3.1/lib/action_dispatch/middleware/ssl.rb:82:in 'ActionDispatch::SSL#call'\n/home/mo/.gem/ruby/3.4.9/gems/railties-7.2.3.1/lib/rails/engine.rb:535:in 'Rails::Engine#call'\n/home/mo/.gem/ruby/3.4.9/gems/puma-8.0.2/lib/puma/configuration.rb:305:in 'Puma::Configuration::ConfigMiddleware#call'\n/home/mo/.gem/ruby/3.4.9/gems/puma-8.0.2/lib/puma/response.rb:79:in 'block in Puma::Response#handle_request'\n/home/mo/.gem/ruby/3.4.9/gems/puma-8.0.2/lib/puma/thread_pool.rb:434:in 'Puma::ThreadPool#with_force_shutdown'\n/home/mo/.gem/ruby/3.4.9/gems/puma-8.0.2/lib/puma/response.rb:78:in 'Puma::Response#handle_request'\n/home/mo/.gem/ruby/3.4.9/gems/puma-8.0.2/lib/puma/server.rb:508:in 'Puma::Server#process_client'\n/home/mo/.gem/ruby/3.4.9/gems/puma-8.0.2/lib/puma/server.rb:263:in 'block in Puma::Server#run'\n/home/mo/.gem/ruby/3.4.9/gems/puma-8.0.2/lib/puma/thread_pool.rb:246:in 'block in Puma::ThreadPool#spawn_thread'"}], 'run_time': 0.075127018}
_fetch_synonym_data
[]
_fetch_accepted_data
[]
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

In [6]:
from scripts.config import GENBANK_PORTAL

# GenBank is run separately because NCBI rate-limits unauthenticated callers
# to 3 req/s. Each get_synonyms() makes 2 requests (esearch + efetch), so we
# sleep 1s between calls to stay well under the limit.
GENBANK_QUERIES = [
    ("Amanita muscaria",   "accepted"),
    ("Agaricus muscarius", "synonym"),
    ("Not species",        "not species"),
]
genbank_client = GenBankAPI()
for species, name_type in GENBANK_QUERIES:
    print(f"\n{'='*60}")
    print(f"  {GENBANK_PORTAL.display_name}  (GenBankAPI)")
    print(f"  Species:   {species}")
    print(f"  Name type: {name_type}")
    print(f"{'='*60}")
    try:
        result = genbank_client.get_synonyms(species)
        print(f"Synonyms returned: {len(result)}")
        show(result)
    except Exception as e:
        print(f"ERROR: {e}")
    time.sleep(1.0)  # NCBI rate limit: max 3 req/s; each call makes 2 requests

============================================================
  GenBank  (GenBankAPI)
  Species:   Amanita muscaria
  Name type: accepted
============================================================
_fetch_query_data
{'header': {'type': 'esearch', 'version': '0.3'}, 'esearchresult': {'count': '1', 'retmax': '1', 'retstart': '0', 'idlist': ['41956'], 'translationset': [], 'translationstack': [{'term': 'Amanita muscaria[Scientific Name]', 'field': 'Scientific Name', 'count': '1', 'explode': 'N'}, 'GROUP'], 'querytranslation': 'Amanita muscaria[Scientific Name]'}}
_fetch_synonym_data
<TaxaSet><Taxon>
    <TaxId>41956</TaxId>
    <ScientificName>Amanita muscaria</ScientificName>
    <OtherNames>
        <GenbankCommonName>fly agaric</GenbankCommonName>
        <Synonym>Agaricus muscarius</Synonym>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Agaricus muscarius L., 1753</DispName>
        </Name>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Amanita muscaria (L.) Lam., 1783</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria on Nothofagus fusca</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria/Nothofagus fusca</DispName>
        </Name>
    </OtherNames>
    <ParentTaxId>41955</ParentTaxId>
    <Rank>species</Rank>
    <Division>Plants and Fungi</Division>
    <GeneticCode>
        <GCId>1</GCId>
        <GCName>Standard</GCName>
    </GeneticCode>
    <MitoGeneticCode>
        <MGCId>4</MGCId>
        <MGCName>Mold Mitochondrial; Protozoan Mitochondrial; Coelenterate Mitochondrial; Mycoplasma; Spiroplasma</MGCName>
    </MitoGeneticCode>
    <Lineage>cellular organisms; Eukaryota; Opisthokonta; Fungi; Dikarya; Basidiomycota; Agaricomycotina; Agaricomycetes; Agaricomycetidae; Agaricales; Pluteineae; Amanitaceae; Amanita</Lineage>
    <LineageEx>
        <Taxon>
            <TaxId>131567</TaxId>
            <ScientificName>cellular organisms</ScientificName>
            <Rank>cellular root</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2759</TaxId>
            <ScientificName>Eukaryota</ScientificName>
            <Rank>domain</Rank>
        </Taxon>
        <Taxon>
            <TaxId>33154</TaxId>
            <ScientificName>Opisthokonta</ScientificName>
            <Rank>clade</Rank>
        </Taxon>
        <Taxon>
            <TaxId>4751</TaxId>
            <ScientificName>Fungi</ScientificName>
            <Rank>kingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>451864</TaxId>
            <ScientificName>Dikarya</ScientificName>
            <Rank>subkingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5204</TaxId>
            <ScientificName>Basidiomycota</ScientificName>
            <Rank>phylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5302</TaxId>
            <ScientificName>Agaricomycotina</ScientificName>
            <Rank>subphylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>155619</TaxId>
            <ScientificName>Agaricomycetes</ScientificName>
            <Rank>class</Rank>
        </Taxon>
        <Taxon>
            <TaxId>452333</TaxId>
            <ScientificName>Agaricomycetidae</ScientificName>
            <Rank>subclass</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5338</TaxId>
            <ScientificName>Agaricales</ScientificName>
            <Rank>order</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2982306</TaxId>
            <ScientificName>Pluteineae</ScientificName>
            <Rank>suborder</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41954</TaxId>
            <ScientificName>Amanitaceae</ScientificName>
            <Rank>family</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41955</TaxId>
            <ScientificName>Amanita</ScientificName>
            <Rank>genus</Rank>
        </Taxon>
    </LineageEx>
    <CreateDate>1995/08/04 11:19:00</CreateDate>
    <UpdateDate>2025/08/08 10:02:44</UpdateDate>
    <PubDate>1996/10/10 01:00:00</PubDate>
</Taxon>

</TaxaSet>
_fetch_accepted_data
<TaxaSet><Taxon>
    <TaxId>41956</TaxId>
    <ScientificName>Amanita muscaria</ScientificName>
    <OtherNames>
        <GenbankCommonName>fly agaric</GenbankCommonName>
        <Synonym>Agaricus muscarius</Synonym>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Agaricus muscarius L., 1753</DispName>
        </Name>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Amanita muscaria (L.) Lam., 1783</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria on Nothofagus fusca</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria/Nothofagus fusca</DispName>
        </Name>
    </OtherNames>
    <ParentTaxId>41955</ParentTaxId>
    <Rank>species</Rank>
    <Division>Plants and Fungi</Division>
    <GeneticCode>
        <GCId>1</GCId>
        <GCName>Standard</GCName>
    </GeneticCode>
    <MitoGeneticCode>
        <MGCId>4</MGCId>
        <MGCName>Mold Mitochondrial; Protozoan Mitochondrial; Coelenterate Mitochondrial; Mycoplasma; Spiroplasma</MGCName>
    </MitoGeneticCode>
    <Lineage>cellular organisms; Eukaryota; Opisthokonta; Fungi; Dikarya; Basidiomycota; Agaricomycotina; Agaricomycetes; Agaricomycetidae; Agaricales; Pluteineae; Amanitaceae; Amanita</Lineage>
    <LineageEx>
        <Taxon>
            <TaxId>131567</TaxId>
            <ScientificName>cellular organisms</ScientificName>
            <Rank>cellular root</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2759</TaxId>
            <ScientificName>Eukaryota</ScientificName>
            <Rank>domain</Rank>
        </Taxon>
        <Taxon>
            <TaxId>33154</TaxId>
            <ScientificName>Opisthokonta</ScientificName>
            <Rank>clade</Rank>
        </Taxon>
        <Taxon>
            <TaxId>4751</TaxId>
            <ScientificName>Fungi</ScientificName>
            <Rank>kingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>451864</TaxId>
            <ScientificName>Dikarya</ScientificName>
            <Rank>subkingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5204</TaxId>
            <ScientificName>Basidiomycota</ScientificName>
            <Rank>phylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5302</TaxId>
            <ScientificName>Agaricomycotina</ScientificName>
            <Rank>subphylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>155619</TaxId>
            <ScientificName>Agaricomycetes</ScientificName>
            <Rank>class</Rank>
        </Taxon>
        <Taxon>
            <TaxId>452333</TaxId>
            <ScientificName>Agaricomycetidae</ScientificName>
            <Rank>subclass</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5338</TaxId>
            <ScientificName>Agaricales</ScientificName>
            <Rank>order</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2982306</TaxId>
            <ScientificName>Pluteineae</ScientificName>
            <Rank>suborder</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41954</TaxId>
            <ScientificName>Amanitaceae</ScientificName>
            <Rank>family</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41955</TaxId>
            <ScientificName>Amanita</ScientificName>
            <Rank>genus</Rank>
        </Taxon>
    </LineageEx>
    <CreateDate>1995/08/04 11:19:00</CreateDate>
    <UpdateDate>2025/08/08 10:02:44</UpdateDate>
    <PubDate>1996/10/10 01:00:00</PubDate>
</Taxon>

</TaxaSet>
Synonyms returned: 2

============================================================
  GenBank  (GenBankAPI)
  Species:   Agaricus muscarius
  Name type: synonym
============================================================
_fetch_query_data
{'header': {'type': 'esearch', 'version': '0.3'}, 'esearchresult': {'count': '1', 'retmax': '1', 'retstart': '0', 'idlist': ['41956'], 'translationset': [], 'translationstack': [{'term': 'Agaricus muscarius[All Names]', 'field': 'All Names', 'count': '1', 'explode': 'N'}, 'GROUP'], 'querytranslation': 'Agaricus muscarius[All Names]'}}
_fetch_synonym_data
<TaxaSet><Taxon>
    <TaxId>41956</TaxId>
    <ScientificName>Amanita muscaria</ScientificName>
    <OtherNames>
        <GenbankCommonName>fly agaric</GenbankCommonName>
        <Synonym>Agaricus muscarius</Synonym>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Agaricus muscarius L., 1753</DispName>
        </Name>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Amanita muscaria (L.) Lam., 1783</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria on Nothofagus fusca</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria/Nothofagus fusca</DispName>
        </Name>
    </OtherNames>
    <ParentTaxId>41955</ParentTaxId>
    <Rank>species</Rank>
    <Division>Plants and Fungi</Division>
    <GeneticCode>
        <GCId>1</GCId>
        <GCName>Standard</GCName>
    </GeneticCode>
    <MitoGeneticCode>
        <MGCId>4</MGCId>
        <MGCName>Mold Mitochondrial; Protozoan Mitochondrial; Coelenterate Mitochondrial; Mycoplasma; Spiroplasma</MGCName>
    </MitoGeneticCode>
    <Lineage>cellular organisms; Eukaryota; Opisthokonta; Fungi; Dikarya; Basidiomycota; Agaricomycotina; Agaricomycetes; Agaricomycetidae; Agaricales; Pluteineae; Amanitaceae; Amanita</Lineage>
    <LineageEx>
        <Taxon>
            <TaxId>131567</TaxId>
            <ScientificName>cellular organisms</ScientificName>
            <Rank>cellular root</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2759</TaxId>
            <ScientificName>Eukaryota</ScientificName>
            <Rank>domain</Rank>
        </Taxon>
        <Taxon>
            <TaxId>33154</TaxId>
            <ScientificName>Opisthokonta</ScientificName>
            <Rank>clade</Rank>
        </Taxon>
        <Taxon>
            <TaxId>4751</TaxId>
            <ScientificName>Fungi</ScientificName>
            <Rank>kingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>451864</TaxId>
            <ScientificName>Dikarya</ScientificName>
            <Rank>subkingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5204</TaxId>
            <ScientificName>Basidiomycota</ScientificName>
            <Rank>phylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5302</TaxId>
            <ScientificName>Agaricomycotina</ScientificName>
            <Rank>subphylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>155619</TaxId>
            <ScientificName>Agaricomycetes</ScientificName>
            <Rank>class</Rank>
        </Taxon>
        <Taxon>
            <TaxId>452333</TaxId>
            <ScientificName>Agaricomycetidae</ScientificName>
            <Rank>subclass</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5338</TaxId>
            <ScientificName>Agaricales</ScientificName>
            <Rank>order</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2982306</TaxId>
            <ScientificName>Pluteineae</ScientificName>
            <Rank>suborder</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41954</TaxId>
            <ScientificName>Amanitaceae</ScientificName>
            <Rank>family</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41955</TaxId>
            <ScientificName>Amanita</ScientificName>
            <Rank>genus</Rank>
        </Taxon>
    </LineageEx>
    <CreateDate>1995/08/04 11:19:00</CreateDate>
    <UpdateDate>2025/08/08 10:02:44</UpdateDate>
    <PubDate>1996/10/10 01:00:00</PubDate>
</Taxon>

</TaxaSet>
_fetch_accepted_data
<TaxaSet><Taxon>
    <TaxId>41956</TaxId>
    <ScientificName>Amanita muscaria</ScientificName>
    <OtherNames>
        <GenbankCommonName>fly agaric</GenbankCommonName>
        <Synonym>Agaricus muscarius</Synonym>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Agaricus muscarius L., 1753</DispName>
        </Name>
        <Name>
            <ClassCDE>authority</ClassCDE>
            <DispName>Amanita muscaria (L.) Lam., 1783</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria on Nothofagus fusca</DispName>
        </Name>
        <Name>
            <ClassCDE>misspelling</ClassCDE>
            <DispName>Amanita muscaria/Nothofagus fusca</DispName>
        </Name>
    </OtherNames>
    <ParentTaxId>41955</ParentTaxId>
    <Rank>species</Rank>
    <Division>Plants and Fungi</Division>
    <GeneticCode>
        <GCId>1</GCId>
        <GCName>Standard</GCName>
    </GeneticCode>
    <MitoGeneticCode>
        <MGCId>4</MGCId>
        <MGCName>Mold Mitochondrial; Protozoan Mitochondrial; Coelenterate Mitochondrial; Mycoplasma; Spiroplasma</MGCName>
    </MitoGeneticCode>
    <Lineage>cellular organisms; Eukaryota; Opisthokonta; Fungi; Dikarya; Basidiomycota; Agaricomycotina; Agaricomycetes; Agaricomycetidae; Agaricales; Pluteineae; Amanitaceae; Amanita</Lineage>
    <LineageEx>
        <Taxon>
            <TaxId>131567</TaxId>
            <ScientificName>cellular organisms</ScientificName>
            <Rank>cellular root</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2759</TaxId>
            <ScientificName>Eukaryota</ScientificName>
            <Rank>domain</Rank>
        </Taxon>
        <Taxon>
            <TaxId>33154</TaxId>
            <ScientificName>Opisthokonta</ScientificName>
            <Rank>clade</Rank>
        </Taxon>
        <Taxon>
            <TaxId>4751</TaxId>
            <ScientificName>Fungi</ScientificName>
            <Rank>kingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>451864</TaxId>
            <ScientificName>Dikarya</ScientificName>
            <Rank>subkingdom</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5204</TaxId>
            <ScientificName>Basidiomycota</ScientificName>
            <Rank>phylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5302</TaxId>
            <ScientificName>Agaricomycotina</ScientificName>
            <Rank>subphylum</Rank>
        </Taxon>
        <Taxon>
            <TaxId>155619</TaxId>
            <ScientificName>Agaricomycetes</ScientificName>
            <Rank>class</Rank>
        </Taxon>
        <Taxon>
            <TaxId>452333</TaxId>
            <ScientificName>Agaricomycetidae</ScientificName>
            <Rank>subclass</Rank>
        </Taxon>
        <Taxon>
            <TaxId>5338</TaxId>
            <ScientificName>Agaricales</ScientificName>
            <Rank>order</Rank>
        </Taxon>
        <Taxon>
            <TaxId>2982306</TaxId>
            <ScientificName>Pluteineae</ScientificName>
            <Rank>suborder</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41954</TaxId>
            <ScientificName>Amanitaceae</ScientificName>
            <Rank>family</Rank>
        </Taxon>
        <Taxon>
            <TaxId>41955</TaxId>
            <ScientificName>Amanita</ScientificName>
            <Rank>genus</Rank>
        </Taxon>
    </LineageEx>
    <CreateDate>1995/08/04 11:19:00</CreateDate>
    <UpdateDate>2025/08/08 10:02:44</UpdateDate>
    <PubDate>1996/10/10 01:00:00</PubDate>
</Taxon>

</TaxaSet>
Synonyms returned: 2

============================================================
  GenBank  (GenBankAPI)
  Species:   Not species
  Name type: not species
============================================================
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

---
## Symbiota Portals

In [7]:
from scripts.config import SYMBIOTA_PORTAL_BY_NAME

_SYMBIOTA_QUERIES = [
    # (portal, accepted_species, synonym_of_accepted)
    (SYMBIOTA_PORTAL_BY_NAME["MyCoPortal"],                       "Agaricus campestris",     "Psalliota villatica"),
    (SYMBIOTA_PORTAL_BY_NAME["Lichen Portal"],                    "Xanthoria parietina",     "Physcia parietina"),
    (SYMBIOTA_PORTAL_BY_NAME["Bryophyte Portal"],                 "Pohlia nutans",           "Webera nutans"),
    (SYMBIOTA_PORTAL_BY_NAME["CCH2"],                             "Heteromeles arbutifolia", "Photinia arbutifolia"),
    (SYMBIOTA_PORTAL_BY_NAME["SERNEC"],                           "Magnolia grandiflora",    "Magnolia foetida"),
    (SYMBIOTA_PORTAL_BY_NAME["NANSH"],                            "Rudbeckia hirta",         "Coreopsis hirta"),
    (SYMBIOTA_PORTAL_BY_NAME["Algae Herbarium Portal"],           "Ulva intestinalis",       "Ilea intestinalis"),
    (SYMBIOTA_PORTAL_BY_NAME["Pterido Portal"],                   "Dryopteris filix-mas",    "Nephrodium filix-mas"),
    (SYMBIOTA_PORTAL_BY_NAME["CNH"],                              "Impatiens capensis",      "Impatiens biflora"),
    (SYMBIOTA_PORTAL_BY_NAME["Mid-Atlantic Herbaria Consortium"], "Quercus rubra",           "Quercus maxima"),
    (SYMBIOTA_PORTAL_BY_NAME["swbiodiversity"],                   "Larrea tridentata",       "Larrea mexicana"),
]

In [8]:
for portal, accepted, synonym in _SYMBIOTA_QUERIES:
    for species, name_type in [(accepted, "accepted"), (synonym, "synonym"), ("Not species", "not species")]:
        print(f"\n{'='*60}")
        print(f"  symbiota / {portal.display_name}")
        print(f"  URL:       {portal.base_url}")
        print(f"  Species:   {species}")
        print(f"  Name type: {name_type}  (synonym of: {accepted})" if name_type == "synonym" else f"  Name type: {name_type}")
        print(f"{'='*60}")
        try:
            client = SymbiotaAPI(portal.display_name)
            result = client.get_synonyms(species)
            print(f"Synonyms returned: {len(result)}")
            show(result)
        except Exception as e:
            print(f"ERROR: {e}")

============================================================
  symbiota / MyCoPortal
  URL:       https://mycoportal.org/portal
  Species:   Agaricus campestris
  Name type: accepted
============================================================
[MyCoPortal] 'api/v2/taxonomy/search' returned results for 'Agaricus campestris'.
_fetch_query_data
{'tid': 214862, 'kingdomName': 'Fungi', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Agaricus', 'unitInd2': None, 'unitName2': 'campestris', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': 'L.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2011-11-18 23:38:57', 'scientificName': 'Agaricus campestris'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Mycology Collections Portal  - Agaricus campestris</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<!-- Responsive viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/accessibility-compliant.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" disabled >
	<link href="/portal/css/symbiota/condensed.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" >

<link href="/portal/assets/custom/css/main.css" type="text/css" rel="stylesheet" />

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>
<script src="/portal/assets/custom/js/main.js" type="text/javascript"></script>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-1036HJZLL9"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-1036HJZLL9');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>

<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="contactUs">
						<button class="button button-tertiary bottom-breathing-room-rel left-breathing-room-rel" onclick="window.location.href='#'">Contact Us</button>
					</span>
					<span id="login">
						<form name="loginForm" method="post" action="/portal/profile/index.php">
							<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=214862">
							<button class="button button-secondary bottom-breathing-room-rel left-breathing-room-rel" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
						<div class="top-brand custom">
				<a href="/portal">
					<div class="image-container">
					</div>
				</a>
                				<div class="brand-name">
                    <h1 class="header-mast-title light"><span class="dark">Mycology</span> Collections Portal</h1>
					<h2></h2>
				</div>
			</div>

		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					                    <li class="search-menu">
                        <a href="/portal/collections/index.php">Explore</a>
                        <ul>
                            <li class="search-menu">
                                <a href="/portal/collections/index.php">Search</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/collections/search/index.php">Advanced Search</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/collections/map/index.php">Map Search</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/collections/exsiccati/index.php">Exsicatti</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/imagelib/search.php">Media Search</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/imagelib/index.php">Media Browser</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/imagelib/contributors.php">Media Providers</a>
                            </li>
                        </ul>
                    </li>

					                    <li class="crowdsource-menu">
                        <a href="/portal/collections/specprocessor/crowdsource/central.php">Crowdsource</a>
                        <ul>
                            <li class="crowdsource-menu">
                                <a href="/portal/misc/crowdsource.php">Get Involved</a>
                            </li>
                            <li class="crowdsource-menu">
                                <a href="/portal/collections/specprocessor/crowdsource/central.php">Score Board</a>
                            </li>
                        </ul>
                    </li>

					                    <li class="checklists-menu">
                        <a href="/portal/projects/index.php?">Checklist Projects</a>
                        <ul>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=13">Fungi (World): Historic</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=4">Fungi (North America): Historic</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=3">Macrofungi (North America): Groups</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=8">Macrofungi (North America): Local</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=2">Macrofungi (North America): Regions</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=7">Macrofungi (World): Countries</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=11">Microfungi (North America): Regions</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=12">Microfungi (World): Countries</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/checklists/dynamicmap.php?interface=checklist">Dynamic Checklist</a>
                            </li>
                        </ul>
                    </li>


					                    <li class="other-menu">
                        <a href="#">Other Resources</a>
                        <ul>
                            <li class="other-menu">
                                <a href="/portal/collections/misc/collstats.php">Collection Statistics</a>
                            </li>
                            <li class="other-menu">
                                <a href="/portal/tk/?/taxonomy-report">Collection taxonomy report</a>
                            </li>
                            <li class="other-menu">
                                <a href="/portal/tk/?/genbank">GenBank source modifiers</a>
                            </li>
                            <li class="other-menu">
                                <a href="/portal/tk/?/">Symbiota toolkit</a>
                            </li>
                            <li class="other-menu">
                                <a href="/portal/misc/links.php">Document Links</a>
                            </li>
                            <li class="other-menu">
                                <a href="https://bryophyteportal.org/portal" target="_blank" rel="noopener noreferrer">Bryophyte Portal</a>
                            </li>
                            <li class="other-menu">
                                <a href="https://lichenportal.org/portal" target="_blank" rel="noopener noreferrer">Lichen Portal</a>
                            </li>
                            <li class="other-menu">
                                <a href="https://swbiodiversity.org/seinet" target="_blank" rel="noopener noreferrer">Vascular Plant Portal</a>
                            </li>
                            <li class="other-menu">
                                <a href="https://symbiota.org" target="_blank" rel="noopener noreferrer">Symbiota Help Page</a>
                            </li>
                        </ul>
                    </li>

										<li class="acknowledgements-menu">
                        <a href="/portal/misc/acknowledgements.php">Acknowledgements</a>
					</li>

					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>

					<li id="lang-select-li">
						<label for="language-selection">Select Language: </label>
						<select oninput="setLanguage(this)" id="language-selection" name="language-selection">
							<option value="en">English</option>
							<option value="es" >Español</option>
							<option value="fr" >Français</option>
							<option value="pt" >Português</option>
						</select>
					</li>
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Agaricus campestris</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Agaricus campestris</i></span>							<span id="author">L.</span>
							&nbsp;<a href="index.php?tid=11736&amp;clid=0&amp;pid=2&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Agaricaceae</div>
						<div id="synonymDiv" title="Synonyms">[<i>Psalliota villatica</i> (Brond.) Bres.]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../imagelib/imgdetails.php?mediaid=43107');return false;"><img src="http://images.mushroomobserver.org/1280/210023.jpg" title="" alt="Agaricus campestris image" /></a></div><div class="creator">NAMA Voucher Collection Project</div></div>					</td>
					<td class="desc">
						<div id="desctabs" class="ui-tabs" style="display:none"><ul class="ui-tabs-nav"><li><a href="resourcetab.php?tid=214862">Resources</a></li></ul>					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="img-div" style="height:300px;overflow:hidden;">

============================================================
  symbiota / MyCoPortal
  URL:       https://mycoportal.org/portal
  Species:   Psalliota villatica
  Name type: synonym  (synonym of: Agaricus campestris)
============================================================
[MyCoPortal] 'api/v2/taxonomy/search' returned results for 'Psalliota villatica'.
_fetch_query_data
{'tid': 527987, 'kingdomName': 'Fungi', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Psalliota', 'unitInd2': None, 'unitName2': 'villatica', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(Brond.) Bres.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'Index Fungorum', 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2011-11-19 14:07:42', 'scientificName': 'Psalliota villatica'}
_fetch_synonym_data
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Mycology Collections Portal  - Agaricus campestris</title>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<link href="/portal/css/jquery-ui.css" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/taxa/index.css" type="text/css" rel="stylesheet" />
	<link href="/portal/css/symbiota/taxa/traitplot.css" type="text/css" rel="stylesheet" >
	<!-- Responsive viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Symbiota styles -->
<link href="/portal/css/symbiota/header.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/footer.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/main.css?ver=16" type="text/css" rel="stylesheet">
<link href="/portal/css/symbiota/customizations.css?ver=16" type="text/css" rel="stylesheet">
	<link href="/portal/css/symbiota/accessibility-compliant.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" disabled >
	<link href="/portal/css/symbiota/condensed.css?ver=16" type="text/css" rel="stylesheet" data-accessibility-link="accessibility-css-link" >

<link href="/portal/assets/custom/css/main.css" type="text/css" rel="stylesheet" />

<script src="/portal/js/symb/lang.js" type="text/javascript"></script>
<script src="/portal/assets/custom/js/main.js" type="text/javascript"></script>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=G-1036HJZLL9"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'G-1036HJZLL9');
	</script>
		<script src="/portal/js/jquery-3.7.1.min.js" type="text/javascript"></script>
	<script src="/portal/js/jquery-ui.min.js" type="text/javascript"></script>
	<script src="../js/symb/taxa.index.js?ver=202101" type="text/javascript"></script>
	<script src="../js/symb/taxa.editor.js?ver=202101" type="text/javascript"></script>
	<style type="text/css">
		.resource-title{ font-weight: bold; }
	</style>
</head>
<body>

<div class="header-wrapper">
	<header>
		<div class="top-wrapper">
			<a class="screen-reader-only" href="#end-nav">Skip Navigation</a>
			<nav class="top-login" aria-label="horizontal-nav">
									<span id="contactUs">
						<button class="button button-tertiary bottom-breathing-room-rel left-breathing-room-rel" onclick="window.location.href='#'">Contact Us</button>
					</span>
					<span id="login">
						<form name="loginForm" method="post" action="/portal/profile/index.php">
							<input name="refurl" type="hidden" value="/portal/taxa/index.php?tid=214862">
							<button class="button button-secondary bottom-breathing-room-rel left-breathing-room-rel" name="loginButton" type="submit">Sign In</button>
						</form>
					</span>
								</nav>
						<div class="top-brand custom">
				<a href="/portal">
					<div class="image-container">
					</div>
				</a>
                				<div class="brand-name">
                    <h1 class="header-mast-title light"><span class="dark">Mycology</span> Collections Portal</h1>
					<h2></h2>
				</div>
			</div>

		</div>
		<div class="menu-wrapper">
			<!-- Hamburger icon -->
			<input class="side-menu" type="checkbox" id="side-menu" name="side-menu" />
			<label class="hamb hamb-line hamb-label" for="side-menu" tabindex="0">☰</label>
			<!-- Menu -->
			<nav class="top-menu" aria-label="hamburger-nav">
				<ul class="menu">
					<li>
						<a href="/portal/index.php">
							Home						</a>
					</li>
					                    <li class="search-menu">
                        <a href="/portal/collections/index.php">Explore</a>
                        <ul>
                            <li class="search-menu">
                                <a href="/portal/collections/index.php">Search</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/collections/search/index.php">Advanced Search</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/collections/map/index.php">Map Search</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/collections/exsiccati/index.php">Exsicatti</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/imagelib/search.php">Media Search</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/imagelib/index.php">Media Browser</a>
                            </li>
                            <li class="search-menu">
                                <a href="/portal/imagelib/contributors.php">Media Providers</a>
                            </li>
                        </ul>
                    </li>

					                    <li class="crowdsource-menu">
                        <a href="/portal/collections/specprocessor/crowdsource/central.php">Crowdsource</a>
                        <ul>
                            <li class="crowdsource-menu">
                                <a href="/portal/misc/crowdsource.php">Get Involved</a>
                            </li>
                            <li class="crowdsource-menu">
                                <a href="/portal/collections/specprocessor/crowdsource/central.php">Score Board</a>
                            </li>
                        </ul>
                    </li>

					                    <li class="checklists-menu">
                        <a href="/portal/projects/index.php?">Checklist Projects</a>
                        <ul>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=13">Fungi (World): Historic</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=4">Fungi (North America): Historic</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=3">Macrofungi (North America): Groups</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=8">Macrofungi (North America): Local</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=2">Macrofungi (North America): Regions</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=7">Macrofungi (World): Countries</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=11">Microfungi (North America): Regions</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/projects/index.php?pid=12">Microfungi (World): Countries</a>
                            </li>
                            <li class="checklists-menu">
                                <a href="/portal/checklists/dynamicmap.php?interface=checklist">Dynamic Checklist</a>
                            </li>
                        </ul>
                    </li>


					                    <li class="other-menu">
                        <a href="#">Other Resources</a>
                        <ul>
                            <li class="other-menu">
                                <a href="/portal/collections/misc/collstats.php">Collection Statistics</a>
                            </li>
                            <li class="other-menu">
                                <a href="/portal/tk/?/taxonomy-report">Collection taxonomy report</a>
                            </li>
                            <li class="other-menu">
                                <a href="/portal/tk/?/genbank">GenBank source modifiers</a>
                            </li>
                            <li class="other-menu">
                                <a href="/portal/tk/?/">Symbiota toolkit</a>
                            </li>
                            <li class="other-menu">
                                <a href="/portal/misc/links.php">Document Links</a>
                            </li>
                            <li class="other-menu">
                                <a href="https://bryophyteportal.org/portal" target="_blank" rel="noopener noreferrer">Bryophyte Portal</a>
                            </li>
                            <li class="other-menu">
                                <a href="https://lichenportal.org/portal" target="_blank" rel="noopener noreferrer">Lichen Portal</a>
                            </li>
                            <li class="other-menu">
                                <a href="https://swbiodiversity.org/seinet" target="_blank" rel="noopener noreferrer">Vascular Plant Portal</a>
                            </li>
                            <li class="other-menu">
                                <a href="https://symbiota.org" target="_blank" rel="noopener noreferrer">Symbiota Help Page</a>
                            </li>
                        </ul>
                    </li>

										<li class="acknowledgements-menu">
                        <a href="/portal/misc/acknowledgements.php">Acknowledgements</a>
					</li>

					<li>
						<a href='/portal/sitemap.php'>
							Sitemap						</a>
					</li>

					<li id="lang-select-li">
						<label for="language-selection">Select Language: </label>
						<select oninput="setLanguage(this)" id="language-selection" name="language-selection">
							<option value="en">English</option>
							<option value="es" >Español</option>
							<option value="fr" >Français</option>
							<option value="pt" >Português</option>
						</select>
					</li>
				</ul>
			</nav>
		</div>
		<div id="end-nav"></div>
	</header>
</div>
<div id="popup-innertext">
	<h1 class="page-heading screen-reader-only">Agaricus campestris</h1>
					<table id="innertable">
				<tr>
					<td colspan="2" style="vertical-align: bottom">
												<div id="scinameDiv">
							<span id="sciname"><i>Agaricus campestris</i></span>							<span id="author">L.</span>
							&nbsp;<a href="index.php?tid=11736&amp;clid=0&amp;pid=2&amp;taxauthid=1"><img class="navIcon" src="../images/toparent.png" title="Go to Parent Taxon"></a>						</div>
													<div id="linkDiv">
															</div>
												</td>
				</tr>
				<tr>
					<td width="300" style="vertical-align=top">
						<div id="family"><b>Family:</b> Agaricaceae</div>
						<div id="synonymDiv" title="Synonyms">[<i>Psalliota villatica</i> (Brond.) Bres.]</div><div id="centralimage"><div class="tptnimg"><a href="#" onclick="openPopup('../imagelib/imgdetails.php?mediaid=43107');return false;"><img src="http://images.mushroomobserver.org/1280/210023.jpg" title="" alt="Agaricus campestris image" /></a></div><div class="creator">NAMA Voucher Collection Project</div></div>					</td>
					<td class="desc">
						<div id="desctabs" class="ui-tabs" style="display:none"><ul class="ui-tabs-nav"><li><a href="resourcetab.php?tid=214862">Resources</a></li></ul>					</td>
				</tr>
				<tr>
					<td colspan="2">
						<div id="img-div" style="height:300px;overflow:hidden;">

============================================================
  symbiota / MyCoPortal
  URL:       https://mycoportal.org/portal
  Species:   Not species
  Name type: not species
============================================================
[MyCoPortal] Search endpoint returned no results for 'Not species'. Attempting autocomplete search.
[MyCoPortal] All searches failed or returned no results for 'Not species'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, order, subfamily, genus, species, author, publication_name, publication_year, status, original_source, api_link, api_internal_id]
Index: []

============================================================
  symbiota / Lichen Portal
  URL:       https://lichenportal.org/portal
  Species:   Xanthoria parietina
  Name type: accepted
============================================================
[Lichen Portal] 'api/v2/taxonomy' returned results for 'Xanthoria parietina'.
_fetch_query_data
{'tid': 56389, 'kingdomName': 'Fungi', 'rankID': 220, 'rankName': None, 'unitInd1': None, 'unitName1': 'Xanthoria', 'unitInd2': None, 'unitName2': 'parietina', 'unitInd3': None, 'unitName3': None, 'cultivarEpithet': None, 'tradeName': None, 'author': '(L.) Th. Fr.', 'reviewStatus': None, 'displayStatus': None, 'isLegitimate': None, 'source': 'USDA PLANTS DB', 'sourceIdentifier': None, 'notes': None, 'securityStatus': 0, 'modifiedTimestamp': None, 'initialTimestamp': '2008-09-29 12:52:57', 'scientificName': 'Xanthoria parietina'}

KeyboardInterrupt: