# Test: `get_synonyms()` for all APIs_pipe clients

Run from the **project root** so that `scripts/` is on the Python path.

Covers:
- COL, GBIF, GenBank, Index Fungorum, MushroomObserver, Tropicos
- Symbiota portals: MyCoPortal, Lichen, Bryophyte, CCH2, SERNEC, NANSH, Macroalgae, Pterido, NE Herbaria, Mid-Atlantic, SW Biodiversity

In [ ]:
import time
import sys, os
# Ensure the project root is on sys.path when running from notebooks.apis_pipe/
project_root = os.path.abspath(os.path.join(os.getcwd(), "../.."))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from IPython.display import display

from scripts.apis_pipe.col import COLAPI
from scripts.apis_pipe.gbif import GBIFAPI
from scripts.apis_pipe.genbank import GenBankAPI
from scripts.apis_pipe.index_fungorum import IndexFungorumAPI
from scripts.apis_pipe.mushroomobs import MushroomObserverAPI
from scripts.apis_pipe.symbiota import SymbiotaAPI
from scripts.apis_pipe.tropicos import TropicosAPI
from scripts.apis_pipe.fishbase import FishBaseAPI

---
## Standard APIs

In [ ]:
from scripts.apis_pipe.config import (
    COL_PORTAL,
    GBIF_PORTAL,
    INDEX_FUNGORUM_PORTAL,
    MUSHROOM_OBSERVER_PORTAL,
    TROPICOS_PORTAL,
    FISHBASE_PORTAL
)

STANDARD_QUERIES = [
    # (portal, client, accepted_species, synonym_of_accepted)
    # (COL_PORTAL,               COLAPI(),              "Quercus robur",    "Quercus atrosanguinea"),
    # (GBIF_PORTAL,              GBIFAPI(),             "Amanita muscaria", "Agaricus muscarius"),
    # (INDEX_FUNGORUM_PORTAL,    IndexFungorumAPI(),    "Amanita muscaria", "Agaricus muscarius"),
    # (MUSHROOM_OBSERVER_PORTAL, MushroomObserverAPI(), "Amanita muscaria", "Amanita amerimuscaria"),
    # (TROPICOS_PORTAL,          TropicosAPI(),         "Quercus robur",    "Quercus pedunculata"),
    (FISHBASE_PORTAL,          FishBaseAPI(),         "Gadus morhua",     "Gadus callarias"),
]

In [ ]:
# display(GBIFAPI().get_synonyms("Agaricus muscarius"))

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,GBIF,U,U,U,U,U,Amanita,muscaria,(L.) Lam.,Encycl. Méth. Bot. (Paris) 1(1): 111.,1783,U,U,https://www.gbif.org/species/8168319,8168319
1,GBIF,U,U,U,U,U,Agaricus,aureolus,Kalchbr.,Icon. Sel. Hymenomyc. Hung. (Budapest) 1: 9.,1873,U,U,https://www.gbif.org/species/5455639,5455639
2,GBIF,U,U,U,U,U,Agaricus,imperialis,Batsch,Elench. Fung. (Halle): 59.,1783,U,U,https://www.gbif.org/species/5955425,5955425
3,GBIF,U,U,U,U,U,Agaricus,muscarius,L.,Sp. Pl. 2: 1172.,1753,U,U,https://www.gbif.org/species/5451774,5451774
4,GBIF,U,U,U,U,U,Agaricus,nobilis,Bolton,"Hist. Fung. Halifax (Huddersfield) 2: 46, Tab....",1788,U,U,https://www.gbif.org/species/3329091,3329091
5,GBIF,U,U,U,U,U,Agaricus,pseudoaurantiacus,Bull.,"Hist. Champ. Fr. (Paris) 2(2): 673, Pl. 122.",1792,U,U,https://www.gbif.org/species/3329092,3329092
6,GBIF,U,U,U,U,U,Agaricus,puellus,Batsch,Elench. Fung. (Halle): 59.,1786,U,U,https://www.gbif.org/species/5452606,5452606
7,GBIF,U,U,U,U,U,Amanita,aureola,(Kalchbr.) Sacc.,Syll. Fung. (Abellini) 5: 12.,1887,U,U,https://www.gbif.org/species/5452441,5452441
8,GBIF,U,U,U,U,U,Amanita,circinnata,Gray,Nat. Arr. Brit. Pl. (London) 1: 600.,1821,U,U,https://www.gbif.org/species/5452605,5452605
9,GBIF,U,U,U,U,U,Amanita,formosa,Gonn. & Rabenh.,"Myc. Europ. (Dresden) 1-2: Tab. 10, Fig. 2.",1869,U,U,https://www.gbif.org/species/5452657,5452657
10,GBIF,U,U,U,U,U,Amanita,muscaria,(L.) Hook.,,,U,U,https://www.gbif.org/species/3329049,3329049
11,GBIF,U,U,U,U,U,Amanita,puella,(Batsch) Gonnerm. & Rabenh.,,,U,U,https://www.gbif.org/species/5452294,5452294
12,GBIF,U,U,U,U,U,Amanitaria,muscaria,(L.) E.-J.Gilbert,"In Bresadola, Iconogr. mycol., Suppl. I (Milan...",1940,U,U,https://www.gbif.org/species/3301084,3301084
13,GBIF,U,U,U,U,U,Hypophyllum,muscarium,(L.) Paulet,"Traité Champ. (Paris) 2: 346, Tab. 157, Figs 1...",1808,U,U,https://www.gbif.org/species/12357845,12357845
14,GBIF,U,U,U,U,U,Venenarius,muscarius,(L.) Millsp.,"West Virginia Geol. Surv., Ser. A 5(1): 131.",1913,U,U,https://www.gbif.org/species/12282853,12282853

In [3]:
for portal, client, accepted, synonym in STANDARD_QUERIES:
    for species, name_type in [(accepted, "accepted"), (synonym, "synonym")]:
        print(f"\n{'='*60}")
        print(f"  {portal.display_name}  ({client.__class__.__name__})")
        print(f"  Species:   {species}")
        print(f"  Name type: {name_type}  (synonym of: {accepted})" if name_type == "synonym" else f"  Name type: {name_type}")
        print(f"{'='*60}")
        try:
            result = client.get_synonyms(species)
            print(f"Synonyms returned: {len(result)}")
            display(result)
        except Exception as e:
            print(f"ERROR: {e}")

============================================================
  COL  (COLAPI)
  Species:   Quercus robur
  Name type: accepted
============================================================
Synonyms returned: 17

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,COL,U,U,U,U,U,Quercus,robur,L.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/4R5YN,4R5YN
1,COL,U,U,U,U,U,Quercus,atrosanguinea,hort.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/SF5RP,SF5RP
2,COL,U,U,U,U,U,Quercus,belgica,Gand.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/8X4Z4,8X4Z4
3,COL,U,U,U,U,U,Quercus,cupressoides,hort.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/SFBKJ,SFBKJ
4,COL,U,U,U,U,U,Quercus,feminea,Mill.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/SFDVF,SFDVF
5,COL,U,U,U,U,U,Quercus,filicifolia,hort. ex A.DC.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/SFDXP,SFDXP
6,COL,U,U,U,U,U,Quercus,foemida,Mill.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/4R4Y4,4R4Y4
7,COL,U,U,U,U,U,Quercus,hentzei,Petz.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/SFGZ6,SFGZ6
8,COL,U,U,U,U,U,Quercus,hohenackeri,Gand.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/8X52M,8X52M
9,COL,U,U,U,U,U,Quercus,louettii,Dippel,U,U,U,U,https://www.catalogueoflife.org/data/taxon/SFMTB,SFMTB
10,COL,U,U,U,U,U,Quercus,malacophylla,Borbás,U,U,U,U,https://www.catalogueoflife.org/data/taxon/5R46R,5R46R
11,COL,U,U,U,U,U,Quercus,pedunculata,Ehrh.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/SFRGP,SFRGP
12,COL,U,U,U,U,U,Quercus,pseudopeduncula,Vuk.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/SFSTJ,SFSTJ
13,COL,U,U,U,U,U,Quercus,robur,(Loudon) O. Schwarz,U,U,U,U,https://www.catalogueoflife.org/data/taxon/SFV5H,SFV5H
14,COL,U,U,U,U,U,Quercus,robur,Vuk.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/5R4FK,5R4FK
15,COL,U,U,U,U,U,Quercus,robur,(Hoffm.) Hook.f.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/5R4GP,5R4GP
16,COL,U,U,U,U,U,Quercus,transiens,A.Reyn.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/CDY39,CDY39

============================================================
  COL  (COLAPI)
  Species:   Quercus atrosanguinea
  Name type: synonym  (synonym of: Quercus robur)
============================================================
Synonyms returned: 356

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,COL,U,U,U,U,U,Quercus,robur,,U,U,U,U,https://www.catalogueoflife.org/data/taxon/5KTTT,5KTTT
1,COL,U,U,U,U,U,Quercus,abbreviata,Vuk.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/4R45Z,4R45Z
2,COL,U,U,U,U,U,Quercus,accessiva,Gand.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/8X4Y9,8X4Y9
3,COL,U,U,U,U,U,Quercus,accomodata,Gand.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/8X4YB,8X4YB
4,COL,U,U,U,U,U,Quercus,acutiloba,Borbás,U,U,U,U,https://www.catalogueoflife.org/data/taxon/4R46X,4R46X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,COL,U,U,U,U,U,Quercus,sessiliflora,(Lapeyr.) Nyman,U,U,U,U,https://www.catalogueoflife.org/data/taxon/5R4L3,5R4L3
352,COL,U,U,U,U,U,Quercus,tomentosa,Ehrh. ex A.DC.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/8X4FJ,8X4FJ
353,COL,U,U,U,U,U,Quercus,tristis,Gand.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/8X4FN,8X4FN
354,COL,U,U,U,U,U,Quercus,turbinata,Kit.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/4R6CC,4R6CC
355,COL,U,U,U,U,U,Quercus,vallicola,Gand.,U,U,U,U,https://www.catalogueoflife.org/data/taxon/8X4FT,8X4FT

============================================================
  GBIF  (GBIFAPI)
  Species:   Amanita muscaria
  Name type: accepted
============================================================
Synonyms returned: 15

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,GBIF,U,U,U,U,U,Amanita,muscaria,,,,U,U,https://www.gbif.org/species/8168319,8168319
1,GBIF,U,U,U,U,U,Agaricus,aureolus,Kalchbr.,Icon. Sel. Hymenomyc. Hung. (Budapest) 1: 9.,1873,U,U,https://www.gbif.org/species/5455639,5455639
2,GBIF,U,U,U,U,U,Agaricus,imperialis,Batsch,Elench. Fung. (Halle): 59.,1783,U,U,https://www.gbif.org/species/5955425,5955425
3,GBIF,U,U,U,U,U,Agaricus,muscarius,L.,Sp. Pl. 2: 1172.,1753,U,U,https://www.gbif.org/species/5451774,5451774
4,GBIF,U,U,U,U,U,Agaricus,nobilis,Bolton,"Hist. Fung. Halifax (Huddersfield) 2: 46, Tab....",1788,U,U,https://www.gbif.org/species/3329091,3329091
5,GBIF,U,U,U,U,U,Agaricus,pseudoaurantiacus,Bull.,"Hist. Champ. Fr. (Paris) 2(2): 673, Pl. 122.",1792,U,U,https://www.gbif.org/species/3329092,3329092
6,GBIF,U,U,U,U,U,Agaricus,puellus,Batsch,Elench. Fung. (Halle): 59.,1786,U,U,https://www.gbif.org/species/5452606,5452606
7,GBIF,U,U,U,U,U,Amanita,aureola,(Kalchbr.) Sacc.,Syll. Fung. (Abellini) 5: 12.,1887,U,U,https://www.gbif.org/species/5452441,5452441
8,GBIF,U,U,U,U,U,Amanita,circinnata,Gray,Nat. Arr. Brit. Pl. (London) 1: 600.,1821,U,U,https://www.gbif.org/species/5452605,5452605
9,GBIF,U,U,U,U,U,Amanita,formosa,Gonn. & Rabenh.,"Myc. Europ. (Dresden) 1-2: Tab. 10, Fig. 2.",1869,U,U,https://www.gbif.org/species/5452657,5452657
10,GBIF,U,U,U,U,U,Amanita,muscaria,(L.) Hook.,,,U,U,https://www.gbif.org/species/3329049,3329049
11,GBIF,U,U,U,U,U,Amanita,puella,(Batsch) Gonnerm. & Rabenh.,,,U,U,https://www.gbif.org/species/5452294,5452294
12,GBIF,U,U,U,U,U,Amanitaria,muscaria,(L.) E.-J.Gilbert,"In Bresadola, Iconogr. mycol., Suppl. I (Milan...",1940,U,U,https://www.gbif.org/species/3301084,3301084
13,GBIF,U,U,U,U,U,Hypophyllum,muscarium,(L.) Paulet,"Traité Champ. (Paris) 2: 346, Tab. 157, Figs 1...",1808,U,U,https://www.gbif.org/species/12357845,12357845
14,GBIF,U,U,U,U,U,Venenarius,muscarius,(L.) Millsp.,"West Virginia Geol. Surv., Ser. A 5(1): 131.",1913,U,U,https://www.gbif.org/species/12282853,12282853

============================================================
  GBIF  (GBIFAPI)
  Species:   Agaricus muscarius
  Name type: synonym  (synonym of: Amanita muscaria)
============================================================
Synonyms returned: 15

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,GBIF,U,U,U,U,U,Amanita,muscaria,(L.) Lam.,Encycl. Méth. Bot. (Paris) 1(1): 111.,1783,U,U,https://www.gbif.org/species/8168319,8168319
1,GBIF,U,U,U,U,U,Agaricus,aureolus,Kalchbr.,Icon. Sel. Hymenomyc. Hung. (Budapest) 1: 9.,1873,U,U,https://www.gbif.org/species/5455639,5455639
2,GBIF,U,U,U,U,U,Agaricus,imperialis,Batsch,Elench. Fung. (Halle): 59.,1783,U,U,https://www.gbif.org/species/5955425,5955425
3,GBIF,U,U,U,U,U,Agaricus,muscarius,L.,Sp. Pl. 2: 1172.,1753,U,U,https://www.gbif.org/species/5451774,5451774
4,GBIF,U,U,U,U,U,Agaricus,nobilis,Bolton,"Hist. Fung. Halifax (Huddersfield) 2: 46, Tab....",1788,U,U,https://www.gbif.org/species/3329091,3329091
5,GBIF,U,U,U,U,U,Agaricus,pseudoaurantiacus,Bull.,"Hist. Champ. Fr. (Paris) 2(2): 673, Pl. 122.",1792,U,U,https://www.gbif.org/species/3329092,3329092
6,GBIF,U,U,U,U,U,Agaricus,puellus,Batsch,Elench. Fung. (Halle): 59.,1786,U,U,https://www.gbif.org/species/5452606,5452606
7,GBIF,U,U,U,U,U,Amanita,aureola,(Kalchbr.) Sacc.,Syll. Fung. (Abellini) 5: 12.,1887,U,U,https://www.gbif.org/species/5452441,5452441
8,GBIF,U,U,U,U,U,Amanita,circinnata,Gray,Nat. Arr. Brit. Pl. (London) 1: 600.,1821,U,U,https://www.gbif.org/species/5452605,5452605
9,GBIF,U,U,U,U,U,Amanita,formosa,Gonn. & Rabenh.,"Myc. Europ. (Dresden) 1-2: Tab. 10, Fig. 2.",1869,U,U,https://www.gbif.org/species/5452657,5452657
10,GBIF,U,U,U,U,U,Amanita,muscaria,(L.) Hook.,,,U,U,https://www.gbif.org/species/3329049,3329049
11,GBIF,U,U,U,U,U,Amanita,puella,(Batsch) Gonnerm. & Rabenh.,,,U,U,https://www.gbif.org/species/5452294,5452294
12,GBIF,U,U,U,U,U,Amanitaria,muscaria,(L.) E.-J.Gilbert,"In Bresadola, Iconogr. mycol., Suppl. I (Milan...",1940,U,U,https://www.gbif.org/species/3301084,3301084
13,GBIF,U,U,U,U,U,Hypophyllum,muscarium,(L.) Paulet,"Traité Champ. (Paris) 2: 346, Tab. 157, Figs 1...",1808,U,U,https://www.gbif.org/species/12357845,12357845
14,GBIF,U,U,U,U,U,Venenarius,muscarius,(L.) Millsp.,"West Virginia Geol. Surv., Ser. A 5(1): 131.",1913,U,U,https://www.gbif.org/species/12282853,12282853

============================================================
  Index Fungorum  (IndexFungorumAPI)
  Species:   Amanita muscaria
  Name type: accepted
============================================================
Synonyms returned: 13

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,Index Fungorum,U,U,U,U,U,Agaricus,aureolus,Kalchbr.,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,298478
1,Index Fungorum,U,U,U,U,U,Agaricus,imperialis,Batsch,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,495382
2,Index Fungorum,U,U,U,U,U,Agaricus,muscarius,L.,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,375287
3,Index Fungorum,U,U,U,U,U,Agaricus,nobilis,Bolton,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,450473
4,Index Fungorum,U,U,U,U,U,Agaricus,pseudoaurantiacus,Bull.,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,494787
5,Index Fungorum,U,U,U,U,U,Agaricus,puellus,Batsch,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,372222
6,Index Fungorum,U,U,U,U,U,Amanita,aureola,(Kalchbr.) Sacc.,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,209653
7,Index Fungorum,U,U,U,U,U,Amanita,circinnata,Gray,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,486444
8,Index Fungorum,U,U,U,U,U,Amanita,formosa,Gonn. & Rabenh.,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,212977
9,Index Fungorum,U,U,U,U,U,Amanita,muscaria,(L.) Lam.,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,161267
10,Index Fungorum,U,U,U,U,U,Amanitaria,muscaria,(L.) E.-J. Gilbert,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,284092
11,Index Fungorum,U,U,U,U,U,Hypophyllum,muscarium,(L.) Paulet,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,652473
12,Index Fungorum,U,U,U,U,U,Venenarius,muscarius,(L.) Earle,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,100185

============================================================
  Index Fungorum  (IndexFungorumAPI)
  Species:   Agaricus muscarius
  Name type: synonym  (synonym of: Amanita muscaria)
============================================================
Synonyms returned: 13

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,Index Fungorum,U,U,U,U,U,Agaricus,aureolus,Kalchbr.,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,298478
1,Index Fungorum,U,U,U,U,U,Agaricus,imperialis,Batsch,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,495382
2,Index Fungorum,U,U,U,U,U,Agaricus,muscarius,L.,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,375287
3,Index Fungorum,U,U,U,U,U,Agaricus,nobilis,Bolton,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,450473
4,Index Fungorum,U,U,U,U,U,Agaricus,pseudoaurantiacus,Bull.,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,494787
5,Index Fungorum,U,U,U,U,U,Agaricus,puellus,Batsch,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,372222
6,Index Fungorum,U,U,U,U,U,Amanita,aureola,(Kalchbr.) Sacc.,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,209653
7,Index Fungorum,U,U,U,U,U,Amanita,circinnata,Gray,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,486444
8,Index Fungorum,U,U,U,U,U,Amanita,formosa,Gonn. & Rabenh.,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,212977
9,Index Fungorum,U,U,U,U,U,Amanita,muscaria,(L.) Lam.,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,161267
10,Index Fungorum,U,U,U,U,U,Amanitaria,muscaria,(L.) E.-J. Gilbert,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,284092
11,Index Fungorum,U,U,U,U,U,Hypophyllum,muscarium,(L.) Paulet,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,652473
12,Index Fungorum,U,U,U,U,U,Venenarius,muscarius,(L.) Earle,U,U,U,U,https://www.indexfungorum.org/Names/NamesRecor...,100185

============================================================
  Mushroom Observer  (MushroomObserverAPI)
  Species:   Amanita muscaria
  Name type: accepted
============================================================
Synonyms returned: 3

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,Mushroom Observer,U,U,U,U,U,Amanita,muscaria,(L.) Lam.,U,U,U,U,U,373
1,Mushroom Observer,U,U,U,U,U,Amanita,amerimuscaria,Tulloss & Geml nom. prov.,U,U,U,U,U,16015
2,Mushroom Observer,U,U,U,U,U,Amanita,muscaria,sensu auct. amer.,U,U,U,U,U,28495

============================================================
  Mushroom Observer  (MushroomObserverAPI)
  Species:   Amanita amerimuscaria
  Name type: synonym  (synonym of: Amanita muscaria)
============================================================
Synonyms returned: 3

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,Mushroom Observer,U,U,U,U,U,Amanita,amerimuscaria,Tulloss & Geml nom. prov.,U,U,U,U,U,16015
1,Mushroom Observer,U,U,U,U,U,Amanita,amerimuscaria,Tulloss & Geml nom. prov.,U,U,U,U,U,16015
2,Mushroom Observer,U,U,U,U,U,Amanita,muscaria,sensu auct. amer.,U,U,U,U,U,28495

============================================================
  Tropicos  (TropicosAPI)
  Species:   Quercus robur
  Name type: accepted
============================================================
Synonyms returned: 2

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,Tropicos,U,U,U,U,U,Quercus,robur,L.,U,U,U,U,https://www.tropicos.org/name/13100004,13100004
1,Tropicos,U,U,U,U,U,Quercus,pedunculata,,U,U,U,U,https://www.tropicos.org/name/13100434,13100434

============================================================
  Tropicos  (TropicosAPI)
  Species:   Quercus pedunculata
  Name type: synonym  (synonym of: Quercus robur)
============================================================
Synonyms returned: 2

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,Tropicos,U,U,U,U,U,Quercus,robur,L.,U,U,U,U,https://www.tropicos.org/name/13100004,13100004
1,Tropicos,U,U,U,U,U,Quercus,pedunculata,,U,U,U,U,https://www.tropicos.org/name/13100434,13100434

In [6]:
from scripts.apis_pipe.config import GENBANK_PORTAL

# GenBank is run separately because NCBI rate-limits unauthenticated callers
# to 3 req/s. Each get_synonyms() makes 2 requests (esearch + efetch), so we
# sleep 1s between calls to stay well under the limit.
GENBANK_QUERIES = [
    ("Amanita muscaria",   "accepted"),
    ("Agaricus muscarius", "synonym"),
]
genbank_client = GenBankAPI()
for species, name_type in GENBANK_QUERIES:
    print(f"\n{'='*60}")
    print(f"  {GENBANK_PORTAL.display_name}  (GenBankAPI)")
    print(f"  Species:   {species}")
    print(f"  Name type: {name_type}")
    print(f"{'='*60}")
    try:
        result = genbank_client.get_synonyms(species)
        print(f"Synonyms returned: {len(result)}")
        display(result)
    except Exception as e:
        print(f"ERROR: {e}")
    time.sleep(1.0)  # NCBI rate limit: max 3 req/s; each call makes 2 requests

============================================================
  GenBank  (GenBankAPI)
  Species:   Amanita muscaria
  Name type: accepted
============================================================
Synonyms returned: 2

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,GenBank,U,U,U,U,U,Amanita,muscaria,U,U,U,U,U,https://www.ncbi.nlm.nih.gov/taxonomy/41956,41956
1,GenBank,U,U,U,U,U,Agaricus,muscarius,U,U,U,U,U,https://www.ncbi.nlm.nih.gov/taxonomy/41956,41956

============================================================
  GenBank  (GenBankAPI)
  Species:   Agaricus muscarius
  Name type: synonym
============================================================
Synonyms returned: 2

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,GenBank,U,U,U,U,U,Amanita,muscaria,U,U,U,U,U,https://www.ncbi.nlm.nih.gov/taxonomy/41956,41956
1,GenBank,U,U,U,U,U,Agaricus,muscarius,U,U,U,U,U,https://www.ncbi.nlm.nih.gov/taxonomy/41956,41956

---
## Symbiota Portals

In [7]:
from scripts.apis_pipe.config import SYMBIOTA_PORTAL_BY_NAME

_SYMBIOTA_QUERIES = [
    # (portal, accepted_species, synonym_of_accepted)
    (SYMBIOTA_PORTAL_BY_NAME["MyCoPortal"],                    "Agaricus campestris",     "Psalliota villatica"),
    (SYMBIOTA_PORTAL_BY_NAME["Lichen Portal"],                 "Xanthoria parietina",     "Physcia parietina"),
    (SYMBIOTA_PORTAL_BY_NAME["Bryophyte Portal"],              "Pohlia nutans",           "Webera nutans"),
    # Photinia arbutifolia is a synonym OF Heteromeles arbutifolia (toyon)
    (SYMBIOTA_PORTAL_BY_NAME["CCH2"],                          "Heteromeles arbutifolia", "Photinia arbutifolia"),
    (SYMBIOTA_PORTAL_BY_NAME["SERNEC"],                        "Magnolia grandiflora",    "Magnolia foetida"),
    (SYMBIOTA_PORTAL_BY_NAME["NANSH"],                         "Rudbeckia hirta",         "Coreopsis hirta"),
    (SYMBIOTA_PORTAL_BY_NAME["Algae Herbarium Portal"],        "Ulva intestinalis",       "Ilea intestinalis"),
    (SYMBIOTA_PORTAL_BY_NAME["Pterido Portal"],                "Dryopteris filix-mas",    "Nephrodium filix-mas"),
    (SYMBIOTA_PORTAL_BY_NAME["CNH"],                           "Impatiens capensis",      "Impatiens biflora"),
    (SYMBIOTA_PORTAL_BY_NAME["Mid-Atlantic Herbaria Consortium"], "Quercus rubra",         "Quercus maxima"),
    (SYMBIOTA_PORTAL_BY_NAME["swbiodiversity"],                "Larrea tridentata",       "Larrea mexicana"),
]

In [8]:
for portal, accepted, synonym in _SYMBIOTA_QUERIES:
    for species, name_type in [(accepted, "accepted"), (synonym, "synonym")]:
        print(f"\n{'='*60}")
        print(f"  symbiota / {portal.display_name}")
        print(f"  URL:       {portal.base_url}")
        print(f"  Species:   {species}")
        print(f"  Name type: {name_type}  (synonym of: {accepted})" if name_type == "synonym" else f"  Name type: {name_type}")
        print(f"{'='*60}")
        try:
            client = SymbiotaAPI(portal.display_name)
            result = client.get_synonyms(species)
            print(f"Synonyms returned: {len(result)}")
            display(result)
        except Exception as e:
            print(f"ERROR: {e}")

============================================================
  symbiota / MyCoPortal
  URL:       https://mycoportal.org/portal
  Species:   Agaricus campestris
  Name type: accepted
============================================================
[MyCoPortal] 'api/v2/taxonomy/search' returned results for 'Agaricus campestris'.
Synonyms returned: 2

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,MyCoPortal,U,U,U,U,U,Agaricus,campestris,L.,U,U,U,U,https://mycoportal.org/portal/taxa/index.php?t...,214862
1,MyCoPortal,U,U,U,U,U,Psalliota,villatica,(Brond.) Bres.],U,U,U,U,https://mycoportal.org/portal/taxa/index.php?t...,214862

============================================================
  symbiota / MyCoPortal
  URL:       https://mycoportal.org/portal
  Species:   Psalliota villatica
  Name type: synonym  (synonym of: Agaricus campestris)
============================================================
[MyCoPortal] 'api/v2/taxonomy/search' returned results for 'Psalliota villatica'.
Synonyms returned: 2

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,MyCoPortal,U,U,U,U,U,Agaricus,campestris,L.,U,U,U,U,https://mycoportal.org/portal/taxa/index.php?t...,214862
1,MyCoPortal,U,U,U,U,U,Psalliota,villatica,(Brond.) Bres.],U,U,U,U,https://mycoportal.org/portal/taxa/index.php?t...,214862

============================================================
  symbiota / Lichen Portal
  URL:       https://lichenportal.org/portal
  Species:   Xanthoria parietina
  Name type: accepted
============================================================
[Lichen Portal] 'api/v2/taxonomy/search' returned no results for 'Xanthoria parietina'.
[Lichen Portal] 'api/v2/taxonomy' returned results for 'Xanthoria parietina'.
Synonyms returned: 15

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,Lichen Portal,U,U,U,U,U,Xanthoria,parietina,(L.) Th. Fr.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
1,Lichen Portal,U,U,U,U,U,Blasteniospora,parietina,(L.) Trevis.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
2,Lichen Portal,U,U,U,U,U,Geissodea,parietina,(L.) J. St.-Hill.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
3,Lichen Portal,U,U,U,U,U,Imbricaria,parietina,(L.) DC.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
4,Lichen Portal,U,U,U,U,U,Lecanora,rutilans,(Ach.) Ach.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
5,Lichen Portal,U,U,U,U,U,Lichen,rutilans,Ach.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
6,Lichen Portal,U,U,U,U,U,Lobaria,parietina,(L.) Hoffm.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
7,Lichen Portal,U,U,U,U,U,Parmelia,rutilans,(Ach.) Ach.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
8,Lichen Portal,U,U,U,U,U,Physcia,ectanea,(Ach.) Linds.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
9,Lichen Portal,U,U,U,U,U,Physcia,parietina,(L.) De Not.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
10,Lichen Portal,U,U,U,U,U,Platysma,parietinum,(L.) Frege,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
11,Lichen Portal,U,U,U,U,U,Teloschistes,parietinus,(Ach.) F. Wilson,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
12,Lichen Portal,U,U,U,U,U,Xanthoria,coomae,S.Y. Kondr. & Kärnefelt,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
13,Lichen Portal,U,U,U,U,U,Xanthoria,ectanea,(Ach.) Räsänen ex Filson,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
14,Lichen Portal,U,U,U,U,U,Xanthoria,polessica,S. Y. Kondr. et A. P. Yatsyna,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389

============================================================
  symbiota / Lichen Portal
  URL:       https://lichenportal.org/portal
  Species:   Physcia parietina
  Name type: synonym  (synonym of: Xanthoria parietina)
============================================================
[Lichen Portal] 'api/v2/taxonomy/search' returned no results for 'Physcia parietina'.
[Lichen Portal] 'api/v2/taxonomy' returned results for 'Physcia parietina'.
Synonyms returned: 15

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,Lichen Portal,U,U,U,U,U,Xanthoria,parietina,(L.) Th. Fr.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
1,Lichen Portal,U,U,U,U,U,Blasteniospora,parietina,(L.) Trevis.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
2,Lichen Portal,U,U,U,U,U,Geissodea,parietina,(L.) J. St.-Hill.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
3,Lichen Portal,U,U,U,U,U,Imbricaria,parietina,(L.) DC.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
4,Lichen Portal,U,U,U,U,U,Lecanora,rutilans,(Ach.) Ach.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
5,Lichen Portal,U,U,U,U,U,Lichen,rutilans,Ach.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
6,Lichen Portal,U,U,U,U,U,Lobaria,parietina,(L.) Hoffm.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
7,Lichen Portal,U,U,U,U,U,Parmelia,rutilans,(Ach.) Ach.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
8,Lichen Portal,U,U,U,U,U,Physcia,ectanea,(Ach.) Linds.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
9,Lichen Portal,U,U,U,U,U,Physcia,parietina,(L.) De Not.,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
10,Lichen Portal,U,U,U,U,U,Platysma,parietinum,(L.) Frege,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
11,Lichen Portal,U,U,U,U,U,Teloschistes,parietinus,(Ach.) F. Wilson,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
12,Lichen Portal,U,U,U,U,U,Xanthoria,coomae,S.Y. Kondr. & Kärnefelt,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
13,Lichen Portal,U,U,U,U,U,Xanthoria,ectanea,(Ach.) Räsänen ex Filson,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389
14,Lichen Portal,U,U,U,U,U,Xanthoria,polessica,S. Y. Kondr. et A. P. Yatsyna,U,U,U,U,https://lichenportal.org/portal/taxa/index.php...,56389

============================================================
  symbiota / Bryophyte Portal
  URL:       https://bryophyteportal.org/portal
  Species:   Pohlia nutans
  Name type: accepted
============================================================
[Bryophyte Portal] 'api/v2/taxonomy/search' returned no results for 'Pohlia nutans'.
[Bryophyte Portal] 'api/v2/taxonomy' returned results for 'Pohlia nutans'.
Synonyms returned: 74

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,Bryophyte Portal,U,U,U,U,U,Pohlia,nutans,(Hedw.) Lindb.,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406
1,Bryophyte Portal,U,U,U,U,U,Bryum,afronutans,Müll. Hal.,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406
2,Bryophyte Portal,U,U,U,U,U,Bryum,austronutans,Müll. Hal.,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406
3,Bryophyte Portal,U,U,U,U,U,Bryum,basalticum,Warnst. & Geh.,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406
4,Bryophyte Portal,U,U,U,U,U,Bryum,bealeyense,(Huebener) Delogne,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Bryophyte Portal,U,U,U,U,U,Webera,rutilans,Schimp.,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406
70,Bryophyte Portal,U,U,U,U,U,Webera,schimperi,(Müll. Hal.) Schimp.,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406
71,Bryophyte Portal,U,U,U,U,U,Webera,sphagnadelphus,(Müll. Hal.) Besch.,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406
72,Bryophyte Portal,U,U,U,U,U,Webera,strangulata,Nees,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406
73,Bryophyte Portal,U,U,U,U,U,Webera,subdenticulata,(Brid.) Brid.,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406

============================================================
  symbiota / Bryophyte Portal
  URL:       https://bryophyteportal.org/portal
  Species:   Webera nutans
  Name type: synonym  (synonym of: Pohlia nutans)
============================================================
[Bryophyte Portal] 'api/v2/taxonomy/search' returned no results for 'Webera nutans'.
[Bryophyte Portal] 'api/v2/taxonomy' returned results for 'Webera nutans'.
Synonyms returned: 74

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,Bryophyte Portal,U,U,U,U,U,Pohlia,nutans,(Hedw.) Lindb.,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406
1,Bryophyte Portal,U,U,U,U,U,Bryum,afronutans,Müll. Hal.,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406
2,Bryophyte Portal,U,U,U,U,U,Bryum,austronutans,Müll. Hal.,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406
3,Bryophyte Portal,U,U,U,U,U,Bryum,basalticum,Warnst. & Geh.,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406
4,Bryophyte Portal,U,U,U,U,U,Bryum,bealeyense,(Huebener) Delogne,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Bryophyte Portal,U,U,U,U,U,Webera,rutilans,Schimp.,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406
70,Bryophyte Portal,U,U,U,U,U,Webera,schimperi,(Müll. Hal.) Schimp.,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406
71,Bryophyte Portal,U,U,U,U,U,Webera,sphagnadelphus,(Müll. Hal.) Besch.,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406
72,Bryophyte Portal,U,U,U,U,U,Webera,strangulata,Nees,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406
73,Bryophyte Portal,U,U,U,U,U,Webera,subdenticulata,(Brid.) Brid.,U,U,U,U,https://bryophyteportal.org/portal/taxa/index....,160406

============================================================
  symbiota / CCH2
  URL:       https://cch2.org/portal
  Species:   Heteromeles arbutifolia
  Name type: accepted
============================================================
[CCH2] 'api/v2/taxonomy/search' returned no results for 'Heteromeles arbutifolia'.
[CCH2] 'api/v2/taxonomy' returned results for 'Heteromeles arbutifolia'.
Synonyms returned: 5

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,CCH2,U,U,U,U,U,Heteromeles,arbutifolia,(Lindl.) M. Roem.,U,U,U,U,https://cch2.org/portal/taxa/index.php?tid=22929,22929
1,CCH2,U,U,U,U,U,Heteromeles,fremontiana,Decne.,U,U,U,U,https://cch2.org/portal/taxa/index.php?taxon=2...,22929
2,CCH2,U,U,U,U,U,Heteromeles,salicifolia,(C. Presl) Abrams,U,U,U,U,https://cch2.org/portal/taxa/index.php?taxon=2...,22929
3,CCH2,U,U,U,U,U,Photinia,arbutifolia,Lindl.,U,U,U,U,https://cch2.org/portal/taxa/index.php?taxon=2...,22929
4,CCH2,U,U,U,U,U,Photinia,salicifolia,C. Presl,U,U,U,U,https://cch2.org/portal/taxa/index.php?taxon=2...,22929

============================================================
  symbiota / CCH2
  URL:       https://cch2.org/portal
  Species:   Photinia arbutifolia
  Name type: synonym  (synonym of: Heteromeles arbutifolia)
============================================================
[CCH2] 'api/v2/taxonomy/search' returned no results for 'Photinia arbutifolia'.
[CCH2] 'api/v2/taxonomy' returned results for 'Photinia arbutifolia'.
Synonyms returned: 5

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,CCH2,U,U,U,U,U,Heteromeles,arbutifolia,(Lindl.) M. Roem.,U,U,U,U,https://cch2.org/portal/taxa/index.php?tid=22929,22929
1,CCH2,U,U,U,U,U,Heteromeles,fremontiana,Decne.,U,U,U,U,https://cch2.org/portal/taxa/index.php?taxon=2...,22929
2,CCH2,U,U,U,U,U,Heteromeles,salicifolia,(C. Presl) Abrams,U,U,U,U,https://cch2.org/portal/taxa/index.php?taxon=2...,22929
3,CCH2,U,U,U,U,U,Photinia,arbutifolia,Lindl.,U,U,U,U,https://cch2.org/portal/taxa/index.php?taxon=2...,22929
4,CCH2,U,U,U,U,U,Photinia,salicifolia,C. Presl,U,U,U,U,https://cch2.org/portal/taxa/index.php?taxon=2...,22929

============================================================
  symbiota / SERNEC
  URL:       https://sernecportal.org/portal
  Species:   Magnolia grandiflora
  Name type: accepted
============================================================
[SERNEC] 'api/v2/taxonomy/search' returned no results for 'Magnolia grandiflora'.
SymbiotaAPI fetch error [https://sernecportal.org/portal/api/v2/taxonomy]: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
[SERNEC] 'api/v2/taxonomy' returned an error; trying next endpoint.
[SERNEC] All search endpoints returned no results for 'Magnolia grandiflora'. Attempting autocomplete search.
SymbiotaAPI fetch error [https://sernecportal.org/portal/taxa/taxonomy/rpc/gettaxasuggest.php]: HTTPSConnectionPool(host='sernecportal.org', port=443): Read timed out. (read timeout=10)
[SERNEC] All searches failed or returned no results for 'Magnolia grandiflora'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, subfamily, genus, species, author, publication_name, publication_year, status, source_name, api_link, api_internal_id]
Index: []

============================================================
  symbiota / SERNEC
  URL:       https://sernecportal.org/portal
  Species:   Magnolia foetida
  Name type: synonym  (synonym of: Magnolia grandiflora)
============================================================
[SERNEC] 'api/v2/taxonomy/search' returned no results for 'Magnolia foetida'.
SymbiotaAPI fetch error [https://sernecportal.org/portal/api/v2/taxonomy]: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
[SERNEC] 'api/v2/taxonomy' returned an error; trying next endpoint.
[SERNEC] All search endpoints returned no results for 'Magnolia foetida'. Attempting autocomplete search.
SymbiotaAPI fetch error [https://sernecportal.org/portal/taxa/taxonomy/rpc/gettaxasuggest.php]: HTTPSConnectionPool(host='sernecportal.org', port=443): Read timed out. (read timeout=10)
[SERNEC] All searches failed or returned no results for 'Magnolia foetida'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, subfamily, genus, species, author, publication_name, publication_year, status, source_name, api_link, api_internal_id]
Index: []

============================================================
  symbiota / NANSH
  URL:       https://nansh.org/portal
  Species:   Rudbeckia hirta
  Name type: accepted
============================================================
SymbiotaAPI fetch error [https://nansh.org/portal/api/v2/taxonomy/search]: HTTPSConnectionPool(host='nansh.org', port=443): Read timed out. (read timeout=10)
[NANSH] 'api/v2/taxonomy/search' returned an error; trying next endpoint.
SymbiotaAPI fetch error [https://nansh.org/portal/api/v2/taxonomy]: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
[NANSH] 'api/v2/taxonomy' returned an error; trying next endpoint.
[NANSH] All search endpoints returned no results for 'Rudbeckia hirta'. Attempting autocomplete search.
SymbiotaAPI fetch error [https://nansh.org/portal/taxa/taxonomy/rpc/gettaxasuggest.php]: HTTPSConnectionPool(host='nansh.org', port=443): Read timed out. (read timeout=10)
[NANSH] All searches failed or returned no results for 'Rudbeckia hirta'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, subfamily, genus, species, author, publication_name, publication_year, status, source_name, api_link, api_internal_id]
Index: []

============================================================
  symbiota / NANSH
  URL:       https://nansh.org/portal
  Species:   Coreopsis hirta
  Name type: synonym  (synonym of: Rudbeckia hirta)
============================================================
SymbiotaAPI fetch error [https://nansh.org/portal/api/v2/taxonomy/search]: HTTPSConnectionPool(host='nansh.org', port=443): Max retries exceeded with url: /portal/api/v2/taxonomy/search?taxon=Coreopsis+hirta&type=EXACT&limit=100&offset=0 (Caused by ConnectTimeoutError(<HTTPSConnection(host='nansh.org', port=443) at 0x309c0e210>, 'Connection to nansh.org timed out. (connect timeout=10)'))
[NANSH] 'api/v2/taxonomy/search' returned an error; trying next endpoint.
SymbiotaAPI fetch error [https://nansh.org/portal/api/v2/taxonomy]: HTTPSConnectionPool(host='nansh.org', port=443): Max retries exceeded with url: /portal/api/v2/taxonomy?taxon=Coreopsis+hirta&type=EXACT&limit=100&offset=0 (Caused by ConnectTimeoutError(<HTTPSConnection(host='nansh.org', port=443) at 0x309c0e270>, 'Connection to nansh.org timed out. (connect timeout=10)'))
[NANSH] 'api/v2/taxonomy' returned an error; trying next endpoint.
[NANSH] All search endpoints returned no results for 'Coreopsis hirta'. Attempting autocomplete search.
SymbiotaAPI fetch error [https://nansh.org/portal/taxa/taxonomy/rpc/gettaxasuggest.php]: HTTPSConnectionPool(host='nansh.org', port=443): Read timed out. (read timeout=10)
[NANSH] All searches failed or returned no results for 'Coreopsis hirta'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, subfamily, genus, species, author, publication_name, publication_year, status, source_name, api_link, api_internal_id]
Index: []

============================================================
  symbiota / Algae Herbarium Portal
  URL:       https://macroalgae.org/portal
  Species:   Ulva intestinalis
  Name type: accepted
============================================================
[Algae Herbarium Portal] 'api/v2/taxonomy/search' returned no results for 'Ulva intestinalis'.
[Algae Herbarium Portal] 'api/v2/taxonomy' returned results for 'Ulva intestinalis'.
Synonyms returned: 3

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,Algae Herbarium Portal,U,U,U,U,U,Ulva,intestinalis,Linnaeus,U,U,U,U,https://macroalgae.org/portal/taxa/index.php?t...,76122
1,Algae Herbarium Portal,U,U,U,U,U,Ilea,intestinalis,(Linnaeus) Leiblein,U,U,U,U,https://macroalgae.org/portal/taxa/index.php?t...,76122
2,Algae Herbarium Portal,U,U,U,U,U,Tetraspora,intestinalis,(Linnaeus) Desvaux,U,U,U,U,https://macroalgae.org/portal/taxa/index.php?t...,76122

============================================================
  symbiota / Algae Herbarium Portal
  URL:       https://macroalgae.org/portal
  Species:   Ilea intestinalis
  Name type: synonym  (synonym of: Ulva intestinalis)
============================================================
[Algae Herbarium Portal] 'api/v2/taxonomy/search' returned no results for 'Ilea intestinalis'.
[Algae Herbarium Portal] 'api/v2/taxonomy' returned results for 'Ilea intestinalis'.
Synonyms returned: 3

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,Algae Herbarium Portal,U,U,U,U,U,Ulva,intestinalis,Linnaeus,U,U,U,U,https://macroalgae.org/portal/taxa/index.php?t...,76122
1,Algae Herbarium Portal,U,U,U,U,U,Ilea,intestinalis,(Linnaeus) Leiblein,U,U,U,U,https://macroalgae.org/portal/taxa/index.php?t...,76122
2,Algae Herbarium Portal,U,U,U,U,U,Tetraspora,intestinalis,(Linnaeus) Desvaux,U,U,U,U,https://macroalgae.org/portal/taxa/index.php?t...,76122

============================================================
  symbiota / Pterido Portal
  URL:       https://pteridoportal.org/portal
  Species:   Dryopteris filix-mas
  Name type: accepted
============================================================
[Pterido Portal] 'api/v2/taxonomy/search' returned no results for 'Dryopteris filix-mas'.
[Pterido Portal] 'api/v2/taxonomy' returned results for 'Dryopteris filix-mas'.
Synonyms returned: 8

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,Pterido Portal,U,U,U,U,U,Dryopteris,filix-mas,,U,U,U,U,https://pteridoportal.org/portal/taxa/index.ph...,386
1,Pterido Portal,U,U,U,U,U,Filix,filix-mas,,U,U,U,U,https://pteridoportal.org/portal/taxa/index.ph...,386
2,Pterido Portal,U,U,U,U,U,Filix-mas,filix-mas,Farw.,U,U,U,U,https://pteridoportal.org/portal/taxa/index.ph...,386
3,Pterido Portal,U,U,U,U,U,Filix-mas,vulgaris,Hill ex Farw.,U,U,U,U,https://pteridoportal.org/portal/taxa/index.ph...,386
4,Pterido Portal,U,U,U,U,U,Nephrodium,filix-mas,(L.) Rich.,U,U,U,U,https://pteridoportal.org/portal/taxa/index.ph...,386
5,Pterido Portal,U,U,U,U,U,Polypodium,umbilicatum,Poir.,U,U,U,U,https://pteridoportal.org/portal/taxa/index.ph...,386
6,Pterido Portal,U,U,U,U,U,Polystichum,filix-mas,Roth,U,U,U,U,https://pteridoportal.org/portal/taxa/index.ph...,386
7,Pterido Portal,U,U,U,U,U,Polystichum,polysorum,Tod.,U,U,U,U,https://pteridoportal.org/portal/taxa/index.ph...,386

============================================================
  symbiota / Pterido Portal
  URL:       https://pteridoportal.org/portal
  Species:   Nephrodium filix-mas
  Name type: synonym  (synonym of: Dryopteris filix-mas)
============================================================
[Pterido Portal] 'api/v2/taxonomy/search' returned no results for 'Nephrodium filix-mas'.
[Pterido Portal] 'api/v2/taxonomy' returned results for 'Nephrodium filix-mas'.
Synonyms returned: 8

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,Pterido Portal,U,U,U,U,U,Dryopteris,filix-mas,,U,U,U,U,https://pteridoportal.org/portal/taxa/index.ph...,386
1,Pterido Portal,U,U,U,U,U,Filix,filix-mas,,U,U,U,U,https://pteridoportal.org/portal/taxa/index.ph...,386
2,Pterido Portal,U,U,U,U,U,Filix-mas,filix-mas,Farw.,U,U,U,U,https://pteridoportal.org/portal/taxa/index.ph...,386
3,Pterido Portal,U,U,U,U,U,Filix-mas,vulgaris,Hill ex Farw.,U,U,U,U,https://pteridoportal.org/portal/taxa/index.ph...,386
4,Pterido Portal,U,U,U,U,U,Nephrodium,filix-mas,(L.) Rich.,U,U,U,U,https://pteridoportal.org/portal/taxa/index.ph...,386
5,Pterido Portal,U,U,U,U,U,Polypodium,umbilicatum,Poir.,U,U,U,U,https://pteridoportal.org/portal/taxa/index.ph...,386
6,Pterido Portal,U,U,U,U,U,Polystichum,filix-mas,Roth,U,U,U,U,https://pteridoportal.org/portal/taxa/index.ph...,386
7,Pterido Portal,U,U,U,U,U,Polystichum,polysorum,Tod.,U,U,U,U,https://pteridoportal.org/portal/taxa/index.ph...,386

============================================================
  symbiota / CNH
  URL:       https://neherbaria.org/portal
  Species:   Impatiens capensis
  Name type: accepted
============================================================
[CNH] 'api/v2/taxonomy/search' returned no results for 'Impatiens capensis'.
[CNH] 'api/v2/taxonomy' returned results for 'Impatiens capensis'.
Synonyms returned: 4

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,CNH,U,U,U,U,U,Impatiens,capensis,Meerb.,U,U,U,U,https://neherbaria.org/portal/taxa/index.php?t...,824846
1,CNH,U,U,U,U,U,Impatiens,biflora,Walter,U,U,U,U,https://neherbaria.org/portal/taxa/index.php?t...,824846
2,CNH,U,U,U,U,U,Impatiens,fulva,Nutt.,U,U,U,U,https://neherbaria.org/portal/taxa/index.php?t...,824846
3,CNH,U,U,U,U,U,Impatiens,nortonii,Rydb.,U,U,U,U,https://neherbaria.org/portal/taxa/index.php?t...,824846

============================================================
  symbiota / CNH
  URL:       https://neherbaria.org/portal
  Species:   Impatiens biflora
  Name type: synonym  (synonym of: Impatiens capensis)
============================================================
[CNH] 'api/v2/taxonomy/search' returned no results for 'Impatiens biflora'.
[CNH] 'api/v2/taxonomy' returned results for 'Impatiens biflora'.
Synonyms returned: 4

,api_name,kingdom,phylum,class,family,subfamily,genus,species,author,publication_name,publication_year,status,source_name,api_link,api_internal_id
0,CNH,U,U,U,U,U,Impatiens,capensis,Meerb.,U,U,U,U,https://neherbaria.org/portal/taxa/index.php?t...,824846
1,CNH,U,U,U,U,U,Impatiens,biflora,Walter,U,U,U,U,https://neherbaria.org/portal/taxa/index.php?t...,824846
2,CNH,U,U,U,U,U,Impatiens,fulva,Nutt.,U,U,U,U,https://neherbaria.org/portal/taxa/index.php?t...,824846
3,CNH,U,U,U,U,U,Impatiens,nortonii,Rydb.,U,U,U,U,https://neherbaria.org/portal/taxa/index.php?t...,824846

============================================================
  symbiota / Mid-Atlantic Herbaria Consortium
  URL:       https://midatlanticherbaria.org/portal
  Species:   Quercus rubra
  Name type: accepted
============================================================
SymbiotaAPI fetch error [https://midatlanticherbaria.org/portal/api/v2/taxonomy/search]: HTTPSConnectionPool(host='midatlanticherbaria.org', port=443): Max retries exceeded with url: /portal/api/v2/taxonomy/search?taxon=Quercus+rubra&type=EXACT&limit=100&offset=0 (Caused by ConnectTimeoutError(<HTTPSConnection(host='midatlanticherbaria.org', port=443) at 0x309c0fe60>, 'Connection to midatlanticherbaria.org timed out. (connect timeout=10)'))
[Mid-Atlantic Herbaria Consortium] 'api/v2/taxonomy/search' returned an error; trying next endpoint.
SymbiotaAPI fetch error [https://midatlanticherbaria.org/portal/api/v2/taxonomy]: HTTPSConnectionPool(host='midatlanticherbaria.org', port=443): Max retries exceeded with url: /portal/api/v2/taxonomy?taxon=Quercus+rubra&type=EXACT&limit=100&offset=0 (Caused by ConnectTimeoutError(<HTTPSConnection(host='midatlanticherbaria.org', port=443) at 0x309c0fa10>, 'Connection to midatlanticherbaria.org timed out. (connect timeout=10)'))
[Mid-Atlantic Herbaria Consortium] 'api/v2/taxonomy' returned an error; trying next endpoint.
[Mid-Atlantic Herbaria Consortium] All search endpoints returned no results for 'Quercus rubra'. Attempting autocomplete search.
SymbiotaAPI fetch error [https://midatlanticherbaria.org/portal/taxa/taxonomy/rpc/gettaxasuggest.php]: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
[Mid-Atlantic Herbaria Consortium] All searches failed or returned no results for 'Quercus rubra'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, subfamily, genus, species, author, publication_name, publication_year, status, source_name, api_link, api_internal_id]
Index: []

============================================================
  symbiota / Mid-Atlantic Herbaria Consortium
  URL:       https://midatlanticherbaria.org/portal
  Species:   Quercus maxima
  Name type: synonym  (synonym of: Quercus rubra)
============================================================
SymbiotaAPI fetch error [https://midatlanticherbaria.org/portal/api/v2/taxonomy/search]: HTTPSConnectionPool(host='midatlanticherbaria.org', port=443): Read timed out. (read timeout=10)
[Mid-Atlantic Herbaria Consortium] 'api/v2/taxonomy/search' returned an error; trying next endpoint.
SymbiotaAPI fetch error [https://midatlanticherbaria.org/portal/api/v2/taxonomy]: HTTPSConnectionPool(host='midatlanticherbaria.org', port=443): Read timed out. (read timeout=10)
[Mid-Atlantic Herbaria Consortium] 'api/v2/taxonomy' returned an error; trying next endpoint.
[Mid-Atlantic Herbaria Consortium] All search endpoints returned no results for 'Quercus maxima'. Attempting autocomplete search.
[Mid-Atlantic Herbaria Consortium] Found match for 'Quercus maxima' via autocomplete.
ERROR: 'tid'

============================================================
  symbiota / swbiodiversity
  URL:       https://swbiodiversity.org/seinet
  Species:   Larrea tridentata
  Name type: accepted
============================================================
[swbiodiversity] 'api/v2/taxonomy/search' returned no results for 'Larrea tridentata'.
SymbiotaAPI fetch error [https://swbiodiversity.org/seinet/api/v2/taxonomy]: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
[swbiodiversity] 'api/v2/taxonomy' returned an error; trying next endpoint.
[swbiodiversity] All search endpoints returned no results for 'Larrea tridentata'. Attempting autocomplete search.
[swbiodiversity] Found match for 'Larrea tridentata' via autocomplete.
ERROR: 'tid'

============================================================
  symbiota / swbiodiversity
  URL:       https://swbiodiversity.org/seinet
  Species:   Larrea mexicana
  Name type: synonym  (synonym of: Larrea tridentata)
============================================================
SymbiotaAPI fetch error [https://swbiodiversity.org/seinet/api/v2/taxonomy/search]: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
[swbiodiversity] 'api/v2/taxonomy/search' returned an error; trying next endpoint.
SymbiotaAPI fetch error [https://swbiodiversity.org/seinet/api/v2/taxonomy]: HTTPSConnectionPool(host='swbiodiversity.org', port=443): Max retries exceeded with url: /seinet/api/v2/taxonomy?taxon=Larrea+mexicana&type=EXACT&limit=100&offset=0 (Caused by ConnectTimeoutError(<HTTPSConnection(host='swbiodiversity.org', port=443) at 0x309c23bf0>, 'Connection to swbiodiversity.org timed out. (connect timeout=10)'))
[swbiodiversity] 'api/v2/taxonomy' returned an error; trying next endpoint.
[swbiodiversity] All search endpoints returned no results for 'Larrea mexicana'. Attempting autocomplete search.
SymbiotaAPI fetch error [https://swbiodiversity.org/seinet/taxa/taxonomy/rpc/gettaxasuggest.php]: HTTPSConnectionPool(host='swbiodiversity.org', port=443): Max retries exceeded with url: /seinet/taxa/taxonomy/rpc/gettaxasuggest.php?term=Larrea+mexicana (Caused by ConnectTimeoutError(<HTTPSConnection(host='swbiodiversity.org', port=443) at 0x309c219d0>, 'Connection to swbiodiversity.org timed out. (connect timeout=10)'))
[swbiodiversity] All searches failed or returned no results for 'Larrea mexicana'.
Synonyms returned: 0

Empty DataFrame
Columns: [api_name, kingdom, phylum, class, family, subfamily, genus, species, author, publication_name, publication_year, status, source_name, api_link, api_internal_id]
Index: []